### PR TITLE
Remove double encoding of querystring

### LINKED ISSUE #11447: Category and tag pages are broken
### Describe the problem and steps to reproduce it:
Open any category page for extensions or themes -see https://addons-dev.allizom.org/en-US/firefox/extensions/category/bookmarks/

### What happened?
A 'Oops! We can’t find that page' is opened. If you look in the browser console Network tab, the request to the respective category page returns a 400 - Bad request.

### What did you expect to happen?
Category pages are successfully opened 

### Anything else we should know?
- the same issue applies to addon tags pages - see https://addons-dev.allizom.org/en-US/firefox/tag/antivirus/?ratings__gte=1&users__gte=0
- if I'm sending the API request directly - for example https://addons-dev.allizom.org/api/v5/addons/search/?app=firefox&appversion=99.0&category=privacy-security&sort=recommended%2Cusers&type=extension&lang=en-US for categories - the API returns results
- this issue reproduces only on AMO -dev

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #11447

### CODE REVIEW

File: tests/unit/amo/api/test_index.js [hunk 1]
```diff
@@ -106,17 +106,35 @@ describe(__filename, () => {
...
 
       await api.callApi({ endpoint });
       mockWindow.verify();
     });
 
+    // See https://github.com/mozilla/addons-frontend/issues/11447.
+    it('does not double-encode URL querystrings', async () => {
+      const endpoint = 'project-ă-ă-â-â-日本語';
+      const params = { sort: 'users,recommended', category: 'bookmarks' };
+      const expectedQueryString = api.makeQueryString(params);
```
Comment (diox) [inline tests/unit/amo/api/test_index.js:124]: While we're here... I don't see tests proving `api.makeQueryString()` encodes values, particularly commas. Maybe we should add one below in the `makeQueryString` tests ? Something like:

```diff
diff --git a/tests/unit/amo/api/test_index.js b/tests/unit/amo/api/test_index.js
index 2b8554deb..0ca96eeb4 100644
--- a/tests/unit/amo/api/test_index.js
+++ b/tests/unit/amo/api/test_index.js
@@ -527,6 +527,11 @@ describe(__filename, () => {
       const query = api.makeQueryString({ some_flag: true });
       expect(query).toEqual('?some_flag=true');
     });
+
+    it('encodes commas in query', () => {
+      const query = api.makeQueryString({ sort: 'foo,bar' });
+      expect(query).toEqual('?sort=foo%2Cbar');
+    });
   });

   describe('fetchAddon', () => {
```

Comment (bobsilverberg) [reply tests/unit/amo/api/test_index.js:124]: Good idea. I've added a test.
