### PR TITLE
I2664 - When pre-loading reviews, create the respective amount placeholders for reviews

### LINKED ISSUE #2664: When pre-loading reviews, create only the number of reviews that the page will load
### Describe the problem and steps to reproduce it:
Before the reviews on the "All reviews" page have loaded, we render a few reviews with `<LoadingText />`. But if we're coming from the add-on details page, we have a review count in state already so we should render that many reviews. This prevents an add-on with only, say, one review from having four "loading" reviews and then cutting the content down to only one review once loaded.

### Anything else we should know?
If you access the page directly, obviously we won't have a review count. In that case we can continue to load a random/set amount.

### PR DESCRIPTION
**Pull request by SeanPrashad**
Fixes #2664: When pre-loading reviews, create only the number of reviews that the page will load

This patch will now render the respective amount of `LoadingText`, ie. placeholders, when a user navigates to an addons reviews page, replacing the current implementation of 4 placeholders.

The new criterion is as follows:

1. If the addon has **between 1 and 25 reviews**, render the exact amount (ex. 3 `LoadingText` placeholders for 3 reviews):

   <details>
   	<summary>🎥 Between 1 and 25 reviews (inclusive)</summary>

   loadingtext_pagination_exact_limit

   </details>

2. If the addon has **more than 25 reviews**, render 25 `LoadingText` placeholders (as per the [pagination limit](https://github.com/mozilla/addons-frontend/blob/fda47b4842a7066ce989a7e5a6ec1a84ecd479fc/src/core/api/index.js#L24)):

   <details>
   	<summary>🎥 25+ reviews</summary>

   loadingtext_pagination_max_limit

   </details>

3. If the user navigates directly to the addon, bypassing the amount of reviews, render 4 `LoadingText` placeholders.

### CODE REVIEW

**Comment by SeanPrashad** [comment]
I think we should split up the tests for checking how many placeholders are rendered - let me know!!

File: src/amo/pages/AddonReviewList/index.js [hunk 1]
```diff
@@ -195,6 +195,10 @@ export class AddonReviewListBase extends React.Component<InternalProps> {
     );
   }
 
+  generateRandomLoadingReviews(min: number, max: number) {
+    return Math.floor(Math.random() * (max - min + 1) + min);
+  }
```
Comment (willdurand) [inline src/amo/pages/AddonReviewList/index.js]: Why do you need to generate a random number? I think let's keep 4 if there is no `addonReviewCount`. Is that even possible?

File: src/amo/pages/AddonReviewList/index.js [hunk 2]
```diff
@@ -263,6 +257,20 @@ export class AddonReviewListBase extends React.Component<InternalProps> {
         <LoadingText />
       );
 
+    let placeholderCount =
+      addonReviewCount || this.generateRandomLoadingReviews(1, 25);
+    if (placeholderCount > 25) {
+      placeholderCount = 25;
```
Comment (willdurand) [inline src/amo/pages/AddonReviewList/index.js]: We should have a constant somewhere (hopefully), that will be better. We use `page_size` in the API if I remember correctly.

File: tests/unit/amo/pages/TestAddonReviewList.js [hunk 3]
```diff
@@ -117,8 +117,10 @@ describe(__filename, () => {
     it('shows placeholders for reviews without an addon', () => {
       const root = render({ addon: null });
 
-      // Make sure four review placeholders were rendered.
-      expect(root.find(AddonReviewCard)).toHaveLength(4);
+      // Generate a random amount of placeholders between 1 and 25 inclusive
+      // when the amount of reviews is unknown.
+      expect(root.find(AddonReviewCard).length).toBeGreaterThanOrEqual(1);
+      expect(root.find(AddonReviewCard).length).toBeLessThanOrEqual(25);
```
Comment (willdurand) [inline tests/unit/amo/pages/TestAddonReviewList.js]: We should keep a fixed number, that'll be easier.

File: tests/unit/amo/pages/TestAddonReviewList.js [hunk 4]
```diff
@@ -117,8 +117,10 @@ describe(__filename, () => {
...
       // Do a sanity check on the first placeholder;
       expect(root.find(AddonReviewCard).at(0)).toHaveProp('addon', null);
       expect(root.find(AddonReviewCard).at(0)).toHaveProp('review', null);
```
Comment (willdurand) [inline tests/unit/amo/pages/TestAddonReviewList.js]: We also need a test case for when `addonReviewCount` is known.

File: src/amo/pages/AddonReviewList/index.js (hunk 1 above)
Comment (willdurand) [reply src/amo/pages/AddonReviewList/index.js]: Ah, I did not see this. We have a fixed number right now, right? I'd start with that first. We can still iterate to improve.

Comment (SeanPrashad) [reply src/amo/pages/AddonReviewList/index.js]: Okay gotcha - and yeah we currently use a hard coded value of 4

File: tests/unit/amo/pages/TestAddonReviewList.js [hunk 5]
```diff
@@ -124,6 +124,41 @@ describe(__filename, () => {
...
+      });
+      _setAddonReviews({ reviews });
+
+      const root = render();
+
+      // Make sure a 1:1 ratio of reviews to placeholders is rendered.
+      expect(root.find(AddonReviewCard)).toHaveLength(numberOfPlaceholders);
+      // Do a sanity check on the first placeholder;
+      expect(root.find(AddonReviewCard).at(0)).toHaveProp('addon', null);
+      expect(root.find(AddonReviewCard).at(0)).toHaveProp('review', null);
```
Comment (SeanPrashad) [inline tests/unit/amo/pages/TestAddonReviewList.js]: This is closer to what we want but still actually renders each review instead of the placeholder... 😕

I've skimmed through the other tests and didn't see the logic that we're looking for. Essentially, we will need a valid `addon` that is not null, has multiple reviews and figure out a way to not actually load each review (_hopefully that makes sense_).

It's been a long day and my brain is toast.. I'll take a look at it again tomorrow but any suggestions/insights would be awesome @willdurand 😃

Comment (SeanPrashad) [reply tests/unit/amo/pages/TestAddonReviewList.js]: This is exactly what I was thinking, thank you!

**Comment by SeanPrashad** [comment]
We have a green ✅from Travis!

I tested locally without my patch and things blow up (_as expected since it will **always** load 4 placeholders_):

without_my_patch

Please let me know if I can polish this up any further!! 😺

File: tests/unit/amo/pages/TestAddonReviewList.js [hunk 6]
```diff
@@ -114,14 +114,68 @@ describe(__filename, () => {
   };
 
   describe('<AddonReviewList/>', () => {
-    it('shows placeholders for reviews without an addon', () => {
```
Comment (willdurand) [inline tests/unit/amo/pages/TestAddonReviewList.js]: ah, I missed this test case. Why did you remove it actually?

File: tests/unit/amo/pages/TestAddonReviewList.js [hunk 7]
```diff
@@ -114,14 +114,68 @@ describe(__filename, () => {
...
-      const root = render({ addon: null });
+    it('displays 4 placeholders when there are no reviews yet', () => {
```
Comment (willdurand) [inline tests/unit/amo/pages/TestAddonReviewList.js]: It is more than just "no reviews". It is only because `test_count` is set to `0`.

I believe the previous test case with `addon: null` is also valid, no?

File: tests/unit/amo/pages/TestAddonReviewList.js [hunk 8]
```diff
@@ -114,14 +114,68 @@ describe(__filename, () => {
...
-      // Do a sanity check on the first placeholder;
-      expect(root.find(AddonReviewCard).at(0)).toHaveProp('addon', null);
-      expect(root.find(AddonReviewCard).at(0)).toHaveProp('review', null);
+      root.find(AddonReviewCard).forEach((card) => {
+        expect(card).toHaveProp('review', null);
+        expect(card).toHaveProp('addon', addon);
+      });
+    });
+
+    it('displays a 1:1 ratio of placeholders to reviews', () => {
```
Comment (willdurand) [inline tests/unit/amo/pages/TestAddonReviewList.js]: Can you be more verbose than `1:1 ratio`?

File: tests/unit/amo/pages/TestAddonReviewList.js [hunk 9]
```diff
@@ -114,14 +114,68 @@ describe(__filename, () => {
...
+        },
+      };
+      const addon = createInternalAddon(externalAddon);
+
+      loadAddon(externalAddon);
+
+      const root = render();
+
+      expect(root.find(AddonReviewCard)).toHaveLength(DEFAULT_API_PAGE_SIZE);
+      root.find(AddonReviewCard).forEach((card) => {
```
Comment (willdurand) [inline tests/unit/amo/pages/TestAddonReviewList.js]: This can be removed, it is done in the test case above.

File: tests/unit/amo/pages/TestAddonReviewList.js (hunk 6 above)
Comment (SeanPrashad) [reply tests/unit/amo/pages/TestAddonReviewList.js]: Whoops - didn't mean to

File: tests/unit/amo/pages/TestAddonReviewList.js (hunk 7 above)
Comment (SeanPrashad) [reply tests/unit/amo/pages/TestAddonReviewList.js]: You're right - this guy is for an existing addon with no reviews whereas the former test is for a null addon.. gotta update descriptions

**Comment by SeanPrashad** [comment]
I've updated the test descriptions and addressed the others nit - feel free to take a look when you have time @willdurand!
