### PR TITLE
Update Flow to 0.145.0 and fix types-first errors

### LINKED ISSUE #10120: Update to the latest Flow and fix all the types-first errors
In order to update to the latest Flow a large number of changes are required, many of which can be applied automatically via a codemode, but after applying that a number of new errors are reported. Both I and Luca spent some time working on this and we can now produce a patch that addresses all of them.

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #10120

### CODE REVIEW

File: src/amo/actions/viewContext.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ import { SET_VIEW_CONTEXT } from 'amo/constants';
 
 export function setViewContext(
   context: $PropertyType<ViewContextState, 'context'>,
-) {
+): {| payload: {| context: string |}, type: string |} {
```
Comment (willdurand) [inline src/amo/actions/viewContext.js:7]: Maybe worth introducing an actual type?

File: src/amo/addonManager.js [hunk 2]
```diff
@@ -78,7 +82,7 @@ export function hasAddonManager({
 
 export function hasPermissionPromptsEnabled({
   navigator,
-}: { navigator: PrivilegedNavigatorType } = {}) {
+}: { navigator: PrivilegedNavigatorType } = {}): any | void | boolean {
```
Comment (willdurand) [inline src/amo/addonManager.js:85]: ugh? It should only be `boolean | void` (void is for undefined, right?)

File: src/amo/addonManager.js [hunk 3]
```diff
@@ -116,7 +120,7 @@ export function hasAbuseReportPanelEnabled(
 export function reportAbuse(
   addonId: string,
   { _mozAddonManager = window.navigator.mozAddonManager }: OptionalParams = {},
-) {
+): void | Promise<mixed> | Promise<boolean> {
```
Comment (willdurand) [inline src/amo/addonManager.js:123]: how can it be `void`?

Comment (willdurand) [reply src/amo/addonManager.js:123]: It should be `Promise<type of the reportAbuse response>`

File: src/amo/addonManager.js [hunk 4]
```diff
@@ -192,7 +196,7 @@ export function addChangeListeners(
   |}) => void,
   mozAddonManager: MozAddonManagerType,
   { _log = log }: {| _log: typeof log |} = {},
-) {
+): (e: AddonChangeEvent) => void | Promise<void> {
```
Comment (willdurand) [inline src/amo/addonManager.js:199]: I think we could introduce a type like `HandleChangeEventFunction`

Comment (willdurand) [reply src/amo/addonManager.js:199]: and a question: why `void`? Shouldn't it be `Promise<void>` only?

File: src/amo/api/abuse.js [hunk 5]
```diff
@@ -25,7 +25,11 @@ export type ReportAddonParams = {|
   message: string,
 |};
 
-export function reportAddon({ addonSlug, api, message }: ReportAddonParams) {
+export function reportAddon({
+  addonSlug,
+  api,
+  message,
+}: ReportAddonParams): Promise<Object> {
```
Comment (willdurand) [inline src/amo/api/abuse.js:32]: Could we use an actual type that is not `Object`?

File: src/amo/components/AddonMeta/index.js [hunk 6]
```diff
@@ -30,7 +30,7 @@ export const roundToOneDigit = (value: number | null): number => {
 };
 
 export class AddonMetaBase extends React.Component<InternalProps> {
-  render() {
+  render(): React.Element<'div'> {
```
Comment (willdurand) [inline src/amo/components/AddonMeta/index.js:33]: Why not `React.Node` like some of the other files?

File: src/amo/withUIState.js [hunk 7]
```diff
@@ -60,7 +63,7 @@ export const mergeUIStateProps = (
   stateProps: Object,
   dispatchProps: Object,
   ownProps: Object,
-) => {
+): any => {
```
Comment (willdurand) [inline src/amo/withUIState.js:66]: mmm shouldn't it be an `Object`?

File: src/amo/withUIState.js [hunk 8]
```diff
@@ -32,7 +32,10 @@ export const createUIStateMapper = ({
   extractId?: ExtractIdFunc,
   fileName?: string,
   uiStateID?: string,
-|}) => {
+|}): ((
+  state: AppState,
+  props: any,
+) => {| uiState: any, uiStateID: any | string |}) => {
```
Comment (willdurand) [inline src/amo/withUIState.js:38]: I don't think we should be using `any`: https://flow.org/en/docs/types/any/

File: src/amo/utils/index.js [hunk 9]
```diff
@@ -404,11 +406,11 @@ export const addQueryParamsToHistory = ({
   history: typeof history,
   _parse?: typeof parse,
   _stringify?: typeof stringify,
-|}) => {
+|}): any => {
   return qhistory(history, _stringify, _parse);
 };
 
-export const userAgentOSToPlatform = {
+export const userAgentOSToPlatform: {||} = {
```
Comment (willdurand) [inline src/amo/utils/index.js:413]: Could we use `{| [lowerCasOS: string]: string |}`?

File: src/amo/utils/index.js [hunk 10]
```diff
@@ -166,15 +166,15 @@ export const stripLangFromAmoUrl = ({
   return urlString;
 };
 
-export function getClientConfig(_config: typeof config) {
+export function getClientConfig(_config: typeof config): { ... } {
```
Comment (willdurand) [inline src/amo/utils/index.js:169]: What does this notation mean?

File: src/amo/reducers/users.js [hunk 11]
```diff
@@ -423,17 +423,50 @@ export const unsubscribeNotification = ({
...
+  username: string,
+): UserType => {
   invariant(username, 'username is required');
   return users.byID[users.byUsername[username.toLowerCase()]];
 };
 
-export const getCurrentUser = (users: UsersState) => {
+export const getCurrentUser = (
+  users: UsersState,
+): null | {|
```
Comment (willdurand) [inline src/amo/reducers/users.js:441]: Don't e have a `UserType` or `InternalUserType`?

File: src/amo/reducers/home.js [hunk 12]
```diff
@@ -399,6 +399,7 @@ const reducer = (
         heroShelves: createInternalHeroShelves(heroShelves, state.lang),
         isLoading: false,
         resultsLoaded: true,
+        // $FlowIgnore: flow can't be sure that reduce result will patch the shelves type definition, let's trust the test coverage here.
```
Comment (willdurand) [inline src/amo/reducers/home.js:402]: :+1:

File: src/amo/reducers/categories.js [hunk 13]
```diff
@@ -141,6 +141,7 @@ export default function reducer(
         categories[appName] = {};
 
         Object.keys(categoryList[appName]).forEach((addonType) => {
+          // $FlowIgnore: flow can't be sure that the reduce result match ExternalCategory definition, let's trust the test coverage here.
```
Comment (willdurand) [inline src/amo/reducers/categories.js:144]: :+1:

File: src/amo/pages/UserProfileEdit/index.js [hunk 14]
```diff
@@ -926,19 +951,19 @@ export function mapStateToProps(state: AppState, ownProps: Props) {
   const isReviewer = hasAnyReviewerRelatedPermission(state);
 
   return {
-    clientApp,
+    clientApp: clientApp || '',
```
Comment (willdurand) [inline src/amo/pages/UserProfileEdit/index.js:954]: is this needed even with the changes from a previous PR?

File: src/amo/pages/UserProfileEdit/index.js [hunk 15]
```diff
@@ -96,7 +100,7 @@ type State = {|
 |};
 
 export class UserProfileEditBase extends React.Component<Props, State> {
-  static defaultProps = {
+  static defaultProps: {| _window: any | { ... } |} = {
```
Comment (willdurand) [inline src/amo/pages/UserProfileEdit/index.js:103]: wondering about this `{ ... }` notation

File: src/amo/components/Categories/index.js [hunk 16]
```diff
@@ -180,10 +176,10 @@ export class CategoriesBase extends React.Component<InternalProps> {
   }
 }
 
-export function mapStateToProps(state: AppState) {
+export function mapStateToProps(state: AppState): PropsFromState {
   return {
     categoriesState: state.categories.categories,
-    clientApp: state.api.clientApp,
+    clientApp: state.api.clientApp || '',
```
Comment (willdurand) [inline src/amo/components/Categories/index.js:182]: is this still needed?

File: src/amo/components/CollectionAddAddon/index.js [hunk 17]
```diff
@@ -44,23 +44,31 @@ export type Props = {|
   filters: CollectionFilters,
 |};
 
+export type DefaultProps = {|
+  clearTimeout: Function,
+  setTimeout: Function,
```
Comment (willdurand) [inline src/amo/components/CollectionAddAddon/index.js:49]: Isn't Flow providing a type for these functions?

File: src/amo/components/CollectionManager/index.js [hunk 18]
```diff
@@ -326,12 +333,19 @@ export class CollectionManagerBase extends React.Component<
...
   const { collection } = ownProps;
   return `collection-${collection ? collection.slug : ''}`;
 };
 
-export const mapStateToProps = (state: AppState) => {
+export const mapStateToProps = (
+  state: AppState,
+): {|
+  clientApp: null | string,
+  currentUserId: null | number,
```
Comment (willdurand) [inline src/amo/components/CollectionManager/index.js:345]: We had a `UserId` type at some point, maybe we could use that.

File: src/amo/addonManager.js (hunk 2 above)
Comment (bobsilverberg) [reply src/amo/addonManager.js:85]: To be honest, I hadn't checked each and every one of these that the codemod added. I was more concerned with removing the extra code not needed for defaultProps and mapStateToProps, and syncing up the types for those, but this is a good point. I'll look at all the changes to see if they all make sense.

File: src/amo/addonManager.js (hunk 4 above)
Comment (bobsilverberg) [reply src/amo/addonManager.js:199]: The type of the response is documented above as `boolean`, so I guess that should suffice.

File: src/amo/addonManager.js (hunk 3 above)
Comment (bobsilverberg) [reply src/amo/addonManager.js:123]: The type of the response is documented above as `boolean`, so I guess that should suffice.

File: src/amo/components/AddonMeta/index.js (hunk 6 above)
Comment (bobsilverberg) [reply src/amo/components/AddonMeta/index.js:33]: This is just what the codemod added. As mentioned above, I haven't gone through these with a fine-toothed comb, and mostly just accepted them. I guess now that I'm going through each file and cleaning things up, I could fix these and standardize them to `React.Node`.

File: src/amo/components/Categories/index.js (hunk 16 above)
Comment (bobsilverberg) [reply src/amo/components/Categories/index.js:182]: nope

File: src/amo/components/CollectionAddAddon/index.js (hunk 17 above)
Comment (bobsilverberg) [reply src/amo/components/CollectionAddAddon/index.js:49]: The definitions Flow created for these, as part of the codemod were... weird. I figured we could just go with `Function` as I don't think we need to be particularly worried with type safety with these, but I relented and created better types for them as part of my cleanup.

Comment (bobsilverberg) [reply src/amo/components/CollectionAddAddon/index.js:49]: The definitions Flow created for these, as part of the codemod were... weird. I figured we could just go with `Function` as I don't think we need to be particularly worried with type safety with these, but I relented and created better types for them as part of my cleanup.

File: src/amo/components/CollectionManager/index.js (hunk 18 above)
Comment (bobsilverberg) [reply src/amo/components/CollectionManager/index.js]: Yes, thanks for pointing that out. I've gone through and replaces all places where we're using `number` for `userId` with `UserId`.

File: src/amo/utils/index.js (hunk 10 above)
Comment (bobsilverberg) [reply src/amo/utils/index.js:169]: I'm not sure myself. I think it's a way of specifying an object, but I don't like it. It's something the codemod added and I'm removing it as I work through the cleanup.

File: src/amo/pages/UserProfileEdit/index.js (hunk 14 above)
Comment (bobsilverberg) [reply src/amo/pages/UserProfileEdit/index.js]: Nope. I've removed it.

File: src/amo/pages/UserProfileEdit/index.js (hunk 15 above)
Comment (bobsilverberg) [reply src/amo/pages/UserProfileEdit/index.js:104]: See my comment above

File: src/amo/reducers/users.js (hunk 11 above)
Comment (bobsilverberg) [reply src/amo/reducers/users.js:441]: Yes, and the codemod used it in most places, but for some reason not here. I've fixed it.

**Comment by bobsilverberg** [comment]
This is ready for another look @willdurand. I only ran into one issue that I struggled to figure out. I added a `$FlowFixMe` to `UserReview` because it was causing a Flow error with `ShowMoreCard`. I documented the reason in `UserReview`, but basically something that works in another component doesn't seem to work with `ShowMoreCard`. It has to do with a numeric default value.

It probably warrants a better fix (maybe changing the code in `ShowMoreCard`), but I figured I'd see if you have any ideas about what might be going on here.

File: src/amo/pages/UsersUnsubscribe/index.js [hunk 19]
```diff
@@ -44,12 +44,16 @@ type Props = {|
   |},
 |};
 
+type PropsFromState = {|
+  isUnsubscribed: boolean | null | void,
```
Comment (willdurand) [inline src/amo/pages/UsersUnsubscribe/index.js:48]: That's not how the previous type was defined. Why does it need to be `null` or `void`, and if that's the case, then maybe we could use a maybe type `?boolean`.

File: src/amo/utils/index.js [hunk 20]
```diff
@@ -29,15 +29,15 @@ import type { AddonType } from 'amo/types/addons';
  * See:
  * https://github.com/django/django/blob/0b9f366c60134a0ca2873c156b9c80acb7ffd8b5/django/amo/signing.py#L180
  */
-export function getDjangoBase62() {
+export function getDjangoBase62(): Object {
```
Comment (willdurand) [inline src/amo/utils/index.js:32]: could it be `typeof base62` instead?

File: src/amo/utils/index.js [hunk 21]
```diff
@@ -133,15 +133,17 @@ export const stripLangFromAmoUrl = ({
   return urlString;
 };
 
-export function getClientConfig(_config: typeof config) {
+export function getClientConfig(
+  _config: typeof config,
+): { [key: string]: any } {
```
Comment (willdurand) [inline src/amo/utils/index.js:138]: `any` :(

File: src/amo/utils/index.js [hunk 22]
```diff
@@ -258,21 +260,21 @@ export function isAllowedOrigin(
...
-export function apiAddonType(addonType: string) {
+export function apiAddonType(addonType: string): string {
   if (!apiAddonTypeIsValid(addonType)) {
     throw new Error(`"${addonType}" not found in API_ADDON_TYPES_MAPPING`);
   }
   return API_ADDON_TYPES_MAPPING[addonType];
 }
 
-export function visibleAddonType(addonType: string) {
+export function visibleAddonType(addonType: string): any {
```
Comment (willdurand) [inline src/amo/utils/index.js:277]: `any` :(

File: src/amo/utils/index.js [hunk 23]
```diff
@@ -371,6 +375,6 @@ export const addQueryParamsToHistory = ({
   history: typeof history,
   _parse?: typeof parse,
   _stringify?: typeof stringify,
-|}) => {
+|}): Object => {
```
Comment (willdurand) [inline src/amo/utils/index.js:378]: `typeof qhistory`?

File: src/amo/utils/sentry.js [hunk 24]
```diff
@@ -4,6 +4,8 @@ type GetSentryReleaseParams = {|
   version: string,
 |};
 
-export const getSentryRelease = ({ version }: GetSentryReleaseParams) => {
+export const getSentryRelease = ({
+  version,
+}: GetSentryReleaseParams): string => {
```
Comment (willdurand) [inline src/amo/utils/sentry.js:9]: I think you should rebase, this shouldn't be there anymore.

File: tests/unit/amo/components/TestSearch.js [hunk 25]
```diff
@@ -416,7 +416,7 @@ describe(__filename, () => {
       expect(mapStateToProps(state)).toEqual({
         context: state.viewContext.context,
         count: state.search.count,
-        filtersUsedForResults: state.search.filters,
+        filtersUsedForResults: {},
```
Comment (willdurand) [inline tests/unit/amo/components/TestSearch.js:419]: why the change?

File: tests/unit/amo/components/TestSearchFilters.js [hunk 26]
```diff
@@ -38,12 +36,9 @@ describe(__filename, () => {
     store = dispatchClientMetadata({ clientApp: CLIENT_APP_FIREFOX }).store,
     ...props
   } = {}) {
-    const errorHandler = createStubErrorHandler();
-
-    store.dispatch(searchStart({ errorHandlerId: errorHandler.id, filters }));
```
Comment (willdurand) [inline tests/unit/amo/components/TestSearchFilters.js:43]: 🤔

**Comment by bobsilverberg** [comment]
Thanks for the review @willdurand. I thought I went through and checked all of the instances of `any`, but I guess I missed a few. I'll go through and address your comments.

File: src/amo/addonManager.js [hunk 27]
```diff
@@ -78,7 +82,7 @@ export function hasAddonManager({
 
 export function hasPermissionPromptsEnabled({
   navigator,
-}: { navigator: PrivilegedNavigatorType } = {}) {
+}: { navigator: PrivilegedNavigatorType } = {}): void | boolean {
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/addonManager.js:85]: I agree. According to https://github.com/mozilla/addons-frontend/blob/master/tests/unit/amo/test_addonManager.js#L65, it looks like the intention was that we could know that `mozAddonManager` was not available by the return value of `undefined`, but we don't make use of that anywhere in our code. I guess as long as I'm cleaning up so much other stuff I might as well clean this up as well.

File: src/amo/components/AddonReviewManager/index.js [hunk 28]
```diff
@@ -32,24 +32,28 @@ type Props = {|
...
-  flashMessage?: FlashMessageType | void,
 |};
 
 export const extractId = (props: Props | InternalProps): string => {
   return props.review.id.toString();
 };
 
 export class AddonReviewManagerBase extends React.Component<InternalProps> {
-  static defaultProps = {
+  static defaultProps: {| puffyButtons: boolean |} = {
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/components/AddonReviewManager/index.js:52]: Yeah, there were a few cases where I didn't bother doing this when there was only one default prop, but I guess for consistency it's better to always do it. I'll update it.

File: src/amo/components/AddonTitle/index.js [hunk 29]
```diff
@@ -104,9 +108,9 @@ export const AddonTitleBase = ({
   );
 };
 
-const mapStateToProps = (state: AppState) => {
+const mapStateToProps = (state: AppState): PropsFromState => {
   return {
-    isRTL: isRtlLang(state.api.lang || ''),
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/components/AddonTitle/index.js:109]: Now that we know that `state.api.lang` can never be a null and will always be a string, this isn't needed anymore.

File: src/amo/components/AddonsByAuthorsCard/index.js [hunk 30]
```diff
@@ -37,31 +37,39 @@ import type { ReactRouterLocationType } from 'amo/types/router';
 
 import './styles.scss';
 
+type DefaultProps = {|
+  pageParam: string,
+  paginate: boolean,
+  showMore?: boolean,
+
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/components/AddonsByAuthorsCard/index.js:44]: 🤷 Fixed!

File: src/amo/components/AddonsByAuthorsCard/index.js [hunk 31]
```diff
@@ -209,7 +217,7 @@ export class AddonsByAuthorsCardBase extends React.Component<InternalProps> {
     );
   }
 
-  render() {
+  render(): any | null | React.Node {
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/components/AddonsByAuthorsCard/index.js:220]: I thought I got rid of all of these, but I guess I missed some. I think I must have just done a simple search for `| any`, which of course this doesn't match. Fixed!

File: src/amo/components/App/index.js [hunk 32]
```diff
@@ -70,7 +75,31 @@ export function getErrorPage(status: number | null) {
...
+          onUninstalled: string,
+          onUninstalling: string,
+        |}>,
+      |}) => Promise<void>,
+      mozAddonManager: MozAddonManagerType,
+      _?: {| _log: any |},
+    ) => any,
+    _navigator: Navigator | null,
+    authTokenValidFor: any,
+    mozAddonManager: any | { ... } | void,
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/components/App/index.js:100]: This was added by the codemod and somehow I missed it. It cannot just be `MozAddonManagerType` because it can also contain `{}`, so I changed it to `MozAddonManagerType | Object`.

File: src/amo/components/App/index.js [hunk 33]
```diff
@@ -70,7 +75,31 @@ export function getErrorPage(status: number | null) {
 export class AppBase extends React.Component<Props> {
   scheduledLogout: TimeoutID;
 
-  static defaultProps = {
+  static defaultProps: {|
+    _addChangeListeners: (
+      callback: ({|
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/components/App/index.js:80]: I tried to detangle this originally and just got myself into a mess, but now I simply extracted it to a type above, so it's not so ugly, and that works fine.

File: src/amo/components/App/index.js [hunk 34]
```diff
@@ -70,7 +75,31 @@ export function getErrorPage(status: number | null) {
 export class AppBase extends React.Component<Props> {
   scheduledLogout: TimeoutID;
 
-  static defaultProps = {
+  static defaultProps: {|
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/components/App/index.js:78]: I tried, and failed, but I gave it another try and was successful. There are a couple of inadequacies, including the fact I had to use an `any`, but it's better than it was before.

File: src/amo/components/Hero/index.js [hunk 35]
```diff
@@ -6,24 +6,27 @@ import { compose } from 'redux';
...
+export type HeroSectionsType = Array<React.Node>;
 
 type Props = {|
   name: string,
   random?: boolean,
   sections: HeroSectionsType,
 |};
 
+type PropsFromState = {|
+  heroBanners: Object,
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/components/Hero/index.js:23]: I deleted this file in https://github.com/mozilla/addons-frontend/pull/10170!

File: src/amo/components/ReportAbuseButton/index.js [hunk 36]
```diff
@@ -20,35 +21,43 @@ import { normalizeFileNameId, sanitizeHTML } from 'amo/utils';
...
+import type { DispatchFunc } from 'amo/types/redux';
 
 import './styles.scss';
 
 type Props = {|
   addon: AddonType,
 |};
 
+type PropsFromState = {|
+  abuseReport: AddonAbuseState | Object,
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/components/ReportAbuseButton/index.js:38]: Because `mapStateToProps` can return `{}` for `abuseReport`. I tried to avoid making changes to code in this patch, and just keeping it to cleaning up types. Looking at this, we could change it to return `null` instead of `{}`, which I suppose is cleaner. This has been this way since 2017. I guess it makes sense to clean it up in this patch.

File: src/amo/components/Search/index.js [hunk 37]
```diff
@@ -29,46 +29,60 @@ import { withFixedErrorHandler } from 'amo/errorHandler';
...
 import type { I18nType } from 'amo/types/i18n';
 import type { DispatchFunc } from 'amo/types/redux';
 
 import './styles.scss';
 
-type Props = {|
+type DefaultExternalProps = {|
   enableSearchFilters?: boolean,
-  filters: SearchFiltersType,
+  filters: SearchFiltersType | Object,
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/components/Search/index.js:44]: This required a few changes in the component, but it's fixed now.

File: src/amo/components/Search/index.js [hunk 38]
```diff
@@ -29,46 +29,60 @@ import { withFixedErrorHandler } from 'amo/errorHandler';
...
+
+type Props = {|
   pathname?: string,
+  ...DefaultExternalProps,
+|};
+
+type PropsFromState = {|
+  context: ViewContextType,
+  count: number,
+  filtersUsedForResults: SearchFiltersType | Object,
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/components/Search/index.js:65]: I fixed this as well.

File: src/amo/components/Search/index.js [hunk 39]
```diff
@@ -232,6 +246,8 @@ export class SearchBase extends React.Component<InternalProps> {
       results,
     } = this.props;
 
+    const defaultPathname = '/search/';
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/components/Search/index.js:249]: This was a weird workaround I came up with for the fact that Flow doesn't understand that `defaultProps` can provide a value for an optional prop. I found another way around it, which also feels a bit wrong, but I think it is better, which is to define an optional prop in `DefaultProps` and then define the same prop as non-optional in `InternalProps`, which is basically telling Flow that `defaultProps` will take care of it.

File: src/amo/components/Search/index.js [hunk 40]
```diff
@@ -288,11 +307,11 @@ export class SearchBase extends React.Component<InternalProps> {
   }
 }
 
-export const mapStateToProps = (state: AppState) => {
+export const mapStateToProps = (state: AppState): PropsFromState => {
   return {
     context: state.viewContext.context,
     count: state.search.count,
-    filtersUsedForResults: state.search.filters,
+    filtersUsedForResults: state.search.filters || {},
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/components/Search/index.js:314]: `filters` is defined in `state.search` as `SearchFilters | null`, and its initialState is `null`. I could probably change that to `{}`, and change the type, but that might result in a bunch of other changes. I'm going to leave that alone for now and just work through the rest of the comments.

File: src/amo/components/UserReview/index.js [hunk 41]
```diff
@@ -54,6 +54,14 @@ function reviewBody({
...
 
   return (
+    // TODO: I cannot figure out why Flow gets mad about this, but something
+    // similar works in FeaturecCollectionCard, where placeholderCount is not
+    // passed into LandingAddonsCard.
+    //
+    // The only difference I can see is that LandingAddonsCard doesn't use
+    // compose.
+    //
+    // $FlowFixMe: See above
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/components/UserReview/index.js:64]: I figured out a different way to address this, which is still slightly hacky, but I think makes sense. The change isn't in here at all, but in `ShowMoreCard`.

File: src/amo/constants.js [hunk 42]
```diff
@@ -95,7 +95,7 @@ export const API_ADDON_TYPES_MAPPING = {
   extensions: ADDON_TYPE_EXTENSION,
   themes: ADDON_TYPE_STATIC_THEME,
 };
-export const VISIBLE_ADDON_TYPES_MAPPING = Object.keys(
+export const VISIBLE_ADDON_TYPES_MAPPING: Object = Object.keys(
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/constants.js:98]: We run into the problem where Flow can't be sure about the output of `reduce`, but I agree that having a more specific type makes sense, so I added a type but also had to add a `$FlowIgnore` because of the `reduce`.

File: src/amo/installAddon.js [hunk 43]
```diff
@@ -458,7 +471,7 @@ export class WithInstallHelpers extends React.Component<WithInstallHelpersIntern
 
 export const withInstallHelpers = (
   WrappedComponent: React.ComponentType<any>,
-) => {
+): React.ComponentType<any> => {
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/installAddon.js:474]: I'm not sure what else to use here, as this can be any component.

[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/installAddon.js:474]: As per your message in Matrix, `mixed` is better, I've updated it.

File: src/amo/pages/UsersUnsubscribe/index.js (hunk 19 above)
Comment (bobsilverberg) [reply src/amo/pages/UsersUnsubscribe/index.js:48]: According to the [docs in the reducer](https://github.com/mozilla/addons-frontend/blob/master/src/amo/reducers/users.js#L110-L113), all three are possible values and each means something different.

File: src/amo/utils/index.js (hunk 21 above)
Comment (bobsilverberg) [reply src/amo/utils/index.js:138]: Switched to `mixed`, because it can be pretty much any type.

File: tests/unit/amo/components/TestSearch.js (hunk 25 above)
Comment (bobsilverberg) [reply tests/unit/amo/components/TestSearch.js]: I undid this change after making a bunch of other changes to `Search`.

File: tests/unit/amo/components/TestSearchFilters.js (hunk 26 above)
Comment (bobsilverberg) [reply tests/unit/amo/components/TestSearchFilters.js:43]: This code doesn't really do anything. `SearchFilters` gets its `filters` prop directly as a prop, not from `mapStateToProps`, so there is no need for this.

**Comment by bobsilverberg** [comment]
I think there are still a few instances of `any` that should be changed to `mixed`. I'll address those this afternoon and add another commit, but you can review everything else whenever you get a chance.

**Review by willdurand — APPROVED** [review]

**Comment by willdurand** [comment]
Thanks!

**Comment by willdurand** [comment]
Thank-you!
