### PR TITLE
Link Removed (Fixes #9578)

### LINKED ISSUE #9578: Remove link to 'Admin add-on status' from add-on detail pages
### Describe the problem and steps to reproduce it:
The Add-on manage admin tool has been removed in https://github.com/mozilla/addons-server/issues/15234. The frontend still exposes a link to that tool in the Admin links section present on add-on detail pages. This link should be removed. 

image

### PR DESCRIPTION
**Pull request by Aakash2408**
Fixes #9578 

90012384-f4a20a80-dcab-11ea-92df-7a86a827ecbf

I have removed the code for this link from the component.
https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/AddonAdminLinks/index.js#L82-L94,

### CODE REVIEW

File: src/amo/components/AddonAdminLinks/index.js [hunk 1]
```diff
@@ -79,19 +79,6 @@ export class AddonAdminLinksBase extends React.Component<InternalProps> {
...
-          className="AddonAdminLinks-admin-status-link"
-          href={`/admin/addon/manage/${addon.slug}/`}
-        >
-          {
-            // translators: This action allows an admin to edit the status of an add-on.
-            i18n.gettext('Admin add-on status')
-          }
-        </a>
-      </li>
-    ) : null;
```
Comment (championshuttler) [inline src/amo/components/AddonAdminLinks/index.js:82]: Seems like you need to remove the extra line as well, make sure to run `yarn prettier-dev`

Comment (Aakash2408) [reply src/amo/components/AddonAdminLinks/index.js:82]: @championshuttler ok I will just remove it

**Comment by caitmuenster** [comment]
Thanks so much for the patch, @Aakash2408! 🎉 Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition) and your profile on mozillians.org has been vouched for. 

Welcome onboard!

**Comment by Aakash2408** [comment]
Thankyou 😻
Looking forward to contribute more and more.
Regards 
Aakash Sangwan
