### PR TITLE
handle server urls that are both app and locale exceptions

### LINKED ISSUE #10308: urls that don't have either an locale and app aren't handled correctly
The middleware that checks for handles urls, and processes the app and locale parts, doesn't handle urls that are both in `validLocaleUrlExceptions` and `validClientAppUrlExceptions` (i.e. no app or locale in the url), and tries to add an app onto it.  On dev/stage/prod this isn't a problem because there is a complete nginx config managed by ops that captures those urls before frontend sees them; in a local development environment we use a much simplified [ngnix config](https://github.com/mozilla/addons-nginx/blob/master/addons.conf) that delegates most urls to frontend.   

Locally, you'll most likely encounter this bug if frontend is being used in combination with addons-server, where 404s generated are passed by the nginx config to addons-server to see if it can handle them instead.  Because the frontend middleware adds on an app and redirects, addons-server receives a url that isn't valid, and is then fixed by addons-server and redirected back (in a loop until the browser detects the loop and gives up)

e.g.

1. /contribute.json -> 301 by frontend to /firefox/contribute.json
2. /firefox/contribute.json -> 404 by frontend
3. /firefox/contribute.json is passed to addons-server by nginx
4. /firefox/contribute.json -> 302 by addons-server to /contribute.json
5. goto 1...

### PR DESCRIPTION
**Pull request by eviljeff**
fixes #10308 - I hope in not a _too_ naive way (existing tests pass so...)

### CODE REVIEW

File: tests/unit/amo/middleware/test_prefixMiddleware.js [hunk 1]
```diff
@@ -288,4 +289,15 @@ describe(__filename, () => {
...
   });
+
+  it('should render a 404 for urls that are both a client app and locale exception', () => {
+    const fakeReq = {
+      originalUrl: '/robots.txt',
+      headers: {},
+    };
+    const statusSpy = sinon.spy(fakeRes, 'status');
+    prefixMiddleware(fakeReq, fakeRes, fakeNext, { _config: fakeConfig });
+    sinon.assert.notCalled(fakeRes.set);
```
Comment (bobsilverberg) [inline tests/unit/amo/middleware/test_prefixMiddleware.js:300]: It might be better to assert that `fakeRes.redirect` is not called, because that is the main thing that happens of consequence. This works, but seems like it's based on more arbitrary behaviour.

**Review by bobsilverberg — APPROVED** [review]
This works and it seems fine. The code for this middleware is pretty ugly, and I really don't like the way we set up vars for `langFromURL` and `appFromURL` and then later use them in different ways. Ideally we'd rewrite this whole thing, imo, to make it a lot cleaner, but it's complicated and unnecessary to do that right now.

All this is to say: Nice work coming up with a solution to this problem in a simple way.

r+wc

**Comment by eviljeff** [comment]
> The code for this middleware is pretty ugly, and I really don't like the way we set up vars for `langFromURL` and `appFromURL` and then later use them in different ways. Ideally we'd rewrite this whole thing, imo, to make it a lot cleaner, but it's complicated and unnecessary to do that right now.

yeah, imo the problem is partly the naming - `langFromURL` might not contain the lang, (e.g. `/firefox/foo`), and  `appFromURL` contains the rest of the url too, not just the app (and might not contain the app at all).  And then later on in the function when we _do_ know what is in each variable we just use `URLPathParts` instead.
