### PR TITLE
Install and uninstall themes

### LINKED ISSUE #461: Theme install is not working
We thought the theme install would work similarly to add-ons but we need to use the lightweight theme install API [1]. Once the theme is installed we can check its status using ```navigator.mozAddonManager.getAddonById(`${addon.id}@personas.mozilla.org`)```.

[1] https://developer.mozilla.org/en-US/Add-ons/Themes/Lightweight_themes#Distributing_lightweight_themes_on_your_own_site

### PR DESCRIPTION
**Pull request by mstriemer**
I'm cheating by always setting the theme to installed but I haven't been able to dig into whether or not it tells us if it worked or not. I'm guessing there's no way to tell but maybe some sort of event happens.

theme-install-uninstall mov

Fixes #461.

### CODE REVIEW

File: tests/client/disco/containers/TestInstallButton.js [hunk 1]
```diff
@@ -104,6 +107,16 @@ describe('<InstallButton />', () => {
     }, Error, 'Invalid add-on status');
   });
 
+  it('should call installThem function on click when uninstalled theme', () => {
```
Comment (muffinresearch) [inline tests/client/disco/containers/TestInstallButton.js]: typo

File: src/disco/themePreview.js [hunk 2]
```diff
@@ -8,3 +8,7 @@ export default function themeAction(node, action, _doc = document) {
   event.initEvent(action, true, false);
   node.dispatchEvent(event);
 }
+
+export function getThemeData({ id, name, headerURL, footerURL, textcolor, accentcolor }) {
```
Comment (muffinresearch) [inline src/disco/themePreview.js]: This looks a bit odd, but looks like this will do the job of ensuring the shape of the data object?

Maybe a comment could be added in case someone looks at this and thinks it should be factored out.

**Comment by muffinresearch** [comment]
r+wc
