### PR TITLE
Static pages - about us and review guide

### LINKED ISSUE #2783: Add static pages
Related to #2748, we need new static pages on the frontend. Should be easy!

- [ ] About
- [ ] Rating Policy

### LINKED ISSUE #3162: Prefix middleware doesn't allow for non-clientApp urls to be served by the app
The Prefixmiddleware has code which forcibly returns a 404. See https://github.com/mozilla/addons-frontend/blob/05da066d1638d77c6e667b21f6282e59e57253f6/src/core/middleware/prefixMiddleware.js#L90

This prevents adding nonClientApp urls that actually need to be served by our app because they result in 404s. (I'm currently working on getting the static pages ready to land). Our about page needs to be at `/%locale%/about/` there's an exception for this which does prevent it being re-written to `/%locale%/%clientApp%/about/` but then we hit https://github.com/mozilla/addons-frontend/blob/05da066d1638d77c6e667b21f6282e59e57253f6/src/core/middleware/prefixMiddleware.js#L90 which causes a 404.

Removing this code means that the non-clientApp part is matched by the `:application` placeholder for other routes e.g: `/%locale%/editors/` (which then serves the homepage) so that's a non-starter because we ideally want this to fall through to a `notFound` route.

We really need a way to ensure only firefox and android are matched as applications. This might require a router upgrade :/

@tofumatt I'd be interested to chat this over with you next week and see if we can find an easy way out of the problem.

### PR DESCRIPTION
**Pull request by muffinresearch**
Fixes #2783
Fixes #3162 

Supercedes and closes #2896

This adds the about page + review guide page based on @tsl143 previous work. 

The last commit: 
 * fixes the routing
 * Adds tests for the prefix changes
 * Adds test for the config to ensure that any future non-client all router /%locale%/blah/ are configured
 * Add a title template, and start using it.
 * Update jest-enzyme, I found in checking failing tests that the messages were broken - upgrading it fixed that problem so you get a decent message using things like `toBePresent()`.
 * The urls have no trailing slash and are still containing `_` for maximum continuity.

Screenshots

about_firefox_add-ons_-_add-ons_for_firefox

review_guidelines_-_add-ons_for_firefox

### CODE REVIEW

**Comment by tofumatt** [comment]
OMG fixing jest fixed the broken messages?! Yay! I’ve been working around that in some new tests and it’s been a pain...

Matthew Riley MacPherson (sent from mobile)

**Comment by muffinresearch** [comment]
QA Note: This will probably need an ops update to enable these urls to be routed to on the server for -dev/stage/prod etc.

File: src/amo/components/StaticPages/About.js [hunk 1]
```diff
@@ -0,0 +1,180 @@
...
+    const { i18n } = this.props;
+
+    return (
+
+      <Card
+        className="StaticPage"
+        header={i18n.gettext('About Mozilla Add-ons')}
+      >
+        <Helmet>
+          <title>{i18n.gettext('About')}</title>
```
Comment (muffinresearch) [inline src/amo/components/StaticPages/About.js]: We need to do this on all the other pages at some point too.

File: src/amo/components/StaticPages/About.js [hunk 2]
```diff
@@ -0,0 +1,180 @@
...
+          </ul>
+        </section>
+        <section>
+          <h2>{i18n.gettext('I have a question')}</h2>
+          <p
+            // eslint-disable-next-line react/no-danger
+            dangerouslySetInnerHTML={
+              sanitizeHTML(
+                i18n.sprintf(
+                  i18n.gettext('A good place to start is our %(startLink)sforums%(endLink)s.'),
```
Comment (tofumatt) [inline src/amo/components/StaticPages/About.js]: `i18n.gettext('Talk to add-on developers, Mozilla community members, and Mozilla staff on our %(startLink)sadd-on forums%(endLink)s. You can get support for your add-on, talk about features, and more.'),`

File: src/amo/components/StaticPages/About.js [hunk 3]
```diff
@@ -0,0 +1,180 @@
...
+                  { startLink: '<a href="https://discourse.mozilla-community.org/c/add-ons">', endLink: '</a>' }
+                ), ['a'])
+            }
+          />
+          <p
+            // eslint-disable-next-line react/no-danger
+            dangerouslySetInnerHTML={
+              sanitizeHTML(
+                i18n.sprintf(
+                  i18n.gettext(`If you really need to contact someone from the Mozilla team,
```
Comment (tofumatt) [inline src/amo/components/StaticPages/About.js]: "If you really need to contact someone from the Mozilla team," is quite hostile phrasing. It feels like: "If you *really* need to ask a question, *fiiiiine*." Let's be friendlier 😉

`If you need to contact someone from the Mozilla team, for instance if there is a security issue with this website or you need to report an abusive add-on,  %(startLink)sfind the right person/team to contact here %(endLink)s.`

File: src/amo/components/StaticPages/ReviewGuide.js [hunk 4]
```diff
@@ -0,0 +1,117 @@
...
+        </Helmet>
+
+        <section id="review-guide">
+          <p>
+            {i18n.gettext(`Add-on reviews are a way for you to share your opinions
+              about the add-ons you’ve installed and used. Our review moderation
+              team reserves the right to refuse or remove any review that does not
+              comply with these guidelines.`)}
+          </p>
+          <h2>{i18n.gettext('Some tips for writing a great review')}</h2>
```
Comment (tofumatt) [inline src/amo/components/StaticPages/ReviewGuide.js]: > Tips for writing a great review

File: src/amo/components/StaticPages/ReviewGuide.js [hunk 5]
```diff
@@ -0,0 +1,117 @@
...
+          <h3>{i18n.gettext('Do:')}</h3>
```
Comment (tofumatt) [inline src/amo/components/StaticPages/ReviewGuide.js]: Urgh, I really don't like these "Do/Don't" styles of pages... it's not very clear and quite infantilizing.

I have a better idea for reorganising. Remove this header... I'll make a suggestion for the "Don't" one.

File: src/amo/components/StaticPages/ReviewGuide.js [hunk 6]
```diff
@@ -0,0 +1,117 @@
...
+          <title>{i18n.gettext('Review Guidelines')}</title>
+        </Helmet>
+
+        <section id="review-guide">
+          <p>
+            {i18n.gettext(`Add-on reviews are a way for you to share your opinions
+              about the add-ons you’ve installed and used. Our review moderation
+              team reserves the right to refuse or remove any review that does not
+              comply with these guidelines.`)}
+          </p>
```
Comment (tofumatt) [inline src/amo/components/StaticPages/ReviewGuide.js]: I'd add a new paragraph that lists some more guidelines to get them out of list format:

```
<p>
  {i18n.gettext('Please only write reviews for add-ons you have personally used. If you like or dislike an add-on but don't want to leave a written review, you can rate an add-on by giving it a star rating (out of five)–but please don't leave one-word reviews like "Wonderful.", "bad", or "Slow!"')}
</p>
```

File: src/amo/components/StaticPages/ReviewGuide.js [hunk 7]
```diff
@@ -0,0 +1,117 @@
...
+                <li>{i18n.gettext('Did the add-on work as you expected it to?')}</li>
+                <li>{i18n.gettext('What features did you like or dislike?')}</li>
+                <li>{i18n.gettext('Was it useful?')}</li>
+                <li>{i18n.gettext('Was it easy to use?')}</li>
+                <li>{i18n.gettext('Will you continue to use this add-on?')}</li>
+              </ul>
+            </li>
+            <li>{i18n.gettext('Take a moment to read your review before submitting it to minimize typos.')}</li>
+          </ul>
+          <h3>{i18n.gettext(`Don't:`)}</h3>
```
Comment (tofumatt) [inline src/amo/components/StaticPages/ReviewGuide.js]: > Reviews will be refused or removed if they:

File: src/amo/components/StaticPages/ReviewGuide.js [hunk 8]
```diff
@@ -0,0 +1,117 @@
...
+          <ul>
+            <li>{i18n.gettext('Submit one-word reviews such as "Great!", "wonderful," or "bad." ')}</li>
```
Comment (tofumatt) [inline src/amo/components/StaticPages/ReviewGuide.js]: Remove this line as I think it's better in a `<p>` above.

File: src/amo/components/StaticPages/ReviewGuide.js [hunk 9]
```diff
@@ -0,0 +1,117 @@
...
+            <li>{i18n.gettext(`Post technical issues, support requests, or feature suggestions. Use
+              the available support options for each add-on, if available. You can find them in
+              the side column next to the About this Add-on section.`)}</li>
```
Comment (tofumatt) [inline src/amo/components/StaticPages/ReviewGuide.js]: It's not "More information" and I'd quote "About this Add-on". So `the side column next to the "More information" section`

File: src/amo/components/StaticPages/ReviewGuide.js [hunk 10]
```diff
@@ -0,0 +1,117 @@
...
+            <li>{i18n.gettext('Write reviews for add-ons which you have not personally used.')}</li>
```
Comment (tofumatt) [inline src/amo/components/StaticPages/ReviewGuide.js]: I'd remove this for `<p>` suggested above.

File: src/amo/components/StaticPages/ReviewGuide.js [hunk 11]
```diff
@@ -0,0 +1,117 @@
...
+            <li>{i18n.gettext('Use profanity, sexual language or language that can be construed as hateful.')}</li>
+            <li>{i18n.gettext('Include HTML, links, source code or code snippets. Reviews are meant to be text only.')}</li>
+            <li>{i18n.gettext('Make false statements, disparage add-on authors or personally insult them.')}</li>
+            <li>{i18n.gettext('Include your own or anyone else’s email, phone number, or other personal details.')}</li>
+            <li>{i18n.gettext('Post reviews for an add-on you or your organization wrote or represent.')}</li>
```
Comment (tofumatt) [inline src/amo/components/StaticPages/ReviewGuide.js]: > Are a review for an add-on you or your organization wrote or represent

File: src/amo/components/StaticPages/ReviewGuide.js [hunk 12]
```diff
@@ -0,0 +1,117 @@
...
+                      { startLink: '<a href="https://discourse.mozilla-community.org/c/add-ons/add-on-support">', endLink: '</a>' }
+                    ), ['a'])
+                }
+              />
+            </dd>
+          </dl>
+          <dl>
+            <dt>{i18n.gettext(`I'm an add-on author, can I delete unfavorable reviews or ratings?`)}</dt>
+            <dd>
+              <p>{i18n.gettext(`In general, no. But if the review did not meet the review guidelines
```
Comment (tofumatt) [inline src/amo/components/StaticPages/ReviewGuide.js]: > In general: no. But if the review did not meet the review guidelines outlined above, you can click "Report this review" to have it moderated. If a review included a complaint that is no longer valid due to a new release of your add-on, we may consider deleting the review.

File: src/amo/routes.js [hunk 13]
```diff
@@ -27,27 +29,33 @@ import ServerError from './components/ErrorPage/ServerError';
...
-    <Route path="simulate-async-error/" component={SimulateAsyncError} />
-    <Route path="simulate-sync-error/" component={SimulateSyncError} />
-    <Route path="simulate-client-error/" component={SimulateClientError} />
-    <Route path=":visibleAddonType/" component={LandingPage} />
-    <Route path="*" component={NotFound} />
-  </Route>
+  <div>
+    <Route path="/:lang" component={App}>
+      <Route path="about" component={About} />
+      <Route path="review_guide" component={ReviewGuide} />
```
Comment (tofumatt) [inline src/amo/routes.js]: Might be nice to TODO: this to have a dash instead. Dashes are cool in URLs and we could do a redirect.

File: tests/unit/TestPrefixConfig.js [hunk 14]
```diff
@@ -0,0 +1,24 @@
...
+    delete process.env.NODE_APP_INSTANCE;
+  });
+
+  it(`checks clientAppRoutes items are present in validClientAppUrlExceptions`, () => {
+    /*
+     * Without this the clientAppRoutes will not work as expected. If you want
+     * /en-US/blah to hit the app, 'blah' must be in both clientAppRoutes
+     * and validClientAppUrlExceptions in the app config.
+     */
+    process.env.NODE_ENV = 'production';
```
Comment (tofumatt) [inline tests/unit/TestPrefixConfig.js]: 😱 Seems scary. Is that just for this test? It's changed back afterward, right?

**Comment by tofumatt** [comment]
Also, I forgot to talk about style but that content should *definitely* have a `max-width`. Spanning the entire page is really intense, so something like a `720px`-ish max width would probably be good.

**Comment by tofumatt** [comment]
Also, and I'm just being REALLY annoying now, but do we have any cute icons/drawings we could use to spruce these pages up? Maybe even a desaturated add-onstopus? Or just it hanging out off to the right on desktop? To fill that empty space when we have a max-width for content. Whismy is important!

File: config/default-amo.js [hunk 15]
```diff
@@ -79,6 +79,14 @@ module.exports = {
     '__frontend_version__',
     '__version__',
   ],
+
+  // These routes are allowed through to the app rather than 404.
+  // Anything in here should also be present in validClientAppUrlExceptions.
+  clientAppRoutes: [
+    'about',
+    'review_guide',
```
[the remark this answers is not in the document]
Comment (muffinresearch) [reply config/default-amo.js]: As mentioned in the description this is for parity and we've got other things to worry about :) It its ugly though!

File: src/amo/components/StaticPages/About.js [hunk 16]
```diff
@@ -0,0 +1,180 @@
...
+            />
+          </ul>
+        </section>
+        <section>
+          <h2>{i18n.gettext('This sounds great! How can I get involved?')}</h2>
+          <p>{i18n.gettext(`There are plenty of ways to get involved. If you're on the technical side:`)}</p>
+          <ul>
+            <li>
+              <Link to={'/developers'}>{i18n.gettext('Make your own add-on.')}</Link>
+              <span> {i18n.gettext('We provide free hosting and update services and can help you reach a large audience of users.')}</span>
```
[the remark this answers is not in the document]
Comment (muffinresearch) [reply src/amo/components/StaticPages/About.js]: That's deliberate. Because we don't have a Link equivalent of JS otherwise the leading link would be substituted in. I think this would be nice to fix, but I didn't want to get into it. Can definitely file an issue for that one. I meant to call it out in the comments.

File: tests/unit/TestPrefixConfig.js (hunk 14 above)
Comment (muffinresearch) [reply tests/unit/TestPrefixConfig.js]: Yeah - see the afterEach ^

File: src/amo/routes.js (hunk 13 above)
Comment (muffinresearch) [reply src/amo/routes.js]: I think we should wait on that until after this site has replaced the old one. Changing the urls on only one side is likely to mess things up and it doesn't buy us much given the huge list of other things we need to do.

**Comment by muffinresearch** [comment]
> Also, I forgot to talk about style but that content should definitely have a max-width. Spanning the entire page is really intense, so something like a 720px-ish max width would probably be good.

Maybe adding back a TOC like the legacy page has would break things up a bit and save having a different core content block size.

**Comment by caitmuenster** [comment]
@tofumatt, the ACE team is going to take a look at the copy for this and make some edits. Thank you for your suggestions! :)

**Comment by tofumatt** [comment]
Ten four! I have strong feelings about copy. ❤️

**Comment by tofumatt** [comment]
@caitmuenster I feel like copy for this was updated but it's not in any linked issues. Am I wrong and it's not ready yet? Or if it's ready could you attach a link here so we can update these pages?

**Comment by caitmuenster** [comment]
Sorry, @tofumatt! The doc is available here: https://docs.google.com/document/d/1KxTKHEMAJHfK0wodVD2PiBG90mc7hafF-Emo8JLKnic/edit?ts=59c8d1eb#

[](url)

**Comment by muffinresearch** [comment]
@tofumatt @caitmuenster That's my fault since I created the docs with the copy to be edited, and since I'm still planning to do the update I didn't link it anywhere. I'm going to look to get that fixed up this week (ahead of the tag if possible).

**Comment by muffinresearch** [comment]
@tofumatt this is updated as per the new copy. The max-width is limited too now, although I chose a slightly larger value of 960px to avoid too much whitespace to the right of the copy.

File: tests/unit/amo/components/TestStaticPages.js [hunk 17]
```diff
@@ -0,0 +1,35 @@
+import { shallow } from 'enzyme';
```
Comment (tofumatt) [inline tests/unit/amo/components/TestStaticPages.js]: We usually keep tests sectioned off for each component; it's easier to find them based on fuzzy search file names that way. I know it's more overhead but I think putting the About and Review Guide tests in their own files will help us keep things organized.

File: tests/unit/amo/components/TestStaticPages.js [hunk 18]
```diff
@@ -0,0 +1,35 @@
...
+import React from 'react';
+
+import { AboutBase } from 'amo/components/StaticPages/About';
+import { ReviewGuideBase } from 'amo/components/StaticPages/ReviewGuide';
+import { getFakeI18nInst } from 'tests/unit/helpers';
+
+
+describe('About', () => {
+  function render() {
+    return shallow(
```
Comment (tofumatt) [inline tests/unit/amo/components/TestStaticPages.js]: This should use `shallowUntilTarget` (see an example here: https://github.com/mozilla/addons-frontend/blob/master/tests/unit/amo/components/TestSearchFilters.js#L31) so you can test the actual exported component and not have to render the base one.

For these tests it matters less as you're just adding translate but it's our usual way to test a component that is `compose`'d with HOCs.

File: tests/unit/core/middleware/test_prefixMiddleware.js [hunk 19]
```diff
@@ -19,7 +19,9 @@ describe('Prefix Middleware', () => {
     fakeConfig.set('validClientApplications', ['firefox', 'android']);
     fakeConfig.set('validLocaleUrlExceptions', ['downloads']);
     fakeConfig.set(
-      'validClientAppUrlExceptions', ['developers', 'validprefix']);
+      'validClientAppUrlExceptions', ['developers', 'validprefix', 'about']);
```
Comment (tofumatt) [inline tests/unit/core/middleware/test_prefixMiddleware.js]: No one cares about alphabetizing but me 🤣

File: src/amo/components/StaticPages/ReviewGuide.js [hunk 20]
```diff
@@ -0,0 +1,110 @@
...
+                team reserves the right to refuse or remove any review that does not
+                comply with these guidelines.`)}
+            </p>
+            <h2>{i18n.gettext('Tips for writing a great review')}</h2>
+            <h3>{i18n.gettext('Do:')}</h3>
+            <ul>
+              <li>{i18n.gettext('Write like you are telling a friend about your experience with the add-on.')}</li>
+              <li>{i18n.gettext('Keep reviews concise and easy to understand.')}</li>
+              <li>{i18n.gettext('Give specific and helpful details. For example:')}
+                <ul>
```
[the remark this answers is not in the document]
Comment (muffinresearch) [reply src/amo/components/StaticPages/ReviewGuide.js]: @tofumatt you know the trouble with Russian dolls? 

...

They're so full of themselves.



badum-tish

File: src/amo/components/StaticPages/About.js [hunk 21]
```diff
@@ -0,0 +1,184 @@
...
+              // eslint-disable-next-line react/no-danger
+              dangerouslySetInnerHTML={
+                sanitizeHTML(
+                  i18n.sprintf(
+                    i18n.gettext(`You can also use AMO to find add-ons for Mozilla
+                      %(startTBLink)sThunderbird%(endTBLink)s and
+                      %(startSMLink)sSeaMonkey%(endSMLink)s.`),
+                    { startTBLink: '<a href="https://addons.mozilla.org/thunderbird/">',
+                      endTBLink: '</a>',
+                      startSMLink: '<a href="https://addons.mozilla.org/en-US/seamonkey/">',
```
[the remark this answers is not in the document]
Comment (muffinresearch) [reply src/amo/components/StaticPages/About.js]: Oops, yep that's copy pasta. 🍟

File: src/amo/components/StaticPages/About.js [hunk 22]
```diff
@@ -0,0 +1,184 @@
...
+                  sanitizeHTML(
+                    i18n.sprintf(
+                      i18n.gettext(`Help improve this website. It's open source, and you
+                        can file bugs and submit patches. You can get started with a
+                        %(startGoodFirstBugLink)sgood first bug%(endGoodFirstBugLink)s
+                        or view all open issues for AMO’s
+                        %(startAddonsServerRepoLink)sserver%(endAddonsServerRepoLink)s and
+                        %(startAddonsFrontendRepoLink)sfrontend%(endAddonsFrontendRepoLink)s
+                        on Github.`),
+                      { startGoodFirstBugLink: '<a href="https://bit.ly/2yVT3GL">',
```
[the remark this answers is not in the document]
Comment (muffinresearch) [reply src/amo/components/StaticPages/About.js]: It was mainly for brevity, the proper link is a beast.

[the remark this answers is not in the document]
Comment (muffinresearch) [reply src/amo/components/StaticPages/About.js]: I will add it back - I did think that it makes it harder to edit in the future.

File: src/amo/components/StaticPages/About.js [hunk 23]
```diff
@@ -0,0 +1,184 @@
...
+              // eslint-disable-next-line react/no-danger
+              dangerouslySetInnerHTML={
+                sanitizeHTML(
+                  i18n.sprintf(
+                    i18n.gettext(`If you would like to learn more about how to manage add-ons in
+                      Firefox, or need to find general Firefox support, please visit
+                      %(startSUMOLink)sSupport%(endSUMOLink)s
+                      Mozilla. If you don't find an answer there, you can
+                      %(startForumLink)sask on our community forum%(endForumLink)s.`),
+                    { startSUMOLink: '<a href="https://support.mozilla.org/en-US/products/firefox/manage-preferences-and-add-ons-firefox/install-and-manage-add-ons">',
```
[the remark this answers is not in the document]
Comment (muffinresearch) [reply src/amo/components/StaticPages/About.js]: Yep, good call.

File: src/amo/components/StaticPages/About.js (hunk 22 above)
[the remark this answers is not in the document]
Comment (tofumatt) [reply src/amo/components/StaticPages/About.js]: I'd definitely rather the beastly link than the shorter though. It'll be easier to edit/change if we add a new repo (or remove one), it's obvious to us what it is, and it's one less request!

File: tests/unit/amo/components/TestStaticPages.js (hunk 18 above)
Comment (muffinresearch) [reply tests/unit/amo/components/TestStaticPages.js]: @tofumatt I've converted to use this pattern, and now I'm seeing:

```    console.error node_modules/fbjs/lib/warning.js:36
      Warning: Failed context type: The context `i18n` is marked as required in `Translate[AboutBase]`, but its value is `undefined`.
          in Translate[AboutBase]
```

This error seems to be coming up in a few other tests using the same pattern.

Presumably this happens because the i18n object isn't reaching the underlying component. It's completely possible I'm missing something - but since the shallowUntilTarget isn't actually doing what the HoC would do (e.g. providing the i18n object) I'm struggling to understand the rationale for using it over testing the component directly.

Comment (tofumatt) [reply tests/unit/amo/components/TestStaticPages.js]: I guess it matters more for consistency when you *would* be testing state in component as well–I don't want someone to look at these tests and think "Oh that's how I should test things".

In this particular case it's more about best practices and fewer surprises than needing to do it because yes: `i18n` isn't passed through with translate using `shallowUntilTarget`. Though really it should be, that seems like a bug.
