### PR TITLE
Show all search results by default

### LINKED ISSUE #6117: No add-ons shown when filtering by ALL on search page
### Describe the problem and steps to reproduce it:

On https://addons.mozilla.org/firefox/search/, when you sort Add-on Type and Operating System by ALL and uncheck Featured Add-ons Only, we return 0 searches.

### What did you expect to happen?

I expect to see all add-ons available on AMO, not 0 add-ons. So it seems we need a way to handle the situation where there is no query string.

Imgur

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #6117

---

We do not reset filters anymore and we show all the results coming from the API, with or without filters.

In order to make sure a fresh call to `/search/` shows all the results, I changed the initial state from `filters: {}` to `filters: null` so that we call the API the very first time only.

### CODE REVIEW

File: src/core/reducers/search.js [hunk 1]
```diff
@@ -13,19 +13,18 @@ export const SEARCH_STARTED: 'SEARCH_STARTED' = 'SEARCH_STARTED';
 export const SEARCH_LOADED: 'SEARCH_LOADED' = 'SEARCH_LOADED';
 
 const SEARCH_ABORTED: 'SEARCH_ABORTED' = 'SEARCH_ABORTED';
-const SEARCH_RESET: 'SEARCH_RESET' = 'SEARCH_RESET';
 
 export type SearchState = {|
   count: number,
-  filters: SearchFilters | {},
+  filters: SearchFilters | {} | null,
```
Comment (kumar303) [inline src/core/reducers/search.js]: Can't it just be this?

```suggestion
  filters: SearchFilters | null,
```

I don't see any Flow errors.

I mean, it doesn't really matter since `SearchFilters` can be an empty object.

Comment (willdurand) [reply src/core/reducers/search.js]: thanks
