### PR TITLE
Don't show inaccessible page numbers in some cases

### LINKED ISSUE #200: Pagination doesn't work correctly for small page counts
When there is a page count less than the number of pages we should you can get an off-by-one where there's an extra page at the end. Try with `count=128 perPage=25`. In this case I think we can skip calculating the offset and make it `currentPage - 1`.

### PR DESCRIPTION
**Pull request by mstriemer**
This fixes an off-by-one error that happened with some page sizes. I refactored the code in hopes of making it more straightforward by defining the different cases instead of having them mixed together in some `Math` function calls.

Fixes #200.

### CODE REVIEW

File: src/core/components/Paginate/index.js [hunk 1]
```diff
@@ -26,22 +34,22 @@ export default class Paginate extends React.Component {
...
+    const showExtra = Math.floor(showPages / 2);
+    const start = Math.max(1, currentPage - showExtra);
+    const end = Math.min(pageCount, currentPage + showExtra);
+
+    // If we can show all of the pages, show them all.
+    if (pageCount <= showPages) {
+      return makePageNumbers({start: 1, end: pageCount});
+    // If we are showing less on the right than we should, define the start by the end.
+    } else if (end - currentPage < showExtra) {
+        return makePageNumbers({start: end - showPages + 1, end});
```
Comment (muffinresearch) [inline src/core/components/Paginate/index.js]: over indented

**Comment by muffinresearch** [comment]
r+wc
