### PR TITLE
Default experiment cookies to secure cookies

### LINKED ISSUE #8957: addons.mozilla.org has failed the web security baseline
Site https://addons.mozilla.org has failed the web security baseline scan.

The failing tests are:

 Cookie No HttpOnly Flag [10010] x 1 
 * https://addons.allizom.org/en-US/firefox/addon/ublock-origin/?src=homepage-primary-hero (200 OK)

 Cookie Without Secure Flag [10011] x 1 
 * https://addons.allizom.org/en-US/firefox/addon/ublock-origin/?src=homepage-primary-hero (200 OK)

This issue was automatically raised.

This issue is managed automatically by the baseline scan:

 * If the failing tests change then it will be updated
 * If it is closed before the tests pass then a new one will be opened
 * When all of the tests pass then it will be closed

Full details, including how to test for these issues locally, can be found on this [Security Baseline Service](https://sql.telemetry.mozilla.org/dashboard/security-baseline-service-latest?p_w53332_site_60280=addons.mozilla.org) dashboard.
If you have any questions or concerns please get in contact with @psiinon

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #8957 by making the cookie secure. @psiinon is going to whitelist the cookie to allow it to remain non-httpOnly.

### CODE REVIEW

File: src/core/withExperiment.js [hunk 1]
```diff
@@ -114,6 +115,7 @@ type withExperimentInternalProps = {|
 export const defaultCookieConfig: CookieConfig = {
   maxAge: DEFAULT_COOKIE_MAX_AGE,
   path: '/',
+  secure: true,
```
Comment (willdurand) [inline src/core/withExperiment.js]: Could you add a comment that links to the GH issue above?

File: src/core/withExperiment.js [hunk 2]
```diff
@@ -62,6 +62,7 @@ export type WithExperimentInjectedProps = {|
 type CookieConfig = {|
   maxAge?: number,
   path?: string,
+  secure?: boolean,
```
Comment (willdurand) [inline src/core/withExperiment.js]: We should probably have done that before, could you please add a comment with [this link](https://github.com/reactivestack/cookies/tree/f9beead40a6bebac475d9bf17c1da55418d26751/packages/react-cookie#setcookiename-value-options) above the type definition?
