### PR TITLE
Set dangerouslySetInnerHTML on a div

### LINKED ISSUE #5587: User's biography not always displayed
### Describe the problem and steps to reproduce it:

Add the following content to your bio and update the profile:

```text
<blockquote><b>hello</b></blockquote>
```

### What happened?

The bio won't be displayed after page reload.

### What did you expect to happen?

The bio is displayed.

### Anything else we should know?

```
Warning: Prop `dangerouslySetInnerHTML` did not match. Server: "" Client: "<blockquote> <b>I'm</b> a great grandmother who learns something new everyday using Photoshop Elements. Will I remember how to do it tomorrow? Hopefully! </blockquote><br>\n<blockquote><b>I</b> began designing Persona themes in 2009. I mainly work on Nature graphics using the Pacific Northwest as my canvas. I was asked to make wallpapers to match my themes. I put the link for the matching wallpaper in the Theme description. I am also using working with paintings and making them work for a theme. It takes a lot of manipulation with Photoshop to do this, but I love the old paintings. And hope you like them for themes.</blockquote><br>\n<blockquote><b>I</b> have learned everything by trial and error. A lot of error! More themes got sent to the recycle bin than I submitted!</blockquote><br>\n<blockquote><b>I</b> got interested in taking photos other than my grandkids so started taking nature photos. I live in a beautiful area where the forests, mountains and seashore are right around the corner. I use many of my photos to make themes and wallpapers. </blockquote><br>\n<blockquote><b>My</b> thanks to all of you that use my designs and take the time to review them. I really appreciate the time it takes for you to do so. I am aware that time is valuable and the older you get the more valuable time becomes. </blockquote><br>\n<blockquote><b>If</b> it wasn't for you, the users I wouldn't be doing this.</blockquote><br>\n<blockquote><b>Check</b> out my blog sometime and become a follower. <b>madonnaspersonas.blogspot</b></blockquote><br>\n<blockquote>Check out the You Tube video Mozilla made of me. Go to You Tube and put in meet madonna</blockquote>"
```

### PR DESCRIPTION
**Pull request by willdurand**
Fix #5587

---

I believe the browser changes the HTML in the DOM to be valid. React
does not find what the server has sent in the `dangerouslySetInnerHTML`
when introspecting the DOM, hence the warning (locally) about the
`dangerouslySetInnerHTML` mismatch (see issue).

React 16 is weird when a difference between server and client occurs.

### CODE REVIEW

File: tests/unit/amo/components/TestUserProfile.js [hunk 1]
```diff
@@ -411,9 +411,11 @@ describe(__filename, () => {
   });
 
   it("renders the user's biography", () => {
+    const biography = '<blockquote><b>Not even vegan!</b></blockquote>';
```
Comment (willdurand) [inline tests/unit/amo/components/TestUserProfile.js]: Note that I cannot reproduce the issue in the test case here, because it is a server vs client issue.
