### PR TITLE
Make add-on reducer state more explicit

### LINKED ISSUE #3024: Make add-on reducer state more explicit
It's really tough to see what properties we actually store in the add-on reducer state. This has led to numerous bugs and has also made it tricky to add new add-on properties.

I'd like to start by restructuring the reducer a bit and getting rid of all spreads, carefully. This will be focused on preparing to solve the following bugs:

* Lack of platform support: https://github.com/mozilla/addons-frontend/issues/2998
* Incomplete theme objects: https://github.com/mozilla/addons-frontend/issues/3014

For QA: please test for regressions in AMO and the Discovery Pane for anything related to installing add-ons and themes.

### PR DESCRIPTION
**Pull request by kumar303**
Fixes #3024 

This will hopefully make the central add-on reducer easier to deal with for features and bug fixes but it has potential to break a lot of stuff. It would help if you could test out add-on/theme installs. I've manually tested AMO and the Discopane.

### CODE REVIEW

File: src/core/reducers/addons.js [hunk 1]
```diff
@@ -1,15 +1,36 @@
 /* @flow */
 import { ADDON_TYPE_THEME } from 'core/constants';
 import type { ErrorHandlerType } from 'core/errorHandler';
-import type { AddonType } from 'core/types/addons';
+import type { AddonType, ExternalAddonType } from 'core/types/addons';
 
 
+export const ADDONS_LOADED = 'ADDONS_LOADED';
```
Comment (willdurand) [inline src/core/reducers/addons.js]: Can we have `LOAD_ADDON` instead? See: https://github.com/mozilla/addons-frontend/pull/3025#discussion_r135909932

File: src/core/reducers/addons.js [hunk 2]
```diff
@@ -37,69 +58,151 @@ export function fetchAddon({ errorHandler, slug }: FetchAddonParams): FetchAddon
...
+    is_disabled: apiAddon.is_disabled,
+    is_experimental: apiAddon.is_experimental,
+    is_featured: apiAddon.is_featured,
+    is_source_public: apiAddon.is_source_public,
+    last_updated: apiAddon.last_updated,
+    latest_unlisted_version: apiAddon.latest_unlisted_version,
+    name: apiAddon.name,
+    previews: apiAddon.previews,
+    public_stats: apiAddon.public_stats,
+    ratings: apiAddon.ratings || undefined,
```
Comment (willdurand) [inline src/core/reducers/addons.js]: Why does this one need this?

File: src/core/reducers/addons.js [hunk 3]
```diff
@@ -37,69 +58,151 @@ export function fetchAddon({ errorHandler, slug }: FetchAddonParams): FetchAddon
...
+  // (which has a header and description) with a minimal add-on object.
+  // For example, the minimal add-on object does not have a description
+  // property so the spread should not override `description`.
+  addon = removeUndefinedProps(addon);
+
+  return addon;
 }
 
-export default function addon(
+const initialState = {};
```
Comment (willdurand) [inline src/core/reducers/addons.js]: Flow type?

File: src/core/reducers/addons.js [hunk 4]
```diff
@@ -37,69 +58,151 @@ export function fetchAddon({ errorHandler, slug }: FetchAddonParams): FetchAddon
...
     // This mimics how Firefox appends @personas.mozilla.org internally.
     // It's needed to look up themes in mozAddonManager.
-    return `${result.id}@personas.mozilla.org`;
+    return `${addon.id}@personas.mozilla.org`;
   }
-  return result.guid;
+  return addon.guid;
+}
+
+export function removeUndefinedProps(object: Object): Object {
```
Comment (willdurand) [inline src/core/reducers/addons.js]: Is this method needed because there are spreads in different places? Otherwise I would argue that the state should have a consistent shape.

File: src/core/actions/index.js [hunk 5]
```diff
@@ -69,15 +68,3 @@ export function setUserAgent(userAgent: string): SetUserAgentAction {
     payload: { userAgent },
   };
 }
-
-export type LoadEntitiesAction = {|
-  payload: {| entities: Array<Object> |},
-  type: string,
-|};
-
-export function loadEntities(entities: Array<Object>): LoadEntitiesAction {
```
Comment (tofumatt) [inline src/core/actions/index.js]: Yay!

File: src/core/reducers/addons.js [hunk 6]
```diff
@@ -1,15 +1,36 @@
...
+
+export type LoadAddonsAction = {|
+  payload: {| addons: ExternalAddonMap |},
+  type: string,
+|};
 
-type Action = Object;
-type AddonState = Object;
+export function loadAddons(
+  entities: {| addons?: ExternalAddonMap |}
```
Comment (tofumatt) [inline src/core/reducers/addons.js]: As mentioned previously I think it would be great to keep flow definitions out of the function signatures if they're being included. They really crowd the function signature and make it very difficult to parse exactly what's happening inside it.

File: src/core/reducers/addons.js [hunk 7]
```diff
@@ -37,69 +58,151 @@ export function fetchAddon({ errorHandler, slug }: FetchAddonParams): FetchAddon
...
+    support_email: apiAddon.support_email,
+    support_url: apiAddon.support_url,
+    tags: apiAddon.tags,
+    type: apiAddon.type,
+    url: apiAddon.url,
+    weekly_downloads: apiAddon.weekly_downloads,
+
+    // These are custom properties not in the API response.
+
+    // TODO: remove this if possible. I think it was added by mistake
```
Comment (tofumatt) [inline src/core/reducers/addons.js]: 👍

File: src/core/reducers/addons.js [hunk 8]
```diff
@@ -37,69 +58,151 @@ export function fetchAddon({ errorHandler, slug }: FetchAddonParams): FetchAddon
...
+        textcolor: apiAddon.theme_data.textcolor,
+        updateURL: apiAddon.theme_data.updateURL,
+        version: apiAddon.theme_data.version,
+      }),
     };
   }
-  return apiAddon;
+
+  if (apiAddon.current_version && apiAddon.current_version.files.length > 0) {
+    // TODO: support specific platform files.
```
Comment (tofumatt) [inline src/core/reducers/addons.js]: All these comments are very helpful 🥂!

File: src/core/reducers/addons.js [hunk 9]
```diff
@@ -37,69 +58,151 @@ export function fetchAddon({ errorHandler, slug }: FetchAddonParams): FetchAddon
...
-      }
-      newState[key] = denormalizeAddon(newState[key]);
-    });
-    return newState;
+  switch (action.type) {
+    case ADDONS_LOADED: {
+      const { addons } = action.payload;
+      const newState = { ...state };
+      Object.keys(addons).forEach((key) => {
+        newState[key] = createInternalAddon(addons[key]);
```
Comment (tofumatt) [inline src/core/reducers/addons.js]: 🎉💃🎉 THANK YOU THIS IS SO MUCH EASIER TO READ 🎉💃🎉

File: src/core/sagas/addons.js [hunk 10]
```diff
@@ -7,9 +7,8 @@ import { hideLoading, showLoading } from 'react-redux-loading-bar';
 import { call, put, select, takeEvery } from 'redux-saga/effects';
 /* eslint-enable import/order */
 
-import { loadEntities } from 'core/actions';
 import { fetchAddon as fetchAddonFromApi } from 'core/api';
-import { FETCH_ADDON } from 'core/reducers/addons';
+import { loadAddons, FETCH_ADDON } from 'core/reducers/addons';
```
Comment (tofumatt) [inline src/core/sagas/addons.js]: Nitpick but I think we usually load constants first. It technically is alphabetical that way but I guess until we have a rule for sorting imports... 😞

File: src/core/sagas/addons.js [hunk 11]
```diff
@@ -25,7 +24,7 @@ export function* fetchAddon(
     yield put(showLoading());
     const state = yield select(getState);
     const response = yield call(fetchAddonFromApi, { api: state.api, slug });
-    yield put(loadEntities(response.entities));
+    yield put(loadAddons(response.entities));
```
Comment (tofumatt) [inline src/core/sagas/addons.js]: This is just way easier to read too. Thanks a million.

File: src/core/types/addons.js [hunk 12]
```diff
@@ -20,15 +20,39 @@ export type AddonAuthorType = {|
...
+  previewURL?: string,
+  textcolor?: string,
+  updateURL?: string,
+  version?: string,
+|};
+
+/*
+ * This is the external API representation of an add-on.
+ *
+ * This is a detailed API response. Not all API responses
```
Comment (tofumatt) [inline src/core/types/addons.js]: Linking to the API docs from here would be cool just so developers could understand better the varied details in responses. Maybe just http://addons-server.readthedocs.io/en/latest/topics/api/addons.html ?

File: tests/unit/core/reducers/test_addons.js [hunk 13]
```diff
@@ -123,65 +176,42 @@ describe(__filename, () => {
...
-        isRestartRequired: false,
-      }),
-    });
+    const state = addons(undefined,
+      loadAddons(createFetchAddonResult(addon).entities));
+    expect(state[addon.slug].isRestartRequired).toBe(false);
   });
 
-  it('sets `isRestartRequired` to `true` when at least one of the files declares it', () => {
+  it('sets `isRestartRequired` to `true` when some files declare it', () => {
```
Comment (tofumatt) [inline tests/unit/core/reducers/test_addons.js]: if the aim here was to shorten this spec I'd say "when any file declares it".

File: src/core/reducers/addons.js (hunk 1 above)
Comment (kumar303) [reply src/core/reducers/addons.js]: ah, right, thanks

File: src/core/reducers/addons.js (hunk 4 above)
Comment (kumar303) [reply src/core/reducers/addons.js]: Yes it is needed for spreads. I added a comment about it below. It's going to be hard to remove the spreads and I think it's a low priority fix.

File: src/core/reducers/addons.js (hunk 2 above)
Comment (kumar303) [reply src/core/reducers/addons.js]: ah, whoops, good catch. That was leftover from me battling with Flow :/

File: src/core/reducers/addons.js (hunk 4 above)
Comment (willdurand) [reply src/core/reducers/addons.js]: > I think it's a low priority fix.

👍

File: src/core/reducers/addons.js (hunk 3 above)
Comment (kumar303) [reply src/core/reducers/addons.js]: There is a type for it -- you can see it assigned in the function signature: https://github.com/mozilla/addons-frontend/pull/3073/files/39fb66595b5b8033cd43288e61a19f35d9f32dbf#diff-21aa4f8ea4fba6406233649d0ce65beaR193

File: src/core/reducers/addons.js (hunk 6 above)
Comment (kumar303) [reply src/core/reducers/addons.js]: The issue I have with making them separate is that it slows down the reader. If you want to know what the type is, you have to cross-reference it from somewhere else. I understand how separation can be helpful for big definitions but this one only spans about 30 characters so I don't think that warrants separation.

File: src/core/types/addons.js (hunk 12 above)
Comment (kumar303) [reply src/core/types/addons.js]: good idea

**Comment by kumar303** [comment]
Thanks for the reviews! Let's start testing this on dev...
