### PR TITLE
Stop sending Cache-Control: no-store, send max-age and s-maxage

### LINKED ISSUE #10678: Use Cache-Control: s-maxage to control nginx caching duration
We currently use `X-Accel-Expires: 180` to control nginx cache duration, and have nginx ignore `Cache-Control` though `proxy_ignore_headers`, because we also return a `Cache-Control: no-store` on all pages.

We only need the `Cache-Control: no-store` to prevent browsers from caching pages (and we only really need that because we don't want them to store tokens in redux cache, so we could be less aggressive about this, but that's out of scope for this issue).

Moving to having everything behind a CDN, we want to consolidate that setup to only use `Cache-Control` header, because `X-Accel-Expires` is proprietary to nginx. This should be possible by returning `max-age=0` with `s-maxage: 180`: `s-maxage` acts as an exception to `max-age`, designed for shared caches like proxies / CDN only.

### PR DESCRIPTION
**Pull request by diox**
We don't want browsers to cache our pages at the moment, but sending `Cache-Control: no-store` prevents proxies and upstream caches from caching as well. We override that in nginx at the moment, but the more standards-based approach is to use `max-age` and `s-maxage` instead.

This unlocks the possibility to have a CDN in front of addons-frontend.

Fixes #10678

### CODE REVIEW

**Review by eviljeff — APPROVED** [review]
interesting/scary we don't have any pytest tests to verify these headers are set

File: tests/unit/amo/server/test_base.js [hunk 1]
```diff
@@ -705,42 +707,54 @@ describe(__filename, () => {
...
         '/en-US/firefox/',
       );
       expect(response.headers).not.toContain(X_ACCEL_EXPIRES_HEADER);
+      expect(response.headers['cache-control']).toEqual(
+        'max-age=0, s-maxage=0',
+      );
     });
 
-    it('does not set a X-Accel-Expires header if response is 404', async () => {
+    it('dsets correct Cache-Control header if response is 404', async () => {
```
Comment (bobsilverberg) [inline tests/unit/amo/server/test_base.js:746]: s/dsets/sets/
