### PR TITLE
Fix search filters when recommended/featured checkbox is unchecked

### LINKED ISSUE #8301: Error message received when removing the Recommended filter option if the `random` sort parameter is present
Similar to #8298

**STR:**

1. Load AMO -dev or stage
2. Click on See more recommended extensions from the homepage shelf
3. Un-check the 'Recommended add-ons only' option from the filters panel

**Actual result:**
The follwoing error is received:
`The "sort" parameter "random" can only be specified when the "featured" or "recommended" parameter is also present, and the "q" parameter absent.`

**Expected result:**
A list of search results is returned

**Notes:**
- reproduced on -dev and stage, but my guess this is also a pre-existing bug, not something introduced by https://github.com/mozilla/addons-frontend/pull/8299

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #8301

### CODE REVIEW

File: tests/unit/amo/components/TestSearchFilters.js [hunk 1]
```diff
@@ -386,6 +387,45 @@ describe(__filename, () => {
...
+        query: convertFiltersToQueryParams({}),
+      });
+    });
+
+    it('does pass sort=random when the recommended checkbox is checked', () => {
+      const root = render({
+        _config,
+        filters: {
+          recommended: false,
+          sort: SEARCH_SORT_RANDOM,
```
Comment (bobsilverberg) [inline tests/unit/amo/components/TestSearchFilters.js]: Hmm, this is an interesting test because our intent is that this state could never exist. That is, having `recommended=false` and `sort=random` together is supposed to be illegal. So maybe we shouldn't have this test at all?

File: tests/unit/amo/components/TestSearchFilters.js [hunk 2]
```diff
@@ -483,6 +523,45 @@ describe(__filename, () => {
         }),
       });
     });
+
+    it('does not pass sort=random when the featured checkbox is unchecked', () => {
```
Comment (bobsilverberg) [inline tests/unit/amo/components/TestSearchFilters.js]: We plan on removing all code related to `featured`, but I guess until we do that we need this test for now.

File: tests/unit/amo/components/TestSearchFilters.js [hunk 3]
```diff
@@ -483,6 +523,45 @@ describe(__filename, () => {
...
+        query: convertFiltersToQueryParams({}),
+      });
+    });
+
+    it('does pass sort=random when the featured checkbox is checked', () => {
+      const root = render({
+        _config,
+        filters: {
+          featured: false,
+          sort: SEARCH_SORT_RANDOM,
```
Comment (bobsilverberg) [inline tests/unit/amo/components/TestSearchFilters.js]: As above, this test creates a start state that should be illegal.

File: tests/unit/amo/components/TestSearchFilters.js (hunk 1 above)
Comment (willdurand) [reply tests/unit/amo/components/TestSearchFilters.js]: Indeed. That might not be needed.

File: src/core/api/search.js [hunk 4]
```diff
@@ -37,6 +41,22 @@ export function search({ api, auth = false, filters = {} }: SearchParams) {
...
   });
 
+  // The API says: 'The "sort" parameter "random" can only be specified when
+  // the "featured" or "recommended" parameter is also present, and the "q"
+  // parameter absent.'
+  // Let's make sure we don't send invalid filters.
+  if (newFilters.sort && newFilters.sort === SEARCH_SORT_RANDOM) {
+    if (
+      !(newFilters.recommended || newFilters.featured) ||
+      ((newFilters.recommended || newFilters.featured) && newFilters.q)
```
Comment (bobsilverberg) [inline src/core/api/search.js]: If the rule states that having `sort=random` and `q` together is illegal (which is how I'm reading it), then maybe you can move this statement one line up and just make it `newFilters.q`. I.e., there doesn't seem to be a need to repeat the check for `newFilters.recommended || newFilters.featured`.

File: src/core/api/search.js [hunk 5]
```diff
@@ -37,6 +41,22 @@ export function search({ api, auth = false, filters = {} }: SearchParams) {
...
+    ) {
+      delete newFilters.sort;
+
+      log.warn(oneLine`search api filter "sort=random" has been removed before
```
Comment (bobsilverberg) [inline src/core/api/search.js]: Would it be worth moving this `log` statement above the `delete` and including `newFilters` in the statement so we can see when a case arises that requires this, and what the data looked like?

File: src/core/api/search.js (hunk 4 above)
Comment (willdurand) [reply src/core/api/search.js]: ah, right 😅

File: src/core/api/search.js (hunk 5 above)
Comment (willdurand) [reply src/core/api/search.js]: so we don't really want to log objects because it has performance implications, especially here since we can have user input (and potentially very large input).
