### PR TITLE
I5568 static theme display on disco

### LINKED ISSUE #5568: Update logic in disco pane so static themes is displayed similiarly to lightweight themes
### Describe the problem and steps to reproduce it:

once static themes are [added to the disco pane](https://github.com/mozilla/addons-server/issues/8572), we should make sure it looks similar to lightweight themes

### PR DESCRIPTION
**Pull request by rebmullin**
fixes #5568 

note: the functionality updates are coming in another PR

### CODE REVIEW

File: src/disco/components/Addon/index.js [hunk 1]
```diff
@@ -121,31 +123,58 @@ export class AddonBase extends React.Component {
   }
 
   getThemeImage() {
-    const { getBrowserThemeData, i18n, name, previewURL } = this.props;
-    if (this.props.type === ADDON_TYPE_THEME) {
+    const { type } = this.props;
```
Comment (willdurand) [inline src/disco/components/Addon/index.js]: I *think* `type` comes from the `addon` prop. I know it is available directly but that's because we spread the whole `addon` if I remember correctly. I think it would be slightly better to retrieve `type` from the `addon`.

This comment also applies to `name`, `previews` and probably `previewURL` too.

File: src/disco/components/Addon/index.js [hunk 2]
```diff
@@ -121,31 +123,58 @@ export class AddonBase extends React.Component {
...
           onClick={this.installTheme}
         >
-          <img
-            src={previewURL}
-            alt={sprintf(i18n.gettext('Preview of %(name)s'), { name })}
-          />
+          {headerImage}
+        </a>
+      ) : (
+        <a className="theme-image" href="#">
```
Comment (willdurand) [inline src/disco/components/Addon/index.js]: Do we really need a `a` here? It has no link and no `onClick` handler.

File: tests/unit/disco/components/TestAddon.js [hunk 3]
```diff
@@ -386,22 +388,59 @@ describe(__filename, () => {
...
+    {
+      type: ADDON_TYPE_STATIC_THEME,
+      previews: [
+        {
+          ...fakePreview,
+          image_url: 'https://addons.cdn.mozilla.net/full/54321.png',
+        },
+      ],
+    },
+  ])(`Addon for %o`, async (testConfig) => {
```
Comment (willdurand) [inline tests/unit/disco/components/TestAddon.js]: I like your use of `.each` but I would like to see a better description. Currently it is:

```
  ● /Users/williamdurand/projects/mozilla/addons-frontend/tests/unit/disco/components/TestAddon.js › Addon for { type: 'statictheme',
  previews:
   [ { id: 1,
       caption: 'Image 1',
       image_url: 'https://addons.cdn.mozilla.net/full/54321.png',
       thumbnail_url: 'https://addons.cdn.mozilla.net/thumb/1.png',
       image_size: [ 400, 200, [length]: 2 ],
       thumbnail_size: [ 200, 100, [length]: 2 ] },
     [length]: 1 ] } › renders the correct image for a theme
```

it is not really readable. I think here that would make more sense to have to set of tests because you are not exactly testing the same things it seems (otherwise `previews` would have the same content, no?)

Alternatively, you can use and configure `previews` in the `beforeEach` block:

```
describe.each([ADDON_TYPE_THEME, ADDON_TYPE_STATIC_THEME])(`Addon with type = %s`, (type) => {
});
```

File: src/disco/components/Addon/index.js (hunk 2 above)
Comment (rebmullin) [reply src/disco/components/Addon/index.js]: Yeh I guess it makes sense to move this to the functionality PR where it does have the its own onClick

File: tests/unit/disco/components/TestAddon.js (hunk 3 above)
Comment (rebmullin) [reply tests/unit/disco/components/TestAddon.js]: I saw some of the same repeating tests but I see what you're saying. Let me try this way you suggest with just type.

**Comment by rebmullin** [comment]
> One question: do you also see the static theme being enabled time to time? Not always. I don't really know why (and it does not matter).

hey @willdurand, are you seeing this on dev? static themes in disco is supposed to be enabled here. @eviljeff set it up that way a  a few weeks ago...
I am actually not sure how this is switched off tho and if QA has been toggling this for testing..? If they are it should be more "on" then "off" tho... I've not seen it disabled since I knew it was enabled...

File: tests/unit/disco/components/TestAddon.js (hunk 3 above)
Comment (rebmullin) [reply tests/unit/disco/components/TestAddon.js]: let me know if how it have it now is ok. I extracted some of it..

**Comment by rebmullin** [comment]
hey @willdurand, thanks for the feedback. Do you mind taking another look at this one?

File: src/core/utils/index.js [hunk 4]
```diff
@@ -304,3 +304,13 @@ export const normalizeFileNameId = (filename) => {
...
+
+export const getPreviewImage = (
+  previews,
+  { version = 0, full = true } = {},
+) => {
+  const previewsType = full ? 'image_url' : 'thumbnail_url';
+  return previews && previews.length > 0 && previews[version][previewsType]
+    ? previews[version][previewsType]
+    : null;
+};
```
Comment (rebmullin) [inline src/core/utils/index.js]: I've only used the function here in this related section.. but I'll set up a follow issue/PR to use this in the other places too

File: src/disco/components/Addon/index.js [hunk 5]
```diff
@@ -121,31 +124,48 @@ export class AddonBase extends React.Component {
   }
 
   getThemeImage() {
-    const { getBrowserThemeData, i18n, name, previewURL } = this.props;
-    if (this.props.type === ADDON_TYPE_THEME) {
+    const { type } = this.props.addon;
+
+    if (ADDON_TYPE_THEMES.includes(type)) {
```
Comment (willdurand) [inline src/disco/components/Addon/index.js]: Should we use `isTheme()` here?

File: src/disco/components/Addon/index.js [hunk 6]
```diff
@@ -121,31 +124,48 @@ export class AddonBase extends React.Component {
...
+      const { addon, getBrowserThemeData, i18n } = this.props;
```
Comment (willdurand) [inline src/disco/components/Addon/index.js]: Would it make sense to get the addon above? (You use `this.props.addon`) to retrieve the `type`, but maybe we can get the `addon` first, and then its type.

File: src/disco/components/Addon/index.js [hunk 7]
```diff
@@ -121,31 +124,48 @@ export class AddonBase extends React.Component {
...
           onClick={this.installTheme}
         >
-          <img
-            src={previewURL}
-            alt={sprintf(i18n.gettext('Preview of %(name)s'), { name })}
-          />
+          {headerImage}
         </a>
+      ) : (
+        <React.Fragment>{headerImage}</React.Fragment>
```
Comment (willdurand) [inline src/disco/components/Addon/index.js]: Do you really need a fragment here?

File: src/disco/components/Addon/index.js [hunk 8]
```diff
@@ -121,31 +124,48 @@ export class AddonBase extends React.Component {
...
     }
+
     return null;
   }
 
   getDescription() {
     const { description, type } = this.props;
 
-    if (type === ADDON_TYPE_THEME) {
+    if (ADDON_TYPE_THEMES.includes(type)) {
```
Comment (willdurand) [inline src/disco/components/Addon/index.js]: `isTheme()`?

File: tests/unit/disco/components/TestAddon.js [hunk 9]
```diff
@@ -386,25 +388,57 @@ describe(__filename, () => {
     });
   });
 
-  describe('<Addon type="theme"/>', () => {
-    let root;
+  describe.each([ADDON_TYPE_THEME, ADDON_TYPE_STATIC_THEME])(
+    `Addon for %s`,
```
Comment (willdurand) [inline tests/unit/disco/components/TestAddon.js]: > Addon with type = %s

What do you think?

File: tests/unit/disco/components/TestAddon.js [hunk 10]
```diff
@@ -386,25 +388,57 @@ describe(__filename, () => {
...
+  });
 
+  describe('<Addon type="theme"/>', () => {
     it('calls installTheme on click', () => {
       const installTheme = sinon.stub();
-      const addon = result;
+      const addon = {
+        ...result,
+        type: ADDON_TYPE_THEME,
+      };
```
Comment (willdurand) [inline tests/unit/disco/components/TestAddon.js]: What is `result` here? Also, I think we should be using `createInternalAddon()` from `core/reducers/addons`.

File: tests/unit/disco/components/TestAddon.js [hunk 11]
```diff
@@ -386,25 +388,57 @@ describe(__filename, () => {
...
-    it('does render the theme image for a theme', () => {
-      expect(root.find('.theme-image')).toHaveLength(1);
-    });
+      it("doesn't render the logo for a theme", () => {
+        expect(root.find('.logo')).toHaveLength(0);
+      });
 
-    it("doesn't render the logo for a theme", () => {
-      expect(root.find('.logo')).toHaveLength(0);
+      it("doesn't render the description for a theme", () => {
```
Comment (willdurand) [inline tests/unit/disco/components/TestAddon.js]: You might not need "for a theme" every time since it is grouped into a `describe` block that should mention the type of the addon.

File: src/core/utils/index.js (hunk 4 above)
Comment (willdurand) [reply src/core/utils/index.js]: Would it make sense to pass the `addon` object instead?

Can you find a way to reuse this helper function somewhere else?

**Comment by eviljeff** [comment]
>> One question: do you also see the static theme being enabled time to time? Not always. I don't really know why (and it does not matter).

> hey @willdurand, are you seeing this on dev? static themes in disco is supposed to be enabled here. @eviljeff set it up that way a a few weeks ago...
I am actually not sure how this is switched off tho and if QA has been toggling this for testing..? If they are it should be more "on" then "off" tho... I've not seen it disabled since I knew it was enabled...

yeah static themes should be included in the API response on if `disco-staticthemes-dev` waffle switch is enabled.

File: src/disco/components/Addon/index.js (hunk 7 above)
Comment (rebmullin) [reply src/disco/components/Addon/index.js]: If I don't have this, it breaks. This is kind of temporary tho anyway, b/c in the functionality PR, we should add back the `a` wrapper tag which has an onClick (a special case for static themes). I realize your work might override that with your work but I am just going off what I know my changes would be for now :)

Comment (willdurand) [reply src/disco/components/Addon/index.js]: mmh, what exactly is breaking? A fragment renders nothing, and I believe `headerImage` is a valid element.

**Comment by willdurand** [comment]
> hey @willdurand, are you seeing this on dev? static themes in disco is supposed to be enabled here. @eviljeff set it up that way a a few weeks ago...
> I am actually not sure how this is switched off tho and if QA has been toggling this for testing..? If they are it should be more "on" then "off" tho... I've not seen it disabled since I knew it was enabled...

Sorry, I was not clear. I meant, when I click to install a theme, it gets enabled sometimes, but not always. I am not sure why because I thought that was not possible.

File: tests/unit/disco/components/TestAddon.js (hunk 10 above)
Comment (rebmullin) [reply tests/unit/disco/components/TestAddon.js]: results comes from `loadedAddons` function which is actually used in the DiscoPane component:

`const result = loadedAddons(_state)[0];`

Is that okay?

Comment (willdurand) [reply tests/unit/disco/components/TestAddon.js]: ah ok, yes. sorry I was a bit lost but not your fault :)

File: src/core/utils/index.js (hunk 4 above)
Comment (rebmullin) [reply src/core/utils/index.js]: hmm..I am not sure I am understanding why we should pass in `addon` instead... But let me take another look...

Comment (willdurand) [reply src/core/utils/index.js]: I think I gave you a bad hint about this function. Do you think we can reuse it somewhere else? The code looks similar but not exactly the same (there are calls to `isAllowedOrigin()` for instance).

**Comment by rebmullin** [comment]
> Sorry, I was not clear. I meant, when I click to install a theme, it gets enabled sometimes, but not always. I am not sure why because I thought that was not possible.

I think this is part of the bug with static theme. I had to explicitly call `enable()` for static themes. I know you said you removed/refactored the Switch but I had something like this:

https://github.com/mozilla/addons-frontend/pull/5683/files#diff-fd3a9b2c8bff28448f81457a3e53f828R25

That PR is a little bit outdated (needs a rebase) but I believe you should always see it working there

File: src/disco/components/Addon/index.js (hunk 7 above)
Comment (rebmullin) [reply src/disco/components/Addon/index.js]: I see this in console:

Caught application error: Invariant Violation: "Objects are not valid as a React child (found: object with keys {headerImage}). If you meant to render a collection of children, use an array instead.

Alt text

File: src/core/utils/index.js (hunk 4 above)
Comment (rebmullin) [reply src/core/utils/index.js]: oh sorry I missed your comment above about isAllowedOrigin and I guess the hint too:) ...

Yeh I guess I missed that piece of it. I am honestly not sure why it's in some places but not others (isAllowedOrigin). I guess I can add it to the getPreviewImage function. Would that work?

Comment (rebmullin) [reply src/core/utils/index.js]: So I added this isAllowedOrigin to the function. It just adds an extra step which I thought would be okay.  I *think* now it should cover the other cases too. Let me know what you think.

**Comment by willdurand** [comment]
@rebmullin I have integrated most of your changes in #5712 🎉

**Comment by rebmullin** [comment]
> I have integrated most of your changes in #5712 

that's awesome @willdurand. I'll close this and #5683 out once that goes through 🎉

**Comment by willdurand** [comment]
@rebmullin what's the status of this PR?

**Comment by rebmullin** [comment]
@willdurand, oh? I thought you were kind of taking this over. I can def update this in the am tho if you need it. let me know...

File: src/core/utils/index.js [hunk 12]
```diff
@@ -314,3 +314,14 @@ export const addQueryParamsToHistory = ({
 }) => {
   return qhistory(history, _stringify, _parse);
 };
+
+export const getPreviewImage = (addon, { version = 0, full = true } = {}) => {
```
Comment (willdurand) [inline src/core/utils/index.js]: Can we move this function to `src/core/imageUtils.js`?

Comment (willdurand) [reply src/core/utils/index.js]: Is it really a `version` or just an index?

File: src/disco/components/Addon/index.js [hunk 13]
```diff
@@ -121,31 +123,49 @@ export class AddonBase extends React.Component {
   }
 
   getThemeImage() {
-    const { getBrowserThemeData, i18n, name, previewURL } = this.props;
-    if (this.props.type === ADDON_TYPE_THEME) {
+    const { addon } = this.props;
+    const { type } = addon;
```
Comment (willdurand) [inline src/disco/components/Addon/index.js]: You could probably destructure `type` from `this.props.addon`;

File: src/disco/components/Addon/index.js [hunk 14]
```diff
@@ -121,31 +123,49 @@ export class AddonBase extends React.Component {
...
+
+    if (isTheme(type)) {
+      const { getBrowserThemeData, i18n } = this.props;
+      const { name, previewURL } = addon;
+
+      let imageUrl = getPreviewImage(addon);
+
+      if (!imageUrl && type === ADDON_TYPE_THEME) {
+        imageUrl = previewURL;
```
Comment (willdurand) [inline src/disco/components/Addon/index.js]: Does that mean `imageUrl` can be `null` for a static theme? What should we be displaying then?

File: src/disco/components/Addon/index.js (hunk 7 above)
Comment (willdurand) [reply src/disco/components/Addon/index.js]: mmh, this works for me:

```js
      return type === ADDON_TYPE_THEME ? (
        <a
          className="theme-image"
          data-browsertheme={getBrowserThemeData()}
          href="#"
          onClick={this.installTheme}
        >
          {headerImage}
        </a>
      ) : (
        headerImage
      );

```

File: src/disco/components/Addon/index.js [hunk 15]
```diff
@@ -233,7 +253,7 @@ export class AddonBase extends React.Component {
     }
 
     const addonClasses = makeClassName('addon', {
-      theme: type === ADDON_TYPE_THEME,
+      theme: ADDON_TYPE_THEMES.includes(type),
```
Comment (willdurand) [inline src/disco/components/Addon/index.js]: Why not using `isTheme()` here?

File: tests/unit/core/utils/test_index.js [hunk 16]
```diff
@@ -792,4 +797,81 @@ describe(__filename, () => {
...
+            ...fakePreview,
+            image_url: 'https://addons.cdn.mozilla.net/image.not.used.here.png',
+          },
+        ],
+      });
+      const image = getPreviewImage(addon);
+      expect(image).toEqual(fullImage);
+    });
+
+    it('returns the full image from the 2nd item in the previews array', () => {
```
Comment (willdurand) [inline tests/unit/core/utils/test_index.js]: I get it but this is weird to see `2nd` in the description and `version: 1` in the assertion.

File: tests/unit/core/utils/test_index.js [hunk 17]
```diff
@@ -792,4 +797,81 @@ describe(__filename, () => {
       });
     });
   });
+
+  describe('getPreviewImage', () => {
+    it('returns the first full image from the previews array', () => {
+      const fullImage = 'https://addons.cdn.mozilla.net/full/12345.png';
```
Comment (willdurand) [inline tests/unit/core/utils/test_index.js]: Can we use `${config.get('amoCDN')}` instead of `https://addons.cdn.mozilla.net` everywhere?

File: src/disco/components/Addon/index.js (hunk 14 above)
Comment (rebmullin) [reply src/disco/components/Addon/index.js]: Static themes should always have this. This was only set up for persona. Initially I was thinking after migration (of lwt themes) persona would have the previews too but it actually should change the type too and never hit here after the migration happens. If that makes sense..

File: tests/unit/core/utils/test_index.js (hunk 16 above)
Comment (rebmullin) [reply tests/unit/core/utils/test_index.js]: hmm ok..let me try something else

File: src/core/utils/index.js (hunk 12 above)
Comment (rebmullin) [reply src/core/utils/index.js]: yeh index is better, thanks

Comment (rebmullin) [reply src/core/utils/index.js]: yep, I'll move that too..

File: tests/unit/disco/components/TestAddon.js [hunk 18]
```diff
@@ -385,25 +387,58 @@ describe(__filename, () => {
...
+          type: ADDON_TYPE_STATIC_THEME,
+        },
+      });
+      const image = shallowRoot.find('.Addon-theme-header-image');
+      expect(image.prop('src')).toEqual(fullImage);
+      expect(image).toHaveProp('alt', `Preview of ${newAddonName}`);
     });
+  });
 
+  describe('<Addon type="theme"/>', () => {
```
Comment (willdurand) [inline tests/unit/disco/components/TestAddon.js]: Can we rename this description to: `addon with type "theme"`

File: tests/unit/disco/components/TestAddon.js [hunk 19]
```diff
@@ -385,25 +387,58 @@ describe(__filename, () => {
...
 
-    it("doesn't render the logo for a theme", () => {
-      expect(root.find('.logo')).toHaveLength(0);
+      it("doesn't render the description", () => {
+        expect(root.find('.editorial-description')).toHaveLength(0);
+      });
+    },
+  );
+
+  describe('<Addon type="statictheme"/>', () => {
```
Comment (willdurand) [inline tests/unit/disco/components/TestAddon.js]: Can we rename this description to: `addon with type "static theme"`

File: tests/unit/disco/components/TestAddon.js [hunk 20]
```diff
@@ -385,25 +387,58 @@ describe(__filename, () => {
...
 
+  describe('<Addon type="theme"/>', () => {
     it('calls installTheme on click', () => {
       const installTheme = sinon.stub();
-      const addon = result;
+      const addon = {
+        ...result,
+        type: ADDON_TYPE_THEME,
+        previews: [],
+      };
```
Comment (willdurand) [inline tests/unit/disco/components/TestAddon.js]: Why do we need this change?

File: tests/unit/disco/components/TestAddon.js [hunk 21]
```diff
@@ -385,25 +387,58 @@ describe(__filename, () => {
...
+            {
+              ...fakePreview,
+              image_url: fullImage,
+            },
+          ],
+          type: ADDON_TYPE_STATIC_THEME,
+        },
+      });
+      const image = shallowRoot.find('.Addon-theme-header-image');
+      expect(image.prop('src')).toEqual(fullImage);
```
Comment (willdurand) [inline tests/unit/disco/components/TestAddon.js]: You can use `toHaveProp` too here.

File: tests/unit/disco/components/TestAddon.js (hunk 20 above)
Comment (rebmullin) [reply tests/unit/disco/components/TestAddon.js]: previews has to be empty and type persona. The getPreviewImage checks inside the add for this info and I believe the default is type extension with previews. SO i am just updating it to match the results for lightweight theme
