### PR TITLE
Fix display issue with Recommended Badge on Guides pages

### LINKED ISSUE #8284: The Recommended badge is not placed next to the add-on name in the guides pages for shorter names
**STR**

1. Go to AMO stage homepage
2. Open the Stay safe online guide - https://addons.allizom.org/en-US/firefox/guides/stay-safe-online/
3. Examine the uBlock Origin card

**Actual result:**
The Recommended badge and the add-on name are too far apart

**Expected result:**
The Recommended badge is displayed next to the add-on name

**Notes:**
- another example is Tabliss in the https://addons.allizom.org/en-US/firefox/guides/organize-tabs-and-bookmarks/ guide
- reproduced on stage with Fx67, Win10x64

image
image

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #8284 

I got this working pretty much exactly how I wanted, with one exception. When the description of the add-on is only on one line, the Install Button looks too close to the bottom of the card (to me, anyway). That's because it is center aligned with the description. To fix this I added some padding to the bottom of the button, which gives it a decent amount of space in this scenario, but it does mean that when there is more than one line of add-on description, the button is not 100% center aligned with the description, but is above center by a very small amount. The longer the description, the less of a difference this makes. 

Perhaps there's something else I can do to fix this without affecting the centering of the button for longer descriptions?

Here's an example of the problem, without the padding that I added:

Screenshot 2019-07-15 14 08 51

and here's how it looks with the padding:

Screenshot 2019-07-15 14 10 32

### CODE REVIEW

**Comment by muffinresearch** [comment]
@bobsilverberg I would consider putting `margin: 8px 0 10px;` on `.GuidesAddonCard-content-button` and remove the `8px` top and bottom margin from: `.GuidesAddonCard-content-description` and remove the bottom padding on `.GuidesAddonCard .GuidesAddonCard-content-button .InstallButtonWrapper`.

That should work in both cases since the container of the paragraph and button has the margin and works if either the text or button is taller.

**Comment by bobsilverberg** [comment]
> @bobsilverberg I would consider putting `margin: 8px 0 10px;` on `.GuidesAddonCard-content-button` and remove the `8px` top and bottom margin from: `.GuidesAddonCard-content-description` and remove the bottom padding on `.GuidesAddonCard .GuidesAddonCard-content-button .InstallButtonWrapper`.
> 
> That should work in both cases since the container of the paragraph and button has the margin and works if either the text or button is taller.
> 
> _Note: The 10px on the bottom margin (rather than 8px) is to match the 6px padding on the bottom to make 16px which matches the padding at the top of the whole thing which is 16px._

Thanks @muffinresearch, I'll give that a try.

**Comment by bobsilverberg** [comment]
@willdurand I just updated this with @muffinresearch's suggestions. It's better now.

File: src/amo/components/GuidesAddonCard/index.js [hunk 1]
```diff
@@ -68,18 +68,20 @@ export class GuidesAddonCardBase extends React.Component<InternalProps> {
                   )}
                 </div>
               </div>
-              <p className="GuidesAddonCard-content-description">
-                {this.props.addonCustomText}
-              </p>
+              <div className="GuidesAddonCard-content-button">
```
Comment (willdurand) [inline src/amo/components/GuidesAddonCard/index.js]: Why is this called `-button` if the first child is the `description`?

**Comment by bobsilverberg** [comment]
> Looks okay but if there is no recommended badge, then it's a visual regression:
> 
> Screen Shot 2019-07-16 at 17 51 47
> 
> r+wc

Is the visual regression the fact that without the badge the button is still center-aligned with the description, as opposed to center-aligned in the card? FTR, anything on the Guides page should be a recommended add-on, but I guess we cannot guarantee that. Do you think this visual regression should be fixed?

File: src/amo/components/GuidesAddonCard/index.js (hunk 1 above)
Comment (bobsilverberg) [reply src/amo/components/GuidesAddonCard/index.js]: Good catch. I've updated the `className`.
