### PR TITLE
Disably addonType search filter when category type is set

### LINKED ISSUE #3747: "Invalid 'type' parameter" red banner for "All" add-on type in each category
Steps to reproduce:
1. Load any add-on category page i.e. https://addons.allizom.org/en-US/firefox/extensions/shopping/
2. Choose "see more" for any sorting option i.e. https://addons.allizom.org/en-US/firefox/search/?category=shopping&sort=hotness&type=extension
3. Change the add-on type to "All"

Expected results:
The search results are refined.

Actual results:
"Invalid 'type' parameter" red banner is displayed.

Notes/Issues:
Verified on AMO-stage FF56(Win 7, Android 7.2.1). 
Reproducing on all servers.

Not sure if is not related with https://github.com/mozilla/addons-frontend/issues/3563 .
Screenshot for this issue:

### PR DESCRIPTION
**Pull request by willdurand**
Fix #3747

---

This PR does not display the add-on type select filter when a category filter is set.

## Screenshot

screen shot 2017-11-02 at 14 32 45

### CODE REVIEW

File: tests/unit/amo/components/TestSearchFilters.js [hunk 1]
```diff
@@ -244,4 +244,10 @@ describe(__filename, () => {
       }),
     });
   });
+
+  it('does not display the addonType filter when a category is defined', () => {
```
Comment (tofumatt) [inline tests/unit/amo/components/TestSearchFilters.js]: Referencing the issue here would be good, as this is unexpected behaviour (to me) and I think warrants explanation as to why we do it. Just a link should be good 😄

**Comment by muffinresearch** [comment]
Would it be any better to show it but have it be disabled if we could know in advance that category doesn't exist for that type? It could show a message to explain why underneath as help text.

This would then allow it to be enabled if a category is common between types.

**Comment by muffinresearch** [comment]
We might want to get some UX and product input on this in terms of what the best long term solution should be.

**Comment by tofumatt** [comment]
But category *names* that are common between types would still have a different ID. They’re tied to clientApp and addonType. Nothing should ever really be shared. And I don’t think any are.

- Matt (Sent from mobile)

**Comment by muffinresearch** [comment]
> But category *names* that are common between types would still have a different ID. They’re tied to clientApp and addonType. Nothing should ever really be shared. And I don’t think any are.

Ah ok, not sure why I thought there was overlap. In which case I think this solution makes sense.
