### PR TITLE
Fix SearchInput issues

### LINKED ISSUE #1443: Search box is unresponsive until animation ends
### Describe the problem and steps to reproduce it:
Types characters are ignored while the magnifying glass is animating.

1. Click on the empty search bar.
2. Immediately start typing.

### What happened?
The first few characters are ignored until the animation ends.

### What did you expect to happen?
The characters I type after clicking should all appear in the search bar regardless of the animation state.

### Anything else we should know?
uuuuck mov

### PR DESCRIPTION
**Pull request by mstriemer**
There were two problems with `SearchInput`, when typing immediately after focus keystrokes would be dropped, and when dismissing the virtual keyboard the animation would stop working and this prevented the input from being focused again.

This patch fixes both problems. The text is now transparent until the animation ends so keystrokes are not lost (instead of cancelling the focus event and manually focusing later).

The virtual keyboard issue was due to how the icon is moved over for animating (there are two icons, one on the label and one that animates to the left-aligned position). The `resize` event fires when the keyboard opens or closes and the icon's position would be recalculated but the calculation only worked if the icon had not been positioned yet. The original location of the icon is now saved when the calculation is first done which allows the `setIconPosition` function to correctly position the icon every time it is called.

search-keyboard-dismissal mp4

Fixes #1443 and #1749.

### CODE REVIEW

File: src/ui/components/SearchInput/index.js [hunk 1]
```diff
@@ -30,32 +30,34 @@ export default class SearchInput extends React.Component {
 
   onBlur = () => {
     this.setState({ focus: false });
+    if (!this.value) {
+      // Animation will start if there is no value.
```
Comment (mstriemer) [inline src/ui/components/SearchInput/index.js]: There is no `transitionstart` event so we need to manually detect when we will start animating.

File: src/ui/components/SearchInput/style.scss [hunk 2]
```diff
@@ -20,19 +20,16 @@ $transition-duration: 250ms;
...
-    opacity: 0;
-    position: absolute;
-    transition: opacity 1ms $transition-duration, transform $transition-duration;
-  }
+  opacity: 0;
+  position: absolute;
 }
 
 .SearchInput--text {
-  @include text-align-start();
```
Comment (mstriemer) [inline src/ui/components/SearchInput/style.scss]: This was just moving the label to the left which is hidden in this state so there was no point (and it might have contributed to messing up position calculations in `setIconPosition`.

File: src/ui/components/SearchInput/index.js (hunk 1 above)
Comment (tofumatt) [inline src/ui/components/SearchInput/index.js]: Makes sense, but I'd be fine if we added that comment to the actual code 😄

File: src/ui/components/SearchInput/style.scss [hunk 3]
```diff
@@ -46,6 +43,15 @@ $transition-duration: 250ms;
     opacity: 1;
     // Use !important to overwrite style properties added in JS.
     transform: translateX(0) !important;
+  }
+}
+
+.SearchInput--animating {
+  .SearchInput-animation-icon {
+    transition: opacity 1ms $transition-duration, transform $transition-duration;
```
Comment (tofumatt) [inline src/ui/components/SearchInput/style.scss]: I see `1ms` and `$transition-duration`; I didn't know about that syntax. What does it mean? I thought the third argument was the transition curve, so `duration` seems like the wrong variable.

File: tests/client/ui/TestSearchInput.js [hunk 4]
```diff
@@ -43,40 +51,45 @@ describe('<SearchInput />', () => {
...
-      assert.notOk(event.preventDefault.called);
-      resolve();
-    })
-  ));
+  it('clears the --animating class on transitionend', () => {
+    const root = renderIntoDocument(<SearchInput name="foo" />);
+    root.setState({ animating: true });
+    assert.ok(root.root.classList.contains('SearchInput--animating'));
+    Simulate.transitionEnd(root.animateIcon);
+    assert.notOk(root.root.classList.contains('SearchInput--animating'));
```
Comment (tofumatt) [inline tests/client/ui/TestSearchInput.js]: I would find these a bit easier to read if we did

```js
assert.include(root.root.classList, 'SearchInput--animating');
Simulate.transitionEnd(root.animateIcon);
assert.notInclude(root.root.classList, 'SearchInput--animating');
```

It's shorter but also I think a bit more distinct. 🤷‍♀️

File: src/ui/components/SearchInput/index.js (hunk 1 above)
Comment (mstriemer) [inline src/ui/components/SearchInput/index.js]: Haha, end of the day Mark was trying, he really was! I guess if I'm writing comments on GitHub to explain something they just belong in the code 😛.

File: src/ui/components/SearchInput/style.scss (hunk 3 above)
Comment (mstriemer) [inline src/ui/components/SearchInput/style.scss]: The first one is the duration, the second is the delay. So the icon will get hidden after `$transition-duration` which is when the label re-appears. I might be able to just set this on `SearchInput--animating` now since we have that class. I'll fix it or add a comment.

File: tests/client/ui/TestSearchInput.js (hunk 4 above)
Comment (mstriemer) [inline tests/client/ui/TestSearchInput.js]: `root.root.classList` is one of those things that is like an array but not actually an array. So `assert.include` fails if you try and use it.

```
  <SearchInput />
    ✖ clears the --animating class on transitionend
      Firefox 51.0.0 (Mac OS X 10.12.0)
    object tested must be an array, an object, or a string, but domtokenlist given

      + expected - actual

      
AssertionError@node_modules/chai/chai.js:5553:18
[12]</module.exports@node_modules/chai/chai.js:4285:11
include@node_modules/chai/chai.js:495:5
assert@node_modules/chai/chai.js:4121:24
[6]</module.exports/assert.include@node_modules/chai/chai.js:2994:5
@webpack:///tests/client/ui/TestSearchInput.js:89:4 <- test-runner.js:168913:6

Comment (mstriemer) [inline tests/client/ui/TestSearchInput.js]: Some helpers might make this clearer.

```js
const assertHasClass = (el, className) =>
  assert.ok(el.classList.contains(className));
const assertNotHasClass = (el, className) => 
  assert.notOk(el.classList.contains(className));

  it('clears the --animating class on transitionend', () => {
    const root = renderIntoDocument(<SearchInput name="foo" />);
    root.setState({ animating: true });
    assertHasClass(root.root, 'SearchInput--animating');
    Simulate.transitionEnd(root.animateIcon);
    assertNotHasClass(root.root, 'SearchInput--animating');
  });

Comment (tofumatt) [inline tests/client/ui/TestSearchInput.js]: Oh, shoot, didn't realise that. The helpers totally read better, if that's not a PITA I like it 👍

Otherwise though just a comment explaining why is fine so someone like me who thinks they're clever doesn't bother with it again. I'd say whichever is shorter and more obvious wins (the comment versus the helper) 😉

File: src/ui/components/SearchInput/style.scss (hunk 3 above)
Comment (tofumatt) [inline src/ui/components/SearchInput/style.scss]: Oh gosh, right! I totally knew this but forgot. I think the comment helps because not everyone is familiar with that delay value (and those like me who know but forget will have their memory jogged). 👍

**Comment by tofumatt** [comment]
All the explanations/comments here make total sense, thanks 👍
