### PR TITLE
Show eula

### LINKED ISSUE #2418: No "EULA" displayed in add-on details page on device
Steps to reproduce:
1. Load detail page for an add-on that has an End-User-Agreement set using your Android device i.e. https://addons-dev.allizom.org/en-US/android/addon/url-fixer/?src=ss
2. Check the EULA

Steps to reproduce:
User is able to access the EULA from his device.

Actual results:
EULA is not listed on device.

Notes/Issues:
Verified on FF53(Win 7). Issue is reproducing on all servers.
Screenshot:

### PR DESCRIPTION
**Pull request by tofumatt**
Fixes #2418 

Builds off code in #2420 so it should be merged first.

### CODE REVIEW

File: tests/client/amo/components/TestAddonMoreInfo.js [hunk 1]
```diff
@@ -108,7 +108,23 @@ describe('<AddonMoreInfo />', () => {
...
+    const root = render();
+
+    assert.equal(findDOMNode(root.eulaLink).textContent,
+      'Read the license agreement for this add-on');
+    assert.include(root.eulaLink.props.href, '/addon/chill-out/eula/');
+  });
+
+  it('does not render a EULA if none exists', () => {
+    const partialAddon = deepcopy(fakeAddon);
+    partialAddon.has_eula = false;
```
Comment (kumar303) [inline tests/client/amo/components/TestAddonMoreInfo.js]: I don't think this needs to be a deep copy. You can just do:
````js
const root = render({ 
  addon: {
    ...fakeAddon,
    has_eula: false,
  },
});
````

File: tests/client/amo/components/TestAddonMoreInfo.js [hunk 2]
```diff
@@ -108,7 +108,23 @@ describe('<AddonMoreInfo />', () => {
       'Read the privacy policy for this add-on');
     // TODO: Change this to an internal `<Link>` tag and use `assert.equal`
     // once https://github.com/mozilla/addons-frontend/issues/1828 is fixed.
-    assert.include(root.privacyPolicyLink.href,
+    assert.include(root.privacyPolicyLink.props.href,
       '/addon/chill-out/privacy/');
   });
+
+  it('renders the EULA and link', () => {
+    const root = render();
```
Comment (kumar303) [inline tests/client/amo/components/TestAddonMoreInfo.js]: Since this test requires `eula` data I think it's helpful to explicitly set up the data you are depending on, like:
````js
const root = render({ 
  addon: {
    ...fakeAddon,
    has_eula: true,
  },
});
````

File: tests/client/amo/components/TestAddonMoreInfo.js (hunk 1 above)
Comment (tofumatt) [inline tests/client/amo/components/TestAddonMoreInfo.js]: True, this is just copied from another similar test for privacy policy. But I'll tidy it up.

**Comment by tofumatt** [comment]
Ready for another r? 😄
