### PR TITLE
Fix search input corners and autocomplete

### LINKED ISSUE #3078: Quickly typing a search term does not autocomplete it
### Describe the problem and steps to reproduce it:

Quickly type a word in the search box

### What happened?

The last few characters you type will not be included in the search term. You can verify this in the network panel -- inspect the API request made to the `autocomplete` endpoint. 

For example, if you type "ad block" quickly, the search term will just be "a". If you type a bit slower, you may get more of the word but probably not the whole thing.

### What did you expect to happen?

Autocompletion should always search for the full word you type.

### Anything else we should know?

This is a regression from fixing https://github.com/mozilla/addons-frontend/issues/3064 . We chatted about it in IRC and I think `handleSuggestionsFetchRequested` can immediately call `setState` without a debounce to change its class name. The call to `dispatch(autocompleteStart())` should still be debounced.

### PR DESCRIPTION
**Pull request by willdurand**
Fix #3078
Refs #3077

---

This PR reverts the trailing edge debouncing implementation introduced in #3065. It also get rid of the async `setState` callback. Last but not the least, it provides a different fix for the search input corners.

Having a `isOpen` in the reducer was misleading: with the recent `autocompleteCancel()` change (cancelling the API call and everything else), the input could be desynchronized. Now, the `SearchForm` is synchronized with `Autosuggest` at the component level and it works better.

### CODE REVIEW

File: src/amo/components/SearchForm/index.js [hunk 1]
```diff
@@ -160,7 +166,7 @@ export class SearchFormBase extends React.Component {
       return;
     }
 
-    this.setState({ searchValue: '' }, () => {
+    this.setState({ autocompleteIsOpen: false, searchValue: '' }, () => {
       this.props.router.push(suggestion.url);
```
Comment (kumar303) [inline src/amo/components/SearchForm/index.js]: I think you could safely remove `router.push()` from the `setState` callback too. I don't think it needs to wait for `setState` to resolve -- they are independent actions. It can be:

```js
this.setState({ autocompleteIsOpen: false, searchValue: '' });
this.props.router.push(suggestion.url);
```

File: src/amo/components/SearchForm/index.js [hunk 2]
```diff
@@ -114,20 +114,32 @@ export class SearchFormBase extends React.Component {
...
 
-    const { addonType, dispatch, errorHandler } = this.props;
+    const { addonType } = this.props;
     const filters = { query: value };
 
     if (addonType) {
       filters.addonType = addonType;
     }
 
+    this.setState({ autocompleteIsOpen: true });
```
Comment (kumar303) [inline src/amo/components/SearchForm/index.js]: To make things a little less complex, you could just add the filter change to this and remove it from the dispatch helper:

```js
this.setState({ 
  autocompleteIsOpen: true, oldAutocompleteFilters: filters, 
});
```

File: src/amo/components/SearchForm/index.js [hunk 3]
```diff
@@ -114,20 +114,32 @@ export class SearchFormBase extends React.Component {
...
-  handleSuggestionsFetchRequested = this.props.debounce(({ value, reason }) => {
+  dispatchAutocompleteStart = this.props.debounce(({ filters }) => {
+    const { dispatch, errorHandler } = this.props;
+
+    dispatch(autocompleteStart({
+      errorHandlerId: errorHandler.id,
+      filters,
+    }));
+    this.setState({ oldAutocompleteFilters: filters });
+  }, 200, { leading: true })
```
Comment (kumar303) [inline src/amo/components/SearchForm/index.js]: I know you're relying on defaults here but since you are already specifying an option, it looks like the `debounce` is configured for leading edge only. I would suggest adding them both: `{ leading: true, trailing: true }`.

Comment (kumar303) [inline src/amo/components/SearchForm/index.js]: How does firing this off on the leading edge help? I don't think the first character that someone types would be useful.

Comment (willdurand) [reply src/amo/components/SearchForm/index.js]: I inverted `leading` and `trailing` it seems.

**Comment by willdurand** [comment]
I have made the requested changes and played with it. Seems to work the same (maybe better without leading edge debouncing 😋 )
