### PR TITLE
Remove `componentWillReceiveProps()` in `AutoSearchInput`

### LINKED ISSUE #6771: Remove `componentWillReceiveProps()` in `AutoSearchInput`
See also: #6188 

---

The following patch works but one test case is still failing (see after the patch):

```diff
diff --git a/src/amo/components/AutoSearchInput/index.js b/src/amo/components/AutoSearchInput/index.js
index 2fd203486..91ad64b6d 100644
--- a/src/amo/components/AutoSearchInput/index.js
+++ b/src/amo/components/AutoSearchInput/index.js
@@ -109,6 +109,17 @@ export class AutoSearchInputBase extends React.Component<InternalProps, State> {
     showInputLabel: true,
   };
 
+  static getDerivedStateFromProps(props: InternalProps, state: State) {
+    if (props.query !== state.searchValue) {
+      return {
+        ...state,
+        searchValue: props.query || '',
+      };
+    }
+
+    return null;
+  }
+
   constructor(props: InternalProps) {
     super(props);
     invariant(props.inputName, 'The inputName property is required');
@@ -143,14 +154,6 @@ export class AutoSearchInputBase extends React.Component<InternalProps, State> {
     };
   }
 
-  componentWillReceiveProps(nextProps: InternalProps) {
-    const { query } = nextProps;
-
-    if (this.props.query !== query) {
-      this.setState({ searchValue: query || '' });
-    }
-  }
-
   createFiltersFromQuery(query: string) {
     const { location, userAgentInfo } = this.props;
     // Preserve any existing search filters.
```

Here is the failing test case:

  ● /Users/williamdurand/projects/mozilla/addons-frontend/tests/unit/amo/components/TestAutoSearchInput.js › search input › only sets an updated query if it is unique

    expect(received).toMatchObject(expected)

    Expected value to match object:
      {"value": "panda themes"}
    Received:
      {"className": "AutoSearchInput-query", "id": "AutoSearchInput-query", "maxLength": 100, "minLength": 3, "name": "query", "onChange": [Function anonymous], "placeholder": "Find add-ons", "type": "search", "value": "ad blocker"}
    Difference:
    - Expected
    + Received

      Object {
    -   "value": "panda themes",
    +   "value": "ad blocker",
      }

      134 |       root.setProps({ query });
      135 |
    > 136 |       expect(getInputProps(root)).toMatchObject({ value: typedQuery });
          |                                   ^
      137 |     });
      138 |
      139 |     it('handles typing text into the input', () => {

      at Object.<anonymous> (tests/unit/amo/components/TestAutoSearchInput.js:136:35)

From what I understand, the test case tries to cover the following scenario:

1. set a value for a `query` prop
2. this value is copied to the component's state in the constructor
3. the state is updated via a child component
4. new props are given to the component
5. we expect that the `query` prop is NOT copied to the component's state that time

I find this scenario a bit weird because we assume a state property can be updated by two different "sources", yet not always.

Is that a real life scenario?

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #6771

---

This PR also updates some related files.

### CODE REVIEW

File: src/amo/components/AutoSearchInput/index.js [hunk 1]
```diff
@@ -111,16 +110,6 @@ export class AutoSearchInputBase extends React.Component<InternalProps, State> {
 
   constructor(props: InternalProps) {
     super(props);
-    invariant(props.inputName, 'The inputName property is required');
```
Comment (kumar303) [inline src/amo/components/AutoSearchInput/index.js]: 👍 Cool. We have Flow coverage for all calling components now 🎉

File: src/amo/components/AutoSearchInput/index.js [hunk 2]
```diff
@@ -236,8 +225,12 @@ export class AutoSearchInputBase extends React.Component<InternalProps, State> {
       this.searchInput.blur();
     }
 
-    const filters = this.createFiltersFromQuery(this.state.searchValue);
-    this.props.onSearch(filters);
+    const { onSearch } = this.props;
+
+    if (onSearch) {
+      const filters = this.createFiltersFromQuery(this.state.searchValue);
+      onSearch(filters);
```
Comment (kumar303) [inline src/amo/components/AutoSearchInput/index.js]: I don't see test coverage for not calling this when `onSearch` is undefined. Even though we have Flow it would be nice to get a test for it.

File: tests/unit/amo/components/TestAutoSearchInput.js [hunk 3]
```diff
@@ -108,30 +114,33 @@ describe(__filename, () => {
...
 
-      const query = 'ad blocker';
-      root.setProps({ query });
+      const root = render({ location });
 
-      expect(getInputProps(root)).toMatchObject({ value: query });
+      expect(root).toHaveState('searchValue', '');
     });
 
     it('only sets an updated query if it is unique', () => {
```
Comment (kumar303) [inline tests/unit/amo/components/TestAutoSearchInput.js]: This spec could use an update. I'm not sure if it even made sense with the old code 😛

File: src/amo/components/AutoSearchInput/index.js (hunk 2 above)
Comment (willdurand) [reply src/amo/components/AutoSearchInput/index.js]: If it is `undefined`, how do we test it? 🤔

**Comment by willdurand** [comment]
> It looks good so far but I'm having trouble testing it due to [mozilla/addons-server#9919](https://github.com/mozilla/addons-server/issues/9919)

Interesting. I did not hit this when I tested myself.

File: src/amo/components/AutoSearchInput/index.js (hunk 2 above)
Comment (kumar303) [reply src/amo/components/AutoSearchInput/index.js]: An adequate test would be to trigger a search with an undefined `onSearch` prop and make sure no errors are thrown. For example, this would have thrown an error:

```diff
diff --git a/src/amo/components/AutoSearchInput/index.js b/src/amo/components/AutoSearchInput/index.js
index dc99b8af4..1ca6c95b7 100644
--- a/src/amo/components/AutoSearchInput/index.js
+++ b/src/amo/components/AutoSearchInput/index.js
@@ -227,10 +227,8 @@ export class AutoSearchInputBase extends React.Component<InternalProps, State> {
 
     const { onSearch } = this.props;
 
-    if (onSearch) {
-      const filters = this.createFiltersFromQuery(this.state.searchValue);
-      onSearch(filters);
-    }
+    const filters = this.createFiltersFromQuery(this.state.searchValue);
+    onSearch(filters);
   };
 
   handleSearchChange = (
```

However, I thought about it more. I think it's OK to just rely on type safety here. No need to add a test.

File: tests/unit/amo/components/TestAutoSearchInput.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (willdurand) [reply tests/unit/amo/components/TestAutoSearchInput.js]: wfm
