### PR TITLE
i-4541 fixes slug leading dash issue

### LINKED ISSUE #4541: Impossible to load an add-on detail page when its slug begins with a dash followed by only numbers
### Describe the problem and steps to reproduce it:
1. Submit an add-on with a slug being a dash (`-`) followed by numbers only.
2. Wait for it to be approved, visit its listing page

### What happened?
On the new frontend, the detail page only shows placeholder content.
37206690-6cd2b0e2-23a2-11e8-85ba-61dd1bc2bb60

### What did you expect to happen?
It should be loaded without any issues. The legacy site works fine in this case.

### Anything else we should know?
Changing the slug to a dash followed by some letters works fine.

There are a few hundred add-ons (probably exclusively themes that were imported with a blank name a long time ago, see mozilla/addons-server#7599) on prod that are affected.

### PR DESCRIPTION
**Pull request by rebmullin**
fixes #4541 - adds a few more checks for slug before trying to redirect

### CODE REVIEW

File: src/amo/components/Addon/index.js [hunk 1]
```diff
@@ -546,10 +553,13 @@ export function mapStateToProps(state, ownProps) {
...
   let addon = getAddonBySlug(state, slug);
 
+  // make sure slug is number or string without leading -
   // It is possible to load an add-on by its ID but in the routing parameters,
   // the parameter is always named `slug`.
   // eslint-disable-next-line no-restricted-globals
-  if (slug && !isNaN(slug)) {
+  if (slug && !isNaN(slug)
+    && ((typeof slug === 'string' && slug.charAt(0) !== '-')
+    || (typeof slug === 'number'))) {
```
Comment (willdurand) [inline src/amo/components/Addon/index.js]: This makes me think that we should probably extract all these checks into a single utility function above the component.

File: src/amo/components/Addon/index.js [hunk 2]
```diff
@@ -107,8 +107,15 @@ export class AddonBase extends React.Component {
     // of an error.
     if (!errorHandler.hasError()) {
       if (addon) {
+        const { slug } = params;
+
+        // make sure slug is number or string without leading -
+        // before redirecting
```
Comment (willdurand) [inline src/amo/components/Addon/index.js]: We tend to write comments as full English sentences.

File: tests/unit/amo/components/TestAddon.js [hunk 3]
```diff
@@ -461,6 +461,25 @@ describe(__filename, () => {
     sinon.assert.callCount(fakeDispatch, 1);
   });
 
+  it('does not dispatch a server redirect when slug is a stringified integer that starts with -', () => {
+    const clientApp = CLIENT_APP_FIREFOX;
```
Comment (willdurand) [inline tests/unit/amo/components/TestAddon.js]: Could you maybe add the link to the GitHub issue in a comment?

File: tests/unit/amo/components/TestAddon.js [hunk 4]
```diff
@@ -461,6 +461,25 @@ describe(__filename, () => {
...
+    const addon = createInternalAddon({
+      ...fakeAddon,
+      slug: '-1234',
+    });
+
+    store.dispatch(_loadAddons({ addon }));
+
+    const fakeDispatch = sinon.spy(store, 'dispatch');
+    renderComponent({
+      params: { slug: `-${addon.id}` }, store,
```
Comment (willdurand) [inline tests/unit/amo/components/TestAddon.js]: why not using `addon.slug`?

Comment (rebmullin) [reply tests/unit/amo/components/TestAddon.js]: yep - thanks : )

File: src/amo/components/Addon/index.js (hunk 2 above)
Comment (rebmullin) [reply src/amo/components/Addon/index.js]: ahh! ok..

**Comment by rebmullin** [comment]
hey @willdurand  - thanks for the feedback. i've updated... when you can please take another look : )

File: src/amo/components/Addon/index.js [hunk 5]
```diff
@@ -60,6 +60,14 @@ import ShowMoreCard from 'ui/components/ShowMoreCard';
 import './styles.scss';
 
 
+// Find out if slug is invalid.
+const isInvalidSlugID = (slug) => {
```
Comment (willdurand) [inline src/amo/components/Addon/index.js]: The slug is not really invalid actually, it is "just" not a string no? If so, we should probably update the function name.

File: src/amo/components/Addon/index.js [hunk 6]
```diff
@@ -60,6 +60,14 @@ import ShowMoreCard from 'ui/components/ShowMoreCard';
...
+  // eslint-disable-next-line no-restricted-globals
+  return slug && !isNaN(slug)
+    && ((typeof slug === 'string' && slug.charAt(0) !== '-')
+    || (typeof slug === 'number'));
```
Comment (willdurand) [inline src/amo/components/Addon/index.js]: We should have a test case for this too and I don't see one.

File: src/amo/components/Addon/index.js [hunk 7]
```diff
@@ -107,8 +115,11 @@ export class AddonBase extends React.Component {
     // of an error.
     if (!errorHandler.hasError()) {
       if (addon) {
-        // eslint-disable-next-line no-restricted-globals
-        if (!isNaN(params.slug)) {
+        const { slug } = params;
+
+        // We want to make sure the slug is invalid before
+        // before we try redirecting.
```
Comment (willdurand) [inline src/amo/components/Addon/index.js]: `before` appears twice in this sentence.

File: tests/unit/amo/components/TestAddon.js [hunk 8]
```diff
@@ -461,6 +461,26 @@ describe(__filename, () => {
...
+    const addon = createInternalAddon({
+      ...fakeAddon,
+      slug: '-1234',
+    });
+
+    store.dispatch(_loadAddons({ addon }));
+
+    const fakeDispatch = sinon.spy(store, 'dispatch');
+    renderComponent({
+      params: { slug: `${addon.slug}` }, store,
```
Comment (willdurand) [inline tests/unit/amo/components/TestAddon.js]: so I guess, we could write: `{ slug: addon.slug },` no?

Comment (rebmullin) [reply tests/unit/amo/components/TestAddon.js]: 🤦‍♂️ yes...

File: src/amo/components/Addon/index.js (hunk 7 above)
Comment (rebmullin) [reply src/amo/components/Addon/index.js]: opps..yepp

File: src/amo/components/Addon/index.js (hunk 6 above)
Comment (rebmullin) [reply src/amo/components/Addon/index.js]: thanks i'll take another look..

File: src/amo/components/Addon/index.js (hunk 5 above)
Comment (rebmullin) [reply src/amo/components/Addon/index.js]: hmm yeh i'll take another look at the name, thanks

File: src/amo/components/Addon/index.js (hunk 6 above)
Comment (rebmullin) [reply src/amo/components/Addon/index.js]: hey @willdurand  - do you mean if it's actually a number? I guess i thought this test was covered under `dispatches a server redirect when slug is a numeric ID` - or let me know which piece.. maybe i misunderstood..?

Comment (rebmullin) [reply src/amo/components/Addon/index.js]: it also checks for all these pieces with the following tests:
`dispatches a server redirect when slug is a numeric ID`
`dispatches a server redirect when slug is a stringified integer`
`does not dispatch a server redirect when slug is a stringified integer that starts with -`

 i believe this covers all these pieces? are you saying these should be combined into one test?

Comment (willdurand) [reply src/amo/components/Addon/index.js]: It is probably fine. I was a bit confused because we did not check the type before but you have to do it because you check the first char.

Comment (willdurand) [reply src/amo/components/Addon/index.js]: Maybe we could get rid of the parentheses btw

File: src/amo/components/Addon/index.js (hunk 5 above)
Comment (rebmullin) [reply src/amo/components/Addon/index.js]: actually from my understanding it could be a number type (legacy) or it could be a string which looks like a number (1234) - either of these cases should redirect. The problem was there are some strings like '-1234' which look like a number but we need to exclude these cases (not redirect)... so i am not sure of a better name - maybe `isSlugValidNumber` ?

File: src/amo/components/Addon/index.js (hunk 6 above)
Comment (rebmullin) [reply src/amo/components/Addon/index.js]: right..i added type check b/c of charAt piece...

i actually had some less parentheses but linting complained (`Unexpected mix of '&&' and '||'  no-mixed-operators`) unless i did i this way..

File: src/amo/components/Addon/index.js (hunk 5 above)
Comment (willdurand) [reply src/amo/components/Addon/index.js]: How about `slugIsID`?

**Comment by rebmullin** [comment]
yes..you're right and i think that might be a better/cleaner approach. I will try to update the code this..
