### PR TITLE
Use native install notifications when permissionPromptsEnabled is true

### LINKED ISSUE #1679: 2 confirmation pop-ups for add-ons installed via DiscoPane
**Note:**
See https://bugzilla.mozilla.org/show_bug.cgi?id=1308310

**Steps to reproduce:**
1.Launch Firefox with clean profile.
2.Create extensions.webextPermissionPrompts and set it to true.
3.Restart the browser.
4.Navigate to Add- ons Manager -> Get Add- ons
5.Enable Block ads add-on.

**Expected Results:**
DiscoPane confirmation doorhanger (Your add-on is ready) is no longer displayed.

**Actual Results:**
- There are 2 confirmation pop-ups displayed.
- This issue reproduces on Firefox 54.0a1 (2017-01-30) under Windows 10 64-bit.
- See attached screenshot:

### PR DESCRIPTION
**Pull request by muffinresearch**
Fixes #1679 

Conditionally dispatch the install notification based on detecting `extensions.webextPermissionPrompts`. 

With `extensions.webextPermissionPrompts` set to false:

fullscreen_06_02_2017__18_16

With `extensions.webextPermissionPrompts` set to true:

fullscreen_06_02_2017__18_15

### CODE REVIEW

File: src/core/addonManager.js [hunk 1]
```diff
@@ -12,14 +12,22 @@ import { addQueryParams } from 'core/utils';
 const testHasWindow = () => typeof window !== 'undefined';
 
 export function hasAddonManager({ hasWindow = testHasWindow, navigator } = {}) {
-  // Returns undefined if it cannot be determined if mozAddonManager is supperted (likely server
+  // Returns undefined if it cannot be determined if mozAddonManager is supported (likely server
```
Comment (kumar303) [inline src/core/addonManager.js]: I assumed that was the British spelling 😭 😭 jk
