### PR TITLE
Add placeholder test and fix locales

### LINKED ISSUE #9566: 500 Errors on nn-NO locale for 404
Go to https://addons.mozilla.org/nn-NO/firefox/addon/mx4/

This should be a 404 but it's a 500 due to a locale placeholder issue. This was also highlighted in Google Analytics.

### PR DESCRIPTION
**Pull request by muffinresearch**
Fixes #9566

Interestingly adding a test for this highlighted a bunch of other errors.

### CODE REVIEW

File: tests/unit/test_localesConfig.js [hunk 1]
```diff
@@ -11,6 +11,8 @@ import { langToLocale, localeToLang } from 'core/i18n/utils';
 const langs = config.get('langs');
 const basePath = config.get('basePath');
 
+const placeholderRX = /%\(.*?\)s/g;
```
Comment (willdurand) [inline tests/unit/test_localesConfig.js:14]: `RX`? 🤔

Comment (muffinresearch) [reply tests/unit/test_localesConfig.js:14]: That's shorthand for Regex, would you prefer something else?

Comment (muffinresearch) [reply tests/unit/test_localesConfig.js:14]: I'm going to land this to avoid it bit-rotting due to incoming locale changes. But if you'd like this changed I can do a quick follow-up.

Comment (willdurand) [reply tests/unit/test_localesConfig.js:14]: yes, pattern or regex would be nice
