### PR TITLE
Don't pass non-strings into Autosuggest

### LINKED ISSUE #11004: Don't pass non-strings into Autosuggest
As described at https://github.com/moroshko/react-autosuggest/issues/368#issuecomment-302985738, `Autosuggest` expects that `inputProps.value` be a string, and will throw exceptions if it is not. One can create a non-string value for `inputProps.value` by using a querystring that makes `q` look like an object, for example `?q[0]=a&q[1]=b` (or even just `?q[0]=a`). Our code needs to make sure that this value never gets passed into `Autosuggest`.

The code for this is at https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/AutoSearchInput/index.js#L337-L352, and the logic which creates `inputProps` is at https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/AutoSearchInput/index.js#L298-L308. Note that `value` comes from `this.state.searchValue`, and `this.state.searchValue` [is initially set to `location.query[inputName]`](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/AutoSearchInput/index.js#L125-L135). It therefore seems like the optimal solution to this is to *not* set `this.state.searchValue` to `location.query[inputName]` if `location.query[inputName]` is not a string, and to just set `this.state.searchValue` to an empty string if that is the case.

`location.query[inputName]` will only be a non-string if someone purposely puts a bad querystring on the url.

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #11004

### CODE REVIEW

File: tests/unit/amo/components/TestAutoSearchInput.js [hunk 1]
```diff
@@ -133,6 +133,14 @@ describe(__filename, () => {
       expect(root).toHaveState('searchValue', '');
     });
 
+    it('sets the search value to an empty string when `location.query` is not a string', () => {
+      const location = createFakeLocation({ query: { query: ['a', 'b'] } });
```
Comment (eviljeff) [inline tests/unit/amo/components/TestAutoSearchInput.js:137]: can we test with queries in the form of array indexes too, like `q[0]`?

**Review by eviljeff — APPROVED** [review]

File: tests/unit/amo/components/TestAutoSearchInput.js (hunk 1 above)
Comment (bobsilverberg) [reply tests/unit/amo/components/TestAutoSearchInput.js:137]: That's what I am attempting to do here. It's `react-router` that is taking the value from the URL and populating `location.query`, so when we are manually creating a `location` here in the test, we are providing a value that looks like what `react-router` would have done. It converts a querystring like `?query[0]=a&query[1]=b` into an array that looks like `query: ['a', 'b']`, so that's what I am using in the test.

Really, because the new code excludes anything that isn't a string, we could have used any non-string value in this test, but I wanted to use something that resembles what is happening in the real world with this bug.

Does that make sense?

Comment (eviljeff) [reply tests/unit/amo/components/TestAutoSearchInput.js:137]: I wouldn't have guessed that `query: ['a', 'b']` would be converted to `?query[0]=a&query[1]=b` (I would have guessed something like `?query=a&query=b` or `?query=[a,b]`) but sure?

Comment (eviljeff) [reply tests/unit/amo/components/TestAutoSearchInput.js:137]: To satisfy my curiosity could we have an assertion on the following line that `createFakeLocation` _does_ render `location` to a string like that?

Comment (bobsilverberg) [reply tests/unit/amo/components/TestAutoSearchInput.js:137]: I don't think we can do exactly what you want. `createFakeLocation` generates an object that looks like a `location` that has already been parsed by `react-router`, so nothing in there is going to resemble `?query[0]=a&query[1]=b`. That's what the URL looks like *before* it is parsed, but we are eliminating the parsing code and just directly creating the result.

Comment (eviljeff) [reply tests/unit/amo/components/TestAutoSearchInput.js:137]: 🤷 I guess we have to trust that it's what would be generated then (the problem with unit tests)

Comment (bobsilverberg) [reply tests/unit/amo/components/TestAutoSearchInput.js:137]: Yes, but, as I mentioned above, the test is perfectly good for testing the code that was changed, as all it's doing it looking for anything that isn't a string. We really need a functional test to test that the bug is fixed, but that's why I always test things manually as well.
