### PR TITLE
I6928 guides pg dble load fix

### LINKED ISSUE #6928: The Guides index page should not double load data
### Describe the problem and steps to reproduce it:

- Go to a guides page, such as http://localhost:3000/en-US/firefox/guides/privacy/ (this isn't available on hosted dev yet)

### What happened?

When the page loads on the client, you can use the Redux tool to see that `FETCH_GUIDES_ADDONS` is dispatched.

### What did you expect to happen?

`FETCH_GUIDES_ADDONS` should not be dispatched on the client because it was already dispatched on the server. You can see this in the console logs:

```
[server|amo] Dispatching FETCH_GUIDES_ADDONS 
```

When it is dispatched twice, the API request to load the data is also made twice. The API request should only be made once.

### Anything else we should know?

Follow up to https://github.com/mozilla/addons-frontend/issues/6661

The pattern for preventing double loading looks like this:

```js
class MyComponent extends React.Component {
  constructor() {
    const { data, dispatch, isLoading } = this.props;
    if (!isLoading && data === undefined) {
      dispatch(loadTheData());
    }
  }
}
```

Here is an explanation:
* The `data` prop would be mapped to something in the state
* Dispatching `loadTheData()` would trigger a saga to make an API request and eventually populate `data` in state. If the API request results in *no data* then the state would be populated with `data: null`
* The loader needs to check `isLoading` to make sure a fetch is not currently in progress.

### PR DESCRIPTION
**Pull request by rebmullin**
fixes #6928

### CODE REVIEW

File: src/amo/pages/Guides/index.js [hunk 1]
```diff
@@ -119,14 +120,16 @@ export class GuidesBase extends React.Component<InternalProps> {
...
-    const { errorHandler, guids } = this.props;
+    const { addons, errorHandler, guids, loading } = this.props;
 
-    this.props.dispatch(
-      fetchGuidesAddons({
-        guids,
-        errorHandlerId: errorHandler.id,
-      }),
-    );
+    if (!loading && Object.keys(addons).length === 0) {
```
Comment (willdurand) [inline src/amo/pages/Guides/index.js]: We should think about the case where no addons are returned by the API. This code will try to always re-fetch the add-ons.

I believe you could make `addons` nullable in the Flow type, and change a bit the logic in `mapStateToProps()` so that either we have a map of `addons` or `null`. Or maybe, you could always initialize the map with the result of `getAddonByGUID()`.

File: tests/unit/amo/pages/TestGuides.js [hunk 2]
```diff
@@ -59,18 +58,43 @@ describe(__filename, () => {
...
+    const errorHandler = createStubErrorHandler();
+
+    render({ errorHandler, store });
 
     const content = getContent('privacy', fakeI18n());
     const guids = content.sections.map((section) => section.addonGuid);
 
+    sinon.assert.calledOnce(dispatchSpy);
+
     sinon.assert.calledWith(
```
Comment (willdurand) [inline tests/unit/amo/pages/TestGuides.js]: I believe we put the `calledOnce` after `calledWith`.

Comment (rebmullin) [reply tests/unit/amo/pages/TestGuides.js]: oh okay, I thought it was the other way around but sure I'll update..

**Comment by rebmullin** [comment]
@willdurand, how's it look now?

File: src/amo/pages/Guides/index.js [hunk 3]
```diff
@@ -35,14 +35,15 @@ type AddonsMap = {|
 
 type InternalProps = {|
   ...Props,
-  addons: AddonsMap | {},
+  addons: AddonsMap | {} | null,
```
[the remark this answers is not in the document]
Comment (willdurand) [reply src/amo/pages/Guides/index.js]: I see that you use the strict notation `{| ... |}` for the map, which means it must be a non-empty map. You can relax this constraint by using the non-strict notation: `{ ... }` and allow an empty map.

File: src/amo/pages/Guides/index.js [hunk 4]
```diff
@@ -399,10 +402,11 @@ export const mapStateToProps = (
   });
 
   return {
-    addons,
-    guids,
+    addons: Object.keys(addons).length !== 0 ? addons : null,
```
[the remark this answers is not in the document]
Comment (rebmullin) [reply src/amo/pages/Guides/index.js]: it is. I guess I didn't understand :/

File: src/amo/pages/Guides/index.js [hunk 5]
```diff
@@ -327,7 +330,7 @@ export class GuidesBase extends React.Component<InternalProps> {
         });
       }
 
-      const addon = addons[section.addonGuid] || null;
+      const addon = addons ? addons[section.addonGuid] : null;
```
[the remark this answers is not in the document]
Comment (rebmullin) [reply src/amo/pages/Guides/index.js]: I believe this is fixed by your suggested changes

[the remark this answers is not in the document]
Comment (willdurand) [reply src/amo/pages/Guides/index.js]: yep

**Comment by rebmullin** [comment]
thanks for all the work shown above @willdurand ++. 

so this is better because if `getAddonByGUID(state, guid)` returns null, then we won't re-fetch b/c we know we've already fetched because `addons[guid]` will still be set and it will not pass our check in the constructor a 2nd time? I'm still a little bit trying to wrap my head around how the change of the sequence does this. Anyway, this is my understanding and just wanted to "talk" it out. So I *think* that makes sense how I've described it above (assuming this is correct:)

**Comment by willdurand** [comment]
> so this is better because if `getAddonByGUID(state, guid)` returns null, then we won't re-fetch b/c we know we've already fetched because `addons[guid]` will still be set and it will not pass our check in the constructor a 2nd time?

Yep. In fact, we need a way to transfer the knowledge from the server to the client, because when the server fetches the data, it puts the data into the (redux) state. The state is serialized and sent to the client. Then, the client initializes with this state. It creates the component and therefore it calls the constructor.

In order to know if a fetch has been performed in the client, we need to set something into the state. `loading` is not enough because when the server sends the response, it does not load anymore (it has the data).

This is also needed to avoid re-fetching the data if there is no corresponding add-on for any `guid` (this should not happen, but still). If you create the addon map from the `guids` as before, then you cannot determine if the map is empty because nothing has been fetched or because of "no results". By creating the map with the `guids` stored into the state after a `fetch`, you know that an empty map (or a map with `null` values) means "no results".

By creating the `addons` with the `guids` from the state, we ensure that a fetch has been performed, otherwise there would be no `guids`. That way, on the client, we know that a fetch has been performed if the state already contains some `guids`.

File: src/amo/reducers/guides.js [hunk 6]
```diff
@@ -44,6 +46,7 @@ const reducer = (
     case FETCH_GUIDES_ADDONS:
       return {
         ...state,
+        guids: action.payload.guids,
         loading: true,
```
Comment (willdurand) [inline src/amo/reducers/guides.js]: Do we have tests for that?

File: tests/unit/amo/pages/TestGuides.js [hunk 7]
```diff
@@ -120,11 +144,20 @@ describe(__filename, () => {
...
       ...fakeAddon,
       guid: guids[0],
     };
 
+    store.dispatch(
+      fetchGuidesAddons({
+        guids,
+        errorHandlerId: errorHandler.id,
+      }),
+    );
```
Comment (willdurand) [inline tests/unit/amo/pages/TestGuides.js]: Why do you need this?

Comment (rebmullin) [reply tests/unit/amo/pages/TestGuides.js]: otherwise addon is null

File: src/amo/reducers/guides.js (hunk 6 above)
Comment (rebmullin) [reply src/amo/reducers/guides.js]: oops..I'll add

File: tests/unit/amo/pages/TestGuides.js [hunk 8]
```diff
@@ -68,9 +69,32 @@ describe(__filename, () => {
...
+        errorHandlerId: errorHandler.id,
       }),
     );
+
+    const dispatchSpy = sinon.spy(store, 'dispatch');
+
+    render({ store });
+
+    sinon.assert.notCalled(dispatchSpy);
   });
```
Comment (willdurand) [inline tests/unit/amo/pages/TestGuides.js]: We could have a similar test case to load empty results and make sure it does not dispatch (the second part of the `if` in the constructor).

File: tests/unit/amo/reducers/test_guides.js [hunk 9]
```diff
@@ -27,5 +27,15 @@ describe(__filename, () => {
 
       expect(newState.loading).toEqual(false);
     });
+
+    it('adds the guids', () => {
```
Comment (willdurand) [inline tests/unit/amo/reducers/test_guides.js]:
```suggestion
    it('stores the add-on GUIDs', () => {
```

**Comment by rebmullin** [comment]
thanks @willdurand

File: tests/unit/amo/pages/TestGuides.js [hunk 10]
```diff
@@ -69,9 +70,59 @@ describe(__filename, () => {
...
+    // This simulates the initial fetch for addons.
+    store.dispatch(
+      fetchGuidesAddons({
+        guids: [guid],
+        errorHandlerId: errorHandler.id,
       }),
     );
+
+    // This simulates loading addons which updates the loading state.
+    _loadAddonResults(store);
```
Comment (willdurand) [inline tests/unit/amo/pages/TestGuides.js]: You should probably use:

```js
store.dispatch(loadAddonResults({  addons });
```

and not inject `addons` in `render()`

Comment (rebmullin) [reply tests/unit/amo/pages/TestGuides.js]: I think you've already fixed this but yes I learned that we should not inject mapStateToProps vars here ,right? Still got to learn a bit more about testing:)

Comment (willdurand) [reply tests/unit/amo/pages/TestGuides.js]: Yep, we should only inject props declared in `Props`, not from `InternalProps`. Unfortunately we still have a few test cases like this...

Comment (kumar303) [reply tests/unit/amo/pages/TestGuides.js]: The rationale for this is that when we inject a mapped prop in a test, we are bypassing all of our mapping logic and moving away from real life usage. If we dispatch the Redux action instead, the test will cover the mapping logic which ensures that the component is working correctly. Additionally, dispatching the Redux action will keep the test in sync with the state and reducers which is what we want.
