### PR TITLE
fix: Render carousel on client to fix CSP errors (fix #3349)

### LINKED ISSUE #3349: Homepage carousel fails CSP
The homepage fails to load with CSP enabled on first page load if you are loading the home page (eg. https://addons-dev.allizom.org/en-GB/firefox/). This results in the homepage looking messed up:

screenshot 2017-10-04 22 01 48

Navigate to the homepage from another page and it's fine:

screenshot 2017-10-04 22 02 10

This is because CSP is blocking it from loading a `<style>` tag.

Possibly related to https://github.com/FormidableLabs/nuka-carousel/issues/182. Hopefully an easy fix!

### PR DESCRIPTION
**Pull request by tofumatt**
fix #3349 

No need for two reviews, just whoever gets to it first (feel free to clear the other person once you start reviewing it).

This fixes the CSP error on the carousel by rendering it on the client after `componentDidMount` runs. It's not lovely but it looks nice enough without huge jumps and it works. Pretty much any carousel, by their nature modifying style props, would require this 😢

### CODE REVIEW

**Comment by tofumatt** [comment]
Note: I tested this using a production build with CSP enabled. You can too by following: https://github.com/mozilla/addons-frontend#building-and-running-services

**Comment by willdurand** [comment]
I am reviewing this PR and I cannot get the expected result it seems 😞 I have followed the instructions in the README but the carousel does not render correctly on page hit, see the Gif where I have to navigate to another page before getting it right:

**Comment by willdurand** [comment]
Mmmh the HTML sent by the server does not contain any `Carousel` HTML:

screen shot 2017-10-05 at 10 38 25

**Comment by willdurand** [comment]
The HTML sent by the server does not have any `Carousel` HTML in it:

screen shot 2017-10-05 at 10 38 25

**Comment by tofumatt** [comment]
Okay, rebased onto master and all set for review. Sorry I mucked this up.

File: src/ui/components/Carousel/index.js [hunk 1]
```diff
@@ -16,31 +18,80 @@ type PropTypes = {|
...
-        }))}
-      </NukaCarousel>
-    </Card>
-  );
-};
+        {this.state.hasRendered ? (
+          <NukaCarousel
+            autoplay
+            autoplayInterval={4000}
+            cellAlign={getDirection(i18n.lang) === 'ltr' ? 'left' : 'right'}
```
Comment (willdurand) [inline src/ui/components/Carousel/index.js]: Didn't see this before, but shouldn't we have constants for that? It would avoid case issues. If so, then I could open a PR because it is unrelated.

https://github.com/mozilla/addons-frontend/blob/92b83273ba0c86ab750e92faf1c8e5a50c033aa8/src/core/i18n/utils.js#L104-L106

File: src/ui/components/Carousel/styles.scss [hunk 2]
```diff
@@ -48,6 +48,38 @@ $extraHeightForCard: 28px;
   }
 }
 
+.Carousel--first-render-wrapper .Card-contents {
+  // HACK: This fixes RTL glitches in the NukaCarousel we will eventually
+  // fix properly. This means te content in RTL doesn't change order after
+  // the client re-render.
+  direction: ltr;
```
Comment (willdurand) [inline src/ui/components/Carousel/styles.scss]: 👍

File: src/ui/components/Carousel/index.js (hunk 1 above)
Comment (willdurand) [reply src/ui/components/Carousel/index.js]: See 3362
