### PR TITLE
I5703 fixing scaled icon flash

### LINKED ISSUE #5703: A glitch appears when opening a theme listing page
STR:

1. Load AMO -dev
2. Select a theme to view its listing page

Actual result:
A glitch appears (a zoomed in default icon) right before the theme details page is loaded

Expected result:
There are no display issues when visiting a theme details page

Notes:
- reproduced on AMO dev with FF61, Win10x64 and Android 8.0
- the issue is also visible on stage but a little bit less pronounced 

theme icon glitch

### PR DESCRIPTION
**Pull request by rebmullin**
fixes #5703 

From what I could tell the url was changed in the src *after* the classname was updated and for a split second you see the icon large b/c it takes on the new classname styles:

Alt text

In the header, the only way that I found that fixes this is to change the html structure or to use a key on the image/wrapping div. This might be another reconciliation issue (?). I decided to go the html approach - changing out a div for a span. let me know what you think..

note: i did a little bit of clean up too : )

### CODE REVIEW

File: src/amo/components/Addon/index.js [hunk 1]
```diff
@@ -154,43 +160,31 @@ export class AddonBase extends React.Component {
...
       );
     }
 
-    const iconUrl = getAddonIconUrl(addon);
-
     return (
-      <div className="Addon-icon">
-        <img className="Addon-icon-image" alt="" src={iconUrl} />
-      </div>
+      <span className="Addon-icon">
```
Comment (willdurand) [inline src/amo/components/Addon/index.js]: Ah well, that's a bit annoying to have to do that but I understand. Would adding `key` work though? I'd like to use `key` over `span` because it is more the react way.

File: tests/unit/amo/components/TestAddon.js [hunk 2]
```diff
@@ -298,6 +298,8 @@ describe(__filename, () => {
 
     // Since withInstallHelpers relies on this, make sure it's initialized.
     expect(root.instance().props.platformFiles).toEqual({});
+
+    expect(root.find('.Addon-icon img').prop('alt')).toEqual('');
```
Comment (willdurand) [inline tests/unit/amo/components/TestAddon.js]: Could we set the value to `null` so that it would not render an empty `alt` attribute?

File: src/amo/components/Addon/index.js (hunk 1 above)
Comment (rebmullin) [reply src/amo/components/Addon/index.js]: yep seems to works too so I can switch : )

File: tests/unit/amo/components/TestAddon.js (hunk 2 above)
Comment (rebmullin) [reply tests/unit/amo/components/TestAddon.js]: oh I thought empty attribute was better than leaving it off but sure I can update

File: src/amo/components/Addon/index.js [hunk 3]
```diff
@@ -154,42 +160,35 @@ export class AddonBase extends React.Component {
...
-      );
+      const themeClassName = 'Addon-theme-header';
 
       return (
         <div
-          className="Addon-theme-header"
-          id="Addon-theme-header"
+          key="Addon-theme-image"
+          className={themeClassName}
+          id={themeClassName}
```
Comment (willdurand) [inline src/amo/components/Addon/index.js]: Do we really need an `id` here? I find it strange to use the `themeClassName`. If the `id` is not useful, let's remove it and also remove the `themeClassName`.

File: src/amo/components/Addon/index.js [hunk 4]
```diff
@@ -154,42 +160,35 @@ export class AddonBase extends React.Component {
...
+            src={previewURL}
+          />
         </div>
       );
     }
 
-    const iconUrl = getAddonIconUrl(addon);
-
     return (
       <div className="Addon-icon">
```
Comment (willdurand) [inline src/amo/components/Addon/index.js]: Don't we need a key here too?

File: tests/unit/amo/components/TestSearchResult.js [hunk 5]
```diff
@@ -177,6 +177,16 @@ describe(__filename, () => {
     expect(root.find('.SearchResult-icon')).not.toHaveProp('alt', '');
   });
 
+  it('renders a loading class name while there is no addon', () => {
+    const root = render({
```
Comment (willdurand) [inline tests/unit/amo/components/TestSearchResult.js]: Could be put on a single line.

File: src/amo/components/Addon/index.js (hunk 3 above)
Comment (rebmullin) [reply src/amo/components/Addon/index.js]: Yeh I guess I just left it b/c it was there already. Sure I can remove this

File: src/amo/components/Addon/index.js (hunk 4 above)
Comment (rebmullin) [reply src/amo/components/Addon/index.js]: I didn't seem like it was needed but to be sure I can add this here too
