### PR TITLE
fix: Use convertFiltersToQueryParams on LandingPage

### LINKED ISSUE #1542: addontype query param is sent instead of type from landing page
Easy fix, coming in a second.

### PR DESCRIPTION
**Pull request by tofumatt**
fix #1542.

I should have been using `convertFilterstoQueryParams` here and wasn't, so the extension type wasn't being passed to search.

### CODE REVIEW

**Comment by tofumatt** [comment]
Yeah, there's another PR I have in the queue for that which will use real URLs... I guess I can just make them real now and fill in the pages later. I'll do that an merge it in.

**Comment by tofumatt** [comment]
Oh and the `Link` component's `to` prop converts query objects to params which I like more than actually manually adding in the query string ourselves.

File: src/amo/components/LandingPage.js [hunk 1]
```diff
@@ -28,7 +28,10 @@ export class LandingPageBase extends React.Component {
         featuredHeader: i18n.gettext('Featured extensions'),
         // TODO: Add this search/route, see:
```
Comment (tofumatt) [inline src/amo/components/LandingPage.js]: Actually I have the TODO above here to convert it later; I'll do that then.
