### PR TITLE
fix: Outgoing add-on links (fix #1859)

### LINKED ISSUE #1859: URL should be truncated if too long and outgoing prefix removed from text
Steps to reproduce:
1.On Android, open https://addons-dev.allizom.org/en-US/android/addon/gotomeeting
2.Go to More information section
3.Observe the address listed under _Website_

Expected results:
The _Website_ should be should be a link to the website page like on desktop

Actual results:
The address displayed is the _outgoin.stage.mozaws,.net..._ long address 

NOTES:
Desktop link to same add-on : https://addons-dev.allizom.org/en-US/firefox/addon/gotomeeting/?src=ss

Please see screenshot of this issue : 
linkify

### PR DESCRIPTION
**Pull request by tofumatt**
fix #1859 

### Before
linkify

### After
screen shot 2017-02-24 at 00 19 29
screen shot 2017-02-24 at 00 19 20

### CODE REVIEW

File: src/amo/components/AddonMoreInfo.js [hunk 1]
```diff
@@ -16,21 +17,25 @@ export class AddonMoreInfoBase extends React.Component {
...
       <Card className="AddonMoreInfo" header={i18n.gettext('More information')}>
         <dl className="AddonMoreInfo-contents">
-          {addon.homepage ? <dt>{i18n.gettext('Website')}</dt> : null}
-          {homepage ? (
-            <dd>
-              <a href={homepage}
-                ref={(ref) => { this.homepageLink = ref; }}>
-                {homepage.replace(/^https?:\/\//, '')}
-              </a>
+          {addon.homepage ? <dt>{i18n.gettext('Add-on Links')}</dt> : null}
```
Comment (muffinresearch) [inline src/amo/components/AddonMoreInfo.js]: The dt will only be shown when addon.homepage is available. Presumably it should now be on the basis of either a homepage link or support url?

**Comment by tofumatt** [comment]
Okay, updated with screenshots and better tests/code. All set for r?

**Comment by muffinresearch** [comment]
I wonder - if a url was missing a sane protocol should we just bin it and not display it at all?

File: src/amo/components/AddonMoreInfo.js [hunk 2]
```diff
@@ -16,21 +17,33 @@ export class AddonMoreInfoBase extends React.Component {
...
       <Card className="AddonMoreInfo" header={i18n.gettext('More information')}>
         <dl className="AddonMoreInfo-contents">
-          {addon.homepage ? <dt>{i18n.gettext('Website')}</dt> : null}
-          {homepage ? (
-            <dd>
-              <a href={homepage}
-                ref={(ref) => { this.homepageLink = ref; }}>
-                {homepage.replace(/^https?:\/\//, '')}
-              </a>
+          {homepage || supportUrl ? (
```
Comment (muffinresearch) [inline src/amo/components/AddonMoreInfo.js]: It might be cleaner to move these bits into separate snippets using if statements to avoid so much ternary in the JSX?

**Comment by muffinresearch** [comment]
r+wc

**Comment by tofumatt** [comment]
> I wonder - if a url was missing a sane protocol should we just bin it and not display it at all?

There's no harm in doing it this way and we have to check either way... so might as well make the best of bad data. I suppose I could log the data, but realistically I think this is better UX than not showing it because _our_ data went off somewhere.
