### PR TITLE
Fix redirect loop

### LINKED ISSUE #2037: Redirect loop on /users/edit[/]
### Describe the problem and steps to reproduce it:
From https://github.com/mozilla/addons-frontend/issues/2029#issuecomment-285452339

Whilst the fxa config has been updated to fix the redirection post-registration the redirect loop still exists.
 
- Login and click my profile.
- And then edit profile.
- Then click "view mobile site" in the footer.
- addons-frontend starts by serving a 404 for /users/edit/
- This tells the proxy to let addons-server serve /users/edit/
- addons-server sees /users/edit/ and redirects to /users/edit
- addons-frontend sees /users/edit and adds a slash to the end
- hilarity ensues

### What happened?

A redirect loop

### What did you expect to happen?

Fallback to /users/edit (we could also not show the "View mobile site" link on this page)
Longer term this will be fixed by added pages for these views in the new mobile site.

### PR DESCRIPTION
**Pull request by tofumatt**
Adds a config that prevents trailing slashes from being added to certain URLs.

fixes #2037

### CODE REVIEW

File: tests/client/core/test_middleware.js [hunk 1]
```diff
@@ -248,6 +255,50 @@ describe('Trailing Slashes Middleware', () => {
...
+      originalUrl: '/firefox/no/trailing',
+      headers: {},
+    };
+    trailingSlashesMiddleware(
+      fakeReq, fakeRes, fakeNext, { _config: fakeConfig });
+    assert.notOk(fakeRes.redirect.called);
+    assert.ok(fakeNext.called);
+  });
+
+  it('should handle trailing slash exceptions with $lang/$clientApp', () => {
```
Comment (muffinresearch) [inline tests/client/core/test_middleware.js]: I may have missed it, but it would be good to ensure that clientApp and or locale prefixed urls still get redirs if not excluded.

**Comment by muffinresearch** [comment]
I wonder if it's worth exploring using react-router to handle the slashes instead of a middleware? 

The middleware will apply to everything regardless of whether we're actually handling that route or not. If we did this in the router to routes we care about that are missing them it might potentially remove a lot of unecessary redirections? It would also then mean we're always consolidating on directory style urls consistently but should not impact anything addons-server currently does differently.

This would also negate the need to wrangle prefixes.

See https://github.com/ReactTraining/react-router/issues/820#issuecomment-256814655 for an example it seems way simpler imho.

File: config/default-amo.js [hunk 2]
```diff
@@ -78,6 +78,17 @@ module.exports = {
...
+  // These URLs are exceptions to our trailing slash URL redirects; if we
+  // find a URL that matches this pattern we won't redirect to the same url
+  // with an appended `/`. This is usually because if we redirect, it will
+  // cause a redirect loop with addons-server; see:
+  // https://github.com/mozilla/addons-frontend/issues/2037
+  //
+  // We use $lang and $clientApp as placeholders so we can have URLs in this
+  // list that don't include those URL pieces, if needed.
+  validTrailingSlashUrlExceptions: [
+    '/$lang/$clientApp/user/edit',
```
Comment (muffinresearch) [inline config/default-amo.js]: This is nice for completeness but definitely makes the implementation more involved due to needing to wrangle the prefixes. I wonder if this could still be useful if it worked with either globs or even if this array defines path suffixes to match against e.g. don't redirect if the path endsWith `/user/edit` or are there cases where that would fall apart?

Comment (tofumatt) [inline config/default-amo.js]: I suppose that would work fine, we'd still need to split on `?` to make sure we didn't get messed with by query strings but I suppose it could work.

File: tests/client/core/test_middleware.js (hunk 1 above)
Comment (tofumatt) [inline tests/client/core/test_middleware.js]: Ah, I didn't actually test that but I can. Sure.

**Comment by tofumatt** [comment]
> If it hasn't already I wonder if it's worth exploring using react-router to handle the slashes instead of a middleware?

I like that idea, I'll give it a go.

**Comment by tofumatt** [comment]
We talked about this on vidyo and for now we'll still need the middleware.

I've extended the test coverage and fixed an issue with query strings. I've also added back the routes backed out in #2046. And then some.

Another r? would be great.

File: src/core/middleware.js [hunk 3]
```diff
@@ -129,13 +133,39 @@ export function prefixMiddleWare(req, res, next, { _config = config } = {}) {
   return next();
 }
 
-export function trailingSlashesMiddleware(req, res, next) {
-  const URLParts = req.originalUrl.split('?');
+export function trailingSlashesMiddleware(
+  req, res, next, { _config = config } = {}
```
Comment (muffinresearch) [inline src/core/middleware.js]: Does this need to be indented?

Comment (tofumatt) [inline src/core/middleware.js]: Yeah, it breaks 80 chars if not.

**Comment by muffinresearch** [comment]
@tofumatt r+wc - I reckon let's land this and test it out on -dev.
