### PR TITLE
I3601 error handling for unknown type in rating manager

### LINKED ISSUE #3601: Static theme details page return a 500 error page if logged out
Steps to reproduce:
1. Submit a static theme i.e. https://addons-dev.allizom.org/en-US/firefox/addon/static-theme-ex2/
2. Being logged out load its details page using the new frontend pages 

Expected results:
Theme details page is loaded.

Actual results:
A 500 error page is loaded.

Notes/Issues:
- being logged in does not reproduce the issue, even if you are not the author of the theme
- using old desktop pages doesn't reproduce the issue, also

Verified on AMO-dev Ff56(Win 7).
Video for this issue:
static theme

### LINKED ISSUE #5102: Rating Manager component text should be updated for static theme type
### Describe the problem and steps to reproduce it:

**(once static theme is added as a valid addon type - see PR #5067)
make sure you're logged out
find a static theme addon: eg: https://addons-dev.allizom.org/en-US/firefox/addon/rm-static-theme-3/?src=search
Alt text

### What did you expect to happen?
expect if on env where static themes are enabled text to be correct (match lwt/persona type text) 

### Anything else we should know?
see somewhat related issue #3601 - also error handling error should be looked at too as noted in the issue

### PR DESCRIPTION
**Pull request by rebmullin**
fixes #3601 

PR #5237 should help with this but here i am addressing the error handling:

basically, i just took this out so it's a little bit more consistent (you can access this page when you're already logged in) - let me know what you think

### CODE REVIEW

**Comment by willdurand** [comment]
> rebmullin (Rebecca Mullin) added this to the 2018.06.21 milestone 31 minutes ago

@rebmullin I think we don't set milestones on PRs.

**Comment by rebmullin** [comment]
lol @willdurand...oops, I've done that a couple of time :/  Meant to do on the issues..

**Comment by rebmullin** [comment]
note: I am also going to revert changes for #5102 since there is another PR for this..

File: tests/unit/amo/components/TestRatingManager.js [hunk 1]
```diff
@@ -333,8 +333,8 @@ describe('RatingManager', () => {
     });
 
     it('cannot render a login prompt for unknown extension types', () => {
```
Comment (willdurand) [inline tests/unit/amo/components/TestRatingManager.js]: can or cannot?

Comment (rebmullin) [reply tests/unit/amo/components/TestRatingManager.js]: 🤦‍♂️

Comment (rebmullin) [reply tests/unit/amo/components/TestRatingManager.js]: yes "can" ... i'll update

Comment (willdurand) [reply tests/unit/amo/components/TestRatingManager.js]: Cool, I think we should link to the original issue too.

File: src/amo/components/RatingManager/index.js [hunk 2]
```diff
@@ -147,12 +147,13 @@ export class RatingManagerBase extends React.Component<Props, State> {
...
         return i18n.gettext('Log in to rate this extension');
-      default:
-        if (!validAddonTypes.includes(addonType)) {
-          throw new Error(`Unknown extension type: ${addonType}`);
-        }
-        log.warn(`Using generic prompt for add-on type: ${addonType}`);
+      default: {
+        const validAddonType = validAddonTypes.includes(addonType);
+        log.warn(`Using generic prompt for ${validAddonType ?
+          'add-on' : 'unknown extension'} type: ${addonType}`
```
Comment (willdurand) [inline src/amo/components/RatingManager/index.js]: so if the addon type is invalid, it will print `using generic prompt for unknown extension`, but is it really an extension? Why do you want to update the log message here?

Comment (rebmullin) [reply src/amo/components/RatingManager/index.js]: well that's what the message said before basically - in that it referred to it as an extension if it was not valid : `Unknown extension type: ${addonType}`. Since we are using a prompt now (instead of throwing the error), I really just added this to the beginning of the original text

Comment (willdurand) [reply src/amo/components/RatingManager/index.js]: mmh but this does not look correct to me, because add-on is the most generic term if I am not mistaken (i.e. a web extension is an add-on).

Comment (rebmullin) [reply src/amo/components/RatingManager/index.js]: I see what you're saying...so what about what this:
```javascript
   log.warn(`Using generic prompt for ${validAddonType ?
     'add-on' : 'unknown addon-on'} type: ${addonType}`
```

Comment (willdurand) [reply src/amo/components/RatingManager/index.js]: :+1: perfect!

File: tests/unit/amo/components/TestRatingManager.js [hunk 3]
```diff
@@ -338,9 +338,12 @@ describe('RatingManager', () => {
       expect(prompt).toContain('theme');
     });
 
-    it('cannot render a login prompt for unknown extension types', () => {
-      expect(() => getAuthPromptForType('xul'))
-        .toThrowError(/Unknown extension type: xul/);
+    // Since you can view this page if you're logged in -
+    // to be consistent - we'll do the same if you're logged out.
+    // See https://github.com/mozilla/addons-frontend/issues/3601.
```
Comment (willdurand) [inline tests/unit/amo/components/TestRatingManager.js]: I like to write "See:" (with the colon) 😉

File: src/amo/components/RatingManager/index.js [hunk 4]
```diff
@@ -147,12 +147,13 @@ export class RatingManagerBase extends React.Component<Props, State> {
...
-      default:
-        if (!validAddonTypes.includes(addonType)) {
-          throw new Error(`Unknown extension type: ${addonType}`);
-        }
-        log.warn(`Using generic prompt for add-on type: ${addonType}`);
+      default: {
+        const validAddonType = validAddonTypes.includes(addonType);
+        log.warn(`Using generic prompt for ${validAddonType ?
+          'add-on' : 'unknown add-on'} type: ${addonType}`
+        );
```
Comment (willdurand) [inline src/amo/components/RatingManager/index.js]: Can we put this parenthesis on the line above it?
