### PR TITLE
handled error when recommendation service down

### LINKED ISSUE #6001: 500 error page (in development) when add-on recommendation service is down
### Describe the problem and steps to reproduce it:

- Do something in the recommendations saga to trigger [`abortFetchRecommendations()`](https://github.com/mozilla/addons-frontend/blob/4cbac1c586e49936e3a1327332e9d942d6b0e71e/src/amo/sagas/recommendations.js#L49). For example, if the API is down, the saga would abort with this error:

```
Error calling: /api/v3/addons/recommendations/ (status: 500)
```
- Load any add-on detail page

### What happened?

A 500 page is shown

### What did you expect to happen?

The add-on detail page should be shown without any recommendations.

### Anything else we should know?

The 500 page is caused by this component error:

```
Caught application error: Invariant Violation: "outcome is required"
```

See https://github.com/mozilla/addons-frontend/blob/4cbac1c586e49936e3a1327332e9d942d6b0e71e/src/amo/components/AddonRecommendations/index.js#L92

~~This will only affect development since `invariant()` doesn't throw in production~~ (it does throw 👻 ). I'm not sure what would happen in production but the tracking event will be strange at the very least.

This only happened to me while hot reloading so that may be a prerequisite. Low priority issue but nice to fix!

### PR DESCRIPTION
**Pull request by TheSTL**
Fixes #6001

Changes inside?

1. In `ComponentDidUpdate` check, if there is an error then return.
2. In `render` check, if there is an error then render nothing.

### CODE REVIEW

File: src/amo/components/AddonRecommendations/index.js [hunk 1]
```diff
@@ -85,7 +85,7 @@ export class AddonRecommendationsBase extends React.Component<Props> {
     if (newRecommendations && oldRecommendations !== newRecommendations) {
       const { fallbackReason, loading, outcome } = newRecommendations;
 
-      if (loading) {
+      if (loading || this.props.errorHandler.hasError()) {
```
Comment (bobsilverberg) [inline src/amo/components/AddonRecommendations/index.js]: You could destructure `errorHandler` from `this.props` at the top of this function where other variables are being destructured (e.g., at line 72).

File: src/amo/components/AddonRecommendations/index.js [hunk 2]
```diff
@@ -114,9 +114,9 @@ export class AddonRecommendationsBase extends React.Component<Props> {
   }
 
   render() {
-    const { className, i18n, recommendations } = this.props;
+    const { className, i18n, recommendations, errorHandler } = this.props;
 
-    if (!recommendations) {
+    if (!recommendations || errorHandler.hasError()) {
       log.debug(
         'No recommendations, hiding the AddonRecommendations component.',
```
Comment (bobsilverberg) [inline src/amo/components/AddonRecommendations/index.js]: It might be worth outputting a different message if there is an error. In that case it's not really because there are no recommendations, so the message could be misleading.

**Comment by TheSTL** [comment]
> This looks good, thanks for the patch @TheSTL! I added a couple of comments, and we should also be adding tests for this new behaviour.

I will add test cases for this behaviour

**Comment by TheSTL** [comment]
@bobsilverberg can you help me in adding test case for this behaviour ? I'm able to do that.

**Comment by bobsilverberg** [comment]
> @bobsilverberg can you help me in adding test case for this behaviour ? I'm able to do that.

It's a little bit complicated, because you need to do some setup for the test, but it's not that difficult. In order to test for an error, you need a couple of things:

1. You need to pass an `errorHandler` into the `render()` function which indicates that an error occurred. You can create one of these with the following snippet:

```js
    const errorHandler = new ErrorHandler({
      id: 'some-id',
      dispatch: store.dispatch,
    });
    errorHandler.handle(new Error('some unexpected error'));
```

2. You need to make sure that the test *would have* rendered something without the error. In the case of this component, as can be seen from most of the existing tests, this means dispatching `doLoadRecommendations` before rendering the component.

Taking both of those into account, here is what a test would look like to check that nothing is output in the case of an error:
```js
  it('renders nothing if there is an error', () => {
    const errorHandler = new ErrorHandler({
      id: 'some-id',
      dispatch: store.dispatch,
    });
    errorHandler.handle(new Error('some unexpected error'));
    store.dispatch(doLoadRecommendations({}));

    const root = render({ errorHandler });
    expect(root).not.toHaveClassName('AddonRecommendations');
  });
```

Notice how we are setting up the `errorHandler`, then dispatching `doLoadRecommendations`, and then passing the `errorHandler` into the `render` method.

So that's one test we need, but we should also have a test for the change you made to `componentDidUpdate`. I will leave that as a challenge for you to see if you can figure out how to write a test for that, based on the test I've shown above, and other tests that already exist in https://github.com/mozilla/addons-frontend/blob/master/tests/unit/amo/components/TestAddonRecommendations.js.

Give this a try and let me know if you have any more questions.

**Comment by TheSTL** [comment]
Thanks @bobsilverberg for help :) 
Please review changes.

File: src/amo/components/AddonRecommendations/index.js [hunk 3]
```diff
@@ -85,7 +86,7 @@ export class AddonRecommendationsBase extends React.Component<Props> {
     if (newRecommendations && oldRecommendations !== newRecommendations) {
       const { fallbackReason, loading, outcome } = newRecommendations;
 
-      if (loading) {
+      if (loading || errorHandler.hasError()) {
```
Comment (bobsilverberg) [inline src/amo/components/AddonRecommendations/index.js]: Looking at this again, after looking at the new test, it seems like we should move this test to the top of the function. I.e., the first thing we do in `componentDidUpdate` is check for `errorHandler.hasError()` and if it is `true` then we `return`. We shouldn't be calling `dispatchFetchRecommendations` if there was an error.

Can you please update this, and then change the new test to check that we do not call `dispatchFetchRecommendations` if there is an error?

Comment (TheSTL) [reply src/amo/components/AddonRecommendations/index.js]: But issue is that after `dispatchFetchRecommendations`,  if sagas throw error than the 500 page is shown. To handle error we should put condition after calling `dispatchFetchRecommendations`. Can you please read this comment  https://github.com/mozilla/addons-frontend/issues/6001#issue-352708353 . I think test cases are not describing the case properly. @bobsilverberg

Comment (bobsilverberg) [reply src/amo/components/AddonRecommendations/index.js]: I think having it in either place is fine, so we can just leave it where it is.

Thanks for your work on this patch @TheSTL.
