### PR TITLE
Remove obsolete permissions

### LINKED ISSUE #9788: Review code link not appearing
### Describe the problem and steps to reproduce it:
On the add-on's product page, in the "Admin Links" section only "Content review add-on" is visible. Before I had access to "Review code" link as well.

### What happened?
I entered on an add-on's product page, scrolled down to "Admin Links" and saw only "Content review add-on" available.

### What did you expect to happen?
I was expecting to see both "Content review add-on" and "Review code" links.

### Anything else we should know?
Me permissions are of an admin reviewer.

### PR DESCRIPTION
**Pull request by wagnerand**
Fixes #9788.

This patch removes obsolete permissions and adapts related permission checks.

### CODE REVIEW

File: src/core/constants.js [hunk 1]
```diff
@@ -280,8 +275,6 @@ export const MOZILLA_COLLECTIONS_EDIT = 'Admin:Curation';
 export const FEATURED_THEMES_COLLECTION_EDIT = 'Collections:Contribute';
 // The slug for the special Featured Themes collection.
 export const FEATURED_THEMES_COLLECTION_SLUG = 'featured-personas';
-// Can confirm approval of automatically approved add-ons.
-export const ADDONS_POST_REVIEW = 'Addons:PostReview';
```
Comment (willdurand) [inline src/core/constants.js:284]: I still see this perm mentioned in addons-server.

**Comment by wagnerand** [comment]
Unfortunately, I wasn't able to test this patch locally. Any guidance would be appreciated!

File: tests/unit/amo/pages/TestUserProfile.js [hunk 2]
```diff
@@ -622,7 +621,7 @@ describe(__filename, () => {
   it('does not render an admin link if no user is found', () => {
     const { store } = signInUserWithProps({
       userId: 1,
-      permissions: [USERS_EDIT, ADMIN_TOOLS],
+      permissions: [USERS_EDIT],
```
Comment (willdurand) [inline tests/unit/amo/pages/TestUserProfile.js:624]: So `Users:Edit` is enough now?

**Review by willdurand — COMMENTED** [review]
Looking good.

File: src/core/constants.js (hunk 1 above)
Comment (wagnerand) [reply src/core/constants.js:284]: `Addons:Review` and `Addons:PostReview` were merged in https://github.com/mozilla/addons-server/issues/14782.

File: tests/unit/amo/pages/TestUserProfile.js (hunk 2 above)
Comment (wagnerand) [reply tests/unit/amo/pages/TestUserProfile.js:624]: Yes, `Admin:Tools` was removed in https://github.com/mozilla/addons-server/pull/15711.

File: src/core/constants.js (hunk 1 above)
Comment (willdurand) [reply src/core/constants.js:284]: https://github.com/mozilla/addons-server/blob/4e2c1f7c9c15fba477be9e6aefbca5b940097a74/src/olympia/reviewers/utils.py#L433

Comment (wagnerand) [reply src/core/constants.js:284]: Hm, looks like some comments and variable names where not updated. Eventually, this actually points to `permission_post_review` which can have various values, but never has `Addons:PostReview`, since that constant was removed. /cc @diox

**Comment by bobsilverberg** [comment]
@willdurand Am I reviewing this or are you? I don't think it needs both of us, and it looks like you've already started looking at it.

**Comment by willdurand** [comment]
> @willdurand Am I reviewing this or are you? I don't think it needs both of us, and it looks like you've already started looking at it.

I left some comments but that wasn't a review.

**Review by bobsilverberg — APPROVED** [review]
It looks good to me, nice work @wagnerand! I didn't test it locally, but the code seems fine. 

What trouble were you having testing it locally? You should be able to change the permissions for a user using the admin for dev, and then run it locally using `yarn am:dev` and see the changes reflected.

**Comment by wagnerand** [comment]
Ok, I was finally able to test this and can confirm and works as expected.
