### PR TITLE
fix: Complete themes are valid add-ons

### LINKED ISSUE #2646: Complete themes cause an error because they are unsupported
### Describe the problem and steps to reproduce it:
See the error here: https://sentry.prod.mozaws.net/operations/addons-frontend-amo-dev/issues/618227/

Visit https://addons-dev.allizom.org/en-GB/android/addon/firefox-2-theme-for-firefox-3x/ when *signed out*, and there will be an error. This is because we don't support complete themes in `validAddonTypes`, but evidently we should 😄 

### What happened?
There was an error.

### What did you expect to happen?
No error!

### Anything else we should know?
Easy fix, incoming.

### PR DESCRIPTION
**Pull request by tofumatt**
Fixes #2646.

### CODE REVIEW

File: src/amo/components/Addon/index.js [hunk 1]
```diff
@@ -136,7 +136,6 @@ export class AddonBase extends React.Component {
           className="Addon-theme-header"
           id="Addon-theme-header"
           data-browsertheme={getBrowserThemeData()}
-          ref={(el) => { this.wrapper = el; }}
```
Comment (tofumatt) [inline src/amo/components/Addon/index.js]: This was unused and caused a non-100% coverage error so I deleted it. I know it's unrelated but figured it was worth it.

File: src/core/constants.js [hunk 2]
```diff
@@ -50,7 +50,9 @@ export const ADDON_TYPE_EXTENSION = 'extension';
 export const ADDON_TYPE_LANG = 'language';
 export const ADDON_TYPE_OPENSEARCH = 'search';
 export const ADDON_TYPE_THEME = 'persona';
+export const ADDON_TYPE_CLASSIC_THEME = 'theme';
```
Comment (kumar303) [inline src/core/constants.js]: can we just call this `ADDON_TYPE_COMPLETE_THEME`?

File: src/core/constants.js [hunk 3]
```diff
@@ -50,7 +50,9 @@ export const ADDON_TYPE_EXTENSION = 'extension';
...
 export const validAddonTypes = [
+  ADDON_TYPE_CLASSIC_THEME, // Remove once we don't support complete themes.
```
Comment (kumar303) [inline src/core/constants.js]: One day we might start grepping `TODO` so it would probably make sense to add that to the comment so we don't forget

File: src/core/constants.js (hunk 2 above)
Comment (tofumatt) [inline src/core/constants.js]: Sure, no problem.
