### PR TITLE
Better Error Message for add-on signature fails

### LINKED ISSUE #7985: Connection error appears when add-on signature fails
The incident from last weekend revealed that AMO doesn't show an accurate error message if an add-on fails to install because of a signature failure. The error currently shown is 

> Download failed. Please check your connection.

This is inaccurate and misleading, since Firefox did download and process the file, but couldn't check the signature. I'm filing this issue to investigate whether Firefox returns anything useful for whatever installation error cases there are, and what AMO can do to provide better error messages.

---

**Update for QA:** this can be reproduced in -dev by setting the `extensions.webapi.testing` pref to `true` **and** `xpinstall.signatures.dev-root` to `false`.

### PR DESCRIPTION
**Pull request by championshuttler**
Fixes #7985

### CODE REVIEW

**Comment by willdurand** [comment]
Looks like a great start, thanks @championshuttler!

**Comment by championshuttler** [comment]
@willdurand I need your help in the last test case , I am not getting the logic and it keeps failing for me , can you please help me with it :)

Thanks

File: src/core/utils/addons.js [hunk 1]
```diff
@@ -25,6 +26,8 @@ export const getErrorMessage = ({
   invariant(i18n, 'i18n is required');
 
   switch (error) {
+    case ERROR_CORRUPT_FILE:
+      return i18n.gettext('Error occurred due to corrupt file');
```
Comment (championshuttler) [inline src/core/utils/addons.js]: Does it seems to be good error message or do you have any better suggestion?

File: tests/unit/disco/components/TestAddon.js [hunk 2]
```diff
@@ -458,6 +459,36 @@ describe(__filename, () => {
       const compatError = root.find(AddonCompatibilityError);
       expect(compatError.prop('reason')).toEqual(reason);
     });
+
+    it('renders an corrupt file error overlay', () => {
```
Comment (championshuttler) [inline tests/unit/disco/components/TestAddon.js]: I need help in this test case actually

Comment (championshuttler) [inline tests/unit/disco/components/TestAddon.js]: I need help in this test case actually

File: src/core/utils/addons.js (hunk 1 above)
Comment (willdurand) [reply src/core/utils/addons.js]: Mmh, maybe we should have something similar to [this](https://searchfox.org/mozilla-central/rev/116bd975c30746ddefc3d20e6947d1871469354f/browser/locales/en-US/chrome/browser/browser.properties#231):

> Installation aborted because the add-on is unverified.

File: tests/unit/core/test_installAddon.js [hunk 3]
```diff
@@ -885,6 +886,26 @@ describe(__filename, () => {
         handler({ state: 'WAT' }, { type: 'onNothingPerformed' });
         sinon.assert.notCalled(dispatch);
       });
+
+      it('sets status to error on onCorruptFile', () => {
+        const dispatch = sinon.spy();
+        const guid = '{my-addon}';
+        const name = 'my-addon';
```
Comment (willdurand) [inline tests/unit/core/test_installAddon.js]: I think you can omit this.

File: tests/unit/core/test_installAddon.js [hunk 4]
```diff
@@ -885,6 +886,26 @@ describe(__filename, () => {
...
+        const type = ADDON_TYPE_EXTENSION;
+        const handler = createProgressHandler({
+          dispatch,
+          guid,
+          name,
+          type,
+        });
+
+        handler({ state: 'STATE_SOMETHING' }, { type: 'ERROR_CORRUPT_FILE' });
```
Comment (willdurand) [inline tests/unit/core/test_installAddon.js]: I believe you can extract `type` into its own variable as it is used below too.

File: tests/unit/disco/components/TestAddon.js (hunk 2 above)
Comment (willdurand) [reply tests/unit/disco/components/TestAddon.js]: I don't think you need to add a test case for the disco pane.

File: tests/unit/core/test_installAddon.js (hunk 4 above)
Comment (willdurand) [reply tests/unit/core/test_installAddon.js]: I was thinking about extracting `type: 'ERROR_CORRUPT_FILE'` instead of the addon's type.

**Comment by willdurand** [comment]
Looks like the added test case is failing, do you need help?

**Comment by willdurand** [comment]
Hey @championshuttler, do you need help to finish this patch?

**Comment by championshuttler** [comment]
Hi @willdurand Yes I need some help, Idk test is not working for me

**Comment by willdurand** [comment]
> Hi @willdurand Yes I need some help, Idk test is not working for me

Ok, I updated the test case a bit and now everything should be ok :)

**Comment by championshuttler** [comment]
Thanks @willdurand 👍

**Comment by championshuttler** [comment]
When I am running the tests locally, 2 of them are not passing though they are not related to this PR changes but travis is green weird.

image

File: src/core/installAddon.js [hunk 5]
```diff
@@ -151,6 +152,8 @@ export function makeProgressHandler({
       });
     } else if (event.type === 'onInstallFailed') {
       dispatch(setInstallError({ guid, error: INSTALL_FAILED }));
+    } else if (event.type === 'onCorruptFile') {
```
Comment (willdurand) [inline src/core/installAddon.js]: Unfortunately, I discovered that FF does not expose this piece of information as a new type. The type is still `onDownloadFailed` but the `event.target.error` contains `ERROR_CORRUPT_FILE`, heh.

**Comment by willdurand** [comment]
> When I am running the tests locally, 2 of them are not passing though they are not related to this PR changes but travis is green weird.

Yeah, that's a problem with node and intl.

**Comment by willdurand** [comment]
Thanks @championshuttler!
