### PR TITLE
Static theme fixes round1

### LINKED ISSUE #4661: stop vertical cropping theme previews (and some other comments)
refiled based on the conclusion of mozilla/addons-server#7888

quoting @jvillalobos 
> What I'd like to avoid is what is shown in the "Search results / category list page (wide browser)" screenshot, which is cropping the image vertically. Can we at least make sure the full height of the preview is shown? 

Search results / category list page (wide browser)
screenshot 2018-03-27 18 22 50

And possible follow-ups:
> Maybe in the future we can do some fancy expand or scroll on hover, so the user can inspect the rest of the preview from those pages.

> It'd be nice if the shelves expanded vertically to become 2x2 rather than 1x4

### LINKED ISSUE #5015: Static themes show an 'Add to Firefox' button instead of an 'Install Theme' button on theme details page
STR:

1. Log in to AMO-dev and go to a static theme details page - see https://addons-dev.allizom.org/en-US/firefox/addon/green-space2/
2. Open the same LWT theme's detail page on AMO stage - https://addons.allizom.org/en-US/firefox/addon/green-space2/
3. Compare the 'Install' button for the two themes

Actual result:
Static theme detail page shows an 'Add to Firefox' button 

Expected result:
Static theme detail page shows an 'Install Theme' button

Note:
- reproduced on AMO-dev with FF60, Win10x64

image

### LINKED ISSUE #5016: 'About this add-on' card should be renamed to 'About this theme' on static theme details page
STR:

1. Log in to AMO-dev and go to a static theme details page - see https://addons-dev.allizom.org/en-US/firefox/addon/green-space2/
2. Open the same LWT theme's detail page on AMO stage - https://addons.allizom.org/en-US/firefox/addon/green-space2/
3. Compare the 'About this xxxx' card for the two themes

Actual result:
The card title in static theme details page is "About this add-on"

Expected result:
The card title in static theme details page is "About this theme"

Notes:
- reproduced on AMO-dev with FF60, Win10x64

image

### LINKED ISSUE #5017: 'More themes by author' card is not correctly positioned in static theme details page
STR

1. Log in to AMO-dev and go to a static theme details page - see https://addons-dev.allizom.org/en-US/firefox/addon/my-first-sentence/
2. Open the same LWT theme's detail page on AMO stage - https://addons.allizom.org/en-US/firefox/addon/my-first-sentence/?src=rating
3. Compare the 'More...by this author' cards for the two themes

Actual result:
'More...by this author' card in Static theme details page is displayed at the bottom and the title says 'More **add-ons** by this author'

Expected result:
'More...by this author' card in Static theme details page should be moved where the 'Screenshots' section is positioned now  and the title should say 'More **themes** by this author'

Notes:
- reproduced on AMO-dev with FF60, Win10x64

image

### LINKED ISSUE #5018: Static theme preview should be positioned similar to LWT preview in theme details page
STR:

1. Log in to AMO-dev and go to a static theme details page - see https://addons-dev.allizom.org/en-US/firefox/addon/my-first-sentence/
2. Open the same LWT theme's detail page on AMO stage - https://addons.allizom.org/en-US/firefox/addon/my-first-sentence/?src=rating
3. Compare the two theme previews

Actual result:
Static theme preview is displayed in a Screenshots section which doesn't clearly mark the theme design as the main focus on the theme details page

Expected result:
Static theme preview should be displayed in the same card LWT are currently displayed; also, the Screenshots section shouldn't really be present on the ST detail page

Notes:
- reproduced on AMO dev with FF60, Win10x64

image

### PR DESCRIPTION
**Pull request by rebmullin**
fixes #5018
fixes #5017 
fixes #5016 
fixes #5015 
fixes #4661 (also some additional notes here about sizes: https://github.com/mozilla/addons-frontend/issues/5018#issuecomment-390280137)

## ADD ON DETAIL PAGES:
before (desktop):
Alt text

after (~ desktop):
Alt text

before    (~ mobile)        |  after (~ mobile)
:-------------------------:|:-------------------------:
  | 

## SEARCH
before (~desktop):
Alt text

after (~ desktop):
Alt text

before    (~ mobile)        |  after (~ mobile)
:-------------------------:|:-------------------------:
  |

### CODE REVIEW

**Comment by rebmullin** [comment]
@willdurand / @bobsilverberg  - can you either of you please give first round of review for this PR?

File: src/amo/components/Addon/index.js [hunk 1]
```diff
@@ -177,12 +184,24 @@ export class AddonBase extends React.Component {
...
     } = this.props;
-    const previewURL = addon ? addon.previewURL : null;
     const type = addon ? addon.type : ADDON_TYPE_EXTENSION;
-    const iconUrl = getAddonIconUrl(addon);
 
-    if (type === ADDON_TYPE_THEME) {
-      const label = isPreviewingTheme ? i18n.gettext('Cancel preview') : i18n.gettext('Tap to preview');
+    // The 'tap to preview' button will be fully removed in the following PR:
+    // https://github.com/mozilla/addons-frontend/pull/4914
+    // for now this is only displayed over lightweight preview images
```
Comment (willdurand) [inline src/amo/components/Addon/index.js]: I guess you dont need this comment here.

File: src/amo/components/Addon/index.js [hunk 2]
```diff
@@ -177,12 +184,24 @@ export class AddonBase extends React.Component {
...
+    if (this.addonIsTheme()) {
+      let previewURL = addon ? addon.previews.length > 0 && addon.previews[0].image_url : null;
```
Comment (willdurand) [inline src/amo/components/Addon/index.js]: I don't think you need to test `addon` here since `addonIsTheme()` does it already.

Also, I find the mix of ternary and logical operator very difficult to read.

File: src/amo/components/Addon/index.js [hunk 3]
```diff
@@ -177,12 +184,24 @@ export class AddonBase extends React.Component {
...
+
+      let label = addon ? i18n.sprintf(
+        i18n.gettext('Preview of %(title)s'),
+        { title: addon.name }
+      ) : '';
+
+      if (type === ADDON_TYPE_THEME) {
+        previewURL = previewURL || (addon && addon.previewURL) || null;
```
Comment (willdurand) [inline src/amo/components/Addon/index.js]: We could probably simplify a bit here, since we know that `addon` is valid.

File: src/amo/components/Addon/index.js [hunk 4]
```diff
@@ -194,7 +213,7 @@ export class AddonBase extends React.Component {
           onClick={this.onClick}
           role="presentation"
         >
-          {installStatus !== ENABLED ? (
+          {installStatus !== ENABLED && type === ADDON_TYPE_THEME ? (
```
Comment (willdurand) [inline src/amo/components/Addon/index.js]: Can you extract this condition to a new variable above?

File: src/amo/components/Addon/index.js [hunk 5]
```diff
@@ -545,7 +569,7 @@ export class AddonBase extends React.Component {
           <div className="Addon-main-content">
             {this.renderAddonsByAuthorsCard({ isForTheme: true })}
 
-            {addonPreviews.length > 0 ? (
+            {addonPreviews.length > 0 && !(this.addonIsTheme()) ? (
```
Comment (willdurand) [inline src/amo/components/Addon/index.js]: Why do you need parentheses here?

File: src/amo/components/AddonsByAuthorsCard/styles.scss [hunk 6]
```diff
@@ -15,6 +15,25 @@
   }
 
   &.AddonsCard--horizontal {
+    // overriding default list styles for theme
```
Comment (willdurand) [inline src/amo/components/AddonsByAuthorsCard/styles.scss]: Why?

File: src/amo/components/SearchResult/index.js [hunk 7]
```diff
@@ -46,10 +46,22 @@ export class SearchResultBase extends React.Component<Props> {
...
-      isAllowedOrigin(addon.themeData.previewURL)) ?
-      addon.themeData.previewURL : null;
-    const imageURL = isTheme ? themeURL : iconURL;
+
+    let imageURL = iconURL;
+
+    if (isTheme) {
+      let themeURL = addon ? addon.previews
+      && addon.previews.length > 0
+      && addon.previews[0].thumbnail_url : null;
```
Comment (willdurand) [inline src/amo/components/SearchResult/index.js]: I'd like to avoid the mix of ternary and logical operator. It's fine to use both, but not together. Here, a simple `if/else` would probably be more readable.

File: src/amo/components/SearchResult/index.js [hunk 8]
```diff
@@ -73,7 +85,10 @@ export class SearchResultBase extends React.Component<Props> {
     }
 
     let summary = null;
-    if (showSummary) {
+    // Because static themes are technically an extension type is has a summary
+    // field, but we want it to look like a theme which does not display this
+    // or description field here
+    if (showSummary && !isTheme) {
```
Comment (willdurand) [inline src/amo/components/SearchResult/index.js]: I understand, but why are we doing this "here"? Can't we change the value of `showSummary` in the parent component?

File: src/core/components/InstallButton/index.js [hunk 9]
```diff
@@ -269,6 +270,10 @@ export class InstallButtonBase extends React.Component {
       } : (event) => {
         this.installExtension({ event, installURL });
       };
+
+      const buttonText = ADDON_TYPE_THEMES.includes(addon.type)
+        ? 'Install Theme' : 'Add to Firefox';
```
Comment (willdurand) [inline src/core/components/InstallButton/index.js]: I don't think this will work because the extraction mechanism does not understand variables. We have to use `gettext('blah')` to have `blah` extracted.

So that's fine to have a `buttonText` variable here, but it needs to call `gettext` twice.

File: src/core/constants.js [hunk 10]
```diff
@@ -75,7 +79,7 @@ export const validAddonTypes = [
 // * '/themes/' -> 'persona'
 export const API_ADDON_TYPES_MAPPING = {
   extensions: ADDON_TYPE_EXTENSION,
-  themes: ADDON_TYPE_THEME,
+  themes: ADDON_TYPE_THEME || ADDON_TYPE_STATIC_THEME,
```
Comment (willdurand) [inline src/core/constants.js]: Does that work? What's the idea here?

File: src/core/constants.js [hunk 11]
```diff
@@ -240,6 +244,7 @@ export const CATEGORY_COLORS = {
   [ADDON_TYPE_EXTENSION]: 10,
   [ADDON_TYPE_LANG]: 12,
   [ADDON_TYPE_OPENSEARCH]: 12,
+  [ADDON_TYPE_STATIC_THEME]: 12, // TODO: verify this is 12
```
Comment (willdurand) [inline src/core/constants.js]: I guess `12` is fine because we have to make these themes look like the older/other themes.

File: src/amo/components/AddonsByAuthorsCard/index.js [hunk 12]
```diff
@@ -201,7 +204,7 @@ export class AddonsByAuthorsCardBase extends React.Component<Props> {
     }
 
     const classnames = makeClassName('AddonsByAuthorsCard', className, {
-      'AddonsByAuthorsCard--theme': addonType === ADDON_TYPE_THEME,
+      'AddonsByAuthorsCard--theme': ADDON_TYPE_THEMES.includes(addonType),
```
Comment (willdurand) [inline src/amo/components/AddonsByAuthorsCard/index.js]: Do we have a test case for this?

**Comment by willdurand** [comment]
I noticed a difference between the current -dev and my local env running the code of this PR:

This PR:

screen shot 2018-05-24 at 12 41 56

-dev:

screen shot 2018-05-24 at 12 42 00

I don't think we should have a difference in terms of `width`, or I did not find the comment/spec in all the issues related to this PR. In any case, I think we need to fix the width because it does not look super nice.

Smaller screens look nice though 👍 

---

I noticed a small difference between the two theme images in this screenshot: https://camo.githubusercontent.com/1d69205b4061d48c6ef99d20dc50a7c031432811/68747470733a2f2f6d6f6e6f736e61702e636f6d2f696d6167652f667135416c764b64723073664b78416774417139343558684768464d34642e706e67

The first one is shorter than the second one.

---

I noticed that the button "Only with Firefox, etc..." is not full-width in this screenshot: https://camo.githubusercontent.com/9bbb426130c79a88ff7dc1838fa9a054eb7953b9/68747470733a2f2f6d6f6e6f736e61702e636f6d2f696d6167652f3232474d364c6c595a326f524f74744c4f55476b644834696c584b3863492e706e67

I would expect this button to be full-width because the other one ("Add to FF") is.

File: src/amo/components/Addon/index.js (hunk 5 above)
Comment (rebmullin) [reply src/amo/components/Addon/index.js]: i dont : ) i will remove...

File: src/amo/components/AddonsByAuthorsCard/index.js (hunk 12 above)
Comment (rebmullin) [reply src/amo/components/AddonsByAuthorsCard/index.js]: i'll add this...

File: src/amo/components/SearchResult/index.js (hunk 7 above)
Comment (rebmullin) [reply src/amo/components/SearchResult/index.js]: hi @willdurand - are you talking about mixing in the same snippet of code? like line 53  here and line 63?

File: src/amo/components/Addon/index.js (hunk 1 above)
Comment (rebmullin) [reply src/amo/components/Addon/index.js]: I thought it was a good idea to leave in till the PR gets merged (it's currently in a "do not merge" state). I am just curious why you think i don't need it?

File: src/core/components/InstallButton/index.js (hunk 9 above)
Comment (rebmullin) [reply src/core/components/InstallButton/index.js]: okay.. I wasn't sure about the variable with that way i did it here but makes sense

File: src/core/constants.js (hunk 10 above)
Comment (rebmullin) [reply src/core/constants.js]: At this point I'm not sure this need to be updated (yet) for the updates in the PR. I'll revert this and circle back on this...

File: src/core/constants.js (hunk 11 above)
Comment (rebmullin) [reply src/core/constants.js]: sounds good to me : )

**Comment by rebmullin** [comment]
>I would have preferred smaller PRs because there are so many different things fixed, but I understand that all the fixes belong to the same "feature".

yes...sorry about that. I was thinking about that afterwards but right ..since they shared some of the code i wasn't sure...

**Comment by rebmullin** [comment]
Hey@jvillalobos, so this is what 2 themes looks like side by side in the search list results:
desktop:
Alt text
mobile:
Alt text

notes:
The static theme (top) in this view is using the thumb version which is 670x64 (cropping on right only when needed)
The lwt size is 680x100 (cropping on right only when needed)

Questions:
My understanding was that we should use the thumb version in this scenario for static theme but i just wanted to make sure since we aren’t vertically cropping lwt anymore (per this issue: 4661) - do you want us to keep using the larger version of 680x92 for static theme in this search/any similar view -for now anyway - to keep the look at bit more consistent between the two types?   

Also at a larger breakpoint/ ~ desktop, is it okay to scale the image up in this case so the image is the full width of that row/section? I don’t think this column ever gets bigger than ~720px width..
Or should we keep the preview image at max-width of the size of the actual image when possible? 

Please let me know if you need any clarification on my questions/ notes or if any of this falls more under the umbrella of UX..

thank you!

**Comment by willdurand** [comment]
@jvillalobos ^

**Comment by jvillalobos** [comment]
Yeah, I think these questions are better answered by @pwalm. He proposed the thumbnail size image, so he probably knows what should be happening here. For the last question, I don't think we should ever scale images up.

**Comment by rebmullin** [comment]
Thanks @jvillalobos 

Hi @pwalm  - Can you please help then with the following questions then:
>My understanding was that we should use the thumb version in this scenario for static theme but i just wanted to make sure since we aren’t vertically cropping lwt anymore (per this issue: 4661) - do you want us to keep using the larger version of 680x92 for static theme in this search/any similar view -for now anyway - to keep the look at bit more consistent between the two types?

Also at a larger breakpoint/ larger desktop, if we don’t scale the images up at these larger breakpoints (~1100px and up) you can see there is extra space now at the end and the users info is no longer aligned with the image:
Alt text

So was wondering is something like this was ok:
Alt text

File: src/amo/components/Addon/index.js (hunk 1 above)
Comment (rebmullin) [reply src/amo/components/Addon/index.js]: ok i see i guess i was just explaining that this was somewhat temporary and reasons for some differences in handling of static vs lightweight themes.

**Comment by pwalm** [comment]
Yes, keep them consistent and use the larger view.

As for the floating user number... Hmm. I think I'd prefer the number staying right aligned, even if that means it moves away from the theme image. Looks tidier aligned hard right.

Thanks!

**Comment by rebmullin** [comment]
hey @willdurand, I made some updates here. can you please take another look?

**Comment by rebmullin** [comment]
updated screenshots for search:
desktop:
Alt text

mobile:
Alt text

File: tests/unit/amo/components/TestAddon.js [hunk 13]
```diff
@@ -757,10 +758,11 @@ describe(__filename, () => {
     expect(src).toEqual('default-64.png');
   });
 
-  it('renders a theme preview as an img', () => {
+  it('renders a lightweight theme preview as an image', () => {
     const root = shallowRender({
       addon: createInternalAddon({
         ...fakeTheme,
+        previews: [],
```
Comment (willdurand) [inline tests/unit/amo/components/TestAddon.js]: We probably need a test case for when there are `previews` no?

File: src/amo/components/Addon/index.js [hunk 14]
```diff
@@ -296,6 +319,7 @@ export class AddonBase extends React.Component {
         case ADDON_TYPE_OPENSEARCH:
           title = i18n.gettext('About this search plugin');
           break;
+        case ADDON_TYPE_STATIC_THEME:
```
Comment (willdurand) [inline src/amo/components/Addon/index.js]: Do we have a test case for this?

File: src/amo/components/Addon/index.js [hunk 15]
```diff
@@ -474,6 +499,7 @@ export class AddonBase extends React.Component {
     return (
       <div
         className={makeClassName('Addon', `Addon-${addonType}`, {
+          'Addon-theme': this.addonIsTheme(),
```
Comment (willdurand) [inline src/amo/components/Addon/index.js]: Do we have a test case for this? (or simply an assertion)

File: tests/unit/amo/components/TestAddonsByAuthorsCard.js [hunk 16]
```diff
@@ -378,6 +379,22 @@ describe(__filename, () => {
     expect(root.find(AddonsCard).props().addons).toHaveLength(numberOfAddons);
   });
 
+  it('should add a theme class if lightweight theme', () => {
```
Comment (willdurand) [inline tests/unit/amo/components/TestAddonsByAuthorsCard.js]: "if it is a lightweight theme"

File: src/amo/components/AddonsCard/index.js [hunk 17]
```diff
@@ -74,7 +79,7 @@ export default class AddonsCard extends React.Component<Props> {
               addon={addon}
               key={addon.slug}
               showMetadata={showMetadata}
-              showSummary={showSummary}
+              showSummary={!isThemeType ? showSummary : false}
             />
           );
         }
```
Comment (willdurand) [inline src/amo/components/AddonsCard/index.js]: We probably need new test cases for this file as well.

File: tests/unit/amo/components/TestSearchResult.js [hunk 18]
```diff
@@ -149,6 +149,10 @@ describe(__filename, () => {
   it('displays a message if the theme preview image is unavailable', () => {
     const addon = createInternalAddon({
       ...fakeAddon,
+      previews: [],
+      theme_data: {
+        previewURL: null,
+      },
```
Comment (willdurand) [inline tests/unit/amo/components/TestSearchResult.js]: So why exactly do we need to change that?

Comment (willdurand) [reply tests/unit/amo/components/TestSearchResult.js]: Also, should we have tests withe one `preview` entry for example?

File: tests/unit/core/components/TestInstallButton.js [hunk 19]
```diff
@@ -127,6 +128,23 @@ describe(__filename, () => {
     );
   });
 
+  it('renders Install Theme text on button when type is statictheme', () => {
```
Comment (willdurand) [inline tests/unit/core/components/TestInstallButton.js]: "when it is a static theme"?

File: tests/unit/core/reducers/test_categories.js [hunk 20]
```diff
@@ -202,6 +231,22 @@ describe('categories reducer', () => {
...
+              type: ADDON_TYPE_STATIC_THEME,
+            },
+            naturé: {
+              ...fakeCategory,
+              application: CLIENT_APP_FIREFOX,
+              name: 'Naturé',
+              slug: 'naturé',
+              type: ADDON_TYPE_STATIC_THEME,
+            },
+          },
```
Comment (willdurand) [inline tests/unit/core/reducers/test_categories.js]: Why do you add these changes here? Because we have a new type of add-ons?

**Comment by willdurand** [comment]
I really like the small screen screenshots but I don't like what we show on larger screens:



I am also very lost in all the comments, docs, and issues related to the size of a static theme image in the search results so I'll ask again: can we do something for this (below)?

68747470733a2f2f6d6f6e6f736e61702e636f6d2f696d6167652f4b7947455263765463544d7451457464466a66594e6646754f56754b544c2e706e67

Maybe we can have a better ratio? The available width for such a list is ~760px.

**Comment by willdurand** [comment]
I really like the small screen screenshots but I don't like what we show on larger screens:



I am also very lost in all the comments, docs, and issues related to the size of a static theme image in the search results so I'll ask again: can we do something for this (below)?

68747470733a2f2f6d6f6e6f736e61702e636f6d2f696d6167652f4b7947455263765463544d7451457464466a66594e6646754f56754b544c2e706e67

@pwalm maybe we can have a better ratio? The available width for such a list is ~760px.

File: src/amo/components/Addon/index.js (hunk 1 above)
Comment (rebmullin) [reply src/amo/components/Addon/index.js]: I guess I can remove it

File: src/amo/components/Addon/index.js [hunk 21]
```diff
@@ -177,15 +184,29 @@ export class AddonBase extends React.Component {
       isPreviewingTheme,
       installStatus,
     } = this.props;
-    const previewURL = addon ? addon.previewURL : null;
     const type = addon ? addon.type : ADDON_TYPE_EXTENSION;
-    const iconUrl = getAddonIconUrl(addon);
```
[the remark this answers is not in the document]
Comment (rebmullin) [reply src/amo/components/Addon/index.js]: since it's only needed by the code below...

it also came up in a preview [PR review](https://github.com/mozilla/addons-frontend/pull/4914#discussion_r187984430)

File: src/amo/components/Addon/index.js [hunk 22]
```diff
@@ -545,7 +571,7 @@ export class AddonBase extends React.Component {
           <div className="Addon-main-content">
             {this.renderAddonsByAuthorsCard({ isForTheme: true })}
 
-            {addonPreviews.length > 0 ? (
+            {addonPreviews.length > 0 && !this.addonIsTheme() ? (
```
[the remark this answers is not in the document]
Comment (rebmullin) [reply src/amo/components/Addon/index.js]: i like it : )

File: src/amo/components/AddonsCard/index.js [hunk 23]
```diff
@@ -60,6 +61,10 @@ export default class AddonsCard extends React.Component<Props> {
 
     if (addons && addons.length) {
       addons.forEach((addon) => {
+        // Because static themes are technically an extension type is has a summary
+        // field, but we want it to look like a theme which does not display this
+        // or description field here
```
[the remark this answers is not in the document]
Comment (rebmullin) [reply src/amo/components/AddonsCard/index.js]: here are 2 links that mention that it is as an extension:
https://github.com/mozilla/addons-frontend/issues/5017#issuecomment-389492397
https://github.com/mozilla/addons-frontend/issues/4899

also if you look at isWebExtension field (under addons) in redux dev tool you can see its value is true for static theme

[the remark this answers is not in the document]
Comment (willdurand) [reply src/amo/components/AddonsCard/index.js]: ah sorry, I meant "is my slightly adapted comment proposal correct?"

File: src/amo/components/SearchResult/styles.scss [hunk 24]
```diff
@@ -2,6 +2,8 @@
 @import "~core/css/inc/mixins";
 @import "~ui/css/vars";
 
+$theme-height-default: 92px;
```
[the remark this answers is not in the document]
Comment (rebmullin) [reply src/amo/components/SearchResult/styles.scss]: i thought about that too...will do..

File: tests/unit/amo/components/TestAddon.js [hunk 25]
```diff
@@ -774,6 +776,36 @@ describe(__filename, () => {
...
+    });
+    const image = root.find('.Addon-theme-header-image');
+    expect(image.type()).toEqual('img');
+    expect(image).toHaveClassName('Addon-theme-header-image');
+    expect(image.prop('src')).toEqual('https://addons.cdn.mozilla.net/123/image.png');
+    expect(image.prop('alt')).toEqual('Preview of Dancing Daisies by MaDonna');
+  });
+
+  it('renders screenshots for type extension', () => {
+    const root = shallowRender();
```
[the remark this answers is not in the document]
Comment (rebmullin) [reply tests/unit/amo/components/TestAddon.js]: sure

File: tests/unit/amo/components/TestAddon.js (hunk 13 above)
Comment (rebmullin) [reply tests/unit/amo/components/TestAddon.js]: well static theme uses data from previews and lightweight theme uses value from theme_data

in the current api response lightweight theme shows previews as an empty array so that's this case here and underneath I have a test case for the static theme scenario (which uses the preview array). 

will those work?

Comment (willdurand) [reply tests/unit/amo/components/TestAddon.js]: ah I see, but then maybe the code in the component should be a bit more defensive?

File: tests/unit/amo/components/TestSearchResult.js (hunk 18 above)
Comment (rebmullin) [reply tests/unit/amo/components/TestSearchResult.js]: ok so i added a test case for the alternate of this - is there is a preview - for each type

File: src/amo/components/Addon/index.js (hunk 15 above)
Comment (rebmullin) [reply src/amo/components/Addon/index.js]: I will add.. thanks

File: src/amo/components/Addon/index.js (hunk 14 above)
Comment (rebmullin) [reply src/amo/components/Addon/index.js]: I will add..

File: tests/unit/amo/components/TestAddon.js (hunk 13 above)
Comment (rebmullin) [reply tests/unit/amo/components/TestAddon.js]: i also added the following comment to describe the purpose of this:

```javascript 
// The 'previews' field is not currently being used by lightweight themes
// So here we are just overridding the fakeAddon values to mimic the API
// response
previews: [],
...
```

File: tests/unit/core/reducers/test_categories.js (hunk 20 above)
Comment (rebmullin) [reply tests/unit/core/reducers/test_categories.js]: Yeh I know it's doesn't seem exactly related to the changes I made here but it was failing here without these updates. Is this ok?

File: src/amo/components/AddonsCard/index.js (hunk 23 above)
[the remark this answers is not in the document]
Comment (rebmullin) [reply src/amo/components/AddonsCard/index.js]: lol : ) ok..yeh sounds good. I will update

File: tests/unit/amo/components/TestAddon.js (hunk 13 above)
Comment (rebmullin) [reply tests/unit/amo/components/TestAddon.js]: >ah I see, but then maybe the code in the component should be a bit more defensive?

I guess my thinking was instead of checking for each type, and using that to determine the previewURL, I would make it a little bit more flexible for when the migration happens (moving lightweight themes to static themes, where they WILL have this field in the near future) ... if that makes sense...

**Comment by rebmullin** [comment]
thanks @willdurand for all the feedback. Hopefully we are close : ) can you please take another look to see what you think?

File: tests/unit/amo/components/TestAddon.js (hunk 13 above)
Comment (willdurand) [reply tests/unit/amo/components/TestAddon.js]: it does I guess, but it leaves code paths untested.

File: tests/unit/core/reducers/test_categories.js (hunk 20 above)
Comment (willdurand) [reply tests/unit/core/reducers/test_categories.js]: I am not sure to understand why it is failing, which change requires these updates?

**Comment by willdurand** [comment]
> thanks @willdurand for all the feedback. Hopefully we are close : ) can you please take another look to see what you think?

Yes, it is almost perfect. I replied to some of your comments. I would like @pwalm's input on the list (cf. comment above).

File: tests/unit/amo/components/TestAddon.js (hunk 13 above)
Comment (rebmullin) [reply tests/unit/amo/components/TestAddon.js]: sorry to clarify.. it actually does check type of (lightweight) theme as a fallback (which means migration hasn't happened yet). 

I can add this fallback scenario as an additional test..

File: tests/unit/core/reducers/test_categories.js (hunk 20 above)
Comment (rebmullin) [reply tests/unit/core/reducers/test_categories.js]: I actually was able to remove some of the updates but its still looking for some static theme info it seems:
Alt text

**Comment by rebmullin** [comment]
Hey @willdurand, I think @pwalm already addressed this above:

> As for the floating user number... Hmm. I think I'd prefer the number staying right aligned, even if that means it moves away from the theme image. Looks tidier aligned hard right.

It *might* be more obvious why by seeing the screenshot with another (non-theme) content type that also shows it right aligned:

Alt text

The alternative being this:
Alt text


I totally understand if you want to discuss this further tho, I am just wondering if its okay to address this style concern in another issue?  Would that be okay so that this isn’t blocked (assuming everything else is okay :)?

**Comment by pwalm** [comment]
Ship it! I'd rather have the user number aligned on the right than have the jagged white space caused by aligning it to the theme preview.

File: tests/unit/amo/components/TestSearchResult.js [hunk 26]
```diff
@@ -146,17 +146,56 @@ describe(__filename, () => {
...
   });
 
+  it("does not display a 'no theme preview available' message if the static theme preview image is available", () => {
+    const addon = createInternalAddon({
+      ...fakeTheme,
+      type: ADDON_TYPE_STATIC_THEME,
+    });
+    const root = render({ addon });
+
+    expect(root.find('.SearchResult-icon')).toHaveLength(1);
```
Comment (willdurand) [inline tests/unit/amo/components/TestSearchResult.js]: maybe we should assert for `not.toIncludeText()` since that's what the test case description says?

File: tests/unit/amo/components/TestSearchResult.js [hunk 27]
```diff
@@ -146,17 +146,56 @@ describe(__filename, () => {
...
+  });
+
+  it("does not display a 'no theme preview available' message if the lightweight theme preview image is available", () => {
+    const addon = createInternalAddon({
+      ...fakeTheme,
       type: ADDON_TYPE_THEME,
     });
     const root = render({ addon });
 
+    expect(root.find('.SearchResult-icon')).toHaveLength(1);
```
Comment (willdurand) [inline tests/unit/amo/components/TestSearchResult.js]: maybe we should assert for `not.toIncludeText()` since that's what the test case description says?

File: tests/unit/amo/components/TestAddonsByAuthorsCard.js [hunk 28]
```diff
@@ -378,6 +379,22 @@ describe(__filename, () => {
...
 
+  it('should add a theme class if it is a lightweight theme', () => {
+    const root = renderAddonsWithType({
+      addonType: ADDON_TYPE_THEME,
+    });
+
+    expect(root).toHaveClassName('AddonsByAuthorsCard--theme');
+  });
+
+  it('should add a theme class if static theme', () => {
```
Comment (willdurand) [inline tests/unit/amo/components/TestAddonsByAuthorsCard.js]: "if it is a static theme"

**Comment by rebmullin** [comment]
> Ship it! I'd rather have the user number aligned on the right than have the jagged white space caused by aligning it to the theme preview.

so for now in the search listing view i am going to stretch the images which is what we were doing before anyway.  I am going to open a new issue to discuss changing the full and thumb versions so this can be avoided // cc @pwalm @willdurand
