### PR TITLE
Fix problem on Collections page when a collection is loading

### LINKED ISSUE #10886: Server error when navigating back and forth between collections
Steps to reproduce:
1. Log in AMO prod with valid credentials 
2. Create 2 collections containing some addons
3. View both collections and eventually sort the collections inside by another criteria(ie. name, pupularity)
4. Navigate back and forth many times between pages previously accessed

Expected results:
No errors should be displayed when navigating back and forth

Actual results:
Server error displayed on https://addons.mozilla.org/en-US/firefox/collections/

Please see a screenshot with the encountered error in console: 
collectionsnavigation

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #10886 

The problem in the issue occurs when a user navigates quickly from a collection detail page back to the same page (but with a different sort sequence), and then to the Collections list. The first navigation causes the detail for the collection to be re-fetched, but because of the quick navigation, the details for that collection are still loading when we try to render the Collections list. The code assumes this will not be the case, hence the error.

The fix is to update the code for `UserCollection` to make it smart enough to deal with a collection that is currently being loaded.

### CODE REVIEW

File: tests/unit/amo/components/TestUserCollection.js [hunk 1]
```diff
@@ -57,6 +57,22 @@ describe(__filename, () => {
     );
   });
 
+  it('can render a collection that is loading', () => {
+    const props = {
+      authorId: 1234,
+      id: 1,
+      name: 'collection name',
+      // When a collection is in a loading state, numberOfAddons is null.
+      numberOfAddons: null,
```
Comment (willdurand) [inline tests/unit/amo/components/TestUserCollection.js:66]: That is not what I can read here: https://github.com/mozilla/addons-frontend/blob/7cfbafe7ddb2325850d2c73f1c395994e0d25bdf/src/amo/reducers/collections.js#L75

File: src/amo/components/UserCollection/index.js [hunk 2]
```diff
@@ -31,7 +31,7 @@ export const UserCollectionBase = (props: InternalProps): React.Node => {
   const linkProps = {};
   let numberText;
 
-  if (loading) {
+  if (loading || numberOfAddons === null) {
```
Comment (willdurand) [inline src/amo/components/UserCollection/index.js:34]: Shouldn't we try to fix the problem here instead? https://github.com/mozilla/addons-frontend/blob/cabfc342cdbd1fed6c9907051cdedceb8998971a/src/amo/pages/CollectionList/index.js#L65-L93

**Review by willdurand — COMMENTED** [review]
> The problem in the issue occurs when a user navigates quickly from a collection detail page back to the same page (but with a different sort sequence), and then to the Collections list. The first navigation causes the detail for the collection to be re-fetched, but because of the quick navigation, the details for that collection are still loading when we try to render the Collections list. The code assumes this will not be the case, hence the error.

Looking at the code only, why do we have collections at all? Is that because we keep collection data in the redux state instead of removing it when we re-fetch?

File: tests/unit/amo/components/TestUserCollection.js (hunk 1 above)
Comment (bobsilverberg) [reply tests/unit/amo/components/TestUserCollection.js:66]: Hmm, that's odd. I wonder why Flow wasn't catching that problem already. Here is where we set `numberOfAddons` to `null`: https://github.com/mozilla/addons-frontend/blob/7cfbafe7ddb2325850d2c73f1c395994e0d25bdf/src/amo/reducers/collections.js#L1076.

**Comment by bobsilverberg** [comment]
> > The problem in the issue occurs when a user navigates quickly from a collection detail page back to the same page (but with a different sort sequence), and then to the Collections list. The first navigation causes the detail for the collection to be re-fetched, but because of the quick navigation, the details for that collection are still loading when we try to render the Collections list. The code assumes this will not be the case, hence the error.
> 
> Looking at the code only, why do we have collections at all? Is that because we keep collection data in the redux state instead of removing it when we re-fetch?

We keep the list of collections around, and when we re-fetch an individual collection we update the data in the state.

File: src/amo/components/UserCollection/index.js (hunk 2 above)
Comment (bobsilverberg) [reply src/amo/components/UserCollection/index.js:34]: I considered doing that, but it strikes me as more appropriate for the `UserCollection` component to be able to handle, and understand, a collection that is loading, than to require the `CollectionList` component to understand when a collection is loading, and then pass that information into `UserCollection`. I think it's a bit of a six-of-one-half-a-dozen-of-another situation, but if a component needs to understand when a collection might be loading, it seems that the `UserCollection` is a more logical place for that logic, as opposed to the `CollectionList` component.

I originally took an entirely different approach, which was to simply set `numberOfAddons` to `0`, instead of `null`, in the reducer, and that fixed the problem, but that seems more like a bandaid than a fix to me.

Comment (willdurand) [reply src/amo/components/UserCollection/index.js:34]: > I originally took an entirely different approach, which was to simply set `numberOfAddons` to `0`, instead of `null`, in the reducer, and that fixed the problem, but that seems more like a bandaid than a fix to me.

Well, that does not sound bad to me and that would match the Flow definition as well.

Comment (bobsilverberg) [reply src/amo/components/UserCollection/index.js:34]: It's true that it matches the Flow definition, but I'm not sure that the Flow definition is correct. The reason I see it as a band-aid, is because it does fix this particular error, which is that we have an `invariant` which is checking `numberOfAddons` for a number, but it doesn't address the bigger issue which is that the code for `UserCollection` does not seem to account for the fact that a collection could be in a loading state. This wouldn't normally happen, but as we've seen with this issue, it's certainly possible.

This is why I am less comfortable just setting `numberOfAddons` to `0` when it is loading, but it's true it would fix the issue.

I can take either route. Do you strongly prefer that I just set `numberOfAddons` to `0` when it is loading?

Comment (willdurand) [reply src/amo/components/UserCollection/index.js:34]: I see what you mean. No need to change `numberOfAddons`.

I think, what bothers me with the current patch (which is r+able, that isn't the problem) is that we have 2 props to define a same behavior. Maybe we should get rid of `loading` and use `numberOfAddons: number|null` only?

Comment (bobsilverberg) [reply src/amo/components/UserCollection/index.js]: Yes, I can see how that's annoying. I updated the patch to just use `numberOfAddons`. I'm a bit concerned with the indirection of it, but I added a comment to explain that `numberOfAddons` is `null` when the collection is in a loading state, so I think that should cover it. I tried defining a `loading` const at the top, which was just equal to `numberOfAddons === null`, but Flow didn't quite understand what I was doing at lines 46 and 47, so I stuck with just using `numberOfAddons === null` in a couple of places. 

Take a look at the latest and see what you think.

**Review by willdurand — APPROVED** [review]
Looks good to me, thanks
