### PR TITLE
Display stats links to admins or users with 'Stats:View' permission

### LINKED ISSUE #3604: Admins should be able to always see a stats link
### Describe the problem and steps to reproduce it:

* Log in as an admin or any user with the `Stats:View` permission
* Go to an add-on detail page for an add-on that you are not an owner of

### What happened?

There is no link to add-on statistics

### What did you expect to happen?

You should see a link to add-on statistics

### Anything else we should know?

This is similar to https://github.com/mozilla/addons-frontend/issues/3603

### PR DESCRIPTION
**Pull request by willdurand**
Fix #3604

---

This PR relies on the newly added `permissions` state (in `user` reducer) to display the stats link to any users with the `Stats:View` permission or admins.

### CODE REVIEW

File: src/amo/components/AddonMoreInfo/index.js [hunk 1]
```diff
@@ -247,9 +256,10 @@ export class AddonMoreInfoBase extends React.Component<Props> {
   }
 }
 
-export const mapStateToProps = (state: Object) => {
+export const mapStateToProps = (state: {| user: UserStateType |}) => {
   return {
     userId: state.user.id,
+    canViewStats: isAdmin(state) || hasPermission(state, STATS_VIEW),
```
Comment (kumar303) [inline src/amo/components/AddonMoreInfo/index.js]: Since the concept of `isAddonAuthor()` is checked separately, it might be a useful clarification to name this property more explicitly like `hasStatsPermission`.

File: src/core/reducers/user.js [hunk 2]
```diff
@@ -45,6 +45,21 @@ export const selectDisplayName = (state: { user: UserStateType }) => {
...
 
+export const hasPermission = (
+  state: { user: UserStateType }, permission: string,
+): boolean => {
+  const permissions = state.user.permissions;
+  if (!permissions) {
+    return false;
+  }
+
+  return permissions.includes(permission);
```
Comment (kumar303) [inline src/core/reducers/user.js]: It's going to be easier to scale this up if you include the admin check as an implementation detail:

```js
return permissions.includes(permission) || isAdmin(state);
```

Admins can do anything.

Comment (willdurand) [reply src/core/reducers/user.js]: ah that makes sense indeed!

File: src/amo/components/AddonMoreInfo/index.js (hunk 1 above)
Comment (willdurand) [reply src/amo/components/AddonMoreInfo/index.js]: That's what I had before and then changed because of `isAdmin()`.

File: src/core/reducers/user.js (hunk 2 above)
Comment (willdurand) [reply src/core/reducers/user.js]: I removed the `isAdmin` for now as we're not using it.

File: tests/unit/amo/components/TestAddonMoreInfo.js [hunk 3]
```diff
@@ -315,6 +317,34 @@ describe(__filename, () => {
...
+    const root = render({
+      addon,
+      store: dispatchSignInActions({ permissions: [STATS_VIEW] }).store,
+    });
+
+    const statsLink = root.find('.AddonMoreInfo-stats-link');
+    expect(statsLink).toHaveLength(1);
+  });
+
+  it('links to stats if user is ADMIN', () => {
```
Comment (kumar303) [inline tests/unit/amo/components/TestAddonMoreInfo.js]: This test should be deleted. It would be testing an implementation detail of `hasPermission()` which is not necessary for this unit test. More importantly, the assertion is a duplication of https://github.com/mozilla/addons-frontend/pull/3741/files#diff-2e12f8c050405872bcaf7b56035e9387R157

**Comment by willdurand** [comment]
Thanks for the review, should be ok now.
