### PR TITLE
Convert AddonReviewList to a saga

### LINKED ISSUE #2608: Convert add-on review list to sagas
Instead of using async-connect to pre-load data for the add-on review listing, we should use a saga. 

Steps to test for regressions:
* Load an add-on detail page for an add-on that has reviews
* Click 'Read N reviews'
* Make sure the review listing still works

This is a step towards https://github.com/mozilla/addons-frontend/issues/2356

### PR DESCRIPTION
**Pull request by kumar303**
Fixes #2608

### CODE REVIEW

File: config/test.js [hunk 1]
```diff
@@ -2,4 +2,5 @@
 module.exports = {
   apiHost: 'https://localhost',
   allowErrorSimulation: true,
+  enableClientConsole: true,
```
Comment (tofumatt) [inline config/test.js]: Will this make test output (any) noiser? I imagine the aim of setting this to `false` here was to make tests not output a log of logging stuff.

File: src/amo/components/AddonReviewList.js [hunk 2]
```diff
@@ -55,118 +106,101 @@ export class AddonReviewListBase extends React.Component {
     return `${this.addonURL()}reviews/`;
   }
 
-  renderReview(review: UserReviewType) {
+  renderReview({ review, key }: RenderReviewParams) {
     const { i18n } = this.props;
-    const timestamp = i18n.moment(review.created).fromNow();
+
+    let byLine;
```
Comment (tofumatt) [inline src/amo/components/AddonReviewList.js]: I feel like `byLine` is a bit of a niche word... I know that's what this is but `reviewAuthor` would work equally well for what this is and might be a bit easier to parse.

File: src/amo/components/AddonReviewList.js [hunk 3]
```diff
@@ -55,118 +106,101 @@ export class AddonReviewListBase extends React.Component {
...
   render() {
-    const { addon, location, params, i18n, reviewCount, reviews } = this.props;
+    const {
+      addon, errorHandler, location, params, i18n, reviewCount, reviews,
+    } = this.props;
     if (!params.addonSlug) {
       throw new Error('params.addonSlug cannot be falsey');
     }
-    if (!reviews || !addon) {
-      // TODO: add a spinner
```
Comment (tofumatt) [inline src/amo/components/AddonReviewList.js]: Hey, we finally did it! 😄

File: src/amo/components/AddonReviewList.js [hunk 4]
```diff
@@ -55,118 +106,101 @@ export class AddonReviewListBase extends React.Component {
...
-      return <div>{i18n.gettext('Loading...')}</div>;
+
+    // When reviews have not loaded yet, make a list of 4 empty reviews
```
Comment (tofumatt) [inline src/amo/components/AddonReviewList.js]: 👍

File: src/amo/sagas/reviews.js [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+  {
+    payload: { errorHandlerId, addonSlug, page },
+  }: FetchReviewsAction
+): Generator<any, any, any> {
+  const errorHandler = createErrorHandler(errorHandlerId);
+  try {
+    yield put(showLoading());
+    const api = yield select(getApi);
+    const response = yield call(getReviews, {
+      // Hide star ratings (reviews that do not have a body).
```
Comment (tofumatt) [inline src/amo/sagas/reviews.js]: This could be clarified slightly: "Hide star-only ratings (reviews that do not have a body)".

All ratings have stars, so "star-only" might help the reader grok this a bit faster.

File: tests/unit/amo/components/TestAddonReviewList.js [hunk 6]
```diff
@@ -43,47 +32,223 @@ describe('amo/components/AddonReviewList', () => {
...
-          </I18nProvider>
-        </Provider>
-      );
-
-      return tree;
-    }
-
-    function renderToDOM(...args) {
-      return findDOMNode(render(...args));
+      return shallow(<AddonReviewListBase {...props} />);
```
Comment (tofumatt) [inline tests/unit/amo/components/TestAddonReviewList.js]: 🎉

File: tests/unit/amo/components/TestAddonReviewList.js [hunk 7]
```diff
@@ -43,47 +32,223 @@ describe('amo/components/AddonReviewList', () => {
...
+      // Do a sanity check on the first placeholder;
+      expect(root.find('.AddonReviewList-li h3').at(0).find(LoadingText))
+        .toHaveLength(1);
+      expect(root.find('.AddonReviewList-li p').at(0).find(LoadingText))
+        .toHaveLength(1);
+      expect(root.find('.AddonReviewList-by-line').at(0).find(LoadingText))
+        .toHaveLength(1);
+    });
+
     it('waits for reviews to load', () => {
```
Comment (tofumatt) [inline tests/unit/amo/components/TestAddonReviewList.js]: This should be changed to "does not render Paginator when reviews aren't loaded" or something like that.

File: tests/unit/amo/components/TestAddonReviewList.js [hunk 8]
```diff
@@ -43,47 +32,223 @@ describe('amo/components/AddonReviewList', () => {
...
-      const root = renderToDOM({ reviews: null });
-      expect(root.textContent).toEqual('Loading...');
+      const root = render({ addon: fakeAddon, reviews: null });
+
+      // Make sure Paginate is not rendered since it will throw an
+      // error about an empty reviewCount.
+      expect(root.find(Paginate)).toHaveLength(0);
+
+      // The other placeholders are checked in the test above.
```
Comment (tofumatt) [inline tests/unit/amo/components/TestAddonReviewList.js]: If you change the test spec you can remove this; I feel like it's just here to explain the old test's name not being changed.

File: tests/unit/amo/components/TestAddonReviewList.js [hunk 9]
```diff
@@ -43,47 +32,223 @@ describe('amo/components/AddonReviewList', () => {
...
+    });
+
+    it('fetches an addon if needed', () => {
```
Comment (tofumatt) [inline tests/unit/amo/components/TestAddonReviewList.js]: I feel like Sagas and dispatching actions that make our requests make it easier to do things like "request an add-on for this review page because neither are loaded". This all feels easier to grok than the asyncConnect stuff, and more unified in its design. 👍

File: tests/unit/amo/components/TestAddonReviewList.js [hunk 10]
```diff
@@ -92,157 +257,91 @@ describe('amo/components/AddonReviewList', () => {
...
-      const ratings = scryRenderedComponentsWithType(tree, Rating);
-      expect(ratings.length).toEqual(2);
+      const ratings = tree.find(Rating);
+      expect(ratings).toHaveLength(2);
 
-      expect(ratings[0].props.rating).toEqual(1);
-      expect(ratings[0].props.readOnly).toEqual(true);
-      expect(ratings[1].props.rating).toEqual(2);
-      expect(ratings[1].props.readOnly).toEqual(true);
+      expect(ratings.at(0).prop('rating')).toEqual(1);
```
Comment (tofumatt) [inline tests/unit/amo/components/TestAddonReviewList.js]: You can use more specific enzyme matchers for these assertions:

```js
// Generic matcher
expect(ratings.at(0).prop('rating')).toEqual(1);
// Enzyme matcher
expect(ratings.at(0)).toHaveProp('rating', 1);
```

I think it's a bit nicer.

File: tests/unit/amo/components/TestAddonReviewList.js [hunk 11]
```diff
@@ -92,157 +257,91 @@ describe('amo/components/AddonReviewList', () => {
...
+        .toIncludeText(fakeReview.user.name);
     });
 
     it("renders the add-on's icon in the header", () => {
-      const root = renderToDOM({ addon: fakeAddon });
-      const img = root.querySelector('.AddonReviewList-header-icon img');
-      expect(img.src).toEqual(fakeAddon.icon_url);
+      const root = render({ addon: fakeAddon });
+      const img = root.find('.AddonReviewList-header-icon img');
+      expect(img.prop('src')).toEqual(fakeAddon.icon_url);
```
Comment (tofumatt) [inline tests/unit/amo/components/TestAddonReviewList.js]: This can use the `toHaveProp('src', fakeAddon.icon_url)` matcher.

File: tests/unit/amo/components/TestAddonReviewList.js [hunk 12]
```diff
@@ -92,157 +257,91 @@ describe('amo/components/AddonReviewList', () => {
...
+      const root = render({
         addon: {
           ...fakeAddon,
           icon_url: 'http://foo.com/hax.png',
         },
       });
-      const img = root.querySelector('.AddonReviewList-header-icon img');
-      expect(img.src).toEqual(fallbackIcon);
+      const img = root.find('.AddonReviewList-header-icon img');
+      expect(img.prop('src')).toEqual(fallbackIcon);
```
Comment (tofumatt) [inline tests/unit/amo/components/TestAddonReviewList.js]: `.toHaveProp()` here too ^_^

File: tests/unit/amo/components/TestAddonReviewList.js [hunk 13]
```diff
@@ -92,157 +257,91 @@ describe('amo/components/AddonReviewList', () => {
...
 
     it('renders a hidden h1 for SEO', () => {
-      const root = renderToDOM({ addon: fakeAddon });
-      const h1 = root.querySelector('.AddonReviewList-header h1');
-      expect(h1.className).toEqual('visually-hidden');
-      expect(h1.textContent).toEqual(`Reviews for ${fakeAddon.name}`);
+      const root = render({ addon: fakeAddon });
+      const h1 = root.find('.AddonReviewList-header h1');
+      expect(h1).toHaveClassName('visually-hidden');
+      expect(h1.text()).toEqual(`Reviews for ${fakeAddon.name}`);
```
Comment (tofumatt) [inline tests/unit/amo/components/TestAddonReviewList.js]: Could this use `toHaveText`?

File: tests/unit/amo/components/TestAddonReviewList.js [hunk 14]
```diff
@@ -92,157 +257,91 @@ describe('amo/components/AddonReviewList', () => {
...
     });
 
     it('configures a paginator with the right URL', () => {
-      const tree = render();
-      const root = findRenderedComponentWithType(tree, AddonReviewListBase);
-      const paginator = findRenderedComponentWithType(tree, Paginate);
-
-      expect(paginator.props.pathname).toEqual(root.url());
+      const root = render();
+      expect(root.find(Paginate).prop('pathname'))
```
Comment (tofumatt) [inline tests/unit/amo/components/TestAddonReviewList.js]: `toHaveProp` matcher here too.

File: tests/unit/amo/components/TestAddonReviewList.js [hunk 15]
```diff
@@ -92,157 +257,91 @@ describe('amo/components/AddonReviewList', () => {
...
+        .toEqual(root.instance().url());
     });
 
     it('configures a paginator with the right Link', () => {
-      const paginator = findRenderedComponentWithType(render(), Paginate);
-      expect(paginator.props.LinkComponent).toEqual(Link);
+      expect(render().find(Paginate).prop('LinkComponent')).toEqual(Link);
```
Comment (tofumatt) [inline tests/unit/amo/components/TestAddonReviewList.js]: `toHaveProp` matcher here too. 😅

File: tests/unit/amo/components/TestAddonReviewList.js [hunk 16]
```diff
@@ -92,157 +257,91 @@ describe('amo/components/AddonReviewList', () => {
...
     });
 
     it('configures a paginator with the right review count', () => {
-      const paginator = findRenderedComponentWithType(
-        render({ reviewCount: 500 }), Paginate);
-      expect(paginator.props.count).toEqual(500);
+      const root = render({ reviewCount: 500 });
+      expect(root.find(Paginate).prop('count')).toEqual(500);
```
Comment (tofumatt) [inline tests/unit/amo/components/TestAddonReviewList.js]: `toHaveProp` matcher here too. I'm just commenting on them all so you can easily tell they're all fixed in the diff/PR comment view. 😅

File: tests/unit/amo/components/TestAddonReviewList.js [hunk 17]
```diff
@@ -92,157 +257,91 @@ describe('amo/components/AddonReviewList', () => {
...
     });
 
     it('sets the paginator to page 1 without a query', () => {
-      const paginator = findRenderedComponentWithType(
-        // Render with an empty query string.
-        render({ location: { query: {} } }), Paginate);
-      expect(paginator.props.currentPage).toEqual(1);
+      // Render with an empty query string.
+      const root = render({ location: { query: {} } });
+      expect(root.find(Paginate).prop('currentPage')).toEqual(1);
```
Comment (tofumatt) [inline tests/unit/amo/components/TestAddonReviewList.js]: `toHaveProp` matcher here too.

File: tests/unit/amo/components/TestAddonReviewList.js [hunk 18]
```diff
@@ -92,157 +257,91 @@ describe('amo/components/AddonReviewList', () => {
...
-          // Expect an action with a filtered review array.
-          // However, the count will not take into account the filtering.
-          const expectedAction = setAddonReviews({
-            addonSlug, reviews: [fakeReview], reviewCount: 2,
-          });
-          expect(dispatch.called).toBeTruthy();
-          expect(dispatch.firstCall.args[0]).toEqual(expectedAction);
-        });
+      const root = render({ location: { query: { page: 3 } } });
+      expect(root.find(Paginate).prop('currentPage')).toEqual(3);
```
Comment (tofumatt) [inline tests/unit/amo/components/TestAddonReviewList.js]: `toHaveProp` matcher here too.

File: tests/unit/amo/sagas/testReviews.js [hunk 19]
```diff
@@ -0,0 +1,85 @@
...
+          filter: 'without_empty_body',
+        })
+        .returns(apiResponsePage({ results: reviews }));
+
+      _fetchReviews();
+
+      await sagaTester.waitFor(SET_ADDON_REVIEWS);
+      mockAmoApi.verify();
+
+      expect(sagaTester.getCalledActions()[1]).toEqual(showLoading());
```
Comment (tofumatt) [inline tests/unit/amo/sagas/testReviews.js]: In the categories test we did:

```js
    const calledActions = sagaTester.getCalledActions();

    expect(calledActions[0]).toEqual(actions.categoriesFetch());

    [...]
```

I found it a touch prettier.

File: tests/unit/amo/components/TestAddonReviewList.js [hunk 20]
```diff
@@ -92,157 +257,91 @@ describe('amo/components/AddonReviewList', () => {
...
-      expect(ratings.length).toEqual(2);
+      const ratings = tree.find(Rating);
+      expect(ratings).toHaveLength(2);
 
-      expect(ratings[0].props.rating).toEqual(1);
-      expect(ratings[0].props.readOnly).toEqual(true);
-      expect(ratings[1].props.rating).toEqual(2);
-      expect(ratings[1].props.readOnly).toEqual(true);
+      expect(ratings.at(0).prop('rating')).toEqual(1);
+      expect(ratings.at(0).prop('readOnly')).toEqual(true);
```
Comment (tofumatt) [inline tests/unit/amo/components/TestAddonReviewList.js]: `toHaveProp` here too.

File: tests/unit/amo/components/TestAddonReviewList.js [hunk 21]
```diff
@@ -92,157 +257,91 @@ describe('amo/components/AddonReviewList', () => {
...
+      expect(ratings.at(1).prop('rating')).toEqual(2);
```
Comment (tofumatt) [inline tests/unit/amo/components/TestAddonReviewList.js]: `toHaveProp` here too.

File: tests/unit/amo/components/TestAddonReviewList.js [hunk 22]
```diff
@@ -92,157 +257,91 @@ describe('amo/components/AddonReviewList', () => {
...
+      expect(ratings.at(1).prop('readOnly')).toEqual(true);
```
Comment (tofumatt) [inline tests/unit/amo/components/TestAddonReviewList.js]: `toHaveProp` here too.

**Comment by tofumatt** [comment]
Oh, just one thing I noticed:

if you load the reviews page from the server seems like we don't dispatch the `setViewContext` action so it appears under "Explore" rather than "Extensions". You'd rarely run into this because usually you go to a review page from the add-on (which would have already set the right context), but technically we should be dispatching it.

screenshot 2017-06-24 00 01 17

It will be good to start dispatching those largely based on URL.

File: config/test.js (hunk 1 above)
Comment (kumar303) [inline config/test.js]: > the aim of setting this to false here was to make tests not output a log of logging stuff.

I sure hope not because that would be the most cruel trick ever played on a developer. It's 100% essential to see logging in test output. However, I would love to hide the test output for passing tests. Maybe that's possible. As for reducing noise, you can use `--quiet`.

File: src/amo/components/AddonReviewList.js (hunk 2 above)
Comment (kumar303) [inline src/amo/components/AddonReviewList.js]: [Byline](https://www.google.com/search?q=define%3A+byline&ie=utf-8&oe=utf-8) has been a standard word since the 1950s. Naming it `reviewAuthor` is awkward because the code already uses a variable named `review.userName`. Plus, this text contains name and date which makes it more of a byline than just an author name.

File: tests/unit/amo/components/TestAddonReviewList.js (hunk 10 above)
Comment (kumar303) [inline tests/unit/amo/components/TestAddonReviewList.js]: That's cool. I thought `toHaveProp()` was just a true/false thing to check if the prop exists.

**Comment by kumar303** [comment]
> we don't dispatch the setViewContext action

Good catch, fixed. Yeah, once we connect this to the URL then it won't require so many manual dispatch logic.

**Comment by kumar303** [comment]
Thanks for the reviews!
