### PR TITLE
Fix flow defs for Intl

### LINKED ISSUE #2500: Fix the flow definition for Intl so that the any escape hatch doesn't need to be used.
See https://github.com/mozilla/addons-frontend/blob/508590c8ae8c8adbdeb75cfdff978c3011564476/src/core/i18n/utils.js#L239 for details.

### PR DESCRIPTION
**Pull request by muffinresearch**
Fixes #2500

After using the flow env to try things out with a reduced test case this seems to work. It appears that you can't use `|` for global definitions or at least removing that makes it work.

See: http://bit.ly/2rI8UbW for the try flow env to see the reduced test case. (Works better in Chrome sadly)

### CODE REVIEW

File: flow/libs/intl.js.flow [hunk 1]
```diff
@@ -10,6 +9,4 @@ declare type IntlType = {
   NumberFormat: Class<Intl$NumberFormat>,
 }
 
-// Mark it as possibly undefined since
-// Safari and some recent versions of Firefox for Android do not implement it.
-declare var Intl: typeof undefined | IntlType;
+declare var Intl: IntlType;
```
Comment (kumar303) [inline flow/libs/intl.js.flow]: I think it's fine to add this as a workaround but ideally we want to say that `Intl` *can* be undefined in some browsers. This will make sure that we don't forget to write defensive code around it.

Can you put a comment in here linking to this Flow bug? I think this is what we're hitting. https://github.com/facebook/flow/issues/4077

File: flow/libs/intl.js.flow [hunk 2]
```diff
@@ -1,5 +1,4 @@
-// This is only a partial definition of
-// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl
+// This is only a partial definition of Intl (https://mzl.la/1dsIHLk MDN)
 
 declare class Intl$NumberFormat {
   constructor(locales: string | Array<string>, options?: Object): void;
```
Comment (kumar303) [inline flow/libs/intl.js.flow]: I just noticed that `format(number: Number)` should be `format(number: number)` -- [the lower case one is what we want](https://flow.org/en/docs/types/primitives/#toc-numbers). I always forget about the difference. Can you add that change? It doesn't help with the bug we're hitting but it will prevent other errors.

File: flow/libs/intl.js.flow (hunk 1 above)
Comment (kumar303) [inline flow/libs/intl.js.flow]: In the comments you may want to point out that the correct definition is:
```
declare var Intl: void | IntlType;
```
