### PR TITLE
Fix landing page

### LINKED ISSUE #3383: Improve "More Featured Extensions/Themes" section
Steps to reproduce:
1. Load Themes homepage https://addons-dev.allizom.org/en-US/firefox/themes/
2. Go to a theme category that has no featured themes i.e. https://addons-dev.allizom.org/en-US/firefox/themes/websites/
3. Go back to Themes homepage
4. Observe "More Featured Themes" section

Expected results:
There are no displayed or layout issues.

Actual results:
The featured section is hidden.

Notes/Issues:
- section reappears after page refresh

**Enhancement suggestion for featured section** - do not show the more link if less then 4 featured add-ons available.

Verified on AMO-dev FF56(Win 7, Android 7.2.1)
Screenshot for this issue:
featured

### PR DESCRIPTION
**Pull request by willdurand**
Fix #3383

---

This PR makes sure a landing page fetches data again after having loaded a category page. It happens because we use the same (redux) action with an optional parameter (`category`) and the `LandingPage` component needed to check it to determine if it had to get data or not. I also made sure that we did not dispatch `setViewContext` too often.

This diff is rather large because I rewrote most of the test file with `shallowUntilTarget()`.

### CODE REVIEW

File: src/amo/components/LandingPage/index.js [hunk 1]
```diff
@@ -37,17 +37,23 @@ const ICON_MAP = {
 
 export class LandingPageBase extends React.Component {
   static propTypes = {
-    addonTypeOfResults: PropTypes.string,
+    // This is a bug; addonTypeOfResults is used in
+    // `componentWillReceiveProps()`.
+    // eslint-disable-next-line react/no-unused-prop-types
```
Comment (kumar303) [inline src/amo/components/LandingPage/index.js]: I say disable it at the top -- it's annoying and full of bugs! If you search for components that disable it, you'll find a lot.

File: src/amo/components/LandingPage/index.js [hunk 2]
```diff
@@ -63,43 +69,49 @@ export class LandingPageBase extends React.Component {
...
   }
 
-  setViewContextType() {
-    const { dispatch, params } = this.props;
+  setViewContextType(nextProps = {}) {
+    const { params } = { ...this.props, ...nextProps };
     const addonType = apiAddonType(params.visibleAddonType);
-    dispatch(setViewContext(addonType));
+
+    if (this.props.context !== addonType) {
```
Comment (kumar303) [inline src/amo/components/LandingPage/index.js]: Should `context` be fetched more like this?

```js
const props = { ...this.props, ...nextProps };
if (props.context ...) {
}
```

File: tests/unit/amo/components/TestLandingPage.js [hunk 3]
```diff
@@ -15,27 +18,40 @@ import {
...
-describe('<LandingPage />', () => {
-  function renderProps(props = {}) {
+describe(__filename, () => {
+  function renderProps({
+    store = dispatchClientMetadata().store,
+    ...otherProps
+  } = {}) {
     return {
-      dispatch: sinon.stub(),
+      dispatch: store.dispatch,
```
Comment (kumar303) [inline tests/unit/amo/components/TestLandingPage.js]: You can delete this. It gets set automatically by `mapDispatchToProps()`.

File: tests/unit/amo/components/TestLandingPage.js [hunk 4]
```diff
@@ -68,97 +82,85 @@ describe('<LandingPage />', () => {
...
-    const addonType = ADDON_TYPE_EXTENSION;
-    const dispatch = sinon.stub();
-    const errorHandler = new ErrorHandler({ id: 'some-id', dispatch });
-    render({
-      dispatch,
-      errorHandler,
-      params: { visibleAddonType: visibleAddonType(addonType) },
-      resultsLoaded: false,
-    });
+    const { store } = dispatchClientMetadata();
```
Comment (kumar303) [inline tests/unit/amo/components/TestLandingPage.js]: This tends to be so common that I think it's better to make a var and initialize it in `beforeEach()`.

File: tests/unit/amo/components/TestLandingPage.js [hunk 5]
```diff
@@ -68,97 +82,85 @@ describe('<LandingPage />', () => {
...
+    sinon.assert.calledWith(fakeDispatch, setViewContext(ADDON_TYPE_EXTENSION));
+    sinon.assert.callCount(fakeDispatch, 1);
   });
 
   it('does not dispatch getLanding when there is an error', () => {
-    const dispatch = sinon.stub();
+    const { store } = dispatchClientMetadata();
+    const fakeDispatch = sinon.stub(store, 'dispatch');
+
     const errorHandler = new ErrorHandler({
```
Comment (kumar303) [inline tests/unit/amo/components/TestLandingPage.js]: it should be possible to rewrite this as:

```js
const errorHandler = new ErrorHandler({
  id: 'some-id', dispatch: store.dispatch,
});
errorHandler.handle(new Error('some error'));

render({ errorHandler, store });
```

File: tests/unit/amo/components/TestLandingPage.js [hunk 6]
```diff
@@ -303,4 +278,56 @@ describe('<LandingPage />', () => {
...
+      addonType,
+      featured: createAddonsApiResult([]),
+      highlyRated: createAddonsApiResult([]),
+      popular: createAddonsApiResult([]),
+    }));
+
+    const fakeDispatch = sinon.stub(store, 'dispatch');
+    render({ errorHandler, store });
+
+    sinon.assert.callCount(fakeDispatch, 2);
```
Comment (kumar303) [inline tests/unit/amo/components/TestLandingPage.js]: This can go at the end of the test since the assertion message won't be so good. The other assertion messages will be more informative.

File: src/amo/components/LandingPage/index.js [hunk 7]
```diff
@@ -63,43 +69,49 @@ export class LandingPageBase extends React.Component {
...
       addonTypeOfResults,
-      dispatch,
       errorHandler,
       loading,
       params,
       resultsLoaded,
-    } = this.props;
+    } = {
+      ...this.props,
+      ...nextProps,
```
Comment (kumar303) [inline src/amo/components/LandingPage/index.js]: If I comment this out all tests pass so the updating logic needs better coverage.

File: src/amo/components/LandingPage/index.js (hunk 1 above)
Comment (tofumatt) [reply src/amo/components/LandingPage/index.js]: But then we lose out on it for the entire file and it's still useful more than it isn't. Removing it means we'll miss out on opportunities to remove unused prop-types in the future, which is handy.

File: tests/unit/amo/components/TestLandingPage.js (hunk 6 above)
Comment (willdurand) [reply tests/unit/amo/components/TestLandingPage.js]: ah right

File: tests/unit/amo/components/TestLandingPage.js (hunk 3 above)
Comment (willdurand) [reply tests/unit/amo/components/TestLandingPage.js]: actually, that was needed for the `renderAndMount()` method that I did not touch.

File: src/amo/components/LandingPage/index.js (hunk 7 above)
Comment (willdurand) [reply src/amo/components/LandingPage/index.js]: I have added a test case to cover this case.

File: src/amo/components/LandingPage/index.js (hunk 1 above)
Comment (kumar303) [reply src/amo/components/LandingPage/index.js]: porting the prop types to Flow will get us much better coverage of prop usage.
