### PR TITLE
Editing a developer reply from a permalink is visually awkward

### LINKED ISSUE #6356: Editing a developer reply from a permalink is visually awkward
### Describe the problem and steps to reproduce it:

- Sign in as a developer
- Go to one of your add-ons that has some reviews
- Go to the review listing
- Reply to a review
- Click the timestamp of the review to view its detail page
- From the detail page, click *Edit my review*

### What happened?

It looks like:

screenshot 2018-09-21 16 22 28

### What did you expect to happen?

* There shouldn't be any stars
* ~~You should only see one review form. Multiple forms are open because the reply is also rendered further down in the listing.~~
  * https://github.com/mozilla/addons-frontend/issues/6443 has been opened to address this.
* ~~The link to edit should have been *Edit my reply*~~
* The buttons should say *Update reply*, etc

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #6356 

Before:

screenshot 2018-09-27 13 42 25

After:

screenshot 2018-09-27 13 41 35

### CODE REVIEW

**Comment by bobsilverberg** [comment]
Note that I uncovered a bug while testing this which I opened at https://github.com/mozilla/addons-frontend/issues/6441. Note also that I did not address the issue of two reply forms opening in the patch, but opened https://github.com/mozilla/addons-frontend/issues/6443 as a follow-up.

File: tests/unit/amo/sagas/test_reviews.js [hunk 1]
```diff
@@ -674,6 +676,26 @@ describe(__filename, () => {
...
+        );
+
+      _updateAddonReview();
+
+      const expectedAction = hideFlashedReviewMessage();
+      await sagaTester.waitFor(expectedAction.type);
+
+      const unexpectedAction = fetchAddon({ errorHandler, slug });
+
+      expect(sagaTester.getCalledActions().map((a) => a.type)).not.toContain(
```
Comment (rebmullin) [inline tests/unit/amo/sagas/test_reviews.js]: can you just do this here:
` expect(sagaTester.numCalled(unexpectedAction.type)).toEqual(0);` ?

File: tests/unit/amo/sagas/test_reviews.js [hunk 2]
```diff
@@ -792,6 +814,44 @@ describe(__filename, () => {
...
+
+      const unexpectedAction = setLatestReview({
+        addonId,
+        addonSlug,
+        review: externalReview,
+        userId,
+        versionId,
+      });
+
+      expect(sagaTester.getCalledActions().map((a) => a.type)).not.toContain(
```
Comment (rebmullin) [inline tests/unit/amo/sagas/test_reviews.js]: same here? or the mapping necessary?

File: src/amo/components/AddonReviewManager/index.js [hunk 3]
```diff
@@ -88,41 +88,59 @@ export class AddonReviewManagerBase extends React.Component<InternalProps> {
...
+    let submitButtonText = i18n.gettext('Submit review');
+    if (review.body) {
+      submitButtonText = review.isDeveloperReply
+        ? i18n.gettext('Update reply')
+        : i18n.gettext('Update review');
+    }
+
+    let submitButtonInProgressText = i18n.gettext('Submitting review');
+    if (review.body) {
+      submitButtonInProgressText = review.isDeveloperReply
```
Comment (rebmullin) [inline src/amo/components/AddonReviewManager/index.js]: just a thought..can this be moved up above (under the above review.body)?

File: src/amo/components/AddonReviewManager/index.js [hunk 4]
```diff
@@ -88,41 +88,59 @@ export class AddonReviewManagerBase extends React.Component<InternalProps> {
     );
 
     /* eslint-disable react/no-danger */
-    const formFooter = (
+    const formFooter = !review.isDeveloperReply ? (
```
Comment (rebmullin) [inline src/amo/components/AddonReviewManager/index.js]: is worth setting review.isDeveloperReply to a var since it's used a few times here?

**Comment by bobsilverberg** [comment]
@rebmullin Regarding the issue you're seeing with the delete functionality, this seems kind of similar to issue #6441, so maybe whatever we do to address that will also fix this issue. If not, then your idea of re-directing to the reviews listing after deleting a reply might be a good solution.

File: tests/unit/amo/sagas/test_reviews.js (hunk 1 above)
Comment (bobsilverberg) [reply tests/unit/amo/sagas/test_reviews.js]: Agreed, this seems simpler. I was just following the model we use everywhere else. Thanks @rebmullin!

File: src/amo/sagas/reviews.js [hunk 5]
```diff
@@ -281,21 +281,23 @@ function* manageAddonReview(
...
-    yield put(
-      setLatestReview({
-        addonId: reviewFromResponse.addon.id,
-        addonSlug: reviewFromResponse.addon.slug,
-        review: reviewFromResponse,
-        userId: reviewFromResponse.user.id,
-        versionId: reviewFromResponse.version.id,
-      }),
-    );
+    if (!reviewFromResponse.is_developer_reply) {
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/sagas/reviews.js]: I did this because `reviewFromResponse.version` is missing and therefore the `invariant` is being triggered. I realized that if we are updating a reply we really don't need to do either of these things (`setLatestReview` or `fetchAddon`), so it made sense to just not do them.

Looking closer now, I'm not sure that the fact that `version` is missing from the response is expected, and maybe that's a bug on the server side. The [docs](https://addons-server.readthedocs.io/en/latest/topics/api/ratings.html#rating-detail-object) don't mention that `version` is optional. I guess I'll file a bug on addons-server for that, but it still makes sense to me that we wouldn't dispatch either of those actions for a reply update as neither are needed.

@kumar303 What do you think?

[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/sagas/reviews.js]: I opened https://github.com/mozilla/addons-server/issues/9550 to report the missing `version`, although I now suspect that that is expected.

**Comment by bobsilverberg** [comment]
Actually, @rebmullin, can you confirm whether you are logged in with an admin account when you saw the delete issue? If you were then it might be invalid. Admin users can see deleted reviews, and there is no data currently available to allow us to know that a review/reply has been deleted. So if you are an admin and you are at the details screen for a review/reply and you delete it, you will still see if in the FeaturedReviewCard because the app will still be able to retrieve it from the API.

**Comment by bobsilverberg** [comment]
Thanks for the reviews @rebmullin and @kumar303. A new version is now available for review.

**Comment by kumar303** [comment]
@rebmullin 

> Click delete my review (or reply) ... I would think it would return you back to the reviews page maybe.? 

Yep, I noticed this the other day, too. We will fix it here: https://github.com/mozilla/addons-frontend/issues/6438

File: src/amo/sagas/reviews.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (kumar303) [reply src/amo/sagas/reviews.js]: Interesting. It looks like someone had already figured out that the version could be missing because our Flow type is correct:

https://github.com/mozilla/addons-frontend/blob/a238ae43335c366c34569a29d6c021130ef982c0/src/amo/api/reviews.js#L31-L43

Comment (kumar303) [inline src/amo/sagas/reviews.js]: > it still makes sense to me that we wouldn't dispatch either of those actions for a reply update as neither are needed.

Yes, I agree. I see it now. I guess `fetchAddon` would be possible since it doesn't require `version` but I can't think of why we need it.
