### PR TITLE
I5217 fixing settimeout memory leak

### LINKED ISSUE #5217: Can't call setState (or forceUpdate) on an unmounted component
### Describe the problem and steps to reproduce it:

1. Go to a collection edit page
2. Add some add-ons (at least one)
3. "Save" the collection
4. Observe the console logs

### What happened?

I see this message:

```text
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in CollectionManagerBase (created by Connect(CollectionManagerBase))
    in Connect(CollectionManagerBase) (created by Connect(Connect(CollectionManagerBase)))
    in Connect(Connect(CollectionManagerBase)) (created by Translate[Connect(Connect(CollectionManagerBase))])
    in Translate[Connect(Connect(CollectionManagerBase))] (created by withRouter(Translate[Connect(Connect(CollectionManagerBase))]))
    in withRouter(Translate[Connect(Connect(CollectionManagerBase))]) (created by CollectionBase)
    in div (created by Card)
    in section (created by Card)
    in Card (created by CollectionBase)
    in div (created by CollectionBase)
    in div (created by CollectionBase)
    in CollectionBase (created by Connect(CollectionBase))
    in Connect(CollectionBase) (created by Connect(Connect(CollectionBase)))
    in Connect(Connect(CollectionBase)) (created by Translate[Connect(Connect(CollectionBase))])
    in Translate[Connect(Connect(CollectionBase))] (created by CollectionEdit)
    in CollectionEdit (created by RouterContext)
```

### What did you expect to happen?

There should not be any message like that.

I don't think it breaks anything since it is a warning but it is worth investigating.

### PR DESCRIPTION
**Pull request by rebmullin**
fixes #5217 

settimeout was the culprit here :/ but by clearing this out in unmount, this issue goes away

@willdurand / @bobsilverberg, please take a look? :)

### CODE REVIEW

File: src/amo/components/CollectionManager/index.js [hunk 1]
```diff
@@ -77,13 +78,16 @@ type State = {|
...
+  timeout: TimeoutID;
+
   static defaultProps = {
     setTimeout: typeof window !== 'undefined' ? window.setTimeout.bind(window) : () => {},
   };
 
   constructor(props: Props) {
     super(props);
     this.state = this.propsToState(props);
+    this.timeout; // eslint-disable-line no-unused-expressions
```
Comment (willdurand) [inline src/amo/components/CollectionManager/index.js]: Do you really need this?

File: src/amo/components/CollectionManager/index.js [hunk 2]
```diff
@@ -104,13 +108,17 @@ export class CollectionManagerBase extends React.Component<Props, State> {
...
-      this.props.setTimeout(
+      this.timeout = this.props.setTimeout(
         this.resetMessageStatus,
         MESSAGE_RESET_TIME
       );
     }
   }
 
+  componentWillUnmount() {
+    clearTimeout(this.timeout);
```
Comment (willdurand) [inline src/amo/components/CollectionManager/index.js]: What happens if you call `clearTimeout` with `this.timeout === undefined` (or `null`)? I guess we could play safe and write:

```js
if (this.timeout) {
  clearTimeout(this.timeout);
}
```

Comment (willdurand) [reply src/amo/components/CollectionManager/index.js]: I think we should also cover this line with a test case.

We could inject `clearTimeout` like `setTimeout` and use `unmount()` from Enzyme: http://airbnb.io/enzyme/docs/api/ShallowWrapper/unmount.html.

File: src/amo/components/CollectionManager/index.js (hunk 1 above)
Comment (rebmullin) [reply src/amo/components/CollectionManager/index.js]: I thought we did but we don't it seems : )

File: src/amo/components/CollectionManager/index.js (hunk 2 above)
Comment (rebmullin) [reply src/amo/components/CollectionManager/index.js]: yes! let me look into this more : )

Comment (rebmullin) [reply src/amo/components/CollectionManager/index.js]: @willdurand, I have a shell set up for this but i may need a little bit of help. I want to try to dig into this a bit before first tho : ). I'll let you know...

File: src/amo/components/CollectionManager/index.js [hunk 3]
```diff
@@ -1,5 +1,6 @@
 /* @flow */
 /* global window */
+/* eslint-disable react/sort-comp */
```
[the remark this answers is not in the document]
Comment (rebmullin) [reply src/amo/components/CollectionManager/index.js]: if I don't put this linting complains about where I declare `timeout`:
`error  timeout should be placed after onAddonSelected  react/sort-comp`

It looks like we are using this in other files for this purpose so I assumed this was ok..

File: tests/unit/amo/components/TestCollectionManager.js [hunk 4]
```diff
@@ -738,6 +738,38 @@ describe(__filename, () => {
     expect(root.find(Notice)).toHaveLength(0);
   });
 
+  it('clearTimeout is called on unmount if timeout is set', () => {
+    const clearTimeoutSpy = sinon.spy();
+    const root = render({ clearTimeout: clearTimeoutSpy });
+    const unMountSpy = sinon.spy(root.instance(), 'componentWillUnmount');
+
+    // Simulates the setTimeout behavior
+    // in which timeout is set.
```
[the remark this answers is not in the document]
Comment (rebmullin) [reply tests/unit/amo/components/TestCollectionManager.js]: good point : )

File: tests/unit/amo/components/TestCollectionManager.js [hunk 5]
```diff
@@ -738,6 +738,38 @@ describe(__filename, () => {
     expect(root.find(Notice)).toHaveLength(0);
   });
 
+  it('clearTimeout is called on unmount if timeout is set', () => {
+    const clearTimeoutSpy = sinon.spy();
+    const root = render({ clearTimeout: clearTimeoutSpy });
+    const unMountSpy = sinon.spy(root.instance(), 'componentWillUnmount');
```
[the remark this answers is not in the document]
Comment (rebmullin) [reply tests/unit/amo/components/TestCollectionManager.js]: oh? ok..

File: src/amo/components/CollectionManager/index.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (willdurand) [reply src/amo/components/CollectionManager/index.js]: mmh I don't know. I think it is fine to put it where ESLint wants:

```diff
diff --git a/src/amo/components/CollectionManager/index.js b/src/amo/components/CollectionManager/index.js
index 26ee76178..097125e55 100644
--- a/src/amo/components/CollectionManager/index.js
+++ b/src/amo/components/CollectionManager/index.js
@@ -1,6 +1,5 @@
 /* @flow */
 /* global window */
-/* eslint-disable react/sort-comp */
 import { oneLineTrim } from 'common-tags';
 import invariant from 'invariant';
 import * as React from 'react';
@@ -79,8 +78,6 @@ type State = {|
 |};
 
 export class CollectionManagerBase extends React.Component<Props, State> {
-  timeout: TimeoutID;
-
   static defaultProps = {
     setTimeout: typeof window !== 'undefined' ? window.setTimeout.bind(window) : () => {},
     clearTimeout: typeof window !== 'undefined' ? window.clearTimeout.bind(window) : () => {},
@@ -257,6 +254,8 @@ export class CollectionManagerBase extends React.Component<Props, State> {
     this.setState({ addonAddedStatus: ADDON_ADDED_STATUS_PENDING });
   };
 
+  timeout: TimeoutID;
+
   resetMessageStatus = () => {
     this.setState({
       addonAddedStatus: null,
```

File: tests/unit/amo/components/TestCollectionManager.js [hunk 6]
```diff
@@ -738,6 +738,27 @@ describe(__filename, () => {
...
+    expect(clearTimeoutSpy.callCount).toEqual(1);
+  });
+
+  it('does not call clearTimeout when unmounting and there is no timeout set', () => {
+    const clearTimeoutSpy = sinon.spy();
+    const root = render({ clearTimeout: clearTimeoutSpy });
+
+    root.unmount();
+
+    expect(clearTimeoutSpy.callCount).toEqual(0);
```
Comment (willdurand) [inline tests/unit/amo/components/TestCollectionManager.js]: We should use `sinon` for this kind of assertions, because `sinon` gives us a better output:

```diff
diff --git a/tests/unit/amo/components/TestCollectionManager.js b/tests/unit/amo/components/TestCollectionManager.js
index f23bd5b92..062f2882f 100644
--- a/tests/unit/amo/components/TestCollectionManager.js
+++ b/tests/unit/amo/components/TestCollectionManager.js
@@ -756,7 +756,7 @@ describe(__filename, () => {
 
     root.unmount();
 
-    expect(clearTimeoutSpy.callCount).toEqual(0);
+    sinon.assert.notCalled(clearTimeoutSpy);
   });
 
   it('removes the notification after a new add-on has been selected', () => {

```

File: tests/unit/amo/components/TestCollectionManager.js [hunk 7]
```diff
@@ -738,6 +738,27 @@ describe(__filename, () => {
...
+  it('calls clearTimeout when unmounting and timeout is set', () => {
+    const clearTimeoutSpy = sinon.spy();
+    const root = render({ clearTimeout: clearTimeoutSpy });
+
+    // Simulates the setTimeout behavior in which timeout is set.
+    root.instance().timeout = 50;
+
+    root.unmount();
+
+    expect(clearTimeoutSpy.callCount).toEqual(1);
```
Comment (willdurand) [inline tests/unit/amo/components/TestCollectionManager.js]: We should use `sinon` for this kind of assertions, because `sinon` gives us a better output:

```diff
diff --git a/tests/unit/amo/components/TestCollectionManager.js b/tests/unit/amo/components/TestCollectionManager.js
index f23bd5b92..0d7fc6416 100644
--- a/tests/unit/amo/components/TestCollectionManager.js
+++ b/tests/unit/amo/components/TestCollectionManager.js
@@ -742,12 +742,13 @@ describe(__filename, () => {
     const clearTimeoutSpy = sinon.spy();
     const root = render({ clearTimeout: clearTimeoutSpy });
 
+    const timeoutID = 123;
     // Simulates the setTimeout behavior in which timeout is set.
-    root.instance().timeout = 50;
+    root.instance().timeout = timeoutID;
 
     root.unmount();
 
-    expect(clearTimeoutSpy.callCount).toEqual(1);
+    sinon.assert.calledWith(clearTimeoutSpy, timeoutID);
   });
 
   it('does not call clearTimeout when unmounting and there is no timeout set', () => {

```

File: tests/unit/amo/components/TestCollectionManager.js (hunk 6 above)
Comment (rebmullin) [reply tests/unit/amo/components/TestCollectionManager.js]: ahh..ok.. that makes sense
