### PR TITLE
Encode URIs with encodeURI() instead of utf8.encode() before calling fetch()

### LINKED ISSUE #11438: URL with kanji results in 404
I assume it is a regression caused by something on the next milestone (05.05.2022)

STR:
1. From edit page of an addon that uses kanji in the name click on View Product Page

https://addons-dev.allizom.org/en-US/developers/addon/%E6%BC%A2%E5%AD%97%E6%BC%A2%E5%AD%97%E6%BC%A2%E5%AD%97%E5%AD%A6%E5%B9%B4%E5%88%A5%E6%BC%A2%E5%AD%97%E9%85%8D%E5%BD%93%E8%A1%A814/edit

Actual result: 
404 page

Expected result:
The detail page should be displayed because the addon has been approved

Notes:
not reproducible on AMO stage, it is only reproducible on AMO dev
only reproducible with kanji addons
cc @diox

### PR DESCRIPTION
**Pull request by diox**
Fixes #11438

### CODE REVIEW

File: src/amo/api/index.js [hunk 1]
```diff
@@ -166,12 +165,9 @@ export function callApi({
   adjustedEndpoint = adjustedEndpoint.endsWith('/')
     ? adjustedEndpoint
     : `${adjustedEndpoint}/`;
-  let apiURL = `${config.get('apiHost')}${adjustedEndpoint}${queryString}`;
-  if (_config.get('server')) {
-    _log.debug('Encoding `apiURL` in UTF8 before fetch().');
-    // Workaround for https://github.com/bitinn/node-fetch/issues/245
-    apiURL = utf8.encode(apiURL);
-  }
+  const apiURL = encodeURI(
```
Comment (bobsilverberg) [inline src/amo/api/index.js:168]: I don't understand why we are now encoding on both the client and server, whereas before we were only encoding on the server.

**Review by bobsilverberg — APPROVED** [review]
I have a question about why the logic changed about when we encode.

r+wc
