### PR TITLE
fix: add locale URL exception (fix #1867)

### LINKED ISSUE #1867: Add-ons cannot be installed from disco pane when mamo cookie is set
Prerequisites:
- `extensions.webservice.discoverURL` is set to point to -dev (https://discovery.addons-dev.allizom.org/%LOCALE%/firefox/discovery/pane/%VERSION%/%OS%/%COMPATIBILITY_MODE%)
- `xpinstall.signatures.dev-root` set to true
- browser used: FF54

Steps to reproduce:
1. On AMO-dev (desktop) homepage,  go to footer and click "View Mobile Site"
2. Go to about:addons and try to install an add-on i.e. Video DownloadHelper

Expected results:
The add-on is installed.

Actual results:
The add-on cannot be installed.

Notes/Issues:
- issue is not reproducing for -stage or -production.
- issue is not reproducing on -dev either if first step is not fulfilled
Verified on FF54(Win 7). Issue is reproducing on AMO-dev.
Screenshot for this issue:
about_addons

### LINKED ISSUE #1991: RelaodEvery does not install and shows connection problem
Steps to reproduce : 

1. Go to https://addons-dev.allizom.org/en-US/firefox/addon/reloadevery/
2. Then use the slider button beside the star button to download it
  

Actual Result :

A pop-up comes which shows connection problem 

Expected Result :

It should have been installed. And if it is not compatible with mobile device then the pop-up should say that "it is not compatible with mobile device"  

Attachment  -

17198039_1282377388519532_929326456_n

### PR DESCRIPTION
**Pull request by tofumatt**
fix #1867
fix #1991

Sorry, more `middleware.js` URL handling. This patch allows root URLs like `/downloads/*` or `/contribute.json` to be served properly without infinite redirects.

### CODE REVIEW

File: config/default-amo.js [hunk 1]
```diff
@@ -24,6 +24,21 @@ module.exports = {
   },
   enableTrailingSlashesMiddleware: true,
   fxaConfig: 'amo',
+
+  // This needs to be kept in sync with addons-server's SUPPORTED_NONLOCALES
+  // settings value: https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/settings_base.py#L274
+  validRootUrlExceptions: [
```
Comment (tofumatt) [inline config/default-amo.js]: Relevant bit in `addons-server` is ready to merge once this PR gets merged. https://github.com/mozilla/addons-server/pull/4772

Comment (kumar303) [inline config/default-amo.js]: I'm confused. Is this supposed to be `validRootExceptions` or is the whitelisted key supposed to be `validRootUrlExceptions`? Either way, they are out of sync.

Comment (muffinresearch) [inline config/default-amo.js]: Would it be clearer to keep the config keys between the server and frontend more similar? Having the locale in the name makes it a bit clear what this does to me somehow.

Comment (kumar303) [inline config/default-amo.js]: I was confused because `validRootUrlExceptions` looks like a typo. Is it not? I don't see it initialized in https://github.com/mozilla/addons-frontend/blob/44b614eba8c7692d903c7806fcd183e962da4882/config/default.js

Comment (kumar303) [inline config/default-amo.js]: Also, the `isValidRootException()` function doesn't check it so it won't be used by anything.

Comment (tofumatt) [inline config/default-amo.js]: Omg yeah and the way we mock out the tests it still passes. Maybe I changed the keys after I tested it in the browser and messed up. /me fixes...

Comment (tofumatt) [inline config/default-amo.js]: > Would it be clearer to keep the config keys between the server and frontend more similar? Having the locale in the name makes it a bit clear what this does to me somehow.

Yeah, I actually misunderstood this a bit because during testing I saw some URL redirects and didn't realise one was to the CDN. I need to change the patch a bit.

**Comment by tofumatt** [comment]
I got confused by this because the addons-server code includes both `contribute.json` and `downloads` in their list... but `contribute.json` is redirected to unless it's at the root and `/downloads/` is redirected to `/firefox/downloads/`.

So it seems the code isn't actually accurate on the server and there could be other redirects happening. I'll do my best to replicate what the server does by trial+error 😢

**Comment by tofumatt** [comment]
Working on this and tidying up the middleware in the process as it was getting a bit hard to understand and outgrowing its original code paths/setup. Patch should be coming later tonight as I'm meeting up with friends who are leaving town so I'll be back later.

**Comment by tofumatt** [comment]
Key names were wrong and I misunderstood the patch. Turns out it was for `/firefox/downloads` not `/downloads`

So I tweaked it and added a bit more test coverage. Ready for another r?

I'm sorry this too me forever 😒

File: tests/client/core/test_middleware.js [hunk 2]
```diff
@@ -68,17 +70,51 @@ describe('Prefix Middleware', () => {
     assert.deepEqual(fakeRes.set.firstCall.args, ['vary', []]);
   });
 
-  it('should render a 404 when a URL exception is found', () => {
+  it('should render 404 when a localeURL exception exists', () => {
```
Comment (muffinresearch) [inline tests/client/core/test_middleware.js]: Presumably this is only the in a case where we don't have a route?

File: config/default-amo.js [hunk 3]
```diff
@@ -24,9 +24,24 @@ module.exports = {
...
+    'blocklist',
+    'static',
+    'user-media',
+    '__version__',
+  ],
+
   // This needs to be kept in sync with addons-server's SUPPORTED_NONAPPS
   // settings value: https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/settings_base.py#L262
-  validUrlExceptions: [
+  validClientAppUrlExceptions: [
```
Comment (muffinresearch) [inline config/default-amo.js]: Nice, this is easier to understand.

File: tests/client/core/test_middleware.js (hunk 2 above)
Comment (tofumatt) [inline tests/client/core/test_middleware.js]: Yeah. Well, all of our routes are prepended with `/:lang/:clientApp/` so we don't have routes that look like these.

I guess if we were eventually serving them it might be weird but I don't think we'd do so with the React Router anyway, so I think it's fine.

Comment (muffinresearch) [inline tests/client/core/test_middleware.js]: My point was the test comment makes it sound like a 404 is tied to the localeURL exception - which might be confusing in the future if we ever needed a route without a locale.

Comment (tofumatt) [inline tests/client/core/test_middleware.js]: Hmm... does `a localeUrlException triggers a 404` work any better? It clearly ties it to a config value. I could add a comment saying "URLs without a locale will still work as long as they aren't in this config"...

Comment (muffinresearch) [inline tests/client/core/test_middleware.js]: How about `should render 404 for localeURL exception when route does not exist`?

Comment (tofumatt) [inline tests/client/core/test_middleware.js]: Oh, no, so it renders a 404 no matter what. The middleware is hit before the routes are accessed and they are in the config–it makes sense to intercept them right away.

If we wanted to serve routes like `/firefox/downloads/foo` but 404 on other things this patch would need to be more complicated.

**Comment by tofumatt** [comment]
@muffinresearch and I chatted about this and agreed that we should stop the middleware from sending out the 404s and just prevent the redirects, but I'll do that in a patch later because we want this to land for release and it doesn't break anything for now.

The middleware shouldn't be sending the 404 though and I'll file a bug to fix it before landing this.

File: config/default-amo.js [hunk 4]
```diff
@@ -24,9 +24,24 @@ module.exports = {
   },
   enableTrailingSlashesMiddleware: true,
   fxaConfig: 'amo',
+
+  // This needs to be kept in sync with addons-server's SUPPORTED_NONLOCALES
```
Comment (kumar303) [inline config/default-amo.js]: I think it would help to add a sentence about what the map is for -- something simple like "These URLs do not require a locale prefix."

File: config/default-amo.js [hunk 5]
```diff
@@ -24,9 +24,24 @@ module.exports = {
...
+  // settings value: https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/settings_base.py#L274
+  validLocaleUrlExceptions: [
+    'contribute.json',
+    'google1f3e37b7351799a5.html',
+    'robots.txt',
+    'services',
+    'downloads',
+    'blocklist',
```
Comment (kumar303) [inline config/default-amo.js]: Since this isn't in addons-server maybe you should add a comment that it exists to support a redirect to the other host?

File: src/core/middleware.js [hunk 6]
```diff
@@ -21,42 +22,70 @@ export function prefixMiddleWare(req, res, next, { _config = config } = {}) {
...
+    prependedOrMovedApplication = true;
   } else if (!hasValidLang) {
     // If lang wasn't valid or was missing prepend one.
     log.info(`Prepending lang to URL: ${lang}`);
     URLParts.splice(0, 0, lang);
     prependedLang = true;
     // If we've prepended the lang to the URL we need to re-check our
     // URL exception and make sure it's valid.
-    hasValidUrlException = isValidUrlException(URLParts[1], { _config });
+    hasValidClientAppUrlException = isValidClientAppUrlException(URLParts[1], { _config });
```
Comment (kumar303) [inline src/core/middleware.js]: I know we don't force 80 char lines but I would be grateful if this was under 80 because I like my split screen :)

File: src/core/middleware.js [hunk 7]
```diff
@@ -21,42 +22,70 @@ export function prefixMiddleWare(req, res, next, { _config = config } = {}) {
...
   }
 
-  let isApplicationFromHeader = false;
-
-  if (!hasValidClientApp && prependedLang &&
-      isValidClientApp(URLParts[1], { _config })) {
+  if (
+    !hasValidClientApp && prependedLang &&
```
Comment (kumar303) [inline src/core/middleware.js]: If I remove `prependedLang` from the statement, all tests still pass.

Comment (kumar303) [inline src/core/middleware.js]: If I remove `!hasValidClientApp` from the statement, all tests still pass.

File: src/core/middleware.js [hunk 8]
```diff
@@ -21,42 +22,70 @@ export function prefixMiddleWare(req, res, next, { _config = config } = {}) {
...
+    isValidClientApp(URLParts[1], { _config })
+  ) {
     // We skip prepending an app if we'd previously prepended a lang and the
     // 2nd part of the URL is now a valid app.
     log.info('Application in URL is valid following prepending a lang.');
-  } else if (hasValidUrlException) {
-    if (hasValidLang) {
+  } else if (
+    !hasValidClientApp && prependedOrMovedApplication &&
```
Comment (kumar303) [inline src/core/middleware.js]: If I remove `!hasValidClientApp`, the tests still pass

File: src/core/middleware.js [hunk 9]
```diff
@@ -21,42 +22,70 @@ export function prefixMiddleWare(req, res, next, { _config = config } = {}) {
...
+    isValidLocaleUrlException(URLParts[1], { _config })
```
Comment (kumar303) [inline src/core/middleware.js]: if I remove this, all tests still pass

**Comment by tofumatt** [comment]
Looking at the test coverage it was actually good (it covers all URL forms we could expect) but I just had extra-wordy conditionals (there was no need to check for one thing when it was checked earlier, etc.). I've tidied them up and added the requested comments 😄

File: config/default-amo.js [hunk 10]
```diff
@@ -25,9 +25,34 @@ module.exports = {
   },
   enableTrailingSlashesMiddleware: true,
   fxaConfig: 'amo',
+
+  // This needs to be kept in sync with addons-server's SUPPORTED_NONLOCALES
+  // settings value: https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/settings_base.py#L274
+  // These are URLs that are ignored by our prefix middleware that will add
+  // a locale (e.g. `en-US`) to any URL that doesn't have a valid locale.
+  // These are all URLs that should not prepend the locale to the URL if it's
```
Comment (kumar303) [inline config/default-amo.js]: Thanks for adding extra comments. I think this sentence needs to be reworded though. "These are all URLs that should not get a locale prepended ... " ?

**Comment by tofumatt** [comment]
Cool. I've filed an issue (#2003) to improve it (hopefully reducing complexity) in the future, but this works for launch.
