### PR TITLE
Fixes #2855 Categories are not alphabetically sorted 

### LINKED ISSUE #2855: Categories are not alphabetically sorted
Steps to reproduce:
1. Load categories pages for extensions or themes while using the new desktop pages i.e. https://addons-dev.allizom.org/en-US/firefox/extensions/categories/

Expected results:
Categories are alphabetically sorted.

Actual results:
Categories are not alphabetically sorted.

Notes/Issues:
- same issue in extensions/themes homepages
Verified on AMO-dev FF54(Win 7).
Screenshots for this issue:

### PR DESCRIPTION
**Pull request by brainzest**
#2855 Categories were not alphabetically sorted. 

- Added a sorting function. 
- This can be added as a helper function if it's going to be reused. 

screen shot 2017-07-26 at 23 04 52
screen shot 2017-07-26 at 23 05 18

### CODE REVIEW

File: src/amo/components/Categories/index.js [hunk 1]
```diff
@@ -91,7 +97,7 @@ export class CategoriesBase extends React.Component {
               );
             })}
           </div>
-        :
+          :
```
Comment (tofumatt) [inline src/amo/components/Categories/index.js]: This change isn't needed, looks like a mistake.

File: src/amo/components/Categories/index.js [hunk 2]
```diff
@@ -51,6 +51,12 @@ export class CategoriesBase extends React.Component {
     const { addonType, className, error, loading, i18n } = this.props;
     const categories = this.props.categories[addonType] ?
       Object.values(this.props.categories[addonType]) : [];
+    categories.sort(function(a,b){
```
Comment (tofumatt) [inline src/amo/components/Categories/index.js]: There's nothing wrong with this style of function declaration but we usually use fat-arrow functions:

```js
categories.sort((a, b) => {
  [...]
});
```

Comment (brainzest) [inline src/amo/components/Categories/index.js]: Noted. I will change it right away.

Comment (brainzest) [inline src/amo/components/Categories/index.js]: @tofumatt   eslint test gives 58:14  error  Do not nest ternary expressions  no-nested-ternary
Should I change it to if else statements?

Comment (tofumatt) [inline src/amo/components/Categories/index.js]: Yes, I didn't get to that part but the nested ternary statements are quite difficult to read.

Note that I think the reducer tries to sort these when stored but I guess they don't stay sorted, so there's probably some code to remove in the reducers.

**Comment by brainzest** [comment]
@tofumatt  Can you please review the  new commit? I am not sure about the coveralls check.

**Comment by tofumatt** [comment]
This line is not covered by the tests https://coveralls.io/builds/12564546/source?filename=src%2Fcore%2Freducers%2Fcategories.js#L79

File: tests/unit/amo/components/TestCategories.js [hunk 3]
```diff
@@ -70,14 +70,14 @@ describe('<Categories />', () => {
       result: [
         {
           application: 'android',
-          name: 'Games',
-          slug: 'Games',
+          name: 'Travel',
```
Comment (tofumatt) [inline tests/unit/amo/components/TestCategories.js]: You should leave this test how it is and add a few out-of-order categories, making a new test to ensure sorting works how you want.

File: src/core/reducers/categories.js [hunk 4]
```diff
@@ -67,7 +67,17 @@ export default function categories(state = initialState, action) {
         Object.keys(categoryList).forEach((appName) => {
           Object.keys(categoryList[appName]).forEach((addonType) => {
             categoryList[appName][addonType] = categoryList[appName][addonType]
-              .sort((a, b) => a.name >= b.name)
+              .sort((a, b) => {
+                const x = a.slug;
```
Comment (tofumatt) [inline src/core/reducers/categories.js]: These definitions aren't necessary; you can just use `a.slug` directly instead as they'll fit on the lines below and these variable definitions actually obscure the variables rather than explaining their contents.

File: src/core/reducers/categories.js [hunk 5]
```diff
@@ -67,7 +67,17 @@ export default function categories(state = initialState, action) {
...
+                const y = b.slug;
```
Comment (tofumatt) [inline src/core/reducers/categories.js]: Why did you change from name to slug? We want to sort based on category name, not slug/URL.

File: tests/unit/amo/components/TestCategories.js (hunk 3 above)
Comment (brainzest) [inline tests/unit/amo/components/TestCategories.js]: Ok. Should I add this test in components side or inside reducers?  Actually it expects the categoryResponse to be already sorted.

**Comment by brainzest** [comment]
@tofumatt  Can you please review the changes?

File: src/core/reducers/categories.js (hunk 5 above)
Comment (brainzest) [inline src/core/reducers/categories.js]: This has been fixed.

File: src/amo/components/Categories/index.js (hunk 1 above)
Comment (muffinresearch) [inline src/amo/components/Categories/index.js]: @brainzest was there a reason for this change?

**Comment by muffinresearch** [comment]
@tofumatt I think this looks good in general - any further comments?

File: src/core/reducers/categories.js [hunk 6]
```diff
@@ -67,7 +67,7 @@ export default function categories(state = initialState, action) {
         Object.keys(categoryList).forEach((appName) => {
           Object.keys(categoryList[appName]).forEach((addonType) => {
             categoryList[appName][addonType] = categoryList[appName][addonType]
-              .sort((a, b) => a.name >= b.name)
+              .sort((a, b) => a.name.localeCompare(b.name))
```
Comment (tofumatt) [inline src/core/reducers/categories.js]: Neat!
