### PR TITLE
fix: Encode query params (fix #1680)

### LINKED ISSUE #1680: After performing a search for the symbol  “&” then performing a refresh of the web page, the message “Internal Server Error” is displayed
### Describe the problem and steps to reproduce it:
Perform a search after the symbol “&”, then refresh the web page.

### What happened?
The message “Internal Server Error” is displayed.

### What did you expect to happen?
A refresh of the web page.

### Anything else we should know?
Verified on FF51.0 (Android 7.1.1) in AMO-dev server.
Here is a video:
internalsymbol

### PR DESCRIPTION
**Pull request by tofumatt**
Fix #1680.

Can't believe we weren't doing this!

### Before
screenshot 2017-02-16 19 53 45
screenshot 2017-02-16 19 53 35

### After
screen shot 2017-02-16 at 19 51 57

### CODE REVIEW

File: src/amo/components/SearchForm.js [hunk 1]
```diff
@@ -25,8 +25,9 @@ export class SearchFormBase extends React.Component {
 
   goToSearch(query) {
     const { api, pathname } = this.props;
+    const encodedQuery = query ? encodeURIComponent(query) : '';
     this.context.router.push(
```
Comment (kumar303) [inline src/amo/components/SearchForm.js]: I think it would be safer to rely on the [router API](https://github.com/ReactTraining/react-router/blob/master/docs/API.md#pushpathorloc):
````js
this.context.router.push({ pathname: ..., query: ... });
````

Comment (tofumatt) [inline src/amo/components/SearchForm.js]: Oh, true. I guess the previous way was just too naive (with the string interpolation). 👍

**Comment by tofumatt** [comment]
Okay, using `router.push` now 😄
