### PR TITLE
100% coverage

### LINKED ISSUE #144: Get coverage to 100%
We've almost got 100% coverage, once we're there we can start failing the build when the coverage goes down (I think this is a thing we want?).

I filed #145 for including coverage in build pass/fail.

### PR DESCRIPTION
**Pull request by mstriemer**
Fixes #144.

### CODE REVIEW

File: src/config/index.js [hunk 1]
```diff
@@ -1,68 +1,73 @@
...
-const APP_NAMES = ['search', 'disco'];
-if (APP_NAMES.indexOf(process.env.APP_NAME) < 0) {
-  config.set('currentApp', 'core');
-} else {
-  config.set('currentApp', process.env.APP_NAME);
-}
+
+/* istanbul ignore next */
+// Looks like you can't ignore a file but you can ignore a function, we don't want coverage here.
+(function defineConfig() {
```
Comment (muffinresearch) [inline src/config/index.js]: I think you can might be able to using excludes in a .istanbul.yml

**Comment by muffinresearch** [comment]
Be nicer not to do the function thing but otherwise r+wc

File: src/config/index.js (hunk 1 above)
Comment (mstriemer) [inline src/config/index.js]: The .istanbul.yml file doesn't appear to be loaded by karma-coverage :(

Comment (mstriemer) [inline src/config/index.js]: I tried looking at this some more and I think it's weird because we only have one file that gets "loaded" (test-runner.js). So it looks like you can ignore a file in the karma conf by making the preprocessors something like `src/!(config)/*.js` but we just has `test-runner.js` in there so I don't think there's much we can do.
