### PR TITLE
Wrapping error components in a base component to encapsulate error page styles 

### LINKED ISSUE #8873: Encapsulate common error page styles
Several error page components share styles for common layout. 

As an example, notice how [`NotAuthorized`](https://github.com/mozilla/addons-frontend/blob/4c6510613847ec4e32875b40922cf47caa6b36d4/src/amo/components/ErrorPage/NotAuthorized/index.js) adds an [`ErrorPage`](https://github.com/mozilla/addons-frontend/blob/4c6510613847ec4e32875b40922cf47caa6b36d4/src/amo/components/ErrorPage/NotAuthorized/index.js#L38) class name which is defined in [a different directory](https://github.com/mozilla/addons-frontend/blob/4c6510613847ec4e32875b40922cf47caa6b36d4/src/amo/components/ErrorPage/styles.scss). (https://github.com/mozilla/addons-frontend/pull/8858/ moved these files around and maybe renamed the class.)

This is risky because it would be easy to break these styles or use the wrong class name without knowing it.

This should be fixed by wrapping each error component in a common base component that sets the styles locally.

### PR DESCRIPTION
**Pull request by atiqueahmedziad**
Fixes #8873 

Wrapping each error components in a common base component named as `ErrorComponent` to encapsulate common error page styles.

### CODE REVIEW

**Comment by bobsilverberg** [comment]
@atiqueahmedziad We have a system of assigning reviewers to pull requests, and this request already had @willdurand assigned, so I have removed the request you just added for me.

**Comment by diox** [comment]
> @atiqueahmedziad We have a system of assigning reviewers to pull requests, and this request already had @willdurand assigned, so I have removed the request you just added for me.

And now @willdurand is out so I've re-assigned you :stuck_out_tongue:

File: tests/unit/amo/components/Errors/TestErrorPage.js [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+
+    expect(root.find('header')).toHaveLength(1);
+    expect(root.find('.Card-header')).toHaveLength(1);
+    expect(root.find('.Card-header')).toHaveText('foo');
+  });
+
+  it('hides header if none supplied', () => {
+    const root = render({ children: 'hello' });
+
+    expect(root.find('header')).toHaveLength(0);
```
Comment (bobsilverberg) [inline tests/unit/amo/components/Errors/TestErrorPage.js]: This assertion is unnecessary. The next one fulfills the same purpose.

File: src/amo/components/Errors/ErrorPage/index.js [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+    code: PropTypes.number,
+    header: PropTypes.node,
+  };
+
+  render() {
+    const { children, className, header, code } = this.props;
+
+    return (
+      <NestedStatus code={code}>
+        <section
```
Comment (bobsilverberg) [inline src/amo/components/Errors/ErrorPage/index.js]: The original files used `Card` inside `NestedStatus`, but this new component uses `section` instead. Is there a reason for this? I anticipate visual regressions as a result of this.

File: src/amo/components/Errors/ErrorPage/index.js [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+          className={makeClassName('Card Errors Card--no-footer', className, {
+            'Card--no-header': !header,
+            NotAuthorized: code === 401,
+            NotFound: code === 404,
+            ServerError: code === 500,
+          })}
+        >
+          {header ? <header className="Card-header">{header}</header> : null}
```
Comment (bobsilverberg) [inline src/amo/components/Errors/ErrorPage/index.js]: Why are you re-implementing `Card` here with this `header` and the following `div`, when you could just used `Card`?

File: src/amo/components/Errors/ErrorPage/index.js (hunk 2 above)
Comment (atiqueahmedziad) [reply src/amo/components/Errors/ErrorPage/index.js]: I thought I should keep all the css class related elements all together in the basic component. So, now I will be doing - 
```
<ErrorPage code={404}>
      <Card
          className="Errors NotFound"
          header={i18n.gettext('Oops! We can’t find that page')}
        >
        .....
      </Card>
</ErrorPage >

is this okay ?

File: src/amo/components/Errors/ErrorPage/index.js (hunk 3 above)
Comment (atiqueahmedziad) [reply src/amo/components/Errors/ErrorPage/index.js]: Tried to get rid of css classes after all, not so fruitful. Will be using `Card`

File: src/amo/components/Errors/ErrorPage/index.js (hunk 2 above)
Comment (bobsilverberg) [reply src/amo/components/Errors/ErrorPage/index.js]: Instead of this, you can move `Card` into the new component that you've created (which you've called `ErrorPage`, but I just realized it should actually be called `Error` or `ErrorComponent`). Then you can just pass the `header` into your new component, and it can pass that `header` into `Card`.

Comment (atiqueahmedziad) [reply src/amo/components/Errors/ErrorPage/index.js]: `ErrorComponent` sounds good. I was searching for a good name. Thanks!

File: src/amo/components/Errors/ErrorPage/index.js [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+    className: PropTypes.string,
+    code: PropTypes.number,
+    header: PropTypes.node,
+  };
+
+  render() {
+    const { children, className, header, code } = this.props;
+
+    return (
+      <NestedStatus code={code}>
```
[the remark this answers is not in the document]
Comment (atiqueahmedziad) [reply src/amo/components/Errors/ErrorPage/index.js]: hmm...wasn't aware of that. Yeah, I think `400` sounds good as default.

File: tests/unit/amo/components/Errors/TestErrorPage.js [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+
+import ErrorPage from 'amo/components/Errors/ErrorPage';
+
+describe(__filename, () => {
+  function render(props = {}) {
+    return shallow(<ErrorPage {...props} />);
+  }
+
+  it('renders an Error Page', () => {
+    const root = render({ className: 'ErrorSection' });
```
[the remark this answers is not in the document]
Comment (atiqueahmedziad) [reply tests/unit/amo/components/Errors/TestErrorPage.js]: Didn't get this one. We are not passing any `className` to `ErrorPage`.

File: src/amo/components/Errors/ErrorComponent/index.js [hunk 6]
```diff
@@ -0,0 +1,40 @@
...
+type InternalProps = {|
+  ...Props,
+|};
+
+export default class ErrorComponent extends React.Component<InternalProps> {
+  render() {
+    const { children, className, code, header } = this.props;
+
+    return (
+      <NestedStatus code={code}>
```
Comment (atiqueahmedziad) [inline src/amo/components/Errors/ErrorComponent/index.js]: @bobsilverberg I was trying `code = {code ? code : 400}` to set a default value if `code` is not available. But it gives me a test error saying  - `Unnecessary use of conditional expression for default assignment`
Any idea on how to make it work?

Comment (bobsilverberg) [reply src/amo/components/Errors/ErrorComponent/index.js]: It's telling you that because instead of `code = {code ? code : 400}` you can just say `code = {code || 400}`. 😉

**Comment by bobsilverberg** [comment]
@atiqueahmedziad Just checking in to see if you're still working on this. I left some comments on Feb. 24 which have yet to be addressed.

File: src/amo/components/Errors/ErrorComponent/index.js [hunk 7]
```diff
@@ -0,0 +1,40 @@
...
+      <NestedStatus code={code || 400}>
+        <Card
+          className={makeClassName('Errors', className, {
+            NotAuthorized: code === 401,
+            NotFound: code === 404,
+            ServerError: code === 500,
+          })}
+          header={header}
+        >
+          {children ? <div>{children}</div> : null}
```
[the remark this answers is not in the document]
Comment (atiqueahmedziad) [reply src/amo/components/Errors/ErrorComponent/index.js]: Maybe yes. I did this since I had to wrap `children` in an element. Is there anyway I can avoid it ?

**Comment by atiqueahmedziad** [comment]
@bobsilverberg thanks for the comments. I have updated the pr.

File: src/amo/components/Errors/ErrorComponent/index.js [hunk 8]
```diff
@@ -0,0 +1,40 @@
...
+import './styles.scss';
+
+type Props = {|
+  children: React.Node,
+  className?: string,
+  code: number,
+  header: React.Element<any> | string,
+|};
+
+type InternalProps = {|
```
Comment (bobsilverberg) [inline src/amo/components/Errors/ErrorComponent/index.js:17]: We don't really need an `InternalProps` that is just the same as `Props`. Just use `Props` in the `class` declaration below.

File: src/amo/components/Errors/ErrorComponent/index.js [hunk 9]
```diff
@@ -0,0 +1,40 @@
...
+import NestedStatus from 'react-nested-status';
+
+import Card from 'ui/components/Card';
+
+import './styles.scss';
+
+type Props = {|
+  children: React.Node,
+  className?: string,
+  code: number,
```
Comment (bobsilverberg) [inline src/amo/components/Errors/ErrorComponent/index.js:13]: You have defined a default value for `code` below, via `code={code || 400}`, but `code` is mandatory here, which means it must be passed in. If we really want to allow a client to not pass a `code` then this should be defined as optional.

File: src/amo/components/Errors/ErrorComponent/index.js [hunk 10]
```diff
@@ -0,0 +1,40 @@
...
+type InternalProps = {|
+  ...Props,
+|};
+
+export default class ErrorComponent extends React.Component<InternalProps> {
+  render() {
+    const { children, className, code, header } = this.props;
+
+    return (
+      <NestedStatus code={code || 400}>
```
Comment (bobsilverberg) [inline src/amo/components/Errors/ErrorComponent/index.js:26]: This will cause `code` to be `400` if `code` was passed as `0`, but I wonder if we need to enforce a set of valid values for `code`? E.g., someone could pass in `12345` as `code`, but I don't think that would be valid for `NestedStatus`, so I think we should have a check to ensure that `code` is an acceptable value, which at this point looks like `400, 401, 404, 500`.

File: src/amo/components/Errors/ErrorComponent/index.js [hunk 11]
```diff
@@ -0,0 +1,40 @@
...
+        <Card
+          className={makeClassName('Errors', className, {
+            NotAuthorized: code == 401,
+            NotFound: code == 404,
+            ServerError: code == 500,
+          })}
+          header={header}
+        >
+          {children ? <>{children}</> : null}
```
Comment (bobsilverberg) [inline src/amo/components/Errors/ErrorComponent/index.js:35]: `children` is defined as mandatory, so do you need the ternary here anymore?

File: tests/unit/amo/components/Errors/TestErrorComponent.js [hunk 12]
```diff
@@ -0,0 +1,61 @@
...
+
+  it('renders an ErrorComponent', () => {
+    const root = render();
+
+    expect(root.find(NestedStatus)).toHaveProp('code', 400);
+    expect(root.find(Card)).toHaveClassName('Errors');
+  });
+
+  it('renders header when header is available', () => {
+    const root = render({ header: 'foo' });
```
Comment (bobsilverberg) [inline tests/unit/amo/components/Errors/TestErrorComponent.js:21]: A better approach, which removes the possibility of a typo in a test, is to use a variable to set a value and then use the same variable in the assert. In this example, you could do:

```
const header = 'foo';
const root = render({ header });

expect(root.find(Card)).toHaveProp('header', header);
```

File: tests/unit/amo/components/Errors/TestErrorComponent.js [hunk 13]
```diff
@@ -0,0 +1,61 @@
...
+
+    expect(root.find(Card)).toHaveProp('header', 'foo');
+  });
+
+  it('renders code when code is supplied', () => {
+    const root = render({ code: 500 });
```
Comment (bobsilverberg) [inline tests/unit/amo/components/Errors/TestErrorComponent.js:27]: As discussed above, using a `const` for `code` and using it in both the `render` and the `expect` is better practice.

File: tests/unit/amo/components/Errors/TestErrorComponent.js [hunk 14]
```diff
@@ -0,0 +1,61 @@
...
+
+    expect(root.find(NestedStatus)).toHaveProp('code', 500);
+  });
+
+  it('renders children', () => {
+    const root = render({ children: 'hello' });
```
Comment (bobsilverberg) [inline tests/unit/amo/components/Errors/TestErrorComponent.js:33]: As discussed above, using a `const` for `children` and using it in both the `render` and the `expect` is better practice.

File: tests/unit/amo/components/Errors/TestNotAuthorized.js [hunk 15]
```diff
@@ -31,6 +31,7 @@ describe(__filename, () => {
   it('renders a not authorized error', () => {
     const root = render();
 
-    expect(root.find(Card)).toHaveProp('header', 'Not Authorized');
+    expect(root.find(ErrorComponent)).toHaveProp('code', 401);
+    expect(root).toHaveProp('header', 'Not Authorized');
```
Comment (bobsilverberg) [inline tests/unit/amo/components/Errors/TestNotAuthorized.js:35]: This should be `expect(root.find(ErrorComponent)).toHaveProp('header', 'Not Authorized');`

File: tests/unit/amo/components/Errors/TestNotFound.js [hunk 16]
```diff
@@ -32,10 +33,8 @@ describe(__filename, () => {
   it('renders a not found error', () => {
     const root = render();
 
-    expect(root.find('.Errors')).toHaveProp(
-      'header',
-      'Oops! We can’t find that page',
-    );
+    expect(root.find(ErrorComponent)).toHaveProp('code', 404);
+    expect(root).toHaveProp('header', 'Oops! We can’t find that page');
```
Comment (bobsilverberg) [inline tests/unit/amo/components/Errors/TestNotFound.js:37]: This should be `expect(root.find(ErrorComponent)).toHaveProp('header', 'Oops! We can’t find that page');`

File: tests/unit/amo/components/Errors/TestServerError.js [hunk 17]
```diff
@@ -30,6 +31,9 @@ describe(__filename, () => {
   it('renders a server error', () => {
     const root = render();
 
+    expect(root.find(ErrorComponent)).toHaveProp('code', 500);
+    expect(root).toHaveProp('header', 'Server Error');
```
Comment (bobsilverberg) [inline tests/unit/amo/components/Errors/TestServerError.js:35]: This should be `expect(root.find(ErrorComponent)).toHaveProp('header', 'Server Error');`

**Comment by bobsilverberg** [comment]
@atiqueahmedziad I wasn't sure if this was ready for another look from me, as you didn't re-request a review from me, but it looks like you've made some changes. I see there's an `eslint` error though. If you're still working on this could you see if you can fix that error, and then, if it's ready, re-request a review?

File: tests/unit/amo/components/Errors/TestErrorComponent.js [hunk 18]
```diff
@@ -13,7 +13,6 @@ describe(__filename, () => {
   it('renders an ErrorComponent', () => {
     const root = render();
 
-    expect(root.find(NestedStatus)).toHaveProp('code', 400);
```
Comment (atiqueahmedziad) [inline tests/unit/amo/components/Errors/TestErrorComponent.js]: @bobsilverberg I have enforce the set of valid values for code. Do we require this test case ?

File: src/amo/components/Errors/ErrorComponent/index.js [hunk 19]
```diff
@@ -0,0 +1,36 @@
...
+import NestedStatus from 'react-nested-status';
+
+import Card from 'ui/components/Card';
+
+import './styles.scss';
+
+type Props = {|
+  children: React.Node,
+  className?: string,
+  code: 400 | 401 | 404 | 500,
```
Comment (bobsilverberg) [inline src/amo/components/Errors/ErrorComponent/index.js:13]: This tells Flow that these are the valid values but, unfortunately, as we do not have complete Flow coverage in this app, we also need to check these values via code.

We often use `invariant` to do this, which you can see examples of in lots of other files. In this case we should define an `invariant` in the `render` function which will throw if `code` is not one of the valid values.

File: tests/unit/amo/components/Errors/TestErrorComponent.js (hunk 18 above)
Comment (bobsilverberg) [reply tests/unit/amo/components/Errors/TestErrorComponent.js]: No, we don't need a test for a default value anymore as there is no default.

File: src/amo/components/Errors/ErrorComponent/index.js (hunk 19 above)
Comment (atiqueahmedziad) [reply src/amo/components/Errors/ErrorComponent/index.js:14]: Done :-)

File: src/amo/components/Errors/ErrorComponent/index.js [hunk 20]
```diff
@@ -20,8 +20,6 @@ export default class ErrorComponent extends React.Component<Props> {
     const { children, className, code, header } = this.props;
     const validCodes = [400, 401, 404, 500];
 
-    invariant(children, 'children is required');
-    invariant(header, 'header is required');
```
Comment (atiqueahmedziad) [inline src/amo/components/Errors/ErrorComponent/index.js]: @bobsilverberg do we require these checks ?

Comment (bobsilverberg) [reply src/amo/components/Errors/ErrorComponent/index.js]: I suppose we should have those too.

**Comment by atiqueahmedziad** [comment]
Thanks a lot @bobsilverberg for guiding me on this. I have learned so much throughout the process 😄
