### PR TITLE
Fix width of site notices and error messages on home page

### LINKED ISSUE #8750: Homepage information banners are too wide
### Describe the problem and steps to reproduce it:
1. Load AMO homepage on stage
2. Notice the layout of the site notice

### What happened?
The banner is too wide

### What did you expect to happen?
The banner should be the same width as the rest of the content

### Anything else we should know?
- this is not reproducing on -dev, where to homepage hero is enabled; there must be some setting that controls the width which is present only when the hero is available
- this could be a regression from https://github.com/mozilla/addons-frontend/pull/8662
- the information banners have the correct with in the rest of the pages, so only the homepage is affected

[layout issues with the site-notice enabled and an server error banner]
image

### LINKED ISSUE #8756: Error messages too wide on home page with new hero
While working on #8750, I discovered that the error banner is too wide when the new heros are active:

Screenshot 2019-10-10 12 13 30

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #8750 
Fixes #8756

Before (#8750):

Screenshot 2019-10-10 09 37 15

After (#8750):

Screenshot 2019-10-10 09 38 17

Before (#8756):

Screenshot 2019-10-10 12 13 30

After (#8756): 

Screenshot 2019-10-10 15 04 27

### CODE REVIEW

**Comment by bobsilverberg** [comment]
> I'm looking at #8756 and it seems like you'll need to fix this issue there so (for the promo case) so maybe that fix will cover both cases? It sounds like fixing it for the non-promo case is not super urgent so I'd rather see a fix for both cases at once, if it's possible. What do you think?

@kumar303 I was actually trying to keep each patch small and discrete, but I can certainly combine them if that's what you'd prefer. Please let me know.

**Comment by kumar303** [comment]
Yeah, I suggest trying to combine them if possible. If that becomes difficult, then we could revisit this patch. As it is currently, this patch seems like it adds an unnecessary exception for the non-hero view (because both views need to be fixed).

**Comment by bobsilverberg** [comment]
> Yeah, I suggest trying to combine them if possible. If that becomes difficult, then we could revisit this patch. As it is currently, this patch seems like it adds an unnecessary exception for the non-hero view (because both views need to be fixed).

Ok, I'll do that now.

File: stories/amo/HeroRecommendation.js [hunk 1]
```diff
@@ -46,6 +48,19 @@ storiesOf('HeroRecommendation', module)
...
           },
+          {
+            title: 'with error',
+            sectionFn: () =>
+              render(
+                {},
+                {
+                  errorHandler: new ErrorHandler({
+                    id: 'some-id',
+                    capturedError: new Error('Some error'),
```
Comment (bobsilverberg) [inline stories/amo/HeroRecommendation.js]: This doesn't work for some reason, and ends up generating an error from the `ErrorList` component when it tries to render it. I'm not sure why because, AFAICT it's doing the exact same thing as `createStubErrorHandler`, which I had trouble using here because `sinon` doesn't exist.

**Comment by bobsilverberg** [comment]
@kumar303 I have included fixes for both #8750 and #8756. I ran into a problem adding a story for the `HeroRecommendation` about which I have added an inline comment on the diff. There is one more change that needs to be done for the Android home page when the new hero is enabled, but I can do that in a separate patch.

**Comment by bobsilverberg** [comment]
@kumar303 I could add the fix for #8757 into this patch as well, or do it as a separate patch.

File: src/amo/pages/Home/index.js [hunk 2]
```diff
@@ -254,11 +254,14 @@ export class HomeBase extends React.Component {
             }}
           />
 
-          {errorHandler.renderErrorIfPresent()}
+          {(!_config.get('enableFeatureHeroRecommendation') ||
+            clientApp === CLIENT_APP_ANDROID) &&
+            errorHandler.renderErrorIfPresent()}
```
Comment (kumar303) [inline src/amo/pages/Home/index.js]: I suggest wrapping this so you can add the `padding: 0 24px` style to it directly:

```jsx
{errorHandler.hasError() 
  ? <div className="Home-noHeroError">{errorHandler.renderError()}</div>
  : null}
```

File: src/amo/components/Page/index.js [hunk 3]
```diff
@@ -39,13 +43,12 @@ export const PageBase = ({
         <div
           className={makeClassName('Page', {
             'Page-not-homepage': !isHomePage,
+            'Page-no-hero-promo': !enableFeatureHeroRecommendation,
```
Comment (kumar303) [inline src/amo/components/Page/index.js]: I don't think this is a great way to control the style changes because the state of the config flag doesn't necessarily mean you need to add the styles. I offered a more direct way to control the style changes.

File: stories/amo/HeroRecommendation.js (hunk 1 above)
Comment (kumar303) [inline stories/amo/HeroRecommendation.js]: > This doesn't work for some reason, and ends up generating an error from the `ErrorList` component when it tries to render it. I'm not sure why because, AFAICT it's doing the exact same thing as `createStubErrorHandler`, which I had trouble using here because `sinon` doesn't exist.

Stories use a real store so I suggest dispatching a real error. Example of usage with a real store:

https://github.com/mozilla/addons-frontend/blob/b16c8f80d5a57c8ce8d84c7a269e17834bedfb53/src/core/api/index.js#L214

File: src/amo/components/Page/index.js (hunk 3 above)
Comment (bobsilverberg) [reply src/amo/components/Page/index.js]: Your suggestion addresses the hacky style I added for the error message padding, but it doesn't address the need for the `max-width` at https://github.com/mozilla/addons-frontend/pull/8753/files#diff-5bb54930f8afd38fcb0856c0b4dedc86R25, so I've kept this in place for now. I can do a follow-up later this week if needed.

File: stories/amo/HeroRecommendation.js (hunk 1 above)
Comment (bobsilverberg) [reply stories/amo/HeroRecommendation.js]: I did some work which has removed the error that was being generated by Storybook, but this still isn't working as more work needs to be done to enable a story to create a `store` and then be able to pass that `store` into the `Provider`. @kumar303 and I discussed this a bit on IRC. In order to land this in a timely fashion, I'm going to file a follow-up to get the story working for a version of the `HeroRecommendation` that displays an error.

Comment (bobsilverberg) [reply stories/amo/HeroRecommendation.js]: I filed #8777
