### PR TITLE
fix: Categories temporary 404 while loading

### LINKED ISSUE #2846: Tapping on any category loads a 404 page for a few seconds
Steps to reproduce:
1. Load AMO homepage on you device https://addons-dev.allizom.org/en-US/android/
2. Tap on a category i.e. "Blocks ads"

Expected results:
Category is loaded without any display or layout issues.

Actual results:
A 404 page is loaded for a few seconds.

Notes/Issues:
- happening first time the page is loaded - reproduce is you must load the page again in a new tab;
- reproducing on new desktop pages also;
- may be a regression from #2084 

Verified on FF54(Win 7). Issue is reproducing around all AMO servers.
Video for this issue:
videotogif_2017 07 24_11 04 39

### PR DESCRIPTION
**Pull request by tofumatt**
Fix #2846.

We weren't checking to see if we had *any* category data yet (or even did a proper loading check) so we'd hit a temporary 404 screen during the load. Because we fetch all categories at once this just marks whether or not we've fetched them and only renders a 404 for a non-existent category once we've compared it to the fetched categories.

### Before
videotogif_2017 07 24_11 04 39

### CODE REVIEW

File: src/amo/components/Category/index.js [hunk 1]
```diff
@@ -67,11 +68,17 @@ export function mapStateToProps(state, ownProps) {
     { ...state.search.filters, page: parsePage(state.search.page) },
     { ...filters, page: queryParams.page },
   );
+
+  const hasFetched = state.categories.hasFetched;
```
Comment (muffinresearch) [inline src/amo/components/Category/index.js]: Could this be derived from the category data rather than needing to be passed as a prop?

**Comment by tofumatt** [comment]
It could but I figured doing it once in the reducer made a bit more sense-categories are fetched essentially all at once so knowing whether we've made the request seemed worth storing once.

- Matthew Riley MacPherson (sent from mobile)

File: src/amo/components/Category/index.js [hunk 2]
```diff
@@ -67,11 +68,17 @@ export function mapStateToProps(state, ownProps) {
...
+  const loading = state.categories.loading || state.search.loading;
```
Comment (kumar303) [inline src/amo/components/Category/index.js]: This looks like the right thing to do. Once you make this `loading` prop effective I believe that you won't need `hasFetched`.

File: src/amo/components/Category/index.js [hunk 3]
```diff
@@ -67,11 +68,17 @@ export function mapStateToProps(state, ownProps) {
...
+
   if (filtersMatchState) {
     return {
       addonType: filters.addonType,
       category,
       filters,
+      hasFetched,
+      loading,
```
Comment (kumar303) [inline src/amo/components/Category/index.js]: This prop is not affecting anything because `...state.search` (below) looks to be overriding it.

File: src/amo/components/Category/index.js [hunk 4]
```diff
@@ -67,11 +68,17 @@ export function mapStateToProps(state, ownProps) {
...
       pathname,
       queryParams,
       ...state.search,
```
Comment (kumar303) [inline src/amo/components/Category/index.js]: I know this is old code but could you remove the spread and instead reference each one of the `state` attributes?

File: src/amo/components/Category/index.js (hunk 1 above)
Comment (kumar303) [inline src/amo/components/Category/index.js]: I don't think you need to introduce this new state attribute since you already have it as `state.categories.loading`. My hunch is that you added it because the new `loading` prop was not taking effect (I explained that below).

**Comment by tofumatt** [comment]
Yeah that makes sense upon looking at this again. I'll do the check in the component, should be ready after lunch.

Matthew Riley MacPherson (sent from mobile)

File: src/amo/components/Category/index.js (hunk 1 above)
Comment (tofumatt) [inline src/amo/components/Category/index.js]: It needs to be a prop as it's based on data in *all* categories but the prop that the component gets is just one category.

**Comment by tofumatt** [comment]
Changed the check to be inside the component's `mapStateToProps` (we don't have all the required data in the component itself and passing in every category just for the check seemed silly). Ready for another r?

**Comment by tofumatt** [comment]
> I don't understand why you need to loop through all loaded categories in the state mapper when there is only one API fetch that populates the categories (not multiple).

I'm just looping through until I find a populated one because it could be there are legitimately no dictionary categories for android, but I can't know if we fetched anything until I see at least one populated category. Previously I set `hasFetched` in state to mark "we made the request and got all the categories" but that was r-'d

That said, it seems object spread strikes again. I didn't clue in to the fact that the spread overwrites the loading prop I see, I think. Rawr. I feel dumb.

I'll try your patch and tweak the test. really sorry I didn't notice that 😞

**Comment by tofumatt** [comment]
Gosh, you're right, I got really tripped up by the spread.

Ready for another r? Basically it's your patch with better loading checks and a few extra tests.

Sorry 'bout that.

File: tests/unit/amo/components/TestCategory.js [hunk 5]
```diff
@@ -139,11 +143,44 @@ describe('Category.mapStateToProps()', () => {
...
       addonType: ADDON_TYPE_THEME,
       category: null,
+      loading: true,
       pathname: '/themes/ad-block/',
       queryParams: { page: 1 },
     });
   });
+
+  it('sets loading to true if categories and search are loading', () => {
+    const { store } = createStore();
```
Comment (kumar303) [inline tests/unit/amo/components/TestCategory.js]: You could move this to `beforeEach` and share it for every test

Comment (tofumatt) [inline tests/unit/amo/components/TestCategory.js]: Good call, will do.
