### PR TITLE
Do not attempt to create a link to a review that has an empty reviewAddon.slug

### LINKED ISSUE #7322: Error page when looking at my profile page while logged in
When I'm logged in and try to access [my profile page](https://addons.mozilla.org/en-US/firefox/user/4230/), I get a server error page. The page loads fine if I'm not logged in.

The page appears to be loading fine and then switches to an error page. I see this in the console, which may be related:

> Caught application error: Invariant Violation: "addonSlug is required"
> 
>     exports Redux
> 
> p reviews.js:551 value Cookies.js:37 ci21React
> 	y Redux	i selectors.js:199 u errors.js:47 dispatch index.js:96 Zn2Redux
> Ur addonsByAuthors.js:17 Br addonsByAuthors.js:25 Fr addonsByAuthors.js:17 O4Redux
> a es6.reflect.construct.js:25 R es6.reflect.construct.js:32 c es6.reflect.set-prototype-of.js:5 exports es6.regexp.constructor.js:16 <anonymous> es7.promise.finally.js:11 a5Webpack
>  
> Object { componentStack: "\n    in n\n    in Translate(n)\n    in Connect(Translate(n))\n    in Connect(Connect(Translate(n)))\n    in li\n    in ul\n    in div\n    in section\n    in t\n    in t\n    in div\n    in div\n    in div\n    in t\n    in Connect(t)\n    in Translate(Connect(t))\n    in Connect(Translate(Connect(t)))\n    in t\n    in t\n    in N\n    in t\n    in Connect(t)\n    in div\n    in div\n    in div\n    in t\n    in t\n    in withRouter(t)\n    in NestedStatus\n    in SideEffect(NestedStatus)\n    in t\n    in withCookies(t)\n    in Translate(Component)\n    in Connect(Translate(Component))\n    in t\n    in withRouter(Connect(Translate(Component)))\n    in StrictMode\n    in t\n    in t\n    in r\n    in Connect(r)\n    in a\n    in t\n    in x" }
> BigInteger.js:110

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #7322

### CODE REVIEW

File: tests/unit/amo/components/TestAddonReviewCard.js [hunk 1]
```diff
@@ -1052,6 +1052,18 @@ describe(__filename, () => {
       );
     });
 
+    it('renders a byLine without a link when the review addon has an empty slug', () => {
+      const review = signInAndDispatchSavedReview({
+        externalReview: {
+          ...fakeReview,
+          addon: { ...fakeReview.addon, slug: '' },
```
Comment (kumar303) [inline tests/unit/amo/components/TestAddonReviewCard.js]: Was it an empty string or null in the case of the reported bug?

Comment (kumar303) [inline tests/unit/amo/components/TestAddonReviewCard.js]: It would be nice to put a comment here with a link to the bug. Otherwise, it seems weird that this test case exists, given the Flow type for `reviewAddon`.

File: src/amo/components/AddonReviewCard/index.js [hunk 2]
```diff
@@ -367,15 +367,21 @@ export class AddonReviewCardBase extends React.Component<InternalProps> {
...
-            })}
-          >
-            {linkParts.innerLinkText}
-          </Link>
+
+          {review.reviewAddon.slug ? (
+            <Link
+              key={review.id}
+              to={reviewListURL({
+                addonSlug: review.reviewAddon.slug,
```
Comment (kumar303) [inline src/amo/components/AddonReviewCard/index.js]: What about falling back to `review.reviewAddon.id`? That will still produce a valid link.

**Comment by bobsilverberg** [comment]
Thanks @kumar303. I've updated the patch with what we discussed in IRC. Could you please take another look?
