### PR TITLE
Use an isLoading flag to prevent fetchHomeData from being dispa…

### LINKED ISSUE #8572: Home hero data is fetched twice
### Describe the problem and steps to reproduce it:

* Clear cache
* Go to any non-home page such as https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus/?src=featured
* Open the Network panel and clear all network requests
* Click on the Firefox icon to navigate home
* Watch the Network panel

### What happened?

The hero data is fetched twice:

Screenshot 2019-09-10 15 11 48

### What did you expect to happen?

The data should only be fetched once since it may impact API performance and page load time (especially as this is the home page).

### Anything else we should know?

It looks like `pages/Home` is dispatching `FETCH_HOME_DATA` twice:

<details>
<summary>Console log</summary>

Screenshot 2019-09-10 15 12 09

</details>

We typically prevent this by storing an `isLoading` flag on the first saga dispatch. This can then be used to prevent dispatching the loader. Example:

https://github.com/mozilla/addons-frontend/blob/28cd4cbebe6b0672f7af9b5ab0a1636ed81ee543/src/amo/reducers/reviews.js#L587-L598

and:

https://github.com/mozilla/addons-frontend/blob/fa9c74e2501bd4a2e4bf6841c4b52b66a757dc9c/src/amo/pages/AddonReviewList/index.js#L136-L146

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #8572

### CODE REVIEW

**Comment by kumar303** [comment]
Disabling strict mode made this behave as you expected, right? The logic looks correct to me. Your observations correlate with what I'd think would happen in strict mode.

**Comment by bobsilverberg** [comment]
> Disabling strict mode made this behave as you expected, right? 

Yes, that resolved my issue, thanks! This is now ready for a full review.

File: src/amo/sagas/home.js [hunk 1]
```diff
@@ -136,6 +142,7 @@ export function* fetchHomeData({
       });
     } catch (error) {
       log.warn(`Home add-ons failed to load: ${error}`);
+      yield put(abortFetchHomeData());
```
Comment (kumar303) [inline src/amo/sagas/home.js]: You don't need this because the error will get caught in an outer block which already aborts the fetch. It would be good to keep the extra test for it, though.

File: src/amo/sagas/home.js [hunk 2]
```diff
@@ -46,6 +50,7 @@ export function* fetchHomeData({
       heroShelves = yield call(getHeroShelves, { api: state.api });
     } catch (error) {
       log.warn(`Home hero shelves failed to load: ${error}`);
+      yield put(abortFetchHomeData());
```
Comment (kumar303) [inline src/amo/sagas/home.js]: Actually, you don't need this one either for the same reason.

File: src/amo/sagas/home.js [hunk 3]
```diff
@@ -68,6 +73,7 @@ export function* fetchHomeData({
           // The collection was not found or is marked private.
           collections.push(null);
         } else {
+          yield put(abortFetchHomeData());
```
Comment (kumar303) [inline src/amo/sagas/home.js]: nor this one

File: tests/unit/amo/sagas/test_home.js [hunk 4]
```diff
@@ -421,6 +444,41 @@ describe(__filename, () => {
...
+      const userId = 123;
+
+      mockHeroApi
+        .expects('getHeroShelves')
+        .returns(Promise.resolve(createHeroShelves()));
+
+      const firstCollection = createFakeCollectionAddonsListResponse();
+      mockCollectionsApi
+        .expects('getCollectionAddons')
+        .withArgs({
```
Comment (kumar303) [inline tests/unit/amo/sagas/test_home.js]: The arguments are already covered by other tests so you can remove this line. Also, `mockCollectionsApi.verify()` is never called (which is fine) so this doesn't have an affect.

File: tests/unit/amo/sagas/test_home.js [hunk 5]
```diff
@@ -421,6 +444,41 @@ describe(__filename, () => {
...
+          slug,
+          userId,
+        })
+        .returns(Promise.resolve(firstCollection));
+
+      const error = new Error('some API error maybe');
+
+      mockSearchApi
+        .expects('search')
+        .exactly(5)
```
Comment (kumar303) [inline tests/unit/amo/sagas/test_home.js]: You can remove this since it won't have an affect (`mockSearchApi.verify()` is not called). It's not important for this test, anyway, which is about handling errors.

File: tests/unit/amo/sagas/test_home.js [hunk 6]
```diff
@@ -421,6 +444,41 @@ describe(__filename, () => {
...
+
+      const firstCollection = createFakeCollectionAddonsListResponse();
+      mockCollectionsApi
+        .expects('getCollectionAddons')
+        .withArgs({
+          api: state.api,
+          slug,
+          userId,
+        })
+        .returns(Promise.resolve(firstCollection));
```
Comment (kumar303) [inline tests/unit/amo/sagas/test_home.js]: I think you can do `.resolves()`

File: tests/unit/amo/sagas/test_home.js [hunk 7]
```diff
@@ -421,6 +444,41 @@ describe(__filename, () => {
...
+
+      const error = new Error('some API error maybe');
+
+      mockSearchApi
+        .expects('search')
+        .exactly(5)
+        .returns(Promise.reject(error));
```
Comment (kumar303) [inline tests/unit/amo/sagas/test_home.js]: I think you can do `.rejects()`

File: tests/unit/amo/sagas/test_home.js [hunk 8]
```diff
@@ -432,5 +490,18 @@ describe(__filename, () => {
       const expectedAction = await sagaTester.waitFor(errorAction.type);
       expect(expectedAction).toEqual(errorAction);
     });
+
+    it('aborts fetching for a failed hero fetch', async () => {
+      const error = createApiError({ response: { status: 500 } });
+
+      mockHeroApi.expects('getHeroShelves').returns(Promise.reject(error));
```
Comment (kumar303) [inline tests/unit/amo/sagas/test_home.js]: This could use `.rejects()`.

**Comment by bobsilverberg** [comment]
Thanks @kumar303. I have addressed all of your comments. I noticed that some of the existing tests could also be cleaned up a bit. Both by replacing instances of  `returns(Promise.reject())` with `rejects()`, and same with `resolves`; and also by removing some of the expectations on the mockApis where we are not later verifying the API call.

I didn't make those changes because I did want to make the patch unnecessarily large, but I'm thinking that maybe I should make those changes before landing this, after you've had a chance to do another review. WDYT?

**Comment by kumar303** [comment]
> I didn't make those changes because I did want to make the patch unnecessarily large

I agree. There is so much cleanup needed in addons-frontend but it's impractical to squeeze into every PR.

File: src/amo/reducers/home.js [hunk 9]
```diff
@@ -251,9 +265,16 @@ const reducer = (
...
+    case ABORT_FETCH_HOME_DATA:
+      return {
+        ...state,
+        isLoading: false,
+      };
+
     case FETCH_HOME_DATA:
       return {
         ...state,
+        isLoading: true,
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/reducers/home.js]: @kumar303 There is this test: https://github.com/mozilla/addons-frontend/blob/d9d68a0b19f376340b60be940039debc3542506f/tests/unit/amo/reducers/test_home.js#L214-L227

Rather than adding a separate test just to check the value of `isLoading`, I updated an existing test to verify that both `isLoading` and `resultsLoaded` are correct after a fetch. This seems okay to me because it represents the expected state for a a single action.

Do you feel it's important to have separate tests for both the `resultsLoaded` and the `isLoading` flags, or did you perhaps miss noticing this change in your review?

[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/reducers/home.js]: @kumar303 I'm just waiting on an answer to this question before merging this patch. Thanks!

[the remark this answers is not in the document]
Comment (kumar303) [reply src/amo/reducers/home.js]: Ship it!
