### PR TITLE
Fix UI glitch on SiteNotices by adding a new sanitize function

### LINKED ISSUE #8616: Markup in site notice causes issues in server render
If you go to https://addons-dev.allizom.org you'll notice the site banner flashes up larger and then reduces in height when the JS kicks in.

Server rendered markup screenshot (with JS disabled):

Add-ons_for_Firefox__en-US_

SiteNotice passes a div to Notice:

https://github.com/mozilla/addons-frontend/blob/0fadd956d4e9eb98d716aefeb6904e4becf2f346/src/core/components/SiteNotices/index.js#L36-L39

Whereas Notice wraps children with a `p`

https://github.com/mozilla/addons-frontend/blob/0fadd956d4e9eb98d716aefeb6904e4becf2f346/src/ui/components/Notice/index.js#L135

This results in a `div` inside a `p` which is not valid. Somehow the server side render results in even weirder markup as seen in the screenshot above.

To fix this the site notice could pass a `span` instead.

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #8616

---

We need to use a new sanitize function so that we can use a `<span />`.

We have an [ESLint rule](https://github.com/mozilla/eslint-plugin-amo#dangerously-set-inner-html) to prevent the use of `sanitizeUserHTML()` with a tag that is not `<div />`.

`<span />` should only have [phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content) as children, which is why we need a new sanitize function. `<a />` is allowed "if it contains only phrasing content", which should be fine here.

### CODE REVIEW

File: src/core/components/SiteNotices/index.js [hunk 1]
```diff
@@ -24,6 +24,15 @@ type InternalProps = {|
   i18n: I18nType,
 |};
 
+// This is needed because of https://github.com/mozilla/addons-frontend/issues/8616
+//
+// We cannot use `sanitizeUserHTML()` on a `<span />`, which is required to
+// avoid the UI glitch so we configure our own sanitize function to make sure
+// it is safe to use `<span />`.
+const sanitizeNoticeHTML = (text: string): string => {
+  return sanitizeHTML(nl2br(text), ['a', 'b', 'br', 'em', 'i', 'strong']);
```
Comment (muffinresearch) [inline src/core/components/SiteNotices/index.js]: I wonder if we really have a use-case for presentational markup such as `i` and `b` in place of `em` and `strong`, buy that's something that can be discussed independently of this patch.

Comment (willdurand) [reply src/core/components/SiteNotices/index.js]: I think it is convenient for admins, especially since there is no WYSIWYG.
