### PR TITLE
Set a default name for license when name is `null`

### LINKED ISSUE #7912: Missing value when `license.name` is `null` in "More info" card
### Describe the problem and steps to reproduce it:

1. Browse https://addons.allizom.org/en-US/firefox/addon/peasshee-hedder-swallamelo/
2. Observe the "More information" card

**Edit:** you can use this add-on in -dev: https://addons-dev.allizom.org/en-US/firefox/addon/gormine-dolphille-crant/

### What happened?

There is no value for "license":

Screen Shot 2019-04-18 at 20 11 03

### What did you expect to happen?

The value should be "Custom License"

### Anything else we should know?

This is not a new bug but it was never an issue until https://github.com/mozilla/addons-frontend/issues/7909, which entirely broke a page. `license.name` can be `null`, which is why we do not have a value in the "More info" card. We should use a fallback value in that case.

addons-server (dev hub) uses "Custom License" as fallback. We should do that too.

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #7912

---

Before:

Screen Shot 2019-04-25 at 12 09 38

After:

Screen Shot 2019-04-25 at 12 09 25

### CODE REVIEW

File: tests/unit/amo/components/TestAddonMoreInfo.js [hunk 1]
```diff
@@ -221,6 +221,26 @@ describe(__filename, () => {
...
+    expect(license.children()).toIncludeText('Custom License');
+  });
+
+  it('renders a default name when the license name and url are null', () => {
+    _loadVersions({ license: { name: null, url: null } });
+
+    const root = render({});
+
+    const license = root.find('.AddonMoreInfo-license-name');
+    expect(license).toHaveLength(1);
```
Comment (kumar303) [inline tests/unit/amo/components/TestAddonMoreInfo.js]: Maybe also assert that `.AddonMoreInfo-license-link` is not present to make sure it's not an orphaned a tag?
