### PR TITLE
fix: Add Privacy Policy to disco pane (fix #2789)

### LINKED ISSUE #2789: Add a link to Mozilla's Privacy Policy to the footer of the Discovery Pane
Looks like we're missing a link to the privacy policy from the Discovery Pane views, which show up in the Add-on Manager. Since that view has Google Analytics in it and isn't clearly linked to AMO, we should probably put a pointer to AMO's Privacy Policy in the footer.

### PR DESCRIPTION
**Pull request by tofumatt**
Fixes #2789

Adds a privacy policy to the Disco Pane.

screenshot 2017-07-12 21 15 52

### CODE REVIEW

File: src/disco/components/Footer/index.js [hunk 1]
```diff
@@ -0,0 +1,33 @@
+/* eslint-disable react/no-danger */
```
Comment (kumar303) [inline src/disco/components/Footer/index.js]: I don't see any danger

california

File: src/disco/components/Footer/styles.scss [hunk 2]
```diff
@@ -0,0 +1,8 @@
+.Footer {
+  text-align: center;
+}
+
+.Footer-privacy-link {
+  color: #444;
```
Comment (kumar303) [inline src/disco/components/Footer/styles.scss]: This should go in a variable

File: tests/unit/disco/components/TestFooter.js [hunk 3]
```diff
@@ -0,0 +1,26 @@
+import { shallow } from 'enzyme';
+import React from 'react';
+
+import { FooterBase } from 'disco/components/Footer';
+import { getFakeI18nInst } from 'tests/unit/helpers';
+
+
+function shallowRender(props) {
```
Comment (kumar303) [inline tests/unit/disco/components/TestFooter.js]: I'm surprised this doesn't need `props = {}` since it's optional. I guess the JSX spread handles nulls.

File: src/disco/components/Footer/index.js (hunk 1 above)
Comment (tofumatt) [inline src/disco/components/Footer/index.js]: Shoot this file was copy-pasta'd. My bad! I need a template for new files.

File: src/disco/components/Footer/styles.scss (hunk 2 above)
Comment (tofumatt) [inline src/disco/components/Footer/styles.scss]: Agreed. Will do!

File: tests/unit/disco/components/TestFooter.js (hunk 3 above)
Comment (tofumatt) [inline tests/unit/disco/components/TestFooter.js]: Yeah it handles it and I feel it's nicer to write it like this... I've been doing it in components lately. The boilerplates of empty objects is annoying.

Comment (kumar303) [inline tests/unit/disco/components/TestFooter.js]: boilerplate? It's just a simple change:

```js
function shallowRender(props = {}) {
}
```
but if it works as is then no worries.

Comment (tofumatt) [inline tests/unit/disco/components/TestFooter.js]: Haha actually that's true, just for some reason a lot of tests were using:

```js
function shallowRender({ ... props } = {}) {
}
```
