### PR TITLE
fix: Don't play the disco pane video in tests (fix #765)

### LINKED ISSUE #765: Prevent Disco pane video test from creating a memory leak, crashing
If you run the tests with `npm run unittest:dev` which runs the unit tests with a watcher, eventually node runs out of memory. 

~~When running the tests in debug mode I noticed the video is actually being played in the disco pane tests. We should fix that.~~ (This is fixed but the memory leak is still happening.)

### PR DESCRIPTION
**Pull request by tofumatt**
This fixes #765, so our tests shouldn't have memory leaks and also shouldn't spook me when I'm testing with loud volume settings late at night.

### CODE REVIEW

File: src/disco/containers/DiscoPane.js [hunk 1]
```diff
@@ -34,13 +34,17 @@ export class DiscoPaneBase extends React.Component {
     results: PropTypes.arrayOf(PropTypes.object).isRequired,
     _addChangeListeners: PropTypes.func,
     _tracking: PropTypes.object,
+    // We allow the video to be overloaded for testing, see:
+    // https://github.com/mozilla/addons-frontend/issues/765
```
Comment (kumar303) [inline src/disco/containers/DiscoPane.js]: I don't think it's necessary to add a comment. This is a common pattern that we use elsewhere. The properties above it have defaults already too.

File: src/disco/containers/DiscoPane.js [hunk 2]
```diff
@@ -55,7 +59,11 @@ export class DiscoPaneBase extends React.Component {
   }
 
   showVideo = (e) => {
-    const { _tracking } = this.props;
+    const { _tracking, _video } = this.props;
+    if (_video) {
+      this.video = _video;
```
Comment (kumar303) [inline src/disco/containers/DiscoPane.js]: Re-assigning `this.video` makes me nervous because refs are kind of magical. I think we need to get this working:
````js
const { _video } = this.props._video || this.video;
````

**Comment by tofumatt** [comment]
All fixed, ready for another look.
