### PR TITLE
Remove code which allows events to be called on the server

### LINKED ISSUE #10376: Remove code which allows events to be called on the server
Some code was added to support the experiment enrollment event which allowed an event to be stored on the server and then later sent to GA on the client. We aren't going to need to do this anymore when we move all of the experiment code to the client, so we can remove this code.

We should also add code to tracking that will raise an exception if we ever try to send an event on the server, as this will be impossible to do, and we don't want any code attempting to do it, and failing silently.

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #10376

### CODE REVIEW

File: src/amo/tracking.js [hunk 1]
```diff
@@ -239,14 +231,7 @@ export class Tracking {
...
     if (_config.get('server')) {
-      if (dispatch) {
-        const event = { action, category, label, value };
-        dispatch(storeTrackingEvent({ event }));
-      } else {
-        throw new Error(
-          'The dispatch argument must be provided to sendEvent when being called on the server',
-        );
-      }
+      throw new Error('sendEvent: cannot send tracking events on the server');
```
Comment (willdurand) [inline src/amo/tracking.js:234]: Maybe we could add a comment here explaining why the developer received this error

**Review by willdurand — APPROVED** [review]
r+wc
