### PR TITLE
Open external links from the Primary Hero shelf in a new tab

### LINKED ISSUE #8533: Link to unlisted primary hero homepage should open in a new tab
Follow up for #8305 

### Describe the problem and steps to reproduce it:

1. Open AMO homepage on -dev
2. Refresh the page until you receive an unlisted add-on in the primary hero section (see example from the below screencast)
3. Click on Get started 

### What happened?
The unlisted add-on homepage opens in the same window although the user is leaving the amo domain

### What did you expect to happen?
Since the add-on homepage is an external link, we might want to open it in a different tab

### Anything else we should know?
I'm not sure if on AMO we have strict rules about external links. For example, external links in the 'More information' card from an add-on details page are opened in the same window, while the sumo links for the 'Recommended' badge and 'Learn more about permissions' are opened in a different tab.  
I'm opening this issue for further discussion.

### PR DESCRIPTION
**Pull request by bobsilverberg**
~~Depends on #8549~~

Fixes #8533

### CODE REVIEW

**Comment by bobsilverberg** [comment]
I rebased this but now there are some test failures. I will address them this afternoon.

**Comment by bobsilverberg** [comment]
I've fixed the issue. This is good to review now.

File: tests/unit/amo/components/TestHeroRecommendation.js [hunk 1]
```diff
@@ -91,6 +91,32 @@ describe(__filename, () => {
         root.instance().makeCallToActionURL(),
       );
     });
+
+    it('configures an external link to open in a new tab', () => {
+      const _isInternalURL = sinon.stub().returns(false);
+      const shelfData = createShelfData({
+        external: fakePrimaryHeroShelfExternal,
```
Comment (kumar303) [inline tests/unit/amo/components/TestHeroRecommendation.js]: Since this relies on a stub, I suggest asserting that `fakePrimaryHeroShelfExternal` gets passed as a parameter to `_isInternalURL()`.

File: tests/unit/amo/components/TestHeroRecommendation.js [hunk 2]
```diff
@@ -91,6 +91,32 @@ describe(__filename, () => {
...
+
+      const link = root.find('.HeroRecommendation-link');
+      expect(link).toHaveProp('rel', 'noopener noreferrer');
+      expect(link).toHaveProp('target', '_blank');
+    });
+
+    it('does not configure an internal link to open in a new tab', () => {
+      const _isInternalURL = sinon.stub().returns(true);
+      const shelfData = createShelfData({
+        external: fakePrimaryHeroShelfExternal,
```
Comment (kumar303) [inline tests/unit/amo/components/TestHeroRecommendation.js]: Similar to above, this should set up a realistic internal link with `shelfData.addon` and assert that it gets passed to `_isInternalURL()`. This will help cover the integration of `this.makeCallToActionURL()`.

File: tests/unit/amo/components/TestHeroRecommendation.js (hunk 1 above)
Comment (bobsilverberg) [reply tests/unit/amo/components/TestHeroRecommendation.js]: This is a good idea. `_isInternalURL()` is just passed `this.makeCallToActionURL()` in the code, but I gather you don't want me to just assert that it's called with that, but rather with whatever the result of `this.makeCallToActionURL()` would be, in this case. I've done that using a sinon matcher which I think gives us what we want, but if you could take another look at it that would be great.

File: tests/unit/amo/components/TestHeroRecommendation.js (hunk 2 above)
Comment (bobsilverberg) [reply tests/unit/amo/components/TestHeroRecommendation.js]: As above, I've made this change. Thanks!
