### PR TITLE
Show description for themes

### LINKED ISSUE #3123: Theme description is covered by "More Themes by author_name" section
Steps to reproduce:
1. Load a details page for a theme with description i.e. https://addons-dev.allizom.org/en-US/firefox/addon/firefox-saucers/

Expected results:
There are no display or layout issues.

Actual results:
Description is covered by "More Themes by author_name" section.

Notes/Issues:
Verified on AMO-dev FF55(Win 7). Not reproducing on device.
Regression from #2767
Video for this issue:
hide

### PR DESCRIPTION
**Pull request by willdurand**
Fix #3123

---

This PR fixes a CSS grid issue that prevented the theme description to be shown when other add-ons by the artists are displayed. It sticks to the mock-ups and works perfectly on FF 55, FF Nightly and Chrome/Opera. It should work with short/long description, and no/one/many other add-ons.

⚠️ This is a "better-than-nothing" yet pixel-perfect fix. I spent too much hours on it and @tofumatt helped a lot too! I don't know if there is a better "css grid way" of doing this but this works without `margin` hacks or similar. Please see all the screenshots to see all the edge cases.

## Screenshots

screen shot 2017-09-15 at 14 38 56

screen shot 2017-09-15 at 14 38 54

screen shot 2017-09-15 at 14 38 50

screen shot 2017-09-15 at 14 38 38

screen shot 2017-09-15 at 14 38 34

screen shot 2017-09-15 at 14 38 14

screen shot 2017-09-15 at 14 38 01

screen shot 2017-09-15 at 14 37 54

screen shot 2017-09-15 at 14 37 39

screen shot 2017-09-15 at 14 37 33

screen shot 2017-09-15 at 15 01 27

screen shot 2017-09-15 at 15 01 18

### CODE REVIEW

File: src/amo/components/Addon/index.js [hunk 1]
```diff
@@ -452,8 +453,14 @@ export class AddonBase extends React.Component {
       isRestartRequired = addon.isRestartRequired;
     }
 
+    const addonsByAuthorsLength = addonsByAuthors ? addonsByAuthors.length : 0;
+    const _classNames = classNames('Addon', `Addon-${addonType}`, {
+      'Addon--has-more-addons': addonsByAuthorsLength > 0,
+      'Addon--has-many-more-addons': addonsByAuthorsLength > 3,
```
Comment (tofumatt) [inline src/amo/components/Addon/index.js]: This is cute but not descriptive 😄

This should be `Addon--has-more-than-3-addons`. Arguable for consistency this could be:

```js
const _classNames = classNames('Addon', `Addon-${addonType}`, {
  'Addon--has-more-than-0-addons': addonsByAuthorsLength > 0,
  'Addon--has-more-than-3-addons': addonsByAuthorsLength > 3,
});
```

Sure it's kinda weird and verbose but it's obvious and consistent.

File: src/amo/components/Addon/index.js [hunk 2]
```diff
@@ -452,8 +453,14 @@ export class AddonBase extends React.Component {
...
+    });
+
     return (
-      <div className={classNames('Addon', `Addon-${addonType}`)}>
+      <div className={_classNames}>
```
Comment (tofumatt) [inline src/amo/components/Addon/index.js]: I don't like the `_` vars as I think of them as private variables. Seems we could be doing naming better here (`cssClasses` would be fine) but in this case why bother? We do multi-line, inline `classNames()` calls [elsewhere in the code](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/CategoryHeader/index.js#L50) and I'm not the biggest fan of assigning a variable that's only used once.

I think this could just be multi-line like it is elsewhere.

File: src/amo/components/Addon/styles.scss [hunk 3]
```diff
@@ -193,13 +193,23 @@
...
+    grid-gap: 0 10px;
     grid-template-columns: minmax(300px, 35%) auto;
     margin: 10px 0 0;
 
     .AddonDescription {
       grid-column: 2;
       grid-row: 1 / span 5;
+
+      .Addon--has-more-addons.Addon-persona & {
+        // This span makes sure the left widdget does not move vertically when
```
Comment (tofumatt) [inline src/amo/components/Addon/styles.scss]: widget.

File: src/amo/components/Addon/styles.scss [hunk 4]
```diff
@@ -193,13 +193,23 @@
...
+        // there is a long description.
+        grid-row: 2 / span 1000;
```
Comment (tofumatt) [inline src/amo/components/Addon/styles.scss]: Hah, I did something similar at first but was worried it was too hacky. If you're gonna do this and want things to really line up you're best going for a wild value. Might as well kick it up to `50000`. Seriously 😅

File: src/amo/components/Addon/styles.scss [hunk 5]
```diff
@@ -229,10 +242,27 @@
...
 
   .AddonMoreInfo {
     grid-column: 1 / 2;
+    grid-row: 4 / span 1;
+
+    .Addon--has-more-addons.Addon-persona & {
+      grid-row: 3 / span 1;
+    }
+
+    .Addon--has-many-more-addons.Addon-persona & {
```
Comment (tofumatt) [inline src/amo/components/Addon/styles.scss]: Yeah seeing this in the CSS a lot I'm definitely convinced we should rename this class. This is weird to read, the numbers should help I think.

File: tests/unit/amo/components/TestAddon.js [hunk 6]
```diff
@@ -1051,6 +1051,38 @@ describe(__filename, () => {
       expect(root).toHaveClassName('.AddonDescription-more-addons--theme');
       expect(root).toHaveProp('addons', addonsByAuthors);
     });
+
+    it('adds a css class to the main component when there are add-ons', () => {
```
Comment (tofumatt) [inline tests/unit/amo/components/TestAddon.js]: I'd uppercase CSS here, just for readibility.

File: tests/unit/amo/components/TestAddon.js [hunk 7]
```diff
@@ -1051,6 +1051,38 @@ describe(__filename, () => {
...
+
+      const root = renderComponent({ params: { slug: addon.slug }, store });
+
+      expect(root).toHaveClassName('.Addon--has-more-addons');
+      expect(root).not.toHaveClassName('.Addon--has-many-more-addons');
+    });
+
+    it('adds a css class when there many other add-ons by authors', () => {
+      const addon = fakeAddon;
+      // We need more than 3 add-ons to indicate that there are "many" other
```
Comment (tofumatt) [inline tests/unit/amo/components/TestAddon.js]: With the CSS classname including the number this comment won't be needed! 😄

File: src/amo/components/Addon/index.js [hunk 8]
```diff
@@ -452,8 +453,14 @@ export class AddonBase extends React.Component {
       isRestartRequired = addon.isRestartRequired;
     }
 
+    const addonsByAuthorsLength = addonsByAuthors ? addonsByAuthors.length : 0;
```
Comment (tofumatt) [inline src/amo/components/Addon/index.js]: Would `numberOfAddonsByAuthor` be a bit more descriptive? Otherwise just make `addonsByAuthors` always an array (with a default value or something?) so you can always do `.length` on it because it's a bit weird to see what is basically `addonsByAuthorsLength = addonsByAuthors.length` 😄

**Comment by tofumatt** [comment]
PS thanks for the screenshots of all of the various states 👍

File: src/amo/components/Addon/index.js (hunk 1 above)
Comment (willdurand) [reply src/amo/components/Addon/index.js]: I was not sure about it, but it sounds good to me.
