### PR TITLE
Put the logic for relative URLs back into `checkInternalURL`

### LINKED ISSUE #8676: Internal URLs from homepage heroes are appended with parameters used for external links
### Describe the problem and steps to reproduce it:

1. Load AMO homepage on -dev
2. Inspect the call to action URL for a listed primary hero, or a secondary hero that links to an internal page

### What happened?
Internal URLs are appended with parameters intended for external links - i.e. `?utm_content=homepage-primary-hero&utm_medium=referral&utm_source=addons-dev.allizom.org"`

### What did you expect to happen?
Internal URLs should have the following parameters: `src=homepage-primary-hero` or `src=homepage-secondary-hero`

**Notes**
This might be a regression from #8674, because the issue was not present last week

image

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #8676

### CODE REVIEW

File: src/amo/utils/index.js [hunk 1]
```diff
@@ -65,7 +65,10 @@ export const checkInternalURL = ({
 |}): { isInternal: boolean, relativeURL: string } => {
   const baseURL = _config.get('baseURL');
   const urlParts = url.parse(urlString, true);
-  const isInternal = url.parse(baseURL).host === urlParts.host;
+  const isInternal =
+    // The double slash is for protocol-free URLs.
+    (urlString.startsWith('/') && !urlString.startsWith('//')) ||
+    url.parse(baseURL).host === urlParts.host;
```
Comment (willdurand) [inline src/amo/utils/index.js]: I believe there should be a check/variable before to determine whether a URL is absolute or relative. Then, if the URL is relative, it is therefore internal. If the URL is absolute, then the `host` must be checked to determine whether the absolute URL is `internal`.

I think that'd be more explicit and future-proof.

Comment (bobsilverberg) [reply src/amo/utils/index.js]: Good idea. I have updated the patch.

File: tests/unit/amo/utils/test_index.js [hunk 2]
```diff
@@ -67,7 +67,19 @@ describe(__filename, () => {
     });
 
     describe('isInternal prop', () => {
-      it('returns true for a URL containing the current host', () => {
+      it('returns true for a single slash-prefixed URL', () => {
+        expect(checkInternalURL({ urlString: pathname }).isInternal).toEqual(
```
Comment (willdurand) [inline tests/unit/amo/utils/test_index.js]: It's not clear to me that `pathname` is a "single slash-prefixed URL", which I guess is a relative URL. I'd rather put a fixed value here like `/relative/url`

File: tests/unit/amo/utils/test_index.js [hunk 3]
```diff
@@ -67,7 +67,19 @@ describe(__filename, () => {
...
+          true,
+        );
+      });
+
+      it('returns false for a double slash-prefixed URL', () => {
+        expect(
+          checkInternalURL({ urlString: '//path/name' }).isInternal,
```
Comment (willdurand) [inline tests/unit/amo/utils/test_index.js]: Something like this would be more accurate:

```suggestion
          checkInternalURL({ urlString: '//example.com/name' }).isInternal,
```

File: tests/unit/amo/utils/test_index.js [hunk 4]
```diff
@@ -67,7 +67,19 @@ describe(__filename, () => {
...
+        ).toEqual(false);
+      });
+
```
Comment (willdurand) [inline tests/unit/amo/utils/test_index.js]: Do we have a test case for an internal protocol-free URL?

Comment (bobsilverberg) [reply tests/unit/amo/utils/test_index.js]: We don't actually support internal protocol-free URLs with the current code. We're using `url.parse` to extract the `host` from the URL (to compare with `baseURL` from `config`), but `url.parse` does not support protocol-free URLs. It just interprets the entire URL as the `path`. I guess if we truly want to support protocol-free URLs we need to write some extra code to deal with this edge-case.

On the other hand, one could argue that we shouldn't ever *need* to support them because of the source of these URLs. They are either
a) URLs that we are generating ourselves in the app (like an add-on URL), and I don't see any reason why we'd ever generate a protocol-free URL, or
b) URLs that are entered into the admin for the hero shelves. If a protocol-free URL is entered into the admin, the API will return it to us with a protocol prepended.

Therefore, I don't think we need to support them in this function, so I will remove the code that I added specifically for them.

File: tests/unit/amo/utils/test_index.js (hunk 3 above)
Comment (bobsilverberg) [reply tests/unit/amo/utils/test_index.js]: This is becoming irrelevant with the removal of code for the double-slash URLs, but thanks!

**Comment by bobsilverberg** [comment]
@willdurand because I removed the support for double-slash URLs, you might want to take one last look at this before I merge it, even though you gave it an r+wc.

File: tests/unit/amo/utils/test_index.js (hunk 4 above)
Comment (willdurand) [reply tests/unit/amo/utils/test_index.js]: I actually do think that we should support protocol free urls, it will be more future proof and that is almost done.

**Comment by willdurand** [comment]
> @willdurand because I removed the support for double-slash URLs, you might want to take one last look at this before I merge it, even though you gave it an r+wc.

oh, ok. I think supporting protocol free urls is a good thing here, we should not make assumptions that it will never be possible. This was almost done so I don't know.

File: tests/unit/amo/utils/test_index.js (hunk 4 above)
Comment (bobsilverberg) [reply tests/unit/amo/utils/test_index.js]: > I actually do think that we should support protocol free urls, it will be more future proof and that is almost done anyway.

Do you also think we need to support internal protocol free urls? I can't see a use case for someone specifically creating a protocol free url that points back to the site? I guess we can do it, but it's extra code to cover a use case that seems like it will never happen.

**Comment by bobsilverberg** [comment]
> > @willdurand because I removed the support for double-slash URLs, you might want to take one last look at this before I merge it, even though you gave it an r+wc.
> 
> oh, ok. I think supporting protocol free urls is a good thing here, we should not make assumptions that it will never be possible. This was almost done so I don't know.

Ok, I'll add it back in. It does ensure it's covered in the future, although I also don't see why we'd ever need to cover it. But I guess we shouldn't make assumptions about what the future might look like.

File: tests/unit/amo/utils/test_index.js (hunk 4 above)
Comment (willdurand) [reply tests/unit/amo/utils/test_index.js]: I had the feeling that protocol free internal urls were already supported. If it is, great. If not, then let's add a comment to mention this limitation.

Comment (bobsilverberg) [reply tests/unit/amo/utils/test_index.js]: Well, now you've got me thinking that if we're going to support it at all, we should probably support it fully. It's a bit of extra code, but I'm going to have ti support both cases (internal and external).

**Comment by bobsilverberg** [comment]
@willdurand I added support for both internal and external protocol-free URLs. Do you mind taking another look?
