### PR TITLE
Redirect slug

### LINKED ISSUE #4271: Mixed case version of slug leads to blank page
Re-filed copy of https://github.com/mozilla/addons/issues/586

### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

Go to an addon location (https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/), but change the case of the name (https://addons.mozilla.org/en-US/firefox/addon/snapLinksplus/) and you don't get an error page, just a blank screen.

### What happened?

You don't get an error page, just a blank screen.

### What did you expect to happen?

Get an error page, like with (https://addons.mozilla.org/en-US/firefox/addon/sadmknmsadlksa/)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Working: https://addons.mozilla.org/en-US/firefox/addon/snaplinksplus/
Working: https://addons.mozilla.org/en-US/firefox/addon/sadmknmsadlksa/
Not working: https://addons.mozilla.org/en-US/firefox/addon/snapLinksplus/

Looks like this:

add-ons_for_firefox

As noted by @diox in https://github.com/mozilla/addons/issues/586#issuecomment-357675409 this worked on the old site. The only issue is the legacy site shows the same content on a different URL (I'm not sure if it uses rel=canonical) - the ideal solution is probably to provide a 301 cacheable redirect to the lower case version.

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #4271

---

Send a redirect when an add-on detail slug is not lower case OR a collection username/slug is not lower case.

### CODE REVIEW

File: src/amo/pages/Addon/index.js [hunk 1]
```diff
@@ -125,11 +131,12 @@ export class AddonBase extends React.Component {
       const { slug } = params;
 
       if (addon) {
-        // We want to make sure the slug converts to a positive
-        // number/ID before we try redirecting.
-        if (slugIsPositiveID(slug)) {
+        // We want to make sure the slug converts to a positive number/ID
+        // before we try redirecting.
+        if (slugIsPositiveID(slug) || isNotLowerCase(slug)) {
```
[the remark this answers is not in the document]
Comment (willdurand) [reply src/amo/pages/Addon/index.js]: it must always be lowercase and it must be enforced now, if the API does not lowercase the slug in the response, it's an API bug.

File: src/amo/pages/Addon/index.js [hunk 2]
```diff
@@ -743,7 +750,10 @@ export class AddonBase extends React.Component {
 }
 
 export function mapStateToProps(state, ownProps) {
-  const { slug } = ownProps.match.params;
+  const slug =
+    typeof ownProps.match.params.slug === 'string'
```
[the remark this answers is not in the document]
Comment (willdurand) [reply src/amo/pages/Addon/index.js]: given that we retrieve the slug based on the routing parameter, we must use the lowercase version, because the only slug valid that should be stored is lowercase.

[the remark this answers is not in the document]
Comment (willdurand) [reply src/amo/pages/Addon/index.js]: I think it is because the test case fails if you remove this line.

File: src/amo/pages/Collection/index.js [hunk 3]
```diff
@@ -223,6 +226,24 @@ export class CollectionBase extends React.Component<InternalProps> {
       }
     }
 
+    // See: https://github.com/mozilla/addons-frontend/issues/4271
+    if (
+      collection &&
+      (isNotLowerCase(params.username) || isNotLowerCase(params.slug))
```
[the remark this answers is not in the document]
Comment (willdurand) [reply src/amo/pages/Collection/index.js]: right, let's ignore this for the username. that's clearly a mistake.

[the remark this answers is not in the document]
Comment (willdurand) [reply src/amo/pages/Collection/index.js]: we'll get rid of usernames soon anyway, user ids won't have this problem in the near future.

File: src/amo/pages/Addon/index.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/pages/Addon/index.js]: I'm not sure I follow. Try testing with http://localhost:3000/en-CA/firefox/addon/Beach_View/.

File: src/amo/pages/Addon/index.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/pages/Addon/index.js]: Ah, I see. I think I better understand how the two changes in `Addon` interact now.

**Comment by willdurand** [comment]
I am marking this PR as blocked because I thought the API was already ready, but it is not the case: the API must return lowercase slugs all the time.

**Comment by willdurand** [comment]
Ok, so the original idea supported by Product was to lowercase slugs all the time, but @eviljeff made a case to support mixed cases since we have done that in the past.

I thought about it last night, and I think we can start by making mixed case work first, and see to lowercase slugs in the near future.

File: src/core/reducers/addons.js [hunk 4]
```diff
@@ -390,11 +398,11 @@ export default function addonsReducer(
           },
           bySlug: {
             ...state.bySlug,
-            [addon.slug]: undefined,
+            [addon.slug.toLowerCase()]: undefined,
           },
           loadingBySlug: {
             ...state.loadingBySlug,
-            [addon.slug]: false,
+            [addon.slug.toLowerCase()]: undefined,
```
Comment (willdurand) [inline src/core/reducers/addons.js]: I think it makes sense to remove it from the state, rather than keeping it.

File: src/core/reducers/addons.js [hunk 5]
```diff
@@ -355,8 +363,8 @@ export default function addonsReducer(
         byID[`${addon.id}`] = addon;
 
         if (addon.slug) {
-          bySlug[addon.slug] = addon.id;
-          loadingBySlug[addon.slug] = false;
+          bySlug[addon.slug.toLowerCase()] = addon.id;
```
Comment (bobsilverberg) [inline src/core/reducers/addons.js]: Should you also be using `slug.toLowerCase()` in `FETCH_ADDON` (line 346)?

File: tests/unit/amo/pages/TestAddon.js [hunk 6]
```diff
@@ -620,6 +620,30 @@ describe(__filename, () => {
...
+  it("dispatches a server redirect when slug param case does not match the add-on's slug case", () => {
+    const clientApp = CLIENT_APP_FIREFOX;
+    const { store } = dispatchClientMetadata({ clientApp });
+    const addon = createInternalAddon(fakeAddon);
+    store.dispatch(_loadAddons({ addon }));
+
+    const fakeDispatch = sinon.spy(store, 'dispatch');
+    renderComponent({
+      // Set the slug param to all uppercase
+      params: { slug: addon.slug.toUpperCase() },
```
Comment (bobsilverberg) [inline tests/unit/amo/pages/TestAddon.js]: Nit: There's no guarantee that `slug` in `fakeAddon` isn't already all upper case, so we should probably set a manual value for `slug` in the test. Of course, the test would fail if that were the case, but it still feels like the right thing to do, to me.

File: tests/unit/amo/pages/TestCollection.js [hunk 7]
```diff
@@ -1392,6 +1371,67 @@ describe(__filename, () => {
       }),
     );
   });
+  it('sends a server redirect when username is not lower case', () => {
```
Comment (bobsilverberg) [inline tests/unit/amo/pages/TestCollection.js]: Should this description be about the case not matching, as opposed to "not lower case"?

File: tests/unit/amo/pages/TestCollection.js [hunk 8]
```diff
@@ -1392,6 +1371,67 @@ describe(__filename, () => {
...
+
+    _loadCurrentCollection({ store });
+
+    fakeDispatch.resetHistory();
+
+    const collection = getCurrentCollection(store.getState().collections);
+
+    const params = {
+      slug: collection.slug,
+      username: collection.authorUsername.toUpperCase(),
```
Comment (bobsilverberg) [inline tests/unit/amo/pages/TestCollection.js]: Nit: As with the nit I filed above, I think we should set a known value for the collection `authorUsername` rather than assuming it's not already upper case.

File: tests/unit/amo/pages/TestCollection.js [hunk 9]
```diff
@@ -1392,6 +1371,67 @@ describe(__filename, () => {
...
+    const fakeDispatch = sinon.spy(store, 'dispatch');
+
+    _loadCurrentCollection({ store });
+
+    fakeDispatch.resetHistory();
+
+    const collection = getCurrentCollection(store.getState().collections);
+
+    const params = {
+      slug: collection.slug.toUpperCase(),
```
Comment (bobsilverberg) [inline tests/unit/amo/pages/TestCollection.js]: Nit: As with the nit I filed above, I think we should set a known value for the collection `slug` rather than assuming it's not already upper case.

File: tests/unit/amo/pages/TestCollection.js [hunk 10]
```diff
@@ -1392,6 +1371,67 @@ describe(__filename, () => {
...
+        status: 301,
+        url: `/${lang}/${clientApp}/collections/${collection.authorUsername}/${
+          collection.slug
+        }/`,
+      }),
+    );
+    sinon.assert.calledOnce(fakeDispatch);
+  });
+
+  it('sends a server redirect when slug is not lower case', () => {
```
Comment (bobsilverberg) [inline tests/unit/amo/pages/TestCollection.js]: Should this description be about the case not matching, as opposed to "not lower case"?

File: tests/unit/core/reducers/test_addons.js [hunk 11]
```diff
@@ -101,6 +101,21 @@ describe(__filename, () => {
     });
   });
 
+  it('stores all add-on slugs in lowercase', () => {
+    const addonResults = [
```
Comment (bobsilverberg) [inline tests/unit/core/reducers/test_addons.js]: Nit: You could avoid hardcoding these by making `FIRST` and `SeCond` consts and then using `toLowerCase()` in the assertion.

File: tests/unit/core/reducers/test_addons.js [hunk 12]
```diff
@@ -566,6 +593,15 @@ describe(__filename, () => {
         createInternalAddon(fakeAddon),
       );
     });
+
+    it('is case insensitive', () => {
+      const { store } = dispatchClientMetadata();
+      store.dispatch(loadAddons(createFetchAddonResult(fakeAddon).entities));
+
+      expect(
+        getAddonBySlug(store.getState(), fakeAddon.slug.toUpperCase()),
```
Comment (bobsilverberg) [inline tests/unit/core/reducers/test_addons.js]: Nit: As above, we're assuming that `fakeAddon.slug` is not already in upper case.

File: src/core/reducers/addons.js [hunk 13]
```diff
@@ -293,7 +293,11 @@ export const getAddonBySlug = (
   state: AppState,
   slug: string,
 ): AddonType | null => {
-  const addonId = state.addons.bySlug[slug];
+  if (typeof slug !== 'string') {
```
Comment (bobsilverberg) [inline src/core/reducers/addons.js]: This doesn't seem to be covered by a test, at least not a test where `slug` is neither a string nor `null` nor `undefined`.

File: src/core/reducers/addons.js [hunk 14]
```diff
@@ -308,7 +312,11 @@ export const getAddonByGUID = (
 };
 
 export const isAddonLoading = (state: AppState, slug: string): boolean => {
-  return Boolean(state.addons.loadingBySlug[slug]);
+  if (typeof slug !== 'string') {
```
Comment (bobsilverberg) [inline src/core/reducers/addons.js]: This doesn't seem to be covered by a test, at least not a test where `slug` is neither a string nor `null` nor `undefined`.

File: src/core/reducers/addons.js (hunk 13 above)
Comment (bobsilverberg) [reply src/core/reducers/addons.js]: Looking again, wouldn't Flow protect us from this ever happening?

File: src/core/reducers/addons.js (hunk 14 above)
Comment (bobsilverberg) [reply src/core/reducers/addons.js]: Looking again, wouldn't Flow protect us from this ever happening?

File: src/core/reducers/addons.js (hunk 13 above)
Comment (willdurand) [reply src/core/reducers/addons.js]: Flow won't be helpful at runtime.

There are 3 test cases for string, null or undefined. I think that's enough, but if yu like, I can still add another one with a number.

File: src/core/reducers/addons.js (hunk 14 above)
Comment (willdurand) [reply src/core/reducers/addons.js]: same as above

File: tests/unit/amo/pages/TestCollection.js (hunk 10 above)
Comment (willdurand) [reply tests/unit/amo/pages/TestCollection.js]: ah right

File: tests/unit/amo/pages/TestCollection.js (hunk 7 above)
Comment (willdurand) [reply tests/unit/amo/pages/TestCollection.js]: ah right

File: tests/unit/amo/pages/TestAddon.js (hunk 6 above)
Comment (willdurand) [reply tests/unit/amo/pages/TestAddon.js]: well, calling the method implies that it is not already the case, but I can of course be more verbose and create an addon with a lowercase slug.

File: src/core/reducers/addons.js (hunk 5 above)
Comment (willdurand) [reply src/core/reducers/addons.js]: oh right, good catch!

File: tests/unit/core/reducers/test_addons.js (hunk 12 above)
Comment (willdurand) [reply tests/unit/core/reducers/test_addons.js]: I'd argue that the test case above explicitly proves that.

Comment (bobsilverberg) [reply tests/unit/core/reducers/test_addons.js]: I'd argue that that statement proves my case. ;-)

File: src/core/reducers/addons.js (hunk 13 above)
Comment (bobsilverberg) [reply src/core/reducers/addons.js]: I'm not sure it's about what I like. If the code is written to return a `null` when a number is passed, it seems like we should have a test for that. Otherwise it could have just been `if(!slug)`.

File: tests/unit/core/reducers/test_addons.js (hunk 12 above)
Comment (willdurand) [reply tests/unit/core/reducers/test_addons.js]: haha, I changed it anyway

File: src/core/reducers/addons.js (hunk 13 above)
Comment (willdurand) [reply src/core/reducers/addons.js]: fair enough, updated!
