### PR TITLE
I7378-Icon star storybook

### LINKED ISSUE #7378: Add configurable IconStar into storybook
This will help prepare the switchover and ideally make sure there are no visual regressions. 

See https://github.com/mozilla/addons-frontend/issues/5925#issuecomment-453227762

### PR DESCRIPTION
**Pull request by rebmullin**
fixes #7378 

~~So I readded IconStar here so it could be set up in storybook. Although, we will officially turn this on in AMO in #7365 (hopefully).~~ 

I've also added the `Rating` ~~and `RatingsByStar`~~ component~~s here too~~ so you can see the 5 star set up and we'll be able to see the changes with the new PR as these files will be updated in that PR as well.

note: while I do like the props grid, since the props are shown in the Component's variations page, maybe this is enough. Especially since the props (with flow and now with HOCs too it seems) aren't always working :/ For now tho, I just commented this out where it wasn't working properly: on Ratings and the RatingsByStar components. 

also, I would recommend looking into using this plugin again:

https://github.com/evgenykochetkov/react-storybook-addon-props-combinations

It was suggested at 1 point by someone and I think it may be easier to use than manually doing all the use cases/mixes of props as we have to do now.

### CODE REVIEW

File: tests/unit/helpers.js [hunk 1]
```diff
@@ -615,8 +615,11 @@ export function JedSpy(data = {}) {
 /*
  * Creates a stand-in for a jed instance,
  */
-export function fakeI18n({ lang = config.get('defaultLang') } = {}) {
-  return makeI18n({}, lang, JedSpy);
+export function fakeI18n({
+  lang = config.get('defaultLang'),
+  includeJedSpy = true,
+} = {}) {
+  return makeI18n({}, lang, includeJedSpy ? JedSpy : undefined);
```
Comment (rebmullin) [inline tests/unit/helpers.js]: AFAIK, there is no test for this but let me know if one should be added..

File: src/ui/components/IconStar/index.js [hunk 2]
```diff
@@ -0,0 +1,131 @@
...
+    case DIM_CLOSED_STYLE:
+      gProps = {
+        ...gProps,
+        transform: 'translate(-140.000000, -607.000000)',
+        fillOpacity: starStyle === DIM_CLOSED_STYLE ? 0.25 : 1,
+      };
+      break;
+    case HALF_STYLE: {
+      // Key is needed in case there are multiple IconStars on 1 page.
+      const key = Math.random();
```
Comment (rebmullin) [inline src/ui/components/IconStar/index.js]: This was 1 of the reasons why the half star didn't show up more than once on the home page (and other place where there could be multiple stars), because this is used as part of the id which needs to be unique.

File: stories/ui/Badge.js [hunk 3]
```diff
@@ -18,10 +18,11 @@ const types = [
   'requires-payment',
 ];
 
-export type Props = {|
+export type Props = {
   props: BadgeProps,
-|};
+};
 
+// $FLOW_FIXME: I made PropsMatrixType exact but it's still not working here :/
```
Comment (rebmullin) [inline stories/ui/Badge.js]: I got stuck on this flow issue here (same thing in Button). I thought if I made this not an exact flow type, the `wrapperClassName` wouldn't be an issue (wrapperClassName is needed for the Rating component). Please let me know if you have any suggestions?

**Comment by rebmullin** [comment]
@kumar303, how's it look now?  I think it looks pretty close now but even with adding the container styles I could not completely match the styles (unless there is something I missed).
Also, I had some issues with flow (noted above), so I might need your help with too.

**Comment by kumar303** [comment]
ok, I'll take a look

File: stories/ui/Rating.js [hunk 4]
```diff
@@ -0,0 +1,153 @@
...
+
+import Rating from 'ui/components/Rating';
+import type { Props as RatingProps } from 'ui/components/Rating';
+
+import { createChapters } from '../utils';
+import Provider from '../setup/Provider';
+
+// Some extra styles for the Rating component
+// are included in the additional files.
+import 'amo/components/RatingManager/styles.scss';
```
Comment (kumar303) [inline stories/ui/Rating.js]: I don't think including these extra styles are necessary. Do you? If there are considerable visual differences then we should just set up storybooks for each one of them (not as part of this issue, though). As a first pass, we should just get a storybook for `Rating` in isolation.

File: stories/ui/Badge.js (hunk 3 above)
Comment (kumar303) [inline stories/ui/Badge.js]: Flow wants all of the `Props` to follow the same shape. In other words, if all components can receive `wrapperClassNames` then all `Props` need to add that. Here is an example:

```diff
diff --git a/stories/ui/Badge.js b/stories/ui/Badge.js
index 81fbd05c0..ff6b2457a 100644
--- a/stories/ui/Badge.js
+++ b/stories/ui/Badge.js
@@ -18,11 +18,11 @@ const types = [
   'requires-payment',
 ];
 
-export type Props = {
+export type Props = {|
   props: BadgeProps,
-};
+  wrapperClassNames?: Array<string>,
+|};
 
-// $FLOW_FIXME: I made PropsMatrixType exact but it's still not working here :/
 function createPropsMatrix(chapter): Array<Props> {
   return [
     {
diff --git a/stories/ui/Rating.js b/stories/ui/Rating.js
index 173b444e8..93de9ada4 100644
--- a/stories/ui/Rating.js
+++ b/stories/ui/Rating.js
@@ -14,10 +14,10 @@ import 'amo/components/RatingManager/styles.scss';
 import 'amo/components/AddonReviewManagerRating/styles.scss';
 import 'amo/components/AddonReviewCard/styles.scss';
 
-export type Props = {
+export type Props = {|
   props: RatingProps,
   wrapperClassNames?: Array<string>,
-};
+|};
 
 function createPropsMatrix(): Array<Props> {
   return [
diff --git a/stories/utils.js b/stories/utils.js
index d2c511089..e43e8dfa8 100644
--- a/stories/utils.js
+++ b/stories/utils.js
@@ -2,10 +2,10 @@
 import * as React from 'react';
 import makeClassName from 'classnames';
 
-type PropsMatrixType = {
+type PropsMatrixType = {|
   props: Object,
   wrapperClassNames?: Array<string>,
-};
+|};
 
 type ChapterType = string | number | void;
 
```

Instead of copying/pasting `wrapperClassNames` to each one you can extend a shared type like `PropMatrixType`.

However, I think you could do this patch without `wrapperClassNames`, right? If so, I would suggest adding it later only when you need it, in a follow-up issue.

File: stories/ui/Rating.js (hunk 4 above)
Comment (rebmullin) [reply stories/ui/Rating.js]: I guess I was trying to match as closely as possible. But you're right in this case it's not maybe not too big of a difference.

File: stories/ui/Badge.js (hunk 3 above)
Comment (rebmullin) [reply stories/ui/Badge.js]: well actually with a class from the styles imported (I believe from `AddonReviewManagerRating`), we see something like this:

Alt text

This is seen when you're editing. If we leave this import out and do not add this class name then it would just look like the stars shown above. Is that okay? I figured we'd want to account for this..

Thanks for the Flow information. I thought if `PropsMatrixType` wasn't an exact type, it would allow for `Badge` and `Button` to have this. I guess it's moot tho if I am removing the `wrapperClassNames` above.

**Comment by rebmullin** [comment]
hey @kumar303, it's ready for another review:) thanks!

File: stories/ui/Rating.js [hunk 5]
```diff
@@ -0,0 +1,138 @@
...
+function createPropsMatrix(): Array<Props> {
+  return [
+    {
+      props: {
+        readOnly: false,
+        styleSize: 'small',
+        rating: 4,
+        yellowStars: true,
+      },
+    },
```
Comment (kumar303) [inline stories/ui/Rating.js]: Here are a few missing states:

```diff
diff --git a/stories/ui/Rating.js b/stories/ui/Rating.js
index 9321035de..af88c437a 100644
--- a/stories/ui/Rating.js
+++ b/stories/ui/Rating.js
@@ -15,6 +15,22 @@ export type Props = {|
 
 function createPropsMatrix(): Array<Props> {
   return [
+    {
+      props: {
+        readOnly: false,
+        styleSize: 'small',
+        rating: undefined,
+        yellowStars: true,
+      },
+    },
+    {
+      props: {
+        readOnly: false,
+        styleSize: 'small',
+        rating: null,
+        yellowStars: true,
+      },
+    },
     {
       props: {
         readOnly: false,
@@ -39,6 +55,14 @@ function createPropsMatrix(): Array<Props> {
         yellowStars: true,
       },
     },
+    {
+      props: {
+        readOnly: false,
+        styleSize: 'large',
+        rating: undefined,
+        yellowStars: true,
+      },
+    },
     {
       props: {
         readOnly: false,
@@ -73,6 +97,14 @@ function createPropsMatrix(): Array<Props> {
         yellowStars: true,
       },
     },
+    {
+      props: {
+        readOnly: true,
+        styleSize: 'small',
+        rating: undefined,
+        yellowStars: false,
+      },
+    },
     {
       props: {
         readOnly: true,
@@ -97,6 +129,14 @@ function createPropsMatrix(): Array<Props> {
         yellowStars: false,
       },
     },
+    {
+      props: {
+        readOnly: true,
+        styleSize: 'large',
+        rating: undefined,
+        yellowStars: false,
+      },
+    },
     {
       props: {
         readOnly: true,
@@ -106,6 +146,22 @@ function createPropsMatrix(): Array<Props> {
         className: 'RatingManager-UserRating',
       },
     },
+    {
+      props: {
+        readOnly: true,
+        styleSize: 'large',
+        rating: 3.4,
+        yellowStars: false,
+      },
+    },
+    {
+      props: {
+        readOnly: true,
+        styleSize: 'large',
+        rating: 4,
+        yellowStars: false,
+      },
+    },
   ];
 }
 
```

File: stories/ui/Rating.js [hunk 6]
```diff
@@ -0,0 +1,138 @@
...
+    {
+      props: {
+        readOnly: false,
+        styleSize: 'large',
+        rating: null,
+        yellowStars: true,
+        className: 'RatingManager-UserRating',
```
Comment (kumar303) [inline stories/ui/Rating.js]: All of these simulated class names can be removed now.

File: stories/ui/Badge.js (hunk 3 above)
Comment (kumar303) [reply stories/ui/Badge.js]: I don't think we should add in simulations of each component that wraps `Rating` as part of this PR. If we do add them in a future PR, they should go in separate stories for each separate component. In other words, trying to manually set class names and include foreign styles will be hard to maintain; they could go out of sync with the real code very easily.

File: tests/unit/helpers.js (hunk 1 above)
Comment (kumar303) [reply tests/unit/helpers.js]: > AFAIK, there is no test for this but let me know if one should be added..

No worries. Storybook will break if we accidentally change it.

File: stories/ui/Rating.js (hunk 5 above)
Comment (rebmullin) [reply stories/ui/Rating.js]: I guess i didn't see these ones on the frontend so I left those out but I can definitely add

File: stories/ui/Badge.js (hunk 3 above)
Comment (rebmullin) [reply stories/ui/Badge.js]: okay, I'll remove all the external styles (including all container code to simulate the actual space there is).
