### PR TITLE
fix: Use Firefox categories for Android themes (fix #2170)

### LINKED ISSUE #2170: Android Theme categories don't exist so "Browse Theme Categories" link goes nowhere
Because #1875, this happens: https://github.com/mozilla/addons-frontend/issues/1745#issuecomment-288984336

We'll need to catch that request as well and stub in the `clientApp` as Firefox instead of Android until Android has its own theme categories...

### PR DESCRIPTION
**Pull request by tofumatt**
fix #2170

Similar to the solution used for searching Android Themes, except we patch the data in the reducer/state instead of the API call because the category list API just returns all categories for all clientApps.

### Before
mar-25-2017 23-05-52

### After
mar-25-2017 23-05-00

### CODE REVIEW

**Comment by tofumatt** [comment]
This would be good to land before today's tag because there are now links to these pages from the improve Extensions/Themes landing pages' headers (#2100). Otherwise users will click links that result in empty categories.

File: src/core/reducers/categories.js [hunk 1]
```diff
@@ -51,6 +52,16 @@ export default function categories(state = initialState, action) {
...
       });
 
+      // Android doesn't have any theme categories but because all lightweight
+      // themes (personas) are installable on Firefox Desktop and Android
+      // we share categories and themes across clientApps.
+      // See: https://github.com/mozilla/addons-frontend/issues/2170
+      //
+      // This can be removed once
+      // https://github.com/mozilla/addons-server/issues/4766 is fixed.
+      categoryList.android[ADDON_TYPE_THEME] = categoryList
```
Comment (kumar303) [inline src/core/reducers/categories.js]: You could use braces to limit the scope of the `categories` variable to just this switch case

Comment (kumar303) [inline src/core/reducers/categories.js]: I know it's not part of this patch but could you log a warning [when we skip an app category](https://github.com/mozilla/addons-frontend/blob/f333d5eb389a017de2641692cf260c5bfc0e6476/src/core/reducers/categories.js#L35)? That could be very confusing if we have incorrect values configured for valid apps.

Comment (kumar303) [inline src/core/reducers/categories.js]: I think it would be nice to log a warning right above this since it would be confusing if we fix the API result and forget to remove this line of code.

Comment (kumar303) [inline src/core/reducers/categories.js]: Maybe add `TODO` in the comment? I've been grepping for those to find temporary code.

File: tests/client/core/reducers/test_categories.js [hunk 2]
```diff
@@ -103,20 +103,27 @@ describe('categories reducer', () => {
     });
 
     it('sets the categories', () => {
+      // Notice all Firefox theme cateories are also set as Android theme
```
Comment (kumar303) [inline tests/client/core/reducers/test_categories.js]: typo: categories

File: tests/client/core/reducers/test_categories.js [hunk 3]
```diff
@@ -126,6 +133,18 @@ describe('categories reducer', () => {
               slug: 'anime',
               type: ADDON_TYPE_THEME,
             },
+            naturé: {
```
Comment (kumar303) [inline tests/client/core/reducers/test_categories.js]: since this entire `ADDON_TYPE_THEME` object is a duplication of the Firefox one, how about pulling it out into a shared constant? I think that will also make the intention of the test case more clear.

File: src/core/reducers/categories.js (hunk 1 above)
Comment (tofumatt) [inline src/core/reducers/categories.js]: 👍  Totally. The more logs the better.

File: tests/client/core/reducers/test_categories.js (hunk 3 above)
Comment (tofumatt) [inline tests/client/core/reducers/test_categories.js]: Good call.
