### PR TITLE
Fix download links (add utm query params)

### LINKED ISSUE #3803: Fix links to Firefox marketing/download on new AMO pages
### Describe the problem and steps to reproduce it:

1. Go here (or really to any addon page) *in Chrome*: https://addons.mozilla.org/en-US/firefox/addon/video-downloadhelper/
2. Hover over the green "Download Firefox" button in the header -- the link is https://mozilla.org/firefox/
3. Hover over the red "download Firefox" message in the page -- the link is https://www.mozilla.org/en-US/firefox/
4. Hover over the "Download Firefox" link in the footer -- the link is https://www.mozilla.org/firefox/new/?utm_source=addons.mozilla.org&utm_campaign=footer&utm_medium=referral

### What happened?

The footer link is correct. Other links are incorrect because...
1. Links shouldn't have l10n on them (we should let the destination site handle l10n routing)
2. Links should have link-specific UTM parameters on them
3. "Download Firefox" links should point at the download page at /firefox/new. 

### What needs to happen?

We should replace the **green header link** with this:

https://www.mozilla.org/firefox/new/?utm_source=addons.mozilla.org&utm_medium=referral&utm_campaign=non-fx-button&utm_content=header-download-button

We should replace the **red in-page link** with this:

https://www.mozilla.org/firefox/new/?utm_source=addons.mozilla.org&utm_medium=referral&utm_campaign=non-fx-button&utm_content=install-addon-button

### PR DESCRIPTION
**Pull request by willdurand**
Fix #3803

---

This PR adds `utm` query parameters to the "download firefox" links.

### CODE REVIEW

File: src/amo/components/AddonCompatibilityError/index.js [hunk 1]
```diff
@@ -37,14 +36,19 @@ export class AddonCompatibilityErrorBase extends React.Component {
...
-      lang,
       log,
       minVersion,
       reason,
       userAgentInfo,
     } = this.props;
-    const downloadUrl = `https://www.mozilla.org/${lang}/firefox/`;
-    let message;
+
+    const queryString = [
```
Comment (tofumatt) [inline src/amo/components/AddonCompatibilityError/index.js]: I'm pretty sure we have an actual `makeQueryParam` helper or something which *might* be nicer just because it already has tests and takes an object as an argument, but this is fine 😄

Comment (willdurand) [reply src/amo/components/AddonCompatibilityError/index.js]: ah, indeed `makeQueryString` it is called 😓  I'll use it!
