### PR TITLE
Fix statsd prefix

### LINKED ISSUE #10213: Add env to statsd prefix
Now that we are not using Datadog anymore, the concept of _tags_ is gone. This
is a problem because our statsd prefix is not unique. With Datadog's tags we
could have data _per_ environment but it's not possible in InfluxDB/Grafana
anymore so we need to make the statsd prefix by adding the environment to it
(similar to what we do in addons-server).

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #10213

### CODE REVIEW

File: src/amo/middleware/responseTime.js [hunk 1]
```diff
@@ -13,7 +13,9 @@ export const responseTime = ({
     const client = new _HotShots({
       host: _config.get('datadogHost'),
       port: _config.get('datadogPort'),
-      prefix: 'addons_frontend.server.',
+      // `NODE_CONFIG_ENV` contains the value of `%{::env}` in ops config
+      // ('dev', 'stage' or 'prod').
+      prefix: `addons-frontend-${process.env.NODE_CONFIG_ENV}.server.`,
```
Comment (eviljeff) [inline src/amo/middleware/responseTime.js:18]: if all the events are `.server`, do we need the `.server`?

**Review by eviljeff — APPROVED** [review]

File: src/amo/middleware/responseTime.js (hunk 1 above)
Comment (willdurand) [reply src/amo/middleware/responseTime.js:18]: Good question, I think we might not have a way to use statsd on the client but we never know so let's keep it as it is now.
