### PR TITLE
I5220-remove-addon/collection 404 fix

### LINKED ISSUE #5220: Page shows 404 when all addons in the second page are deleted
### Describe the problem and steps to reproduce it:
1. Editing a collection (an existing collection)
2. Having more than 25 addons in a collection, so that the pagination shows up.
3. Go to the second page, and delete them all.

### What happened?
It shows `Page not found`. 

### What did you expect to happen?
Ideally, it should be redirected to previous page, page 1 in this case.

vlpebxfoo1

### PR DESCRIPTION
**Pull request by rebmullin**
fixes #5220 

I wanted to check into this approach before I changed any tests. I hope that's okay...

Also, just a note, originally I had a nested try catch inside the catch but I wasn't sure if this was ideal (based on various feedback when I looked into this a bit) plus I saw a few lint issues which are avoided when I do it this way. 

let me know what you think : )

### CODE REVIEW

**Comment by rebmullin** [comment]
Thanks for the feedback @bobsilverberg. I'll take another look into...

**Comment by rebmullin** [comment]
@willdurand @kumar303, I've made some changes (per the first review). When you have some time, please let me know if this is any better : )

File: src/amo/components/Collection/index.js [hunk 1]
```diff
@@ -247,15 +249,36 @@ export class CollectionBase extends React.Component<InternalProps> {
     invariant(slug, 'slug is required');
     invariant(username, 'username is required');
 
+    const { pageSize } = collection;
+    const pages = pageSize ? (collection.numberOfAddons - 1) / pageSize : null;
+    const isNewPage = pages && pages % 1 === 0;
+    const newFilter = (pages && Math.ceil(pages)) || 1;
```
Comment (willdurand) [inline src/amo/components/Collection/index.js]: 3 lines of basic maths, yet I don't understand anything..

I would like to see a helper function above the class with a name explaining what it is supposed to do, and we should not mix `&&` and `||` and ternary operators. I would like to avoid the modulo 1 as well, because this is JS black magic.

File: src/amo/components/Collection/index.js [hunk 2]
```diff
@@ -247,15 +249,36 @@ export class CollectionBase extends React.Component<InternalProps> {
...
+    const filter = isNewPage ? newFilter : filters.page;
```
Comment (willdurand) [inline src/amo/components/Collection/index.js]: why not naming this variable `page`?

File: tests/unit/amo/components/TestCollection.js [hunk 3]
```diff
@@ -1268,6 +1268,66 @@ describe(__filename, () => {
         username: detail.author.username,
       }),
     );
+
+    sinon.assert.notCalled(root.instance().props.history.push);
+  });
+
+  it('set up new filters and a page when removeAddon removes the last addon on the page', () => {
```
Comment (willdurand) [inline tests/unit/amo/components/TestCollection.js]: s/set up new filters/updates the page

File: src/amo/components/Collection/index.js (hunk 1 above)
Comment (rebmullin) [reply src/amo/components/Collection/index.js]: yikes ok : )let me see if I can clarify and clean up a bit

**Comment by rebmullin** [comment]
@willdurand, thanks for feedback. Please let me know if this is any better : )
thanks

File: src/amo/components/Collection/index.js [hunk 4]
```diff
@@ -102,6 +104,24 @@ export type SaveAddonNoteFunc = (
   notes: string,
 ) => void;
 
+// Let's find out what page we'll be on after we remove
+// the item from the collection.
+const getCollectionPage = (collection) => {
```
Comment (willdurand) [inline src/amo/components/Collection/index.js]: Should it be `getPreviousCollectionPage`?

File: src/amo/components/Collection/index.js [hunk 5]
```diff
@@ -102,6 +104,24 @@ export type SaveAddonNoteFunc = (
...
+  const { numberOfAddons, pageSize } = collection;
+
+  if (pageSize) {
+    return (numberOfAddons - 1) / pageSize;
+  }
+
+  return 1;
+};
+
+const switchCollectionPage = (collection) => {
```
Comment (willdurand) [inline src/amo/components/Collection/index.js]: `shouldChangePage` maybe?

File: src/amo/components/Collection/index.js [hunk 6]
```diff
@@ -247,15 +267,38 @@ export class CollectionBase extends React.Component<InternalProps> {
     invariant(slug, 'slug is required');
     invariant(username, 'username is required');
 
+    const isNewPage = switchCollectionPage(collection);
+
+    let page = filters.page;
+
+    if (isNewPage) {
+      page = Math.ceil(getCollectionPage(collection)) || 1;
```
Comment (willdurand) [inline src/amo/components/Collection/index.js]: Why do you need `Math.ceil` here? That should be done in `getCollectionPage`, no?

**Comment by willdurand** [comment]
> Please let me know if this is any better : )

Yeah that looks definitely better!

File: src/amo/components/Collection/index.js (hunk 6 above)
Comment (rebmullin) [reply src/amo/components/Collection/index.js]: I was going to move it up there but then swithcCollectionPage would always return true here so I decided to leave this way. I guess I can make this into another function if that would make it more clear..?

File: src/amo/components/Collection/index.js (hunk 5 above)
Comment (rebmullin) [reply src/amo/components/Collection/index.js]: that works : )

File: src/amo/components/Collection/index.js (hunk 4 above)
Comment (rebmullin) [reply src/amo/components/Collection/index.js]: actually here we are trying to figure out the collection page...
let me think about this..

Comment (rebmullin) [reply src/amo/components/Collection/index.js]: ok I think I am going to combine the ceil func inside this function (as you've suggested/asked about below) and so i've changed things a bit...

regarding this name, I decided to go with getNewCollectionPage as it's only called when its determined that we need to switch the page.

**Comment by rebmullin** [comment]
hey @willdurand, can you please take another look at this one if you have time :)

File: src/amo/components/Collection/index.js [hunk 7]
```diff
@@ -102,6 +104,31 @@ export type SaveAddonNoteFunc = (
...
+  return 1;
+};
+
+const shouldChangePage = (collection) => {
+  const { numberOfAddons, pageSize } = collection;
+
+  let page = 1;
+
+  if (pageSize) {
+    page = (numberOfAddons - 1) / pageSize;
```
Comment (willdurand) [inline src/amo/components/Collection/index.js]: I see that we do that in the function above. Can we do merge the two functions?

```js
export const computeNewCollectionPage = (
  collection: CollectionType,
): number | null => {
  const { numberOfAddons, pageSize } = collection;

  let page = 1;
  if (pageSize) {
    page = (numberOfAddons - 1) / pageSize;
  }

  if (!Number.isInteger(page)) {
    return null;
  }

  return Math.ceil(page) || 1;
};
```

Comment (willdurand) [reply src/amo/components/Collection/index.js]: In which case do we have `page` that is not an integer?

Comment (willdurand) [reply src/amo/components/Collection/index.js]: So, I think we can do this:

```js
export const computeNewCollectionPage = (
  collection: CollectionType,
): number => {
  const { numberOfAddons, pageSize } = collection;

  let page = 1;
  if (pageSize) {
    page = Math.ceil((numberOfAddons - 1) / pageSize);
  }

  return page || 1;
};


```

Comment (willdurand) [reply src/amo/components/Collection/index.js]: and use it like this:

```js
  removeAddon: RemoveCollectionAddonFunc = (addonId: number) => {
    const { collection, dispatch, errorHandler, filters, history } = this.props;

    invariant(collection, 'collection is required');

    const { slug, authorUsername: username } = collection;

    invariant(slug, 'slug is required');
    invariant(username, 'username is required');

    let { page } = filters;
    let shouldPushNewRoute = false;
    const newCollectionPage = computeNewCollectionPage(collection);

    if (page !== newCollectionPage) {
      page = newCollectionPage;
      shouldPushNewRoute = true;
    }

    dispatch(
      removeAddonFromCollection({
        addonId,
        errorHandlerId: errorHandler.id,
        filters: {
          ...filters,
          page,
        },
        slug,
        username,
      }),
    );

    if (shouldPushNewRoute) {
      const { location } = history;

      history.push({
        pathname: location.pathname,
        query: {
          ...location.query,
          page,
        },
      });
    }
  };

```

What do you think? That would prevent a push to happen for no reason, and also make the code more understandable, no?

File: tests/unit/amo/components/TestCollection.js [hunk 8]
```diff
@@ -1268,6 +1268,66 @@ describe(__filename, () => {
         username: detail.author.username,
       }),
     );
+
+    sinon.assert.notCalled(root.instance().props.history.push);
+  });
+
+  it('updates the page when removeAddon removes the last addon on the page', () => {
+    const history = createFakeHistory();
```
Comment (willdurand) [inline tests/unit/amo/components/TestCollection.js]: You probably want to use it, you should pass it a `location` that is created a few lines after:

``` js
const location = createFakeLocation({ query: { page, collection_sort: sort } });
const history = createFakeHistory({ location });
```

Then you can pass both `location` and `history` and use the latter in `assert.test.calledWith(histor.push, ...)`.

File: tests/unit/amo/components/TestCollection.js [hunk 9]
```diff
@@ -1268,6 +1268,66 @@ describe(__filename, () => {
...
+    const authorUserId = 11;
+    const { store } = dispatchSignInActions({ userId: authorUserId });
+
+    const addons = createFakeCollectionAddons();
+    const addonId = addons[0].addon.id;
+    const detail = createFakeCollectionDetail({
+      authorId: authorUserId,
+      // This will simulate only 1 item on the 2nd page.
+      count: DEFAULT_API_PAGE_SIZE + 1,
```
Comment (willdurand) [inline tests/unit/amo/components/TestCollection.js]: We probably need a test with `DEFAULT_API_PAGE_SIZE + 2`.

File: tests/unit/amo/components/TestCollection.js [hunk 10]
```diff
@@ -1268,6 +1268,66 @@ describe(__filename, () => {
...
+      location: createFakeLocation({ query: { page, collection_sort: sort } }),
+      store,
+    });
+
+    fakeDispatch.resetHistory();
+
+    // This simulates the user clicking the "Remove" button on the
+    // EditableCollectionAddon component.
+    root.instance().removeAddon(addonId);
+    sinon.assert.callCount(fakeDispatch, 1);
```
Comment (kumar303) [inline tests/unit/amo/components/TestCollection.js]: I prefer to see `assert.calledWith` come before `assert.callCount` because `calledWith` will give a better error message on a failure.

File: tests/unit/amo/components/TestCollection.js (hunk 8 above)
Comment (kumar303) [inline tests/unit/amo/components/TestCollection.js]: You should pass this to `renderComponent()` to make the test more robust. In other words, you want to keep it in sync with your assertion.

File: tests/unit/amo/components/TestCollection.js [hunk 11]
```diff
@@ -1268,6 +1268,66 @@ describe(__filename, () => {
...
+      removeAddonFromCollection({
+        addonId,
+        errorHandlerId: errorHandler.id,
+        filters: { page: 1, collectionSort: sort },
+        slug: detail.slug,
+        username: detail.author.username,
+      }),
+    );
+
+    sinon.assert.calledWith(root.instance().props.history.push, {
```
Comment (kumar303) [inline tests/unit/amo/components/TestCollection.js]: After passing `history` to `renderComponent`, I think you could make this `sinon.assert.calledWith(history.push, ...)`

File: src/amo/components/Collection/index.js (hunk 7 above)
Comment (rebmullin) [reply src/amo/components/Collection/index.js]: unless I a missing something, the only difference I really see is this piece:

```javascript
  let { page } = filters;

    if (isNewPage) {
      page = getNewCollectionPage(collection);
    }
...
```

As far as pushing the page, I was already doing that - only pushing if isNewPage was true but I agree your names make it a little clearer

Comment (willdurand) [reply src/amo/components/Collection/index.js]: Exactly! You did the hard work by finding the issue and the patch to fix it. I just made it a bit more readable because I really had troubles understanding it.

File: tests/unit/amo/components/TestCollection.js (hunk 9 above)
Comment (rebmullin) [reply tests/unit/amo/components/TestCollection.js]: I thought about this but the original case I guess assumes and does this really. Maybe it would be okay to just update that case to include this info so it's clear?

File: tests/unit/amo/components/TestCollection.js (hunk 11 above)
Comment (rebmullin) [reply tests/unit/amo/components/TestCollection.js]: yeh works, thanks!

File: src/amo/components/Collection/index.js (hunk 7 above)
Comment (rebmullin) [reply src/amo/components/Collection/index.js]: and my comments too : )

File: tests/unit/amo/components/TestCollection.js (hunk 9 above)
Comment (willdurand) [reply tests/unit/amo/components/TestCollection.js]: That should probably be covered to distinguish the happy path (page = 1).

**Comment by rebmullin** [comment]
hey @willdurand, how's it look now?

File: tests/unit/amo/components/TestCollection.js [hunk 12]
```diff
@@ -1234,8 +1234,12 @@ describe(__filename, () => {
     });
     const errorHandler = createStubErrorHandler();
     const fakeDispatch = sinon.spy(store, 'dispatch');
-    const page = 123;
+    const page = 5;
```
Comment (willdurand) [inline tests/unit/amo/components/TestCollection.js]: 😄 I noticed this one too. Do we know why it is evaluated to 5?

File: tests/unit/amo/components/TestCollection.js [hunk 13]
```diff
@@ -1257,7 +1262,61 @@ describe(__filename, () => {
     // This simulates the user clicking the "Remove" button on the
     // EditableCollectionAddon component.
     root.instance().removeAddon(addonId);
+    sinon.assert.calledWith(
+      fakeDispatch,
+      removeAddonFromCollection({
+        addonId,
+        errorHandlerId: errorHandler.id,
+        filters: { page: 5, collectionSort: sort },
```
Comment (willdurand) [inline tests/unit/amo/components/TestCollection.js]: It is probably fine to have `page`, it has been assigned to `5` above.

File: tests/unit/amo/components/TestCollection.js (hunk 12 above)
Comment (rebmullin) [reply tests/unit/amo/components/TestCollection.js]: yes : )

should i show the math here? basically it should be ~ numberofaddons / pageSize

Comment (willdurand) [reply tests/unit/amo/components/TestCollection.js]: Looking at the helper functions, we don't really create 5*25 add-ons in the collection, hence my surprise. I think it is because `count = 123` in a helper function. Is that the reason?

Comment (rebmullin) [reply tests/unit/amo/components/TestCollection.js]: yeh, the count comes from 123 - from the helper function. Now that we have updated the logic to check if the page != newCollectionPage, it needs to be the correct page number here otherwise we won't get the expected results.

I could either change the count or the page to do this and went with the page...

I am not totally clear of your question maybe, so let me know if that helps

Comment (willdurand) [reply tests/unit/amo/components/TestCollection.js]: Can we fix the `count` value to be more realistic?

Comment (rebmullin) [reply tests/unit/amo/components/TestCollection.js]: Sure

File: tests/unit/amo/helpers.js [hunk 14]
```diff
@@ -347,7 +347,7 @@ export function dispatchAutocompleteResults({
 
 export const createFakeCollectionDetail = ({
   name = 'My Addons',
-  count = 123,
+  count = 30,
```
Comment (willdurand) [inline tests/unit/amo/helpers.js]: That will likely break other tests. I think we should override `count` in `createFakeCollectionDetail()`, just for this test case.

Comment (rebmullin) [reply tests/unit/amo/helpers.js]: oh ok sure..

File: tests/unit/amo/components/TestCollection.js [hunk 15]
```diff
@@ -1231,11 +1231,16 @@ describe(__filename, () => {
     const addonId = addons[0].addon.id;
     const detail = createFakeCollectionDetail({
       authorId: authorUserId,
+      count: 30,
```
Comment (willdurand) [inline tests/unit/amo/components/TestCollection.js]: I'd add a comment saying that we pretend there are > 25 addons so that we are on page 2.

Comment (rebmullin) [reply tests/unit/amo/components/TestCollection.js]: what about doing something like this: 

```javascript
 // This will simulate a few items on the 2nd page.
 count: DEFAULT_API_PAGE_SIZE + 2,
```

Comment (willdurand) [reply tests/unit/amo/components/TestCollection.js]: Yes!

Comment (rebmullin) [reply tests/unit/amo/components/TestCollection.js]: lol..

but I just realized this is actually identical to the test I have below now. I I guess I can remove this

**Comment by rebmullin** [comment]
thanks for the review everyone : )
