### PR TITLE
I6236 Update AddonReviewManager to use RatingManagerNotification 

### LINKED ISSUE #6236: Update AddonReviewManager to use RatingManagerNotification
**For QA**: please check for regressions in the *Saving* / *Saved* notifications that are shown when you update a rating or review.

`RatingManagerNotification` was introduced via https://github.com/mozilla/addons-frontend/pull/6213, and while it's currently being used by `RatingManager` it should also be used by `AddonReviewManager`. It can be used to replace the code at https://github.com/mozilla/addons-frontend/blob/2018.09.13/src/amo/components/AddonReviewManager/index.js#L101-L111

### PR DESCRIPTION
**Pull request by mirefly**
Fixes #6236

### CODE REVIEW

File: tests/unit/amo/components/TestAddonReviewManager.js [hunk 1]
```diff
@@ -216,11 +217,10 @@ describe(__filename, () => {
 
     const root = render({ store });
 
-    const message = root.find('.AddonReviewManager-savedRating');
-    expect(message).toHaveText('Saving');
-    expect(message).not.toHaveClassName(
-      '.AddonReviewManager-savedRating-hidden',
-    );
+    const message = root.find(RatingManagerNotice);
```
Comment (willdurand) [inline tests/unit/amo/components/TestAddonReviewManager.js]: Shouldn't this be `notice` instead?

File: tests/unit/amo/components/TestAddonReviewManager.js [hunk 2]
```diff
@@ -216,11 +217,10 @@ describe(__filename, () => {
...
+    expect(message).toHaveProp('message', 'Saving');
+    expect(message).toHaveProp('hideMessage', false);
+    expect(message).not.toHaveProp('type');
```
Comment (willdurand) [inline tests/unit/amo/components/TestAddonReviewManager.js]: I don't think we need this assertion, do we?

File: tests/unit/amo/components/TestAddonReviewManager.js [hunk 3]
```diff
@@ -229,11 +229,10 @@ describe(__filename, () => {
 
     const root = render({ store });
 
-    const message = root.find('.AddonReviewManager-savedRating');
-    expect(message).toHaveText('Saved');
-    expect(message).not.toHaveClassName(
-      '.AddonReviewManager-savedRating-hidden',
-    );
+    const message = root.find(RatingManagerNotice);
```
Comment (willdurand) [inline tests/unit/amo/components/TestAddonReviewManager.js]: Shouldn't this be `notice` instead?

File: tests/unit/amo/components/TestAddonReviewManager.js [hunk 4]
```diff
@@ -229,11 +229,10 @@ describe(__filename, () => {
...
+    expect(message).toHaveProp('message', 'Saved');
+    expect(message).toHaveProp('hideMessage', false);
+    expect(message).not.toHaveProp('type');
```
Comment (willdurand) [inline tests/unit/amo/components/TestAddonReviewManager.js]: I don't think we need this assertion.

File: tests/unit/amo/components/TestAddonReviewManager.js [hunk 5]
```diff
@@ -244,8 +243,8 @@ describe(__filename, () => {
 
     const root = render({ store });
 
-    const message = root.find('.AddonReviewManager-savedRating');
-    expect(message).toHaveClassName('.AddonReviewManager-savedRating-hidden');
+    const message = root.find(RatingManagerNotice);
```
Comment (willdurand) [inline tests/unit/amo/components/TestAddonReviewManager.js]: Shouldn't this be `notice` instead?

**Comment by willdurand** [comment]
Thanks!
