### PR TITLE
Redirect invalid locales

### LINKED ISSUE #531: When the locale is wrong we don't currently redirect
When a locale is wrong we fallback to en-US however we should also redirect to that URL.

Here's an example:

https://discovery.addons-dev.allizom.org/whatevs/firefox/discovery/pane/46.0.1/Darwin/normal

Should redirect to:

https://discovery.addons-dev.allizom.org/en-US/firefox/discovery/pane/46.0.1/Darwin/normal

### PR DESCRIPTION
**Pull request by muffinresearch**
Fixes #531

### CODE REVIEW

**Comment by mstriemer** [comment]
Can you add a test with something like `/invalid/firefox/discovery/pane/48.0/Darwin/normal?lang=firefox`? I think it will pass out of the box but if the precedence of params/query changes it would fail.

File: src/core/server/base.js [hunk 1]
```diff
@@ -112,6 +112,14 @@ function baseServer(routes, createStore, { appInstanceName = appName } = {}) {
       ) : {};
 
       const lang = getLangFromRouter(renderProps);
+
+      if (renderProps.params && renderProps.params.lang) {
+        const origLang = renderProps.params.lang;
+        if (lang !== origLang) {
+          return res.redirect(301, req.originalUrl.replace(encodeURI(origLang), lang));
```
Comment (mstriemer) [inline src/core/server/base.js]: I'm not crazy about using replace. I feel like it might be better to explicitly replace the first part of the URL but I can't think of a great way of doing that. Splitting would be a bit gross but should work.

**Comment by mstriemer** [comment]
r+wc

File: src/core/server/base.js [hunk 2]
```diff
@@ -112,6 +112,22 @@ function baseServer(routes, createStore, { appInstanceName = appName } = {}) {
       ) : {};
 
       const lang = getLangFromRouter(renderProps);
+
+      if (renderProps.params && renderProps.params.lang) {
+        const origLang = renderProps.params.lang;
+        if (lang !== origLang) {
+          // Remove the first slash and split on the /
+          const urlParts = req.originalUrl.replace(/^\//, '').split('/');
```
Comment (mstriemer) [inline src/core/server/base.js]: I think you can destructure here, unless something weird happens because of node. Either way you shouldn't need to pop off that first slash, and increment the indexes by 1.

```js
const [ _, origLang, ...rest ] = url.split('/');
res.redirect(301, ['', lang, ...rest].join('/'))

**Comment by mstriemer** [comment]
r+wc

File: src/core/server/base.js (hunk 2 above)
Comment (muffinresearch) [inline src/core/server/base.js]: Nice - idea. Thanks!
