### PR TITLE
Avoid encoding the slug twice on the client

### LINKED ISSUE #3138: Cannot load an add-on on the client side but it works on the server
I have found this add-on "project-ă-ă-â-â-日本語" in dev: https://addons-dev.allizom.org/en-US/firefox/addon/project-%C4%83-%C4%83-%C3%A2-%C3%A2-%E6%97%A5%E6%9C%AC%E8%AA%9E/. You can, maybe, find it with [this search](https://addons-dev.allizom.org/en-US/firefox/search/?q=project&type=extension).

It does not load when you click on it in the search results, but it works when you load it from the server (page refresh for instance). I suspect an encoding issue because the `callApi` throws an error.

<details>
<summary>error log</summary>

```
user.js:18 [amo] Failed to load add-on with slug project-ă-ă-â-â-日本語: Error: Error calling: /api/v3/addons/addon/project-Ä-Ä-Ã¢-Ã¢-æ¥æ¬èª/ (status: 404)
(anonymous) @ user.js:18
r @ runtime.js:246
(anonymous) @ runtime.js:608
e.(anonymous function) @ runtime.js:463
h @ proc.js:633
n @ proc.js:185
(anonymous) @ proc.js:738
Promise (async)
(anonymous) @ amo-a02c4ad….js:3070
Promise (async)
(anonymous) @ raven.js:1394
a @ amo-a02c4ad….js:3070
u @ Link.js:30
x @ proc.js:1
_ @ proc.js:720
h @ proc.js:654
n @ proc.js:185
j @ moment.js:94
_ @ proc.js:724
h @ proc.js:654
n @ proc.js:185
(anonymous) @ proc.js:1
r @ proc.js:418
u @ proc.js:425
o @ proc.js:422
(anonymous) @ EventPluginHub.js:46
t @ EventPropagators.js:26
(anonymous) @ reviews.js:63
value @ index.js:287
performInitialMount @ ReactCompositeComponent.js:744
mountComponent @ ReactCompositeComponent.js:650
mountComponent @ PatternUtils.js:211
performInitialMount @ ReactCompositeComponent.js:762
mountComponent @ ReactCompositeComponent.js:650
mountComponent @ PatternUtils.js:211
performInitialMount @ ReactCompositeComponent.js:762
mountComponent @ ReactCompositeComponent.js:650
mountComponent @ PatternUtils.js:211
performInitialMount @ ReactCompositeComponent.js:762
mountComponent @ ReactCompositeComponent.js:650
mountComponent @ PatternUtils.js:211
performInitialMount @ ReactCompositeComponent.js:762
mountComponent @ ReactCompositeComponent.js:650
mountComponent @ PatternUtils.js:211
performInitialMount @ ReactCompositeComponent.js:762
mountComponent @ ReactCompositeComponent.js:650
mountComponent @ PatternUtils.js:211
_updateRenderedComponent @ ReactDOMEmptyComponent.js:52
_performComponentUpdate @ ReactDOMEmptyComponent.js:22
updateComponent @ ReactServerUpdateQueue.js:14
receiveComponent @ getIteratorFn.js:16
receiveComponent @ _getNative.js:12
_updateRenderedComponent @ ReactDOMEmptyComponent.js:34
_performComponentUpdate @ ReactDOMEmptyComponent.js:22
updateComponent @ ReactServerUpdateQueue.js:14
receiveComponent @ getIteratorFn.js:16
receiveComponent @ _getNative.js:12
updateChildren @ ReactCompositeComponent.js:393
_reconcilerUpdateChildren @ ReactCompositeComponent.js:176
_updateChildren @ ReactCompositeComponent.js:255
updateChildren @ ReactCompositeComponent.js:249
_updateDOMChildren @ ReactDOMInput.js:39
updateComponent @ amo-a02c4ad….js:52898
receiveComponent @ CSSPropertyOperations.js:184
receiveComponent @ _getNative.js:12
updateChildren @ ReactCompositeComponent.js:393
_reconcilerUpdateChildren @ ReactCompositeComponent.js:176
_updateChildren @ ReactCompositeComponent.js:255
updateChildren @ ReactCompositeComponent.js:249
_updateDOMChildren @ ReactDOMInput.js:39
updateComponent @ amo-a02c4ad….js:52898
receiveComponent @ CSSPropertyOperations.js:184
receiveComponent @ _getNative.js:12
updateChildren @ ReactCompositeComponent.js:393
_reconcilerUpdateChildren @ ReactCompositeComponent.js:176
_updateChildren @ ReactCompositeComponent.js:255
updateChildren @ ReactCompositeComponent.js:249
_updateDOMChildren @ ReactDOMInput.js:39
updateComponent @ amo-a02c4ad….js:52898
receiveComponent @ CSSPropertyOperations.js:184
receiveComponent @ _getNative.js:12
_updateRenderedComponent @ ReactDOMEmptyComponent.js:34
_performComponentUpdate @ ReactDOMEmptyComponent.js:22
updateComponent @ ReactServerUpdateQueue.js:14
receiveComponent @ getIteratorFn.js:16
receiveComponent @ _getNative.js:12
_updateRenderedComponent @ ReactDOMEmptyComponent.js:34
_performComponentUpdate @ ReactDOMEmptyComponent.js:22
updateComponent @ ReactServerUpdateQueue.js:14
receiveComponent @ getIteratorFn.js:16
receiveComponent @ _getNative.js:12
_updateRenderedComponent @ ReactDOMEmptyComponent.js:34
_performComponentUpdate @ ReactDOMEmptyComponent.js:22
updateComponent @ ReactServerUpdateQueue.js:14
receiveComponent @ getIteratorFn.js:16
receiveComponent @ _getNative.js:12
_updateRenderedComponent @ ReactDOMEmptyComponent.js:34
_performComponentUpdate @ ReactDOMEmptyComponent.js:22
updateComponent @ ReactServerUpdateQueue.js:14
receiveComponent @ getIteratorFn.js:16
receiveComponent @ _getNative.js:12
_updateRenderedComponent @ ReactDOMEmptyComponent.js:34
_performComponentUpdate @ ReactDOMEmptyComponent.js:22
updateComponent @ ReactServerUpdateQueue.js:14
receiveComponent @ getIteratorFn.js:16
receiveComponent @ _getNative.js:12
_updateRenderedComponent @ ReactDOMEmptyComponent.js:34
_performComponentUpdate @ ReactDOMEmptyComponent.js:22
updateComponent @ ReactServerUpdateQueue.js:14
performUpdateIfNecessary @ flattenChildren.js:61
performUpdateIfNecessary @ index.js:8
u @ _typed-array.js:158
perform @ ReactBrowserEventEmitter.js:121
perform @ ReactBrowserEventEmitter.js:121
perform @ _typed-array.js:202
x @ _typed-array.js:217
closeAll @ ReactBrowserEventEmitter.js:146
perform @ ReactBrowserEventEmitter.js:124
batchedUpdates @ ReactDOMSelection.js:105
s @ _typed-array.js:166
r @ DOMUtils.js:49
enqueueSetState @ amo-a02c4ad….js:16168
r.setState @ inputValueTracking.js:95
(anonymous) @ ScrollBehaviorContext.js:66
amo-a02c4ad….js:98260 [amo] Extracting messages from error object: Error: Error calling: /api/v3/addons/addon/project-Ä-Ä-Ã¢-Ã¢-æ¥æ¬èª/ (status: 404)
    at i (amo-a02c4ad….js:3104)
    at amo-a02c4ad….js:3110
    at <anonymous>
```

</details>

### PR DESCRIPTION
**Pull request by willdurand**
Fix #3138

---

This PR prevents the client to call the API with URLs encoded twice. Encoding should only be forced on the server, see #1920.

### CODE REVIEW

File: src/core/api/index.js [hunk 1]
```diff
@@ -73,6 +73,7 @@ type CallApiParams = {|
   params?: Object,
   schema?: Object,
   state?: ApiStateType,
+  _config?: config,
```
Comment (kumar303) [inline src/core/api/index.js]: It doesn't matter too much since the result will be `Object` but this should be `_config?: typeof config`. You didn't get an error because the test files do not opt into Flow.

File: tests/unit/core/api/test_index.js [hunk 2]
```diff
@@ -41,7 +41,28 @@ describe(__filename, () => {
...
+        .once()
+        .returns(createApiResponse());
+
+      // We use `cloneDeep()` to allow modifications on the `config` object,
+      // since a call to `get()` makes it immutable.
+      const clientConfig = configUtil.cloneDeep(config);
+      clientConfig.client = true;
+      clientConfig.server = false;
+
+      return api.callApi({
```
Comment (kumar303) [inline tests/unit/core/api/test_index.js]: Does this test fail without your patch? I can't think of how it would. I think you won't really be able to make it fail since our tests run in NodeJS, not the browser. Thus, I think you should just make an assertion about not encoding the query string in the client. This isn't the greatest test but it at least solidifies the *intention* of the code. You can use a stub for that:

```js
const fakeUtf8Encode = sinon.stub();

return api.callApi({
  _config: clientConfig,
  _utf8: { encode: fakeUtf8Encode },
  endpoint,
})
  .then(() => mockWindow.verify())
  .then(() => {
    sinon.assert.notCalled(fakeUtf8Encode);
  });
```

Comment (kumar303) [reply tests/unit/core/api/test_index.js]: I'd say you do not need to do the inverse for the server-behavior test because in that case you *will* be able to reproduce the failure.

Comment (willdurand) [reply tests/unit/core/api/test_index.js]: Well it fails actually:

```
  ● /Users/william/projects/mozilla/addons-frontend/tests/unit/core/api/test_index.js › core.callApi › does not encode non-ascii URLs in UTF8 on the client

    ExpectationError: Unexpected call: fetch(https://localhost/api/v3/project-Ä-Ä-Ã¢-Ã¢-æ¥æ¬èª/, { body: undefined, credentials: undefined, headers: {  }, method: "GET" })
        Expected fetch(https://localhost/api/v3/project-ă-ă-â-â-日本語/, { body: undefined, credentials: undefined, headers: {  }, method: "GET" }[, ...]) once (never called)
```

**Comment by willdurand** [comment]
So I pushed a commit that reverts the patch to prove the bug with the test case I have added (linter also fails because I did not remove the `_config` argument, but it is meaningless). The output can be seen at: https://api.travis-ci.org/jobs/275773415/log.txt?deansi=true.

```
Summary of all failing tests
 FAIL  tests/unit/core/api/test_index.js
  ● /home/travis/build/mozilla/addons-frontend/tests/unit/core/api/test_index.js › core.callApi › does not encode non-ascii URLs in UTF8 on the client

    ExpectationError: Unexpected call: fetch(https://localhost/api/v3/project-Ä-Ä-Ã¢-Ã¢-æ¥æ¬èª/, { body: undefined, credentials: undefined, headers: {  }, method: "GET" })
        Expected fetch(https://localhost/api/v3/project-ă-ă-â-â-日本語/, { body: undefined, credentials: undefined, headers: {  }, method: "GET" }[, ...]) once (never called)
      
      at Object.fail (node_modules/sinon/lib/sinon/mock-expectation.js:281:25)
      at Object.invokeMethod (node_modules/sinon/lib/sinon/mock.js:172:25)
      at node_modules/sinon/lib/sinon/mock.js:66:35
      at Object.callApi (src/core/api/index.js:250:59)
      at Object.<anonymous> (tests/unit/core/api/test_index.js:59:18)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
```

Re-adding the patch makes the test pass.

**Comment by willdurand** [comment]
Seeing this in the logs without patch and for slug `project-ă-ă-â-â-日本語`:

```
[1] [2017-09-15T07:53:39.053Z]  INFO: server/41977 on MBP.local: First component render to dispatch loading actions (app=amo)
[2] [2017-09-15T07:53:39.724Z]  INFO: proxy/41972 on MBP.local: 200 ~> https://addons-dev.allizom.org/api/v3/accounts/profile/ (app=amo)
[2] [2017-09-15T07:53:39.779Z]  INFO: proxy/41972 on MBP.local: 200 ~> https://addons-dev.allizom.org/api/v3/addons/addon/project-Ä-Ä-Ã¢-Ã¢-æ¥æ¬èª/?lang=en-US (app=amo)
[1] [2017-09-15T07:53:39.788Z]  INFO: server/41977 on MBP.local: Second component render after sagas have finished (app=amo)
```

File: tests/unit/core/api/test_index.js (hunk 2 above)
Comment (kumar303) [reply tests/unit/core/api/test_index.js]: ok, duh. I see. It fails without your patch because the old code was doing the UTF8 encoding. Alright, this test is good. There is no need to introduce a new stub for the utf8 encoder.

**Comment by kumar303** [comment]
> Could it be possible that node is not broken but node-fetch actually is?

Yes, that's exactly the problem. This is the bug: https://github.com/bitinn/node-fetch/issues/245

I was actually slightly confused about what's going on so I made this quick `server.py` script:

```python
import urllib
from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer

class RequestHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        path = urllib.unquote(self.path)
        print u'** path (Byte string): {}'.format(repr(path))
        print u'** path (UTF8 decoded): {}'.format(path.decode('utf8', 'replace'))
        self.send_response(200)
        self.send_header('Content-type', 'text')
        self.end_headers()
        self.wfile.write("Response from server.py")

httpd = HTTPServer(('', 9001), RequestHandler)
print 'Starting server at http://localhost:9001 ...'
httpd.serve_forever()
```

When running it, you can do this in a node shell:

```
> const fetch = require('node-fetch');
undefined
> fetch('http://localhost:9001/project-ă-ă-â-â-日本語');
```

You can do the same thing in a browser console and see the difference in the request log. The browser `fetch()` requests the correct URL, the `node-fetch` call does not.

File: tests/unit/core/api/test_index.js [hunk 3]
```diff
@@ -41,15 +41,45 @@ describe(__filename, () => {
...
       const endpoint = 'diccionario-español-venezuela';
       mockWindow.expects('fetch')
         .withArgs(utf8.encode(`${apiHost}/api/v3/${endpoint}/`), {
           body: undefined, credentials: undefined, method: 'GET', headers: {},
         })
         .once()
         .returns(createApiResponse());
-      return api.callApi({ endpoint }).then(() => mockWindow.verify());
+
+      // We use `cloneDeep()` to allow modifications on the `config` object,
```
Comment (kumar303) [inline tests/unit/core/api/test_index.js]: I don't think it's really necessary to keep putting this comment everywhere. It doesn't hurt though.

**Comment by willdurand** [comment]
Thanks for the python script, quite handy to know what was going on!
