### PR TITLE
Fix problem with static files for local development

### LINKED ISSUE #10978: statics aren't loading in local (docker) env
For frontend running within addons-server's docker containers the static assets (javascript, fonts, images, css) aren't loading correctly.  Whichever service is supposed to serve those urls isn't doing it, so they're being redirected to `/<locale>/app/` like any other random addons url would be (and then 404'ing).

It's not clear where the change needs to be made (could be in this repo, or addons-server, or addons-nginx) so move when the fix it identified.

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #10978 

This fixes the problem locally, but I'm not sure if it also fixes the problem when running the code inside the docker container.

### CODE REVIEW

File: config/development-local.js [hunk 1]
```diff
@@ -1,4 +1,6 @@
-import { staticPath } from './lib/shared';
+const webpackServerHost = process.env.WEBPACK_SERVER_HOST || '127.0.0.1';
+const webpackServerPort = 7001;
```
Comment (willdurand) [inline config/development-local.js:2]:
```suggestion
const webpackServerPort = process.env.WEBPACK_SERVER_PORT || 7001;
```

File: config/development-local.js [hunk 2]
```diff
@@ -9,15 +11,15 @@ module.exports = {
 
   baseURL: 'http://olympia.test',
 
-  webpackServerPort: 7001,
+  webpackServerHost,
```
Comment (willdurand) [inline config/development-local.js:14]:
```suggestion
  // We need this config variables for `bin/webpack-dev-server.js`.
  webpackServerHost,
```

**Review by willdurand — CHANGES_REQUESTED** [review]
I made two suggestions, the first one being required to fully fix the issue referenced in the PR description. The other one is because I keep forgetting about why we need those webpack config vars.

**Comment by willdurand** [comment]
I noticed that we could do some more clean-ups and simplify our config files, so here is a new diff (sorry):

```diff
diff --git a/bin/webpack-dev-server.js b/bin/webpack-dev-server.js
index f949651e4..78748a075 100644
--- a/bin/webpack-dev-server.js
+++ b/bin/webpack-dev-server.js
@@ -13,7 +13,6 @@ const webpackHotMiddleware = require('webpack-hot-middleware');
 
 const webpackDevConfig = require('../webpack.dev.config.babel').default;
 
-const host = config.get('webpackServerHost');
 const port = config.get('webpackServerPort');
 
 const compiler = webpack(webpackDevConfig);
@@ -42,6 +41,6 @@ server.listen(port, (err) => {
   if (err) {
     console.error(err);
   } else {
-    console.info(`🚧  Webpack development server listening on host: ${host} port: ${port}`);
+    console.info(`🚧  Webpack development server listening on port: ${port}`);
   }
 });
diff --git a/config/custom-environment-variables.json b/config/custom-environment-variables.json
index 5206efb0c..abe14e264 100644
--- a/config/custom-environment-variables.json
+++ b/config/custom-environment-variables.json
@@ -9,7 +9,5 @@
   "proxyPort": "PROXY_PORT",
   "serverHost": "SERVER_HOST",
   "serverPort": "SERVER_PORT",
-  "trackingEnabled": "TRACKING_ENABLED",
-  "webpackServerHost": "WEBPACK_SERVER_HOST",
-  "webpackServerPort": "WEBPACK_SERVER_PORT"
+  "trackingEnabled": "TRACKING_ENABLED"
 }
diff --git a/config/default.js b/config/default.js
index bb8824d68..6bc74df63 100644
--- a/config/default.js
+++ b/config/default.js
@@ -320,7 +320,8 @@ module.exports = {
     'robots.txt',
     'services',
     'sitemap.xml',
-    'static',
+    'static-frontend',
+    'static-server',
     'user-media',
   ],
 
@@ -352,7 +353,8 @@ module.exports = {
     'robots.txt',
     'services',
     'sitemap.xml',
-    'static',
+    'static-frontend',
+    'static-server',
     'statistics',
     'user-media',
   ],
diff --git a/config/development-local.js b/config/development-local.js
index a2e9f444d..b33727ad2 100644
--- a/config/development-local.js
+++ b/config/development-local.js
@@ -1,6 +1,12 @@
 import { staticPath } from './lib/shared';
 
-// This config should be used with a local addons-server setup.
+// This config should be used with a local addons-server setup, i.e. run
+// addons-server locally (docker env) and use `yarn amo:olympia` in this
+// project to allow the frontend to talk to the addons-server API.
+//
+// This configuration is also used by the `addons-frontend` container in
+// addons-server's docker stack, with some configuration values changed by
+// using environment variables.
 module.exports = {
   apiHost: 'http://olympia.test',
   proxyPort: 7000,
@@ -9,15 +15,9 @@ module.exports = {
 
   baseURL: 'http://olympia.test',
 
-  webpackServerPort: 7001,
-
   mozillaUserId: 10968,
-  CSP: false,
 
-  // `config/development.js` overrides the static path to use
-  // webpack-dev-server but we don't want that for this environment.
-  staticPath,
-  enableNodeStatics: true,
+  CSP: false,
 
   // See: https://github.com/mozilla/addons-frontend/issues/10545
   enableTrailingSlashesMiddleware: false,
diff --git a/config/development.js b/config/development.js
index e100f2325..218fc463a 100644
--- a/config/development.js
+++ b/config/development.js
@@ -2,7 +2,7 @@
 import { baseUrlDev, analyticsHost, apiDevHost } from './lib/shared';
 
 const webpackServerHost = process.env.WEBPACK_SERVER_HOST || '127.0.0.1';
-const webpackServerPort = 3001;
+const webpackServerPort = process.env.WEBPACK_SERVER_PORT || 3001;
 const webpackDevServer = `${webpackServerHost}:${webpackServerPort}`;
 
 module.exports = {
@@ -34,7 +34,8 @@ module.exports = {
   enableStrictMode: true,
 
   serverPort: 3333,
-  webpackServerHost,
+
+  // We need this config variable for `bin/webpack-dev-server.js`.
   webpackServerPort,
 
   // In local dev, we serve static files using webpack-dev-server.
diff --git a/package.json b/package.json
index 60b417f50..0a31199fd 100644
--- a/package.json
+++ b/package.json
@@ -64,7 +64,8 @@
     "amo:olympia": {
       "command": "better-npm-run start-dev-proxy",
       "env": {
-        "NODE_APP_INSTANCE": "local"
+        "NODE_APP_INSTANCE": "local",
+        "WEBPACK_SERVER_HOST": "olympia.test"
       }
     },
     "amo:dev": {
```

File: config/development-local.js [hunk 3]
```diff
@@ -1,4 +1,6 @@
-import { staticPath } from './lib/shared';
+const webpackServerHost = process.env.WEBPACK_SERVER_HOST || '127.0.0.1';
+const webpackServerPort = 7001;
+const webpackDevServer = `${webpackServerHost}:${webpackServerPort}`;
```
Comment (eviljeff) [inline config/development-local.js:3]: why do we define these up here, separately, rather than directly within `module.exports`? default.js (or stage.js, etc) don't do it this way.

Comment (willdurand) [reply config/development-local.js:3]: because it is used in two places in the exported config (first as a config var, then as part of another config var)

**Comment by bobsilverberg** [comment]
I applied the changes and can confirm that it now appears to work for both `yarn amo:olympia` and also when running frontend from the docker container. Thanks @willdurand!

**Review by willdurand — APPROVED** [review]
