### PR TITLE
Switch to a logged out state when auth tokens expire

### LINKED ISSUE #2237: Anticipate expiring auth tokens and switch to a logged out state
### Describe the problem and steps to reproduce it:

Open a page on AMO, let your auth token expire (see https://github.com/mozilla/addons-frontend/issues/2130), and try to do something requiring auth like submit a star rating. 

### What happened?

You see an error like this:
screenshot 2017-04-04 17 27 50

### What did you expect to happen?

The frontend code should anticipate the time at which the token will expire and change the UI to a logged out state. It might be nice to show a message saying "you have been logged out" but at the very least everything will make more sense in a logged out state.

### PR DESCRIPTION
**Pull request by kumar303**
Fixes #2237 

This handles the case when a user's auth token expires while they are using the app. Previously in https://github.com/mozilla/addons-frontend/issues/2238 the solution was to show an error and prompt the user to reload the page (note that due to obscure race conditions, this is still possible). 

In this patch, the user will be logged out automatically when the token expires.

Here are some scenarios to give you an example of what that will feel like:

## A happy-ish scenario
- Log in, load an add-on detail page
- Allow time to lapse so that your auth token expires
- Instead of seeing stars for rating, you will suddenly see the *Log in to rate this add-on* button

## A sad scenario
- Log in, load an add-on detail page
- Select a star rating
- Begin entering a text review
- As you are typing, be unfortunate enough to have your auth token expire
- You will now lose everything you typed and you will see the *Log in to rate this add-on* button

The sad scenario is sad but keep in mind that without this patch, the user will not be able to submit the review anyway. 

If that sounds okay, we could move forward with this patch and do a follow-up patch that will add a special case for components like this (ones that do text entry) so that the user sees a message to log out instead. I could maybe try to implement it in this patch but it could get complicated.

Another possibility is to follow-up with a patch that shows a warning before expiration time, like, "Your session is about to expire in 2 minutes."

Thoughts?

### CODE REVIEW

File: config/default-amo.js [hunk 1]
```diff
@@ -104,4 +104,10 @@ module.exports = {
 
   // https://sentry.prod.mozaws.net/operations/addons-frontend-amo-prod/
   publicSentryDsn: 'https://dbce4e759d8b4dc6a1731d3301fdaab7@sentry.prod.mozaws.net/183',
+
+  // The amount of time (in seconds) that an auth token lives for.
+  // This needs to match the SESSION_COOKIE_AGE in addons-server:
+  // https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/settings_base.py#L990
+  authTokenValidFor: 2592000, // 30 days
+  // TODO: patch addons-server with a comment about keeping in sync with this.
```
Comment (tofumatt) [inline config/default-amo.js]: Worth filing an issue for this if you haven't already, just so it doesn't get lost.

File: tests/client/amo/containers/TestApp.js [hunk 2]
```diff
@@ -204,4 +206,118 @@ describe('App', () => {
...
+      const props = {
+        authToken: userAuthToken(),
+        logOutUser: sinon.stub(),
+        ...customProps,
+      };
+      return render(props);
+    }
+
+    beforeEach(() => {
+      clock = sinon.useFakeTimers(Date.now());
```
Comment (tofumatt) [inline tests/client/amo/containers/TestApp.js]: I love this API.

File: tests/client/amo/containers/TestApp.js [hunk 3]
```diff
@@ -204,4 +206,118 @@ describe('App', () => {
...
+      clock.restore();
+    });
+
+    it('logs out when the token expires', () => {
+      const authTokenValidFor = 10; // seconds
+      const logOutUser = sinon.stub();
+
+      renderAppWithAuth({ authTokenValidFor, logOutUser });
+
+      const fuzz = 3; // acount for rounding the offset calculation.
```
Comment (tofumatt) [inline tests/client/amo/containers/TestApp.js]: Typo: should be "account"

File: tests/client/amo/containers/TestApp.js [hunk 4]
```diff
@@ -204,4 +206,118 @@ describe('App', () => {
...
+    it('only sets one timer when receiving new props', () => {
+      const authTokenValidFor = 10; // seconds
+      const authToken = userAuthToken();
+      const logOutUser = sinon.stub();
+
+      const root = render({ authToken, authTokenValidFor, logOutUser });
+      // Simulate updating the component with new properties.
+      root.componentWillReceiveProps({ authToken });
+
+      const fuzz = 3; // acount for rounding the offset calculation.
```
Comment (tofumatt) [inline tests/client/amo/containers/TestApp.js]: "account"

File: tests/client/amo/containers/TestApp.js [hunk 5]
```diff
@@ -204,4 +206,118 @@ describe('App', () => {
...
+
+    it('does not log out until the token expires', () => {
+      const authTokenValidFor = 10; // seconds
+      const logOutUser = sinon.stub();
+
+      renderAppWithAuth({ authTokenValidFor, logOutUser });
+
+      clock.tick(5 * 1000); // 5 seconds
+      assert.notOk(logOutUser.called,
+        'expected logOutUser() to NOT be called');
```
Comment (tofumatt) [inline tests/client/amo/containers/TestApp.js]: Nitpick: "NOT to be called" is technically correct and I think a bit better.

File: src/amo/containers/App.js [hunk 6]
```diff
@@ -1,46 +1,65 @@
...
-    clientApp: PropTypes.string.isRequired,
-    handleGlobalEvent: PropTypes.func.isRequired,
-    i18n: PropTypes.object.isRequired,
-    lang: PropTypes.string.isRequired,
-    location: PropTypes.object.isRequired,
-    mozAddonManager: PropTypes.object,
-    setUserAgent: PropTypes.func.isRequired,
-    userAgent: PropTypes.string,
-  }
+  mastHead: Node;
```
Comment (kumar303) [inline src/amo/containers/App.js]: It's an annotation of a [class property](https://flow.org/en/docs/types/classes/#toc-class-fields-properties) which is cool because [things like refs](https://github.com/kumar303/addons-frontend/blob/556b2a8a890706aa50708e142f7c7522fbc67a67/src/amo/containers/App.js#L199) tend to be a bit obscure if you're seeing them for the first time in test code. With the Flow annotations, you can always look at the top of the class and see all the ref properties.

File: src/amo/containers/App.js [hunk 7]
```diff
@@ -74,9 +96,76 @@ export class AppBase extends React.Component {
         'userAgent not in state on App load; using navigator.userAgent.');
       setUserAgent(_navigator.userAgent);
     }
+
+    if (authToken) {
+      log.info('Setting a logout timer when the token expires');
+      this.setLogOutTimer(authToken);
```
Comment (kumar303) [inline src/amo/containers/App.js]: Ah, yeah, that's better. Thanks.

File: src/amo/containers/App.js [hunk 8]
```diff
@@ -74,9 +96,76 @@ export class AppBase extends React.Component {
...
+        `Auth token "${encodedTimestamp}" triggered this base62 error: "${base62Error}"`);
+      return;
+    }
+    // If the encoded timestamp was malformed it will be 0 or negative.
+    if (createdAt <= 0) {
+      log.error(oneLine`Got an invalid timestamp from auth token;
+        encoded value: ${encodedTimestamp}; decoded value: ${createdAt}`);
+      return;
+    }
+    const readableCreatedAt = new Date(createdAt * 1000).toString();
```
Comment (kumar303) [inline src/amo/containers/App.js]: I didn't think of that. Hmm. Looking at `moment().format()` I don't think it would buy much though.

File: src/amo/containers/App.js [hunk 9]
```diff
@@ -74,9 +96,76 @@ export class AppBase extends React.Component {
...
+    this.scheduledLogout = setTimeout(() => {
+      log.info('Logging out because the auth token has expired');
+      logOutUser();
+    }, expirationTime * 1000);
+  }
+
+  onViewDesktop = (
+    event: Event,
+    {
+      window_ = window, cookie_ = cookie,
```
Comment (kumar303) [inline src/amo/containers/App.js]: Heh, looks like I inherited some legacy. I fixed them, thanks.

File: config/default-amo.js (hunk 1 above)
Comment (kumar303) [inline config/default-amo.js]: Thanks for the reminder, I did actually forget :) https://github.com/mozilla/addons-server/issues/5284

**Comment by kumar303** [comment]
Thanks for the review.
