### PR TITLE
Fix top-level describe block descriptions

### LINKED ISSUE #2928: Show test suite file names in failure output
### Describe the problem and steps to reproduce it:

Trigger a test failure that happens on the event loop. In other words, one that won't produce a stack trace pointing back to the test file.

### What happened?

You have no easy way to figure out which test file produced the error. Example:

screenshot 2017-08-11 10 26 14

### What did you expect to happen?

You should be able to easily figure out which test file produced the error.

### Anything else we should know?

We can totally do this now that Jest runs from NodeJS! We can start every test with `describe(__filename, ...)` which will produce errors like this:

screenshot 2017-08-11 10 23 57

### PR DESCRIPTION
**Pull request by willdurand**
Fix #2928 

---

This PR makes sure we always have a top-level `describe` block with `__filename` as a description.

Note: the diff is large because I added a few top-level `describe` blocks in test files where there were multiple `describe` top-level blocks (hence re-indenting almost all the code in the files).

### CODE REVIEW

**Comment by willdurand** [comment]
I used this eslint rule 🙈 https://github.com/willdurand/eslint-plugin-amo/blob/master/README.md#describe-with-filename

**Comment by willdurand** [comment]
also rebased this one

File: tests/unit/amo/components/TestAddon.js [hunk 1]
```diff
@@ -1423,7 +1423,7 @@ describe(__filename, () => {
   });
 });
 
-describe('mapStateToProps', () => {
+describe(__filename, () => {
```
Comment (rebmullin) [inline tests/unit/amo/components/TestAddon.js]: here is the double occurrence...
