### PR TITLE
Fixes Compatibility message for iOS users

### LINKED ISSUE #10253: Compatibility message for iOS users is incorrect on non-listing pages
If you open the AMO homepage on iOS, you get this message: "This add-on is not compatible with this browser. Try installing it on Firefox for desktopn". It looks like we should have a different message for non-listing pages. It looks like it wasn't specified as part of https://github.com/mozilla/addons-frontend/issues/9177, so how about something like:

"Add-ons are not compatible with this Firefox for iOS. Try installing them on Firefox for desktop."

### PR DESCRIPTION
**Pull request by championshuttler**
Fixes #10253

### CODE REVIEW

File: src/amo/components/WrongPlatformWarning/index.js [hunk 1]
```diff
@@ -89,7 +89,7 @@ export class WrongPlatformWarningBase extends React.Component<InternalProps> {
     if (_isFirefoxForIOS(userAgentInfo)) {
       // Firefox for iOS.
       message = i18n.gettext(
-        `This add-on is not compatible with this browser. Try installing it on Firefox for desktop.`,
+        `Add-ons are not compatible with Firefox for iOS. Try installing it on Firefox for desktop.`,
```
Comment (willdurand) [inline src/amo/components/WrongPlatformWarning/index.js:92]:
```suggestion
        `Add-ons are not compatible with Firefox for iOS. Try installing them on Firefox for desktop.`,
```

Comment (championshuttler) [reply src/amo/components/WrongPlatformWarning/index.js]: Done

**Review by willdurand — APPROVED** [review]

**Comment by willdurand** [comment]
thanks
