### PR TITLE
Move version-related types into versions reducer

### LINKED ISSUE #7015: Move version-related types into versions reducer
There are a number of types in `core/types/addons.js` which only pertain to versions. These should be moves into `core/reducers/versions.js` as that's where they really belong.

While doing this, we should update `VersionLicenseType` to support the new `is_custom` property that was added in https://github.com/mozilla/addons-server/issues/9914.

For QA:

While this will not change any observable behaviour, it does move code around in some highly used components, so should be checked. Checking for regressions on the Add-on Detail page, as well as with the install process should be sufficient.

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #7015 

Note that this also adds the `isCustom` property to `VersionLicenseType`.

### CODE REVIEW

File: src/core/types/addons.js [hunk 1]
```diff
@@ -1,8 +1,12 @@
...
-import type { VersionIdType, VersionLicenseType } from 'core/reducers/versions';
+import type {
+  VersionIdType,
+  ExternalAddonVersionType,
+  PartialExternalAddonVersionType,
+} from 'core/reducers/versions';
 import type { AddonTypeType } from 'core/constants';
 
-type AddonStatus =
+export type AddonStatusType =
```
Comment (willdurand) [inline src/core/types/addons.js]: It'd be nice to avoid the `Type` suffix whenever we can. It is more a general comment, but usually we don't need it. I know we are not consistent everywhere, but I don't think we should encourage the "Type" suffix. Flow is all about types, so we already know that we deal with types, and because JS (the language) does not support types anyway, we cannot be confused.

The only exception would be a conflict when importing a type in a file that already has something with the same name, but we could alias the type in this case:

```
import type { Addon as AddonType } from '...';
```

Comment (willdurand) [reply src/core/types/addons.js]: I will prepare a list of conventions for the All Hands and we'll discuss each, one by one. You can leave it as is.

Comment (bobsilverberg) [reply src/core/types/addons.js]: Ok, that saves me a step, thanks. 😃
