### PR TITLE
Fix l10n bundling

### LINKED ISSUE #458: Fix the bundling of the locales
Currently the bundle size has balooned since all the locale data is making it's way into the client bundle.

### PR DESCRIPTION
**Pull request by muffinresearch**
Fixes #458

* Builds all the locales into separate js files
* Excludes the bundles if it's not for a relevant app (this was the hardest part) see the ContextReplacementPlugin bit
* Excludes the bundles being output on the page by the server html since webpack does that bit itself.
* Webpack automatically loads the localization via jsonp.

### CODE REVIEW

File: src/core/client/base.js [hunk 1]
```diff
@@ -21,29 +21,30 @@ export default function makeClient(routes, createStore) {
...
-  const jedData = require(`json!../../locale/${locale}/${appName}.json`);
-  const i18n = new Jed(jedData);
-
-  if (initialStateContainer) {
-    try {
-      initialState = JSON.parse(initialStateContainer.textContent);
-    } catch (error) {
-      log.error('Could not load initial redux data');
+  // eslint-disable-next-line global-require, max-len
+  require(`bundle?name=[name]-i18n-[folder]!json!../../locale/${locale}/${appName}.json`)((jedData) => {
```
Comment (muffinresearch) [inline src/core/client/base.js]: Would be nice to move this into the config but I'm not sure how to do that in a good way at the moment.

File: webpack.prod.config.babel.js [hunk 2]
```diff
@@ -67,14 +67,17 @@ export default {
...
+      new RegExp(`^\\.\\/.*?\\/${appName}\\.json$`)
+    ),
     new ExtractTextPlugin('[name]-[chunkhash].css', {allChunks: true}),
     new SriStatsPlugin({
       algorithm: 'sha512',
       write: true,
       saveAs: path.join(__dirname, 'dist/sri.json'),
     }),
-    // ignore dev config
-    new webpack.IgnorePlugin(/\.\/webpack\.dev/, /\/babel$/),
```
Comment (muffinresearch) [inline webpack.prod.config.babel.js]: We don't need this any more since the config moved.

**Comment by mstriemer** [comment]
When I ran `npm run build:disco` it generated a file `disco-i18n-[folder]-964031ce759930910a8a.js` which is 23K and seems to include all of the locales. This is the file that was loaded in browser dynamically. It also seems to be loaded with all the locales in `npm run dev:disco`.

**Comment by mstriemer** [comment]
Maybe I didn't extract properly?

**Comment by mstriemer** [comment]
I blew away my node_modules and reinstalled, then it worked.

r+
