### PR TITLE
Log a GA event when the Primary Hero CTA is clicked

### LINKED ISSUE #8538: [Primary hero] Log a GA event when the CTA is clicked
Follow up for #8305

### Describe the problem and steps to reproduce it:
As part of the requirement for the new homepage primary hero:
>An event should be logged on GA when the CTA is clicked, recording a click on the shelf and the destination.

### PR DESCRIPTION
**Pull request by bobsilverberg**
~~Depends on #8539~~

Fixes #8538 

This includes some fixes to the `PrimaryHeroShelfType` that I realized we should probably have.

### CODE REVIEW

File: src/amo/components/HeroRecommendation/index.js [hunk 1]
```diff
@@ -60,6 +62,41 @@ export const addParamsToHeroURL = ({
...
+
+    const { shelfData } = props;
+    invariant(shelfData, 'The shelfData property is required');
+
+    const { addon, external } = shelfData;
+    this.callToActionURL = '';
+
+    if (addon) {
+      this.callToActionURL = addParamsToHeroURL({
+        urlString: `/addon/${addon.slug}/`,
```
Comment (kumar303) [inline src/amo/components/HeroRecommendation/index.js]: It would be nice if we had a shared function for this. This isn't a change request, just a comment. I see it hard coded in `SearchResult`, `AddonReviewList`, `AddonSummaryCard`, and `AddonTitle` 👀

File: src/amo/components/HeroRecommendation/index.js [hunk 2]
```diff
@@ -60,6 +62,41 @@ export const addParamsToHeroURL = ({
...
+    super(props);
+
+    const { shelfData } = props;
+    invariant(shelfData, 'The shelfData property is required');
+
+    const { addon, external } = shelfData;
+    this.callToActionURL = '';
+
+    if (addon) {
+      this.callToActionURL = addParamsToHeroURL({
```
Comment (kumar303) [inline src/amo/components/HeroRecommendation/index.js]: It would be safer to make `callToActionURL` a method rather than a property. As a property created only at construction time, the URL will go stale if the component gets updated with a new `shelfData` prop. In the current app, that probably won't happen (because components are recreated by the router) but it could easily happen with some changes.

File: tests/unit/amo/reducers/test_home.js [hunk 3]
```diff
@@ -104,7 +104,9 @@ describe(__filename, () => {
     it('loads hero shelves', () => {
       const { store } = dispatchClientMetadata();
 
-      const heroShelves = createHeroShelves();
+      const heroShelves = createHeroShelves({
+        primaryProps: { addon: fakeAddon },
```
Comment (kumar303) [inline tests/unit/amo/reducers/test_home.js]: Since `addon` is not relevant to this test, it would benefit from a `_createHeroShelves()` helper like you added to the other suite. Removing irrelevant setup data makes tests more readable.

File: src/amo/components/HeroRecommendation/index.js (hunk 1 above)
Comment (bobsilverberg) [reply src/amo/components/HeroRecommendation/index.js]: Thanks @kumar303, I opened #8563 for this.

File: src/amo/components/HeroRecommendation/index.js (hunk 2 above)
Comment (bobsilverberg) [reply src/amo/components/HeroRecommendation/index.js]: Good idea. I wasn't too keen on the property approach, but I'm not sure why I didn't think to make it a method instead. This is much better.
