### PR TITLE
RE: Fix title and footer text within homepage shelves (isHomepageCard props)

### LINKED ISSUE #10373: Fix `title` and `footer text` within homepage shelves
Per #9996, the `title` and `footer text` fields from the [shelfmodule](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/shelfmodule/) are not limited to a number of chars. The screenshot below displays both fields at 100 characters:

114384010-dbcd5a00-9b96-11eb-80e9-4cc2c8417a3d

The maximum text length that the UI supports will also need to be determined.

### LINKED ISSUE #10509: Homepage shelves - at a screen resize letters overlap
The layout won't look good when the title and see more links are a bit longer starting at ~ 850 px

I can reproduce this on AMO prod - with Recommended password managers at 728 px

On dev: 
800px

### PR DESCRIPTION
**Pull request by xlisachan**
Fixes #10373 
Fixes #10509

@bobsilverberg, as discussed, this pull request fixes the overlap between the header and footer_text within the homepage shelves by passing through a props (`isHomepageCard`) that `Card` can then utilize. If we proceed with this update, I'll work on updating the tests.

Please see screenshots below:
Homepage (width: 1024px)-
Screen Shot 2021-06-09 at 5 02 31 PM

Homepage (width: 768px)- 
Screen Shot 2021-06-09 at 5 02 44 PM

Homepage (width: 425px)- 
Screen Shot 2021-06-09 at 5 03 00 PM

Rating (included as it utilizes `Card` component)-
Screen Shot 2021-06-09 at 5 03 49 PM

Review (included as it utilizes `Card` component)-
Screen Shot 2021-06-09 at 5 03 56 PM

Please review when you have a moment. Thank you!

### CODE REVIEW

**Comment by xlisachan** [comment]
@bobsilverberg - per your feedback, I have updated the tests for this approach. The latest push also includes an updated Card stylesheet as the [at]extend rule was failing CI tests. Please see screenshots below for reference.

Homepage (width: 1024)
Screen Shot 2021-06-16 at 3 14 17 PM

Homepage (width: 768)
Screen Shot 2021-06-16 at 3 14 27 PM

Homepage (width: 425)
Screen Shot 2021-06-16 at 3 14 36 PM

Rating (as it utilizes Card)
Screen Shot 2021-06-16 at 3 14 53 PM

Review (as it utilizes Card)
Screen Shot 2021-06-16 at 3 15 02 PM

Please review when you have a moment. Thank you!

File: src/amo/components/Card/index.js [hunk 1]
```diff
@@ -63,12 +66,34 @@ export default class Card extends React.Component {
...
+        {header ? (
+          <header
+            className={makeClassName('Card-header', {
+              'HomepageCard-header': isHomepageCard,
+            })}
+          >
+            <div className="Card-header-text">{header}</div>
+
+            {isHomepageCard && footer ? (
+              <footer className="HomepageCard-footer-in-header">
```
Comment (bobsilverberg) [inline src/amo/components/Card/index.js:78]: Because this is in the `Card` component, the `className` should start with `Card` and not `HomepageCard`.

File: src/amo/components/AddonsCard/index.js [hunk 2]
```diff
@@ -44,6 +45,7 @@ type Props = {|
   footerLink?: Object | string | null,
   footerText?: string,
   header?: React.Node,
+  isHomepageCard?: boolean,
```
[the remark this answers is not in the document]
Comment (xlisachan) [reply src/amo/components/AddonsCard/index.js]: I have updated this to be kept in `DefaultProps` and removed it from `Props`. I'm trying to remember if I was using `showPromotedBadge?`as an example - it was placed in both `DefaultProps` and `Props` as well (line 27 and line 40). Should I remove `showPromotedBadge?` in `Props`?

**Comment by xlisachan** [comment]
Thanks for the feedback, @bobsilverberg !

The latest push includes all of the updates. Please let me know how to proceed with `AddonsCard` component (see comment regarding `showPromotedBadge?` property above).

Please review when you have a moment. Thank you!

File: src/amo/components/AddonsCard/index.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/components/AddonsCard/index.js]: I think `isHomepageCard` could be just in `Props` and not in `DefaultProps`, because it will default to `false` if omitted. I think the reason `showPromotedBadge` is in both places is because it is defaulted to `true` when `defaultProps` are set.

File: src/amo/components/AddonsCard/index.js [hunk 3]
```diff
@@ -19,6 +19,7 @@ import './styles.scss';
 
 type DefaultProps = {|
   editing?: boolean,
+  isHomepageShelf?: boolean,
```
Comment (bobsilverberg) [inline src/amo/components/AddonsCard/index.js:22]: As discussed in my reply to your question, I think this should be moved into `Props`.

File: src/amo/components/AddonsCard/index.js [hunk 4]
```diff
@@ -58,6 +59,7 @@ type Props = {|
 export default class AddonsCard extends React.Component<Props> {
   static defaultProps: DefaultProps = {
     editing: false,
+    isHomepageShelf: false,
```
Comment (bobsilverberg) [inline src/amo/components/AddonsCard/index.js:62]: This can be removed.

File: src/amo/components/Card/index.js [hunk 5]
```diff
@@ -13,10 +13,12 @@ export default class Card extends React.Component {
     footerLink: PropTypes.node,
     footerText: PropTypes.node,
     header: PropTypes.node,
+    isHomepageShelf: PropTypes.bool,
     photonStyle: PropTypes.bool,
   };
 
   static defaultProps = {
+    isHomepageShelf: false,
```
Comment (bobsilverberg) [inline src/amo/components/Card/index.js:21]: This isn't needed.

File: src/amo/components/AddonsCard/index.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/components/AddonsCard/index.js]: Actually, I take all of that back! They can both stay in `DefaultProps` and be removed from `Props`.

File: tests/unit/amo/components/TestLandingAddonsCard.js [hunk 6]
```diff
@@ -63,6 +63,18 @@ describe(__filename, () => {
     );
   });
 
+  it.each([true, false])(
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply tests/unit/amo/components/TestLandingAddonsCard.js:66]: You marked this as done, but I still see this testing both `true` and `false`.

File: tests/unit/amo/components/TestAddonsCard.js [hunk 7]
```diff
@@ -166,6 +166,18 @@ describe(__filename, () => {
     expect(root.find(CardList)).toHaveProp('header', header);
   });
 
+  it.each([true, false])(
```
Comment (bobsilverberg) [inline tests/unit/amo/components/TestAddonsCard.js:169]: I missed this last time, but as with the test for `LandingAddonsCard`, we don't really need to test both `true` and `false` here. I'd just test with `true`.

**Review by bobsilverberg — CHANGES_REQUESTED** [review]
Looks good, thanks for the updates @xlisachan. I answered your question and added a couple of comments.

File: tests/unit/amo/components/TestAddonsCard.js (hunk 7 above)
Comment (xlisachan) [reply tests/unit/amo/components/TestAddonsCard.js:169]: Ah, I had updated the wrong test - sorry! Updated!

File: tests/unit/amo/components/TestLandingAddonsCard.js (hunk 6 above)
[the remark this answers is not in the document]
Comment (xlisachan) [reply tests/unit/amo/components/TestLandingAddonsCard.js:66]: Ah, I had updated the wrong test - sorry! Updated!

**Comment by xlisachan** [comment]
Thanks @bobsilverberg !

I removed the `showPromotedBadge?` property from `Props` as advised, and updated the correct tests - sorry about that!

Please review when you have a moment. Thanks!

**Review by bobsilverberg — CHANGES_REQUESTED** [review]
It all looks good, thanks for all of your efforts @xlisachan, great work!

I tried running it locally and the only issue I have is that it seems like the minimum gap between the shelf title and the footer link should be a bit wider. Here's an example of the home page on dev at 758px wide:

Screen Shot 2021-07-19 at 1 55 00 PM

Can you see if you can specify a minimum gap so that there is still a bit of space between them in that scenario?

**Comment by xlisachan** [comment]
I added a `margin-left` property to `.Card-shelf-footer-in-header` as adding a margin to the `.Card-header-text` would affect non-Homepage Cards. Please let me know if you're aligned and/or whether `16px` is enough space.

Screen width: 774px
Screen Shot 2021-07-20 at 3 59 37 PM

(w/ grid for reference)
Screen Shot 2021-07-20 at 3 59 32 PM

Please review when you have a moment. Thanks!

**Review by bobsilverberg — APPROVED** [review]
It looks great, thanks @xlisachan.

This is an issue that has been around for a long time, and a fix has been attempted by contributors in the past, but nobody was successful. Thank you for sticking with it and coming up with a solution that works so well. Well done @xlisachan!
