### PR TITLE
Show loading indicators when switching between landing pages

### LINKED ISSUE #2882: Loading indicators aren't show when switching between landing pages
Sorry I didn't catch this when doing local testing, I must not have noticed as I was on a fast enough connection that blinking would hide the fact that no loading bars appeared.

### Describe the problem and steps to reproduce it:
If you are on a landing page (`/extensions/` or `/themes/`) then navigate to the other landing page, loading indicators are not shown and the old content remains until the new content is loaded from the server.

### What happened?
The old content remains until the new content loads.

### What did you expect to happen?
There to be an intermediate loading state while the route changes but the load is taking place.

### Screencasts

Loading animation happens on first landing page load, but not on subsequent loads:

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #2882 

---

This PR enables the loader when we change from one landing page to another by resetting the add-ons sets when a new request is triggered. In addition, I fixed a visual glitch by reducing the size of the loader related to the number of users (a width of `100%` put the loader on a new line).

### CODE REVIEW

File: tests/unit/amo/reducers/testLanding.js [hunk 1]
```diff
@@ -53,6 +53,30 @@ describe('landing reducer', () => {
 
       expect(state.resultsLoaded).toEqual(false);
     });
+
+    it('resets each set of add-ons', () => {
+      const entities = {
+        addons: {
+          bar: { slug: 'bar' },
```
Comment (tofumatt) [inline tests/unit/amo/reducers/testLanding.js]: I think it would be best to use actual add-ons here rather than the stubs. It should be as easy as using `import { fakeAddon } from 'tests/unit/amo/helpers';` and doing: `bar: { ...fakeAddon, slug: 'bar' },`.

Just in case the reducers start to rely more on the structure of the add-on.

Comment (willdurand) [inline tests/unit/amo/reducers/testLanding.js]: Oh nice, I did not know about it sorry 😕

**Comment by tofumatt** [comment]
No worries :-)
