### PR TITLE
Fix languageTools reducer

### LINKED ISSUE #9967: Some lang packs and dictionaries are missing
Steps to reproduce:
1. Go to https://addons.mozilla.org/en-US/firefox/language-tools/

Expected results:
All lang packs and dictionaries are displayed

Actual results:
Some lang packs and dictionaries are missing

Please see the screenshot : 
langtools

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #9967

### CODE REVIEW

File: tests/unit/core/reducers/test_languageTools.js [hunk 1]
```diff
@@ -77,7 +80,7 @@ describe(__filename, () => {
     it('returns an array of languages', () => {
       const lang = 'fr';
       const language = createFakeLanguageTool({ target_locale: lang });
```
Comment (willdurand) [inline tests/unit/core/reducers/test_languageTools.js:82]: I suggest we change the default in `createFakeLanguageTool()`:

```diff
diff --git a/tests/unit/helpers.js b/tests/unit/helpers.js
index 904dfe480..9331b75f0 100644
--- a/tests/unit/helpers.js
+++ b/tests/unit/helpers.js
@@ -954,7 +954,7 @@ export function createFakeLanguageTool({
     default_locale: DEFAULT_LANG_IN_TESTS,
     guid: fakeAddon.guid,
     locale_disambiguation: '',
-    name: createLocalizedString(name, target_locale),
+    name: createLocalizedString(name, 'en-US'),
     target_locale,
     type: ADDON_TYPE_LANG,
     url: 'https://addons.allizom.org/en-US/firefox/addon/acholi-ug-lp-test',
```

This will avoid issues in the future. We don't really care about `target_locale` really.

File: tests/unit/core/reducers/test_languageTools.js [hunk 2]
```diff
@@ -19,28 +19,31 @@ describe(__filename, () => {
   });
 
   it('stores language tools', () => {
-    const language = createFakeLanguageTool();
+    const lang = 'fr';
+    const language = createFakeLanguageTool({ target_locale: lang });
+    const stateWithLang = reducer(undefined, setLang(lang));
```
Comment (willdurand) [inline tests/unit/core/reducers/test_languageTools.js:24]: We shouldn't use the same `lang` and `target_locale` I think. We need a different `target_locale` than the current locale in order to reproduce the bug.

File: tests/unit/core/reducers/test_languageTools.js (hunk 1 above)
Comment (willdurand) [reply tests/unit/core/reducers/test_languageTools.js:82]: instead of hardcoding `en-US`, we can use `DEFAULT_LANG_IN_TEST`

**Review by willdurand — APPROVED** [review]
Well, we'll fix the tests later I suppose.

**Comment by bobsilverberg** [comment]
> Well, we'll fix the tests later I suppose.

Best to fix them now, I think. I'll have a commit up in a few minutes.

**Review by willdurand — APPROVED** [review]
