### PR TITLE
use sinon.assert everywhere

### LINKED ISSUE #2437: Replace sinon calls wrapped with expect to use sinon.assert directly
If we wrap things like `stub.calledWith('blah')` with assertions then it hides useful error messages that tell us that the args were wrong etc.

A better solution is to cover to using [sinon.assert](http://legacy.sinonjs.org/docs/#assertions) directly OR use something like [sinon-jasmine](https://github.com/froots/jasmine-sinon). 

I have already tried the latter and it appears to be out of date so it might be easier just to use sinon.asserts for now.

### PR DESCRIPTION
**Pull request by willdurand**
Fix #2437 

---

- use `sinon.assert` everywhere
- remove more unused code

### CODE REVIEW

**Comment by willdurand** [comment]
rebased.

**Comment by willdurand** [comment]
re-rebased 😄

**Comment by willdurand** [comment]
re-re-rebased 😅

File: tests/unit/amo/components/TestRatingManager.js [hunk 1]
```diff
@@ -101,9 +101,8 @@ describe(__filename, () => {
       loadSavedReview,
     });
 
-    expect(loadSavedReview.called).toEqual(true);
-    const args = loadSavedReview.firstCall.args[0];
-    expect(args).toEqual({
+    sinon.assert.called(loadSavedReview);
```
Comment (kumar303) [inline tests/unit/amo/components/TestRatingManager.js]: Whenever you use `assert.calledWith(theFunction, ...)`, it's not necessary to precede it with `assert.called(theFunction)`. In fact, it's worse because the first test failure you would see is not as informative.

File: tests/unit/amo/components/TestRatingManager.js [hunk 2]
```diff
@@ -392,9 +391,8 @@ describe(__filename, () => {
           .returns(Promise.resolve({ ...fakeReview, ...params }));
 
         return actions.submitReview(params).then(() => {
-          expect(dispatch.called).toEqual(true);
-          const action = dispatch.firstCall.args[0];
-          expect(action).toEqual(setReview(fakeReview));
+          sinon.assert.called(dispatch);
```
Comment (kumar303) [inline tests/unit/amo/components/TestRatingManager.js]: This should be removed since there is a `calledWith` after it

File: tests/unit/amo/components/TestRatingManager.js [hunk 3]
```diff
@@ -424,8 +422,8 @@ describe(__filename, () => {
           })
           .then(() => {
             mockApi.verify();
-            expect(dispatch.called).toEqual(true);
-            expect(dispatch.firstCall.args[0]).toEqual(setReview(fakeReview));
+            sinon.assert.called(dispatch);
```
Comment (kumar303) [inline tests/unit/amo/components/TestRatingManager.js]: This should be removed

File: tests/unit/core/TestAddonManager.js [hunk 4]
```diff
@@ -125,70 +124,68 @@ describe(__filename, () => {
...
+        await addonManager.install(fakeInstallUrl, fakeCallback, {
           _mozAddonManager: fakeMozAddonManager,
           src: 'home',
-        })
-        .then(unexpectedSuccess, () =>
-          expect(fakeInstallObj.install.called).toBeTruthy(),
-        );
+        });
+
+        done.fail(new Error('this should not be called'));
```
Comment (kumar303) [inline tests/unit/core/TestAddonManager.js]: This pattern is a bit clunky to me. I think it's more succinct in promise form (as the test was before) and it's less prone to errors such as forgetting to call `done()`.

File: tests/unit/core/testErrorHandler.js [hunk 5]
```diff
@@ -174,8 +174,9 @@ describe(__filename, () => {
       const error = new Error();
       errorHandler.handle(error);
 
-      expect(store.dispatch.called).toBeTruthy();
-      expect(store.dispatch.firstCall.args[0]).toEqual(
+      sinon.assert.called(store.dispatch);
```
Comment (kumar303) [inline tests/unit/core/testErrorHandler.js]: This can be removed

File: tests/unit/core/testErrorHandler.js [hunk 6]
```diff
@@ -357,8 +358,9 @@ describe(__filename, () => {
     it('dispatches an error', () => {
       const error = new Error();
       errorHandler.handle(error);
-      expect(errorHandler.dispatch.called).toBeTruthy();
-      expect(errorHandler.dispatch.firstCall.args[0]).toEqual(
+      sinon.assert.called(errorHandler.dispatch);
```
Comment (kumar303) [inline tests/unit/core/testErrorHandler.js]: This can be removed

File: tests/unit/core/testErrorHandler.js [hunk 7]
```diff
@@ -396,8 +398,9 @@ describe(__filename, () => {
 
     it('clears an error', () => {
       errorHandler.clear();
-      expect(errorHandler.dispatch.called).toBeTruthy();
-      expect(errorHandler.dispatch.firstCall.args[0]).toEqual(
+      sinon.assert.called(errorHandler.dispatch);
```
Comment (kumar303) [inline tests/unit/core/testErrorHandler.js]: This can be removed

File: tests/unit/core/utils/test_index.js [hunk 8]
```diff
@@ -610,16 +608,15 @@ describe(__filename, () => {
...
+      sinon.assert.calledWith(_config.get, configKey);
     });
 
     it('passes through component and props when enabled', () => {
       const _config = { get: () => true };
       const SomeComponent = sinon.spy(() => <div />);
       render({ color: 'orange', size: 'large' }, { SomeComponent, _config });
 
-      expect(SomeComponent.called).toBeTruthy();
+      sinon.assert.called(SomeComponent);
```
Comment (kumar303) [inline tests/unit/core/utils/test_index.js]: I assume you held off on converting this call because it was only partially matching the arguments? For cases like that, use `sinon.match()` like this:

```diff
diff --git a/tests/unit/core/utils/test_index.js b/tests/unit/core/utils/test_index.js
index 74c780123..44396a0b7 100644
--- a/tests/unit/core/utils/test_index.js
+++ b/tests/unit/core/utils/test_index.js
@@ -616,10 +616,10 @@ describe(__filename, () => {
       const SomeComponent = sinon.spy(() => <div />);
       render({ color: 'orange', size: 'large' }, { SomeComponent, _config });
 
-      sinon.assert.called(SomeComponent);
-      const props = SomeComponent.firstCall.args[0];
-      expect(props.color).toEqual('orange');
-      expect(props.size).toEqual('large');
+      sinon.assert.calledWith(
+        SomeComponent,
+        sinon.match({ color: 'orange', size: 'large' }),
+      );
     });
   });
 
```

However, in this case I think matching all call arguments would work fine:

```diff
diff --git a/tests/unit/core/utils/test_index.js b/tests/unit/core/utils/test_index.js
index 74c780123..dfed5e860 100644
--- a/tests/unit/core/utils/test_index.js
+++ b/tests/unit/core/utils/test_index.js
@@ -616,10 +616,10 @@ describe(__filename, () => {
       const SomeComponent = sinon.spy(() => <div />);
       render({ color: 'orange', size: 'large' }, { SomeComponent, _config });
 
-      sinon.assert.called(SomeComponent);
-      const props = SomeComponent.firstCall.args[0];
-      expect(props.color).toEqual('orange');
-      expect(props.size).toEqual('large');
+      sinon.assert.calledWith(
+        SomeComponent,
+        { color: 'orange', size: 'large' },
+      );
     });
   });
 
```

It's usually a good idea to partially match call arguments so that the test is only checking exactly what it needs to. Otherwise, making an unrelated change to a function signature could force you to update more tests than you need to.

File: tests/unit/ui/components/TestRating.js [hunk 9]
```diff
@@ -65,40 +65,40 @@ describe(__filename, () => {
     const onSelectRating = sinon.stub();
     const root = render({ onSelectRating });
     selectRating(root, 1);
-    expect(onSelectRating.called).toEqual(true);
-    expect(onSelectRating.firstCall.args[0]).toEqual(1);
+    sinon.assert.called(onSelectRating);
```
Comment (kumar303) [inline tests/unit/ui/components/TestRating.js]: This can be removed

File: tests/unit/ui/components/TestRating.js [hunk 10]
```diff
@@ -65,40 +65,40 @@ describe(__filename, () => {
...
+    sinon.assert.calledWith(onSelectRating, 1);
   });
 
   it('lets you select a two star rating', () => {
     const onSelectRating = sinon.stub();
     const root = render({ onSelectRating });
     selectRating(root, 2);
-    expect(onSelectRating.called).toEqual(true);
-    expect(onSelectRating.firstCall.args[0]).toEqual(2);
+    sinon.assert.called(onSelectRating);
```
Comment (kumar303) [inline tests/unit/ui/components/TestRating.js]: This can be removed

File: tests/unit/ui/components/TestRating.js [hunk 11]
```diff
@@ -65,40 +65,40 @@ describe(__filename, () => {
...
+    sinon.assert.calledWith(onSelectRating, 2);
   });
 
   it('lets you select a three star rating', () => {
     const onSelectRating = sinon.stub();
     const root = render({ onSelectRating });
     selectRating(root, 3);
-    expect(onSelectRating.called).toEqual(true);
-    expect(onSelectRating.firstCall.args[0]).toEqual(3);
+    sinon.assert.called(onSelectRating);
```
Comment (kumar303) [inline tests/unit/ui/components/TestRating.js]: This can be removed

File: tests/unit/ui/components/TestRating.js [hunk 12]
```diff
@@ -65,40 +65,40 @@ describe(__filename, () => {
...
+    sinon.assert.calledWith(onSelectRating, 3);
   });
 
   it('lets you select a four star rating', () => {
     const onSelectRating = sinon.stub();
     const root = render({ onSelectRating });
     selectRating(root, 4);
-    expect(onSelectRating.called).toEqual(true);
-    expect(onSelectRating.firstCall.args[0]).toEqual(4);
+    sinon.assert.called(onSelectRating);
```
Comment (kumar303) [inline tests/unit/ui/components/TestRating.js]: This can be removed

File: tests/unit/ui/components/TestRating.js [hunk 13]
```diff
@@ -65,40 +65,40 @@ describe(__filename, () => {
...
+    sinon.assert.calledWith(onSelectRating, 4);
   });
 
   it('lets you select a five star rating', () => {
     const onSelectRating = sinon.stub();
     const root = render({ onSelectRating });
     selectRating(root, 5);
-    expect(onSelectRating.called).toEqual(true);
-    expect(onSelectRating.firstCall.args[0]).toEqual(5);
+    sinon.assert.called(onSelectRating);
```
Comment (kumar303) [inline tests/unit/ui/components/TestRating.js]: This can be removed

File: tests/unit/core/TestAddonManager.js (hunk 4 above)
Comment (willdurand) [reply tests/unit/core/TestAddonManager.js]: reverted
