### PR TITLE
fix: Use addonType not type in query

### LINKED ISSUE #1811: Themes displayed when pressing "More highly rated extensions" link
Steps to reproduce:
1.On Android, go to AMO-dev
2.Press the extensions button
3.Click on _More highly rated extensions_ link

Expected results:
Extensions sorted by rating are displayed

Actual results:
Themes sorted by rating are displayed

NOTES:
Same issue for _More popular extensions_
Nor reproducible for _More featured extensions_ 

Please see video for this bug : 
moreext

### LINKED ISSUE #1869: Extensions are shown when clicking "More popular themes"
### Describe the problem and steps to reproduce it:
Relates to https://github.com/mozilla/addons-frontend/issues/1811

- Go to /en-US/firefox/themes/ 
- Scroll down and click "MORE POPULAR THEMES" 

### What happened?
- You are sent to /en-US/firefox/search/?sort=hotness which is just extensions.

### What did you expect to happen?
- You should see a url that is just themes e.g. /en-US/firefox/search/?sort=hotness&type=persona

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Screenshot of /en-US/firefox/search/?sort=hotness

screen shot 2017-02-22 at 15 27 12

### PR DESCRIPTION
**Pull request by tofumatt**
Fixes #1811
Fixes #1869

### CODE REVIEW

File: src/amo/components/LandingPage.js [hunk 1]
```diff
@@ -55,13 +55,16 @@ export class LandingPageBase extends React.Component {
         popularHeader: i18n.gettext('Most popular extensions'),
         popularFooterLink: {
           pathname: '/search/',
-          query: { sort: SEARCH_SORT_POPULAR, type: ADDON_TYPE_EXTENSION },
+          query: { addonType: ADDON_TYPE_EXTENSION, sort: SEARCH_SORT_POPULAR },
```
Comment (muffinresearch) [inline src/amo/components/LandingPage.js]: Aha so this was being set but was transformed elsewhere? Would be good to have a regression test to cover this.

**Comment by muffinresearch** [comment]
r + with tests

**Comment by tofumatt** [comment]
Depends on #1895 to get the tests passing now because a new lang was added.
