### PR TITLE
Use FxA link from the API

### LINKED ISSUE #5390: Different URLs for "Manage firefox account" links in legacy and new frontend.
Steps to reproduce:
1.Login to AMO-dev
2.From Edit Profile, click the "Manage firefox account" link from both new frontend and legacy frontend
3.Observe the URLs

Expected results:
URLs are the same

Actual results:
Links are different (https://accounts.firefox.com/settings for new frontend, https://stable.dev.lcip.org/settings for legacy frontend)

Please see a photo of this bug :
fxa

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #5390

### CODE REVIEW

File: tests/unit/amo/pages/TestUserProfileEdit.js [hunk 1]
```diff
@@ -1659,4 +1660,19 @@ describe(__filename, () => {
 
     sinon.assert.calledWith(dispatchSpy, errorHandler.createClearingAction());
   });
+
+  it('renders a FxA management link', () => {
```
Comment (rebmullin) [inline tests/unit/amo/pages/TestUserProfileEdit.js]: would it be a little bit better to say when this link is present? 
something like: `renders a FxA management link when it's the user's own profile`
