### PR TITLE
Make sure the proper viewContext is set when loading a category page

### LINKED ISSUE #4043: Themes menu option is not highlighted while accessing any theme category from homepage
Steps to reproduce:
1. Load a theme category from homepage i.e. https://addons.allizom.org/en-US/firefox/themes/scenery/
2. Observe underlined option from the menu

Expected results:
"Themes" option is underlined.

Actual results:
"Explore" option is underlined.

Notes/Issues:
Verified on AMO-stage FF57(Win 7). Issue is reproducing on all servers.
Screenshot for this issue:

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #4043 

When a category page is visited via direct link, the viewContext is not set to the proper value
which results in the wrong link in SectionLinks being highlighted. This patch adds a dispatch for
SET_VIEW_CONTEXT to the Category component to fix this issue.

I'm not entirely sure about the behaviour in the test for `does not fetch anything, but sets a viewContext when already loaded`. I think we still need to do this (i.e., set the viewContext), and that the test is therefore accurate, but I could be wrong about that.

### CODE REVIEW

File: tests/unit/amo/components/TestCategory.js [hunk 1]
```diff
@@ -235,22 +238,23 @@ describe(__filename, () => {
...
+  it('dispatches getLanding and sets a viewContext when results are not loaded', () => {
     _categoriesFetch();
     _categoriesLoad();
 
     const fakeDispatch = sinon.stub(store, 'dispatch');
     render({}, { autoDispatchCategories: false });
 
-    sinon.assert.callCount(fakeDispatch, 1);
+    sinon.assert.callCount(fakeDispatch, 2);
+    sinon.assert.calledWith(fakeDispatch, setViewContext(fakeCategory.type));
```
Comment (kumar303) [inline tests/unit/amo/components/TestCategory.js]: This test exercises [a specific if branch](https://github.com/bobsilverberg/addons-frontend/blob/d41b5e99ba24219eab50f1a1127f937497195fa6/src/amo/components/Category/index.js#L110).

It's not necessary to check the view context logic because that's not affected by the if branch. In fact, by checking the view context behavior, you are duplicating the [other test](https://github.com/bobsilverberg/addons-frontend/blob/d41b5e99ba24219eab50f1a1127f937497195fa6/tests/unit/amo/components/TestCategory.js#L141). Such a duplication won't really hurt anything but it could potentially introduce a maintenance burden.

I would suggest these changes:
* Remove the `assert.callCount()` from this test since it's not necessary
* Remove the assertion of the `setViewContext()` call

File: tests/unit/amo/components/TestCategory.js [hunk 2]
```diff
@@ -272,14 +276,15 @@ describe(__filename, () => {
       },
     });
 
+    sinon.assert.calledWith(fakeDispatch, setViewContext(fakeCategory.type));
```
Comment (kumar303) [inline tests/unit/amo/components/TestCategory.js]: Similarly, this test exercises [only a specific if branch](https://github.com/bobsilverberg/addons-frontend/blob/d41b5e99ba24219eab50f1a1127f937497195fa6/src/amo/components/Category/index.js#L113). It's not necessary to make an assertion about the view context logic since that's not affected by the if branch.

File: tests/unit/amo/components/TestCategory.js [hunk 3]
```diff
@@ -307,6 +312,7 @@ describe(__filename, () => {
       category,
       errorHandlerId: errorHandler.id,
     }));
+    sinon.assert.calledWith(fakeDispatch, setViewContext(addonType));
```
Comment (kumar303) [inline tests/unit/amo/components/TestCategory.js]: And again, this test was meant to cover [a specific if branch](https://github.com/bobsilverberg/addons-frontend/blob/d41b5e99ba24219eab50f1a1127f937497195fa6/src/amo/components/Category/index.js#L112) so it's not necessary to add an assertion for the view context logic.

File: tests/unit/amo/components/TestCategory.js [hunk 4]
```diff
@@ -161,7 +163,8 @@ describe(__filename, () => {
     const fakeDispatch = sinon.stub(store, 'dispatch');
     render({}, { autoDispatchCategories: false });
 
-    sinon.assert.notCalled(fakeDispatch);
+    sinon.assert.callCount(fakeDispatch, 1);
+    sinon.assert.calledWith(fakeDispatch, setViewContext(fakeCategory.type));
```
Comment (kumar303) [inline tests/unit/amo/components/TestCategory.js]: I saw your question about this test. The test intends to cover [only this if branch](https://github.com/bobsilverberg/addons-frontend/blob/d41b5e99ba24219eab50f1a1127f937497195fa6/src/amo/components/Category/index.js#L95) which is there to prevent fetching data when the data is already loaded. Because of that, I don't think it's necessary to cover the view context logic.

The old approach was to assert that nothing is dispatched but that won't work anymore. I suggest changing the assertion to be specific about category fetching:

```js
import { CATEGORIES_FETCH } from 'core/constants';

sinon.assert.neverCalledWith(fakeDispatch, sinon.match({ type: CATEGORIES_FETCH }));
```

Comment (bobsilverberg) [reply tests/unit/amo/components/TestCategory.js]: Thanks Kumar, that all makes sense. 👍

File: tests/unit/amo/components/TestCategory.js [hunk 5]
```diff
@@ -137,22 +139,23 @@ describe(__filename, () => {
     expect(root.find(ErrorList)).toHaveLength(1);
   });
 
-  it('fetches categories and landing data when not yet loaded', () => {
+  it('fetches categories and landing data and sets a viewContext when not yet loaded', () => {
```
Comment (kumar303) [inline tests/unit/amo/components/TestCategory.js]: Just FYI: we try to keep line length to 80 characters. It's not mandatory, just a nice-to-have for people like me who prefer to use horizontal splits. We haven't put a [lint rule](https://github.com/mozilla/addons-frontend/issues/3045) in place because no one has the courage to review the patch 🙂

File: tests/unit/amo/components/TestCategory.js [hunk 6]
```diff
@@ -161,7 +164,8 @@ describe(__filename, () => {
     const fakeDispatch = sinon.stub(store, 'dispatch');
     render({}, { autoDispatchCategories: false });
 
-    sinon.assert.notCalled(fakeDispatch);
+    sinon.assert.callCount(fakeDispatch, 1);
```
Comment (kumar303) [inline tests/unit/amo/components/TestCategory.js]: I'd like to avoid call count assertions unless absolutely necessary because they introduce a maintenance burden. For example, we may later add another unrelated dispatch to the component but that should not break this test.

File: tests/unit/amo/components/TestCategory.js [hunk 7]
```diff
@@ -137,22 +139,24 @@ describe(__filename, () => {
     expect(root.find(ErrorList)).toHaveLength(1);
   });
 
-  it('fetches categories and landing data when not yet loaded', () => {
+  it('fetches categories and landing data ' +
```
Comment (muffinresearch) [inline tests/unit/amo/components/TestCategory.js]: You could have use a template literal here - also there's helper tag called `oneLine` that will remove leading whitespace from the second line. See https://github.com/mozilla/addons-frontend/blob/350227964acd5818bacefb5057108678a463a36e/src/core/server/sriDataPlugin.js#L5 for an example.
