### PR TITLE
Fix page loading bug (close #1401)

### LINKED ISSUE #1401: page 2 of search results are broken (passing count: 0)
The second page of search results are broken: https://addons-dev.allizom.org/en-GB/firefox/search/?page=2&q=test

Not sure why it's happening or when it started, but threw me for a loop on a branch when I thought I messed something up, only to see master was broken...

### PR DESCRIPTION
**Pull request by tofumatt**
This should be a simple fix for the second page not loading.

### CODE REVIEW

**Comment by mstriemer** [comment]
The `filtersMatch()` function should check all keys in both `filters` and `otherFilters`. This is essentially `chai.assert.deepEqual()` but returning a boolean instead of throwing. It looks like they use a library called `deep-eql`.

Might be nice to just use `deep-eql` instead. Could be overkill if we just use it once though.

I'm now too deep into this (is that a pun? unintended). Spreading the two sets of props together would fix the function in this case and that should get tests that show the props need to match. That means we could be iterating over each prop twice though that sucks. Putting it into a `Set` would fix that but `Set`s don't have the `every()` method so we'd need to convert it back to an `Array`. You could create a third object and use its keys though (lol, wtf why is this so hard?). Actually this one looks kind of nice (provided there isn't something else I haven't thought of).

```js
const filtersMatch = (filters, otherFilters) =>
  Object.keys({ ...filters, ...otherFilters })
    .every((k) => filters[k] === otherFilters[k]);
```

Just using `deep-eql` may be the best solution, we know it's a good implementation.

**Comment by mstriemer** [comment]
I forgot the link to [`deep-eql`](https://github.com/chaijs/deep-eql/blob/145dd2629e0e1e90e4fabaf0f8b8635ad3015a7a/index.js#L118). Looks like it's just used as:

```js
import deepEqual from 'deep-eql';

const filtersMatch = (x, y) => deepEqual(x, y);

**Comment by Ryuno-Ki** [comment]
In Python, you would actual convert a list to a set and back to a list to make its elements unique …
How high is the penalty if this would be done in JavaScript? That is, how does a transpiled set looks like?

**Comment by tofumatt** [comment]
@mstriemer I'm fine with just using `deep-equal`, we could re-invent the wheel but it has tests already and we know it works well, I'll just use it.

**Comment by tofumatt** [comment]
Okay, switched to using `deep-eql`. r?

File: tests/client/amo/components/TestAddonDetail.js [hunk 1]
```diff
@@ -6,8 +6,9 @@ import {
 } from 'react-addons-test-utils';
 import { Provider } from 'react-redux';
 
-import AddonDetail, { allowedDescriptionTags }
-  from 'amo/components/AddonDetail';
+import AddonDetail, {
+  allowedDescriptionTags,
+} from 'amo/components/AddonDetail';
```
Comment (mstriemer) [inline tests/client/amo/components/TestAddonDetail.js]: Looks like this could fit on one line. It's also probably why you have a conflict so maybe just leave it as-is.

Comment (tofumatt) [inline tests/client/amo/components/TestAddonDetail.js]: Ah, indeed, previously it had two imports and needed the spacing? Or something. I'll fix it 👍
