### PR TITLE
Return domain in set-cookie

### LINKED ISSUE #9490: Addon detail page 404s at page refresh for users who deleted their accounts on FxA
Follow up for #9482 

### Describe the problem and steps to reproduce it:
1. Log in to AMO stage
2. Open an add-on detail page
3. In a separate tab, open the FxA account management page
4. Delete your account from FxA
5. Go back to AMO and refresh the tab where the add-on detail page was opened

### What happened?
You receive a 404 for the add-on detail page

### What did you expect to happen?
The add-on detail page is loaded

### Anything else we should know?
- the error will also reproduce when trying to reload an reviews page
- as far as I can tell, the error happens because the frontend-auth cookie was force deleted

### LINKED ISSUE #9491: 'Incorrect authentication credentials' error displayed on any profile page for users who deleted their accounts on FxA
Follow up for #9482 and similar to #9490

### Describe the problem and steps to reproduce it:
1. Log in to AMO stage
2. Open any user profile page
3. In a separate tab, open the FxA account management page
4. Delete your account from FxA
5. Go back to AMO and refresh the tab where the user profile page was opened

### What happened?
There is an 'Incorrect authentication credentials' error displayed (no connected error visible in the console though)

### What did you expect to happen?
The user profile page should be loaded (or throw a 404 if no longer exists)

### Anything else we should know?
Similar to #9490 , the issue is caused by the frontend-auth cookie being deleted

image

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #9490 (again)

Fixes #9491 (again)

### CODE REVIEW

File: tests/unit/core/server/test_base.js [hunk 1]
```diff
@@ -592,9 +592,9 @@ describe(__filename, () => {
       expect(auth_cookie).toContain(
         `${defaultConfig.get('cookieName')}=; Max-Age=0;`,
       );
-      expect(auth_cookie).toContain('HttpOnly');
-      expect(auth_cookie).toContain('Secure');
-      expect(auth_cookie).toContain('Lax');
+      expect(auth_cookie).toContain('Domain=.addons.mozilla.org;');
```
Comment (willdurand) [inline tests/unit/core/server/test_base.js:595]: I do not use the config value to make sure the config evaluates the template string correctly.
