### PR TITLE
Render noindex,follow meta when search page does not have any results

### LINKED ISSUE #10831: Set meta=robots (noindex, follow) to search pages with 0 results
### Describe the problem and steps to reproduce it:

1. Load a search page (or category page) with no results

### What happened?

This page will be indexed by search engines.

### What did you expect to happen?

This page should NOT be indexed.

### Anything else we should know?

We should render a `<meta="robots" content="noindex, follow">`.

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #10831

---

This should work with all search pages, including category pages and soon tag pages. FWIW, we use this `meta` tag for other pages.

### CODE REVIEW

File: tests/unit/amo/components/TestSearch.js [hunk 1]
```diff
@@ -433,6 +433,16 @@ describe(__filename, () => {
...
+  it('renders a robots meta when there is no results', () => {
+    const root = render({ count: 0 });
+
+    expect(root.find('meta[name="robots"]')).toHaveLength(1);
+    expect(root.find('meta[name="robots"]')).toHaveProp(
+      'content',
+      'noindex, follow',
+    );
+  });
+
```
Comment (diox) [inline tests/unit/amo/components/TestSearch.js:445]: Because we really don't want SEO regressions and because it can be a little difficult to notice those regressions in time... I think we need a few more tests proving that:
- We don't accidentally add the meta to non-search pages that don't have `count` in `props`.
- We don't accidentally add the meta to search pages with a positive result count
- We add the meta to category pages specifically when they have a result count of 0
- We don't accidentally add the meta to category pages specifically with a positive result count

Comment (willdurand) [reply tests/unit/amo/components/TestSearch.js:445]: Right, I can add some assertions to make sure the meta isn't present in most cases.

Comment (willdurand) [reply tests/unit/amo/components/TestSearch.js:448]: > * We don't accidentally add the meta to non-search pages that don't have `count` in `props`.

Not sure what that means, this is only impacting a `Search` component so non search pages cannot be affected.

> * We don't accidentally add the meta to search pages with a positive result count

Added (assertion + test case)

> * We add the meta to category pages specifically when they have a result count of 0
> * We don't accidentally add the meta to category pages specifically with a positive result count

Category pages use the `Search` component so that's covered by the tests of this component.

File: tests/unit/amo/components/TestSearch.js [hunk 2]
```diff
@@ -433,6 +435,24 @@ describe(__filename, () => {
     expect(wrapper.find(NotFound)).toHaveLength(1);
   });
 
+  it('renders a robots meta when there is no results', () => {
+    const { store } = dispatchSearchResults({ addons: [] });
+    const root = renderWithStore({ store });
```
Comment (willdurand) [inline tests/unit/amo/components/TestSearch.js:440]: Minor improvement because we shouldn't set the `count` manually. It is a redux prop (injected).

File: tests/unit/amo/components/TestSearch.js (hunk 1 above)
Comment (diox) [reply tests/unit/amo/components/TestSearch.js:448]: > Not sure what that means, this is only impacting a `Search` component so non search pages cannot be affected.

I read too quickly :) Still would be nice to have a test proving we handle when `count` is `undefined` (or even a falsy non-integer).

>> We add the meta to category pages specifically when they have a result count of 0
>> We don't accidentally add the meta to category pages specifically with a positive result count
>
> Category pages use the Search component so that's covered by the tests of this component.

Yes, but my point was to have some redundancy. We know we are using the Search component, but if for some reason the category page starts passing `0` as the `count` in props for instance, it would break.

Comment (willdurand) [reply tests/unit/amo/components/TestSearch.js:448]: > Still would be nice to have a test proving we handle when `count` is `undefined` (or even a falsy non-integer).

This is an injected prop so unlikely to end up in a state like this but we can hack around and have a test case for that. The check in the component is a strict comparison to an integer so that won't be a problem.

> Yes, but my point was to have some redundancy. We know we are using the Search component, but if for some reason the category page starts passing `0` as the `count` in props for instance, it would break.

This isn't easily doable because Flow would prevent that (I added the prop on L94):

```
yarn flow
yarn run v1.22.10
$ flow
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/amo/pages/CategoryPage/index.js:93:10

Cannot create Search element because property count is missing in
Props [1] but exists in props [2]. [prop-missing]

     src/amo/pages/CategoryPage/index.js
      90│     return (
      91│       <Page>
      92│         <HeadLinks />
 [2]  93│         <Search
      94│           count={0}
      95│           enableSearchFilters
      96│           filters={filtersForSearch}
      97│           pageTitle={this.getPageTitle(categoryName)}
      98│           paginationQueryParams={convertFiltersToQueryParams(filters)}
      99│           pathname={getCategoryResultsPathname({
     100│             addonType,
     101│             slug: categorySlug,
     102│           })}
     103│         />

     src/amo/components/Search/index.js
 [1] 334│ const Search: React.ComponentType<Props> = compose(
```

**Review by diox — APPROVED** [review]
