### PR TITLE
Simplify lang selector

### LINKED ISSUE #3205: Hard to read language selector
Steps to reproduce:
1. Load AMO-dev homepage https://addons-dev.allizom.org/en-US/firefox/
2. Go to page footer and observe language selector

Expected results:
The language selector is clear and readable.

Actual results:
The language is written using black on gray background with icon and drop-down arrow in white.

Notes/Issues:
Maybe we can use white background? Or white color font for language as in production.
Verified on AMO-dev FF55(Win 7). 
Screenshot for this issue:

### PR DESCRIPTION
**Pull request by muffinresearch**
Fixes #3205 

Before:

add-ons_for_firefox

After:

add-ons_fur_firefox

### CODE REVIEW

File: src/amo/components/LanguagePicker.js [hunk 1]
```diff
@@ -46,12 +46,13 @@ export class LanguagePickerBase extends React.Component {
 
     return (
       <div className="LanguagePicker">
-        <h3 className="LanguagePicker-header">
+        <label htmlFor="lang-picker" className="LanguagePicker-header">
```
Comment (tofumatt) [inline src/amo/components/LanguagePicker.js]: Oops, my bad 😢

Comment (muffinresearch) [reply src/amo/components/LanguagePicker.js]: All's well that ends well :)
