### PR TITLE
Prevent the test suite from ever calling a real API

### LINKED ISSUE #1138: Prevent the test suite from ever calling a real API
### Describe the problem and steps to reproduce it:
- write a test for an action that calls the API
- forget to mock out the `callApi` method
### What happened?

This will attempt to make a real API request (depending on what server is configured). The result will probably be a harmless 401 Unauthorized since no real tokens are used in the test suite but this can cause slowness.
### What did you expect to happen?

It should not make any real API request at all even though it was a mistake not to mock the component.
### Anything else we should know?

(Please include a link to the page, screenshots and any relevant files.)

### PR DESCRIPTION
**Pull request by willdurand**
Fix #1138

---

I tested by removing all the "mock" code of a saga test suite and in
some API test cases in the disco test suite.

### CODE REVIEW

File: tests/setup.js [hunk 1]
```diff
@@ -73,6 +73,11 @@ global.sinon = sinon.createSandbox();
 // Stub the magic constant webpack normally supplies.
 global.CLIENT_CONFIG = require('core/utils').getClientConfig(config);
 
+// See: https://github.com/mozilla/addons-frontend/issues/1138
+global.fetch = () => {
+  throw new Error('API calls MUST be mocked.');
```
Comment (kumar303) [inline tests/setup.js]: It would be nice if this message included the URL that was getting fetched since we don't always get a stack trace, especially in sagas. Seeing the URL should help track it down. I guess you'll have to look for `input.url || input` in [fetch()](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#Syntax).

File: tests/unit/amo/sagas/test_collections.js [hunk 2]
```diff
@@ -127,6 +127,11 @@ describe(__filename, () => {
         .once()
         .returns(Promise.reject(error));
 
+      mockApi
+        .expects('getCollectionAddons')
```
Comment (kumar303) [inline tests/unit/amo/sagas/test_collections.js]: 👀
