### PR TITLE
I6351: show notice for deleted reviews to admin users

### LINKED ISSUE #6351: Show a warning when viewing a deleted review
Depends on https://github.com/mozilla/addons-server/issues/9371

### Describe the problem and steps to reproduce it:

- Sign in as an admin
- Go to the add-on review listing
- Click on the timestamp of a review to view its detail page
- Delete the review

### What happened?

It appears as though the review was not deleted

### What did you expect to happen?

You should see a warning similar to https://github.com/mozilla/addons-frontend/issues/4244 saying "This review has been deleted and is only visible to adminstrators"

### Anything else we should know?

See https://github.com/mozilla/addons-frontend/issues/6321 for a screencast.

### PR DESCRIPTION
**Pull request by tsl143**
Fixes #6351

### CODE REVIEW

**Comment by willdurand** [comment]
@tsl143 could you please rebase your branch? thanks!

**Comment by tsl143** [comment]
@willdurand I have updated the PR

**Comment by tsl143** [comment]
@willdurand , is there anything more needs to be done for this?

**Comment by willdurand** [comment]
> @willdurand , is there anything more needs to be done for this?

sorry @tsl143, I believe it is fine but I am not familiar with the original issue. I believe @kumar303 might be a better reviewer here since he is the author of the bug.

File: src/amo/components/AddonReviewCard/index.js [hunk 1]
```diff
@@ -493,6 +494,13 @@ export class AddonReviewCardBase extends React.Component<InternalProps> {
       >
         <div className="AddonReviewCard-container">
           {errorHandler.renderErrorIfPresent()}
+          {review && review.isDeleted && (
+            <Notice type="error" className="Addon-non-public-notice">
+              {i18n.gettext(
+                'This is not a public review. You are only seeing it because of elevated permissions.',
```
Comment (kumar303) [inline src/amo/components/AddonReviewCard/index.js]: The notice needs some margin below it to the spacing consistent. We use even increments like `2px`, `4px`, `6px`, `8px`, `12px`, `16px`. This is buried in a Sketch file somewhere. The best thing would be to match the spacing of surrounding elements but be sure to also match the spacing on smaller screens (second screenshot).

screen shot 2019-02-22 at 10 18 16 am
screen shot 2019-02-22 at 10 18 41 am

Comment (kumar303) [inline src/amo/components/AddonReviewCard/index.js]: Let's change the text to: 'This rating or review has been deleted. You are only seeing it because of elevated permissions.' This will help communicate exactly what happened.

File: src/amo/api/reviews.js [hunk 2]
```diff
@@ -20,6 +20,7 @@ type ExternalReviewTypeBase = {|
   created: Date,
   id: number,
   is_developer_reply: boolean,
+  is_deleted: boolean,
```
Comment (kumar303) [inline src/amo/api/reviews.js]: Since technically we are keeping these alphabetical, it needs to move up a line

File: src/amo/components/AddonReviewCard/index.js [hunk 3]
```diff
@@ -493,6 +494,13 @@ export class AddonReviewCardBase extends React.Component<InternalProps> {
       >
         <div className="AddonReviewCard-container">
           {errorHandler.renderErrorIfPresent()}
+          {review && review.isDeleted && (
+            <Notice type="error" className="Addon-non-public-notice">
```
Comment (kumar303) [inline src/amo/components/AddonReviewCard/index.js]: By using the class `Addon-non-public-notice`, you are relying on the  [`Addon/styles.scss`](https://github.com/mozilla/addons-frontend/blob/18e3ce5d1adcbdffcbadc1d4b9b93ea30d773a6e/src/amo/pages/Addon/styles.scss) file which doesn't get imported here. In other words, it only works by accident. You need to name the class based on this component, such as `AddonReviewCard-non-public-notice` (or whatever name) and add the styles to `AddonReviewCard/styles.scss` since that *is* imported at the top. 

Alternatively you could create a shared component for both to use, like `NonPublicObjectNotice` but that's overkill for the case here which is to get some margins.

**Comment by tsl143** [comment]
@kumar303 , Apparently it wasn't working that's why we got margin issue.
Inferring from addon details page, I used `margin-bottom: 12px`
