### PR TITLE
fix: Android lacks theme categories

### LINKED ISSUE #1723: No content in Themes categories
Steps to reproduce:
1. Load AMO-dev on your Android device
2. Click on any theme category i.e Wild

Expected results:
Themes are displayed.

Actual results:
No themes displayed.

Notes/Issues:
- "Browse all themes" link is working as expected.
  
Verified on AMO-dev FF51(Android 6.0.1)
Screenshot for this issue: 
wt

### PR DESCRIPTION
**Pull request by tofumatt**
Fixes #1723

Admittedly a very hacky fix but it works.

### CODE REVIEW

File: src/amo/containers/CategoryPage.js [hunk 1]
```diff
@@ -14,10 +14,21 @@ export function CategoryPageBase(props) {
 }
 
 export function mapStateToProps(state, ownProps) {
+  // HACK: This loads Firefox personas (lightweight themes) for Android
+  // until https://github.com/mozilla/addons-frontend/issues/1723#issuecomment-278793546
```
Comment (kumar303) [inline src/amo/containers/CategoryPage.js]: In addition to linking here, I think it would be good to file an addons-server bug asking to insert the new mobile categories and link to that issue

File: src/amo/containers/CategoryPage.js [hunk 2]
```diff
@@ -14,10 +14,21 @@ export function CategoryPageBase(props) {
 }
 
 export function mapStateToProps(state, ownProps) {
+  // HACK: This loads Firefox personas (lightweight themes) for Android
```
Comment (kumar303) [inline src/amo/containers/CategoryPage.js]: I would suggest changing this to `TODO` since we already have those. It would give us one less thing to grep for.

File: src/core/api/index.js [hunk 3]
```diff
@@ -111,7 +111,11 @@ export function search({ api, page, auth = false, filters = {} }) {
     endpoint: 'addons/search',
     schema: { results: [addon] },
     params: {
-      app: api.clientApp,
+      // We allow overrides to clientApp because of
+      // https://github.com/mozilla/addons-frontend/issues/1723
+      // When it stops requiring overrides to the clientApp this
+      // can likely be restored to `api.clientApp` only.
```
Comment (kumar303) [inline src/core/api/index.js]: I think this feature is fine. I don't think you'd need to remove it later.

File: src/core/searchUtils.js [hunk 4]
```diff
@@ -108,10 +108,22 @@ export function loadByCategoryIfNeeded(
...
+
+  // HACK: This loads Firefox personas (lightweight themes) for Android
+  // until https://github.com/mozilla/addons-frontend/issues/1723#issuecomment-278793546
+  // is more fully addressed.
+  // Essentially: right now there are no categories for the combo
+  // of "Android" + "Themes" but Firefox lightweight themes will work fine
+  // on mobile so we request them.
+  // Obviously we need to fix this on the API end so our requests aren't
+  // overridden, but for now this will work.
+  const clientApp = params.application === 'android' ?
```
Comment (kumar303) [inline src/core/searchUtils.js]: The `loadByCategoryIfNeeded` function and the `mapStateToProps` function both look like they end up calling `core/api:search()`. Can't you just put the android->firefox hack in `search()` so that it only gets switched in one place?

File: tests/client/core/api/test_api.js [hunk 5]
```diff
@@ -244,6 +244,20 @@ describe('api', () => {
         .then(() => mockWindow.verify());
     });
 
+    it('allows overrides to clientApp', () => {
+      // FIXME: This shouldn't fail if the args are in a different order.
```
Comment (kumar303) [inline tests/client/core/api/test_api.js]: ugh, yeah, I've noticed this too. It will be a bit annoying to fix.

File: src/core/api/index.js [hunk 6]
```diff
@@ -111,7 +111,11 @@ export function search({ api, page, auth = false, filters = {} }) {
...
+      app: filters.clientApp || api.clientApp,
```
Comment (kumar303) [inline src/core/api/index.js]: is there a test for this? I can't spot it.

File: src/core/searchUtils.js (hunk 4 above)
Comment (tofumatt) [inline src/core/searchUtils.js]: Yeah actually, I can do it in there for sure. I think I put it in two places because it compares the filters sent to callApi and those in state... but putting in it `search` is better I think.

File: src/core/api/index.js (hunk 6 above)
Comment (tofumatt) [inline src/core/api/index.js]: It's here: https://github.com/mozilla/addons-frontend/pull/1875/files#diff-da8c6fe27817853c3f04c9897c485535R247

But it's implicit because it's also about switching android -> firefox. I'll make it clearer.

File: src/amo/containers/CategoryPage.js (hunk 1 above)
Comment (tofumatt) [inline src/amo/containers/CategoryPage.js]: Done, filed https://github.com/mozilla/addons-server/issues/4766

**Comment by tofumatt** [comment]
Ready for another r?

File: src/core/api/index.js [hunk 7]
```diff
@@ -107,12 +108,28 @@ export function callApi({
 }
 
 export function search({ api, page, auth = false, filters = {} }) {
+  const _filters = { ...filters };
+  if (!_filters.clientApp && api.clientApp) {
```
Comment (kumar303) [inline src/core/api/index.js]: I think it would be nice to log a debug message here in case something surprising happens

File: src/core/api/index.js [hunk 8]
```diff
@@ -107,12 +108,28 @@ export function callApi({
...
+  // until github.com/mozilla/addons-frontend/issues/1723#issuecomment-278793546
+  // and https://github.com/mozilla/addons-server/issues/4766 are addressed.
+  // Essentially: right now there are no categories for the combo
+  // of "Android" + "Themes" but Firefox lightweight themes will work fine
+  // on mobile so we request "Firefox" + "Themes" for Android instead.
+  // Obviously we need to fix this on the API end so our requests aren't
+  // overridden, but for now this will work.
+  if (
+    _filters.clientApp === 'android' && _filters.addonType === ADDON_TYPE_THEME
+  ) {
```
Comment (kumar303) [inline src/core/api/index.js]: this could use debug logging too since setting `firefox` could be surprising

Comment (tofumatt) [inline src/core/api/index.js]: Good call. 😄
