### PR TITLE
Fix OpenSearch title

### LINKED ISSUE #9284: OpenSearch AMO engines are not recognised as already being installed
From https://bugzilla.mozilla.org/show_bug.cgi?id=1623063

**Steps to reproduce**
1. Launch Firefox
2. Add the Search bar in the toolbar
3. Go to https://addons.mozilla.org/en-US/firefox/
4, Click on the plus sign on the magnifying glass in the search bar
5. Click on Add "Firefox Addons (en-us)"

### What happened?
The search engine was added to the list of engines. However, the plus sign and the option to add the search engine are still displayed. 

### What did you expect to happen?
The plus sign and option to add the search engine should no longer be displayed

### Anything else we should know?

The problem here is that addons.mozilla.org is specifying the title differently to the xml file. In the html I see:

https://addons.mozilla.org/en-US/firefox/
```
<link data-react-helmet="true" title="Firefox Add-ons (en-US)" rel="search" type="application/opensearchdescription+xml" href="/en-US/firefox/opensearch.xml">
```

The xml file specifies:

https://addons.mozilla.org/en-US/firefox/opensearch.xml
```
<OpenSearchDescription>
  <ShortName>Firefox Add-ons</ShortName>
  <Url type="text/html" method="get" template="https://addons.mozilla.org/en-US/firefox/search/?q={searchTerms}"> </Url>
```

The problem here is that when Firefox tries to reconcile what is already installed, the title doesn't match between the installed engine ("Firefox Add-ons") and that provided by the page ("Firefox Add-ons (en-US)") so we think they are different.

Seeing as AMO provides a different URL in the opensearch.xml for each locale, I guess it would be possible to change the title in there for each locale as well.

### PR DESCRIPTION
**Pull request by xlisachan**
Fixes #9284 

- Updated the SearchForm component by removing the locales in the openSearchTitle localization strings
- Revised test file by removing the expectations that the link titles include the locales

Before:
Screen Shot 2020-03-25 at 10 23 18 AM

After:
Screen Shot 2020-03-25 at 10 22 20 AM

### CODE REVIEW

File: src/amo/components/SearchForm/index.js [hunk 1]
```diff
@@ -58,13 +58,13 @@ export class SearchFormBase extends React.Component<Props> {
     };
 
     let openSearchTitle = i18n.sprintf(
```
Comment (willdurand) [inline src/amo/components/SearchForm/index.js]: We do not need the call to `i18n.sprintf()` anymore so it can be removed here and below too. We also don't need the `i18nValues` variable.

Maybe we can have something like that in the end:

```
const openSearchTitle = clientApp === CLIENT_APP_ANDROID ? i18n.gettext(...) : i18n.gettext(...);
```

File: tests/unit/amo/components/TestSearchForm.js [hunk 2]
```diff
@@ -173,7 +173,6 @@ describe(__filename, () => {
 
     const link = root.find('link');
     expect(link).toHaveProp('href', `/${lang}/${clientApp}/opensearch.xml`);
-    expect(link).toHaveProp('title', `Firefox Add-ons for Android (${lang})`);
```
Comment (willdurand) [inline tests/unit/amo/components/TestSearchForm.js]: We should update the test cases (with new strings) instead of deleting assertions.

**Comment by xlisachan** [comment]
@willdurand , I was able to reproduce the issue. After the link title was updated, it recognized that it was  installed and "Add "Firefox Addons" is no longer there. Please see the requested revisions.

Screen Shot 2020-03-25 at 12 21 43 PM
