### PR TITLE
HMR for Redux

### LINKED ISSUE #1096: Make redux actions hot reloadable again
### Describe the problem and steps to reproduce it:

Run a dev server with the react hot reloader enabled. Example:

```
npm run dev:amo
```

Change the code in any action creator.
### What happened?

The old code is still running.
### What did you expect to happen?

The hot reloader should automatically reload the action code so that you don't have to refresh the entire page and potentially lose your state.
### Anything else we should know?

It looks like this was a regression in some upstream module but there are a couple different issues. See:
- https://github.com/reactjs/redux/issues/782
- https://github.com/gaearon/babel-plugin-react-transform/issues/26

React Hot Loader 3.0 should fix this. Preview: https://github.com/gaearon/react-hot-boilerplate/pull/61

### PR DESCRIPTION
**Pull request by willdurand**
Fix #1096

---

Add HMR for redux code. It is possible to add a new reducer without reloading and/or to change the code of a reducer. I have added some tests for the `core/client/base.js` file because the HMR code depends on it.

I enabled the `NamedModulesPlugin` webpack plugin to ease HMR debugging (it prints the filenames instead of numbers when something cannot be updated).

### CODE REVIEW

File: src/amo/client.js [hunk 1]
```diff
@@ -7,11 +10,18 @@ import App from './components/App';
 import sagas from './sagas';
 import createStore from './store';
 
-createClient(createStore, { sagas }).then(({ renderApp }) => {
+createClient(createStore, { sagas }).then(({ history, renderApp, store }) => {
   renderApp(App);
 
   if (module.hot) {
-    module.hot.accept('./components/App', () => {
+    module.hot.accept(['./sagas', './store'], () => {
```
Comment (kumar303) [inline src/amo/client.js]: It would be nice to see a comment here explaining that sagas aren't hot reloadable but this is needed to facilitate reducer/store reloading.

File: src/amo/client.js [hunk 2]
```diff
@@ -7,11 +10,18 @@ import App from './components/App';
...
+      // eslint-disable-next-line global-require
+      const { reducers } = require('./store');
+      const nextRootReducer = connectRouter(history)(combineReducers(reducers));
```
Comment (kumar303) [inline src/amo/client.js]: To minimize bugs, I'd like to see `connectRouter(history)(combineReducers(reducers))` moved to a function like `createRootReducer()` (or something) so it can also be called [in the real store](https://github.com/mozilla/addons-frontend/blob/bc32a8c978894f7dc2fbd1135cdc710a07dd6aec/src/amo/store.js#L133).

File: src/disco/client.js [hunk 3]
```diff
@@ -19,10 +21,17 @@ if (config.get('trackingSendInitPageView') === false) {
...
 
-createClient(createStore, { sagas }).then(({ renderApp }) => {
+createClient(createStore, { sagas }).then(({ history, renderApp, store }) => {
   renderApp(App);
 
   if (module.hot) {
+    module.hot.accept(['./sagas', './store'], () => {
+      // eslint-disable-next-line global-require
+      const { reducers } = require('./store');
+      const nextRootReducer = connectRouter(history)(combineReducers(reducers));
```
Comment (kumar303) [inline src/disco/client.js]: This may also benefit from a `createRootReducer()` function.

File: tests/unit/core/client/test_base.js [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+describe(__filename, () => {
+  describe('createClient()', () => {
+    const fakeCreateStore = () => {
+      return {
+        sagaMiddleware: null,
+        store: null,
+      };
+    };
+
+    const fakeFastClick = {
```
Comment (kumar303) [inline tests/unit/core/client/test_base.js]: I'd rather see this initialized before every test otherwise the call history of the stub *might* leak across tests. It might not because of [sandboxing](https://github.com/mozilla/addons-frontend/blob/master/tests/setup.js#L71) but I'd feel better if it were a new instance mainly as not to obscure the intention of the code 😀 

For easy access in assertions, we usually do it like:

```js
let fakeFastClick;

beforeEach(() => {
  fakeFastClick = {
    attach: sinon.stub(),
  };
});
```

File: webpack.dev.config.babel.js [hunk 5]
```diff
@@ -71,6 +71,7 @@ export default Object.assign({}, webpackConfig, {
       'react-dom/umd/react-dom.development.js',
     ),
     new webpack.NormalModuleReplacementPlugin(/^redux$/, 'redux/dist/redux.js'),
+    new webpack.NamedModulesPlugin(),
```
Comment (kumar303) [inline webpack.dev.config.babel.js]: D'oh. Good find. It looks like this will be the default for development in [webpack 4](https://github.com/webpack/webpack/issues/3476#issuecomment-368300958).

File: src/amo/client.js (hunk 2 above)
Comment (willdurand) [reply src/amo/client.js]: That totally makes sense :+1:

**Comment by willdurand** [comment]
rebased.
