### PR TITLE
Address layout issue for non-logged-in UserProfileEdit page

### LINKED ISSUE #8738: The layout of the page is broken after I log out from edit profile page
STR:
1. Login and go to edit profile page 
2. Log out and notice the layout 

Expected result:
Page should look like this 

as it should be

Actual result:

regression

Notes:
This is not reproducible when I log out from other pages (at least I could not reproduce it elsewhere). 
It is reproducible on AMO dev and AMO stage with FF69(Win10). 
Not reproducible on AMO prod.

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #8738 

Note that I am going to review the code for the `render` function of all `page` components to see if this problem might exist elsewhere as well.

### CODE REVIEW

File: src/amo/pages/UserProfileEdit/index.js [hunk 1]
```diff
@@ -465,14 +465,16 @@ export class UserProfileEditBase extends React.Component<Props, State> {
...
       return (
-        <div className="UserProfileEdit">
-          <Card className="UserProfileEdit-authenticate">
-            <AuthenticateButton
-              noIcon
-              logInText={i18n.gettext('Log in to edit the profile')}
-            />
-          </Card>
-        </div>
+        <Page>
```
Comment (kumar303) [inline src/amo/pages/UserProfileEdit/index.js]: It would be nicer to move this to a variable like `output` so that `render()` can wrap *any* kind of output in `<Page>`. This approach might prevent the bug from happening again.

This is just a suggestion for an enhancement and doesn't need to block landing this feature.

Comment (bobsilverberg) [reply src/amo/pages/UserProfileEdit/index.js]: Good idea. I'll make that change.

File: src/amo/pages/UserProfileEdit/index.js [hunk 2]
```diff
@@ -463,8 +463,10 @@ export class UserProfileEditBase extends React.Component<Props, State> {
       userId,
     } = this.props;
 
+    let alternateOutput;
+
     if (!currentUser) {
-      return (
+      alternateOutput = (
```
Comment (kumar303) [inline src/amo/pages/UserProfileEdit/index.js]: Since this is no longer returning, it would be safer to wrap everything below it in an else statement. I'm not sure what the error handling code is going to do, for example.

**Comment by bobsilverberg** [comment]
> Hmm, what is this going to do?
> 
> https://github.com/mozilla/addons-frontend/blob/262cafdc6d0aa45ebb0bee2534a2f694857e91e2/src/amo/pages/UserProfileEdit/index.js#L484
> 

This should be fine because `<NotFound>` itself wraps its output in `<Page>`. There is code line this in a number of `render` functions in page components and it works because `<NotFound>` includes `<Page>`, so I think this is a non-issue. Do you agree?

**Comment by kumar303** [comment]
> This should be fine because `<NotFound>` itself wraps its output in `<Page>`. There is code line this in a number of `render` functions in page components and it works because `<NotFound>` includes `<Page>`, so I think this is a non-issue. Do you agree?



There's no way to look at this output and *guess* what will happen (whether a nested component will be wrapped in Page or not) so I think it's fragile but I'm all for shipping whatever works and fixing it later.

**Comment by willdurand** [comment]
> There's no way to look at this output and _guess_ what will happen (whether a nested component will be wrapped in Page or not) so I think it's fragile but I'm all for shipping whatever works and fixing it later.

I think that's because `NotFound` and other similar components should be in the `pages` folder (and we should likely import them as `NotFoundPage`).

**Comment by kumar303** [comment]
TBH, I was suggesting to ship your first patch because that is the least disruptive. Otherwise, I'd like to see an else statement in here to make sure the error handling code doesn't execute (since it can return output).

**Comment by bobsilverberg** [comment]
> TBH, I was suggesting to ship your first patch because that is the least disruptive. Otherwise, I'd like to see an else statement in here to make sure the error handling code doesn't execute (since it can return output).

I've made both changes.

**Comment by kumar303** [comment]
> I think that's because `NotFound` and other similar components should be in the `pages` folder (and we should likely import them as `NotFoundPage`).

That's what I'm thinking, too. However, we probably want to keep the `NotFound` and friends in components so that other page components can return them in conditionals if they need to. In other words, adding `pages/NotFoundPage`, etc, as wrappers would make more sense for when we need them to be [routes](https://github.com/mozilla/addons-frontend/blob/262cafdc6d0aa45ebb0bee2534a2f694857e91e2/src/amo/components/Routes/index.js#L166). Keeping both around would help make it obvious what the rendered output will be.

**Comment by willdurand** [comment]
> That's what I'm thinking, too. However, we probably want to keep the `NotFound` and friends in components so that other page components can return them in conditionals if they need to. In other words, adding `pages/NotFoundPage`, etc, as wrappers would make more sense for when we need them to be [routes](https://github.com/mozilla/addons-frontend/blob/262cafdc6d0aa45ebb0bee2534a2f694857e91e2/src/amo/components/Routes/index.js#L166). Keeping both around would help make it obvious what the rendered output will be.

Oh yeah, I agree.
