### PR TITLE
fix: Don't spread theme_data description

### LINKED ISSUE #2233: "None" text listed for theme with no description
Steps to reproduce:

1. Load https://addons.allizom.org/en-US/android/ (or any version of AMO)
2. Search for a theme without a description. Example: search for 'Flag of France'
3. Tap the result to view the theme detail page

Expected results:
No text displayed in the "About this persona" section.

Actual results:
"None" text is displayed.

Notes/Issues:
* If you refresh the page while on the detail view, the "None" goes away

Verified on FF52(Win 7). Issue is reproduced all around AMO-servers.

none

### LINKED ISSUE #2569: Theme without description have layout issues in details page
Steps to reproduce:
1. Load details page on desktop for a theme without a description i.e. https://addons-dev.allizom.org/en-US/firefox/addon/cute-pastel-flowers/

Expected results:
There are no display or layout issues.

Actual results:
"None" text is affecting the review section.

Notes/Issues:
Verified on AMO-dev FF53(Android 7.1.2).
Screenshot for this issue:
none2

### PR DESCRIPTION
**Pull request by tofumatt**
Hide the "About this extension" when description and summary are blank.

Fixes #2233.
Fixes #2569.

### Desktop
screenshot 2017-06-15 01 20 19

### Mobile
screen shot 2017-06-15 at 01 20 35

### CODE REVIEW

File: src/core/reducers/addons.js [hunk 1]
```diff
@@ -30,6 +30,12 @@ export default function addon(state = initialState, action) {
         newState[key] = {
           ...thisAddon,
           ...thisAddon.theme_data,
+          // TODO: Remove this when
+          // https://github.com/mozilla/addons-frontend/issues/1416 is fixed.
+          // theme_data will contain `description: 'None'` when the description
```
Comment (kumar303) [inline src/core/reducers/addons.js]: do we have an API bug on file for this yet?

File: src/core/reducers/addons.js [hunk 2]
```diff
@@ -30,6 +30,12 @@ export default function addon(state = initialState, action) {
         newState[key] = {
           ...thisAddon,
           ...thisAddon.theme_data,
```
Comment (kumar303) [inline src/core/reducers/addons.js]: table-flip

File: src/core/reducers/addons.js [hunk 3]
```diff
@@ -30,6 +30,12 @@ export default function addon(state = initialState, action) {
...
+          // TODO: Remove this when
+          // https://github.com/mozilla/addons-frontend/issues/1416 is fixed.
+          // theme_data will contain `description: 'None'` when the description
+          // is actually `null` and we don't want to set that on the addon
+          // itself so we reset it in case it's been overwritten.
+          description: thisAddon.description,
```
Comment (kumar303) [inline src/core/reducers/addons.js]: yep, good call 🌤

File: tests/unit/core/reducers/test_addons.js [hunk 4]
```diff
@@ -82,4 +82,38 @@ describe('addon reducer', () => {
       },
     });
   });
+
+  it('does not use description from theme_data', () => {
+    // See: https://github.com/mozilla/addons-frontend/issues/2569
+    // TODO: Remove this when
```
Comment (kumar303) [inline tests/unit/core/reducers/test_addons.js]: I don't think you need a TODO here. It's enough to put it in the offending code.

File: tests/unit/core/reducers/test_addons.js [hunk 5]
```diff
@@ -82,4 +82,38 @@ describe('addon reducer', () => {
...
+              slug: 'baz',
+              id: 42,
+              theme_data: { theme_thing: 'some-data', description: 'None' },
+              type,
+            },
+          },
+        },
+      },
+    });
+    expect(state).toEqual({
```
Comment (kumar303) [inline tests/unit/core/reducers/test_addons.js]: I think checking the whole state is overkill and will introduce a maintenance burden. Can you try to only assert the `description` property? I think this will do it but make sure it fails without your fix:

```js
expect(state).toEqual(expect.objectContaining({
  baz: { description: null },
})).
```

File: tests/unit/core/reducers/test_addons.js [hunk 6]
```diff
@@ -82,4 +82,38 @@ describe('addon reducer', () => {
       },
     });
   });
+
+  it('does not use description from theme_data', () => {
+    // See: https://github.com/mozilla/addons-frontend/issues/2569
+    // TODO: Remove this when
+    // https://github.com/mozilla/addons-frontend/issues/1416 is fixed.
+    const type = ADDON_TYPE_THEME;
+    const state = addons(originalState, {
```
Comment (kumar303) [inline tests/unit/core/reducers/test_addons.js]: I think it will be easy to convert this test file to use real actions instead of simulated actions. I wouldn't suggest that if I thought it would slow you down significantly, I swear.  😁 

There are only 5 tests to fix! Here's [how to use the `loadEntities` action](https://github.com/mozilla/addons-frontend/blob/master/tests/unit/core/test_utils.js#L423).

File: src/core/reducers/addons.js (hunk 2 above)
Comment (kumar303) [inline src/core/reducers/addons.js]: Not you fault, I know. I just had to let it out.

Comment (tofumatt) [inline src/core/reducers/addons.js]: Oh I'm right there with you.

File: src/core/reducers/addons.js (hunk 1 above)
Comment (tofumatt) [inline src/core/reducers/addons.js]: I've filed https://github.com/mozilla/addons-server/issues/5650 but I suspect it might be a requirement because we put that object in the weird `data-browsertheme` or whatever. Still, filed! I'll add it to the comment.

File: tests/unit/core/reducers/test_addons.js (hunk 5 above)
Comment (tofumatt) [inline tests/unit/core/reducers/test_addons.js]: Agreed, just doing what was already done but I guess I'm refactoring the tests anyway 😉

Comment (kumar303) [inline tests/unit/core/reducers/test_addons.js]: > ...just doing what was already done

Nothing is that easy on `addons-frontend` !

Comment (tofumatt) [inline tests/unit/core/reducers/test_addons.js]: I forgot to do this part, one second.

Comment (tofumatt) [inline tests/unit/core/reducers/test_addons.js]: Done. The actual test just looks like:

```js
expect(state).toMatchObject({
    baz: { theme_thing: 'some-data', },
});
```

File: tests/unit/core/reducers/test_addons.js [hunk 7]
```diff
@@ -1,28 +1,36 @@
...
+    addonsState = addons({},
+      loadEntities(createFetchAddonResult(fakeAddon).entities));
+    addonsState = addons(addonsState,
+      loadEntities(createFetchAddonResult(anotherFakeAddon).entities));
   });
 
   it('returns the old state', () => {
-    expect(originalState).toBe(addons(originalState, { type: 'BLAH' }));
+    expect(addonsState)
+      .toEqual(addons(addonsState, { type: 'UNRELATED_ACTION' }));
```
Comment (kumar303) [inline tests/unit/core/reducers/test_addons.js]: 👍 

I always get confused by unrealistic values -- this is better, thanks :)

File: tests/unit/core/reducers/test_addons.js [hunk 8]
```diff
@@ -34,13 +42,14 @@ describe('addon reducer', () => {
         files: [fileOne, fileTwo],
```
Comment (kumar303) [inline tests/unit/core/reducers/test_addons.js]: It would be nice if `addon` here extended `fakeAddon` just to future proof the properties:
```js
const addon = {
  ...fakeAddon,
  slug: 'installable',
  current_version: {
    ...fakeAddon.current_version,
    files: [fileOne, fileTwo],
  },
};
```

File: tests/unit/core/reducers/test_addons.js [hunk 9]
```diff
@@ -49,37 +58,48 @@ describe('addon reducer', () => {
       slug: 'installable',
```
Comment (kumar303) [inline tests/unit/core/reducers/test_addons.js]: Same thing here. The `addon` object should extend from `fakeAddon`.

File: tests/unit/core/reducers/test_addons.js [hunk 10]
```diff
@@ -49,37 +58,48 @@ describe('addon reducer', () => {
...
-    const type = ADDON_TYPE_THEME;
-    const state = addons(originalState, {
-      payload: {
-        entities: {
-          addons: {
-            baz: { slug: 'baz', id: 42, theme_data: { theme_thing: 'some-data' }, type },
-          },
-        },
-      },
+    const theme = {
```
Comment (kumar303) [inline tests/unit/core/reducers/test_addons.js]: this should extend from `fakeAddon` to future proof the properties (in case new required properties are introduced).

File: tests/unit/core/reducers/test_addons.js [hunk 11]
```diff
@@ -49,37 +58,48 @@ describe('addon reducer', () => {
...
-        guid: '42@personas.mozilla.org',
-        type: ADDON_TYPE_THEME,
-      },
+  });
+
+  it('does not use description from theme_data', () => {
+    // See: https://github.com/mozilla/addons-frontend/issues/2569
+    // Can be removed when
+    // https://github.com/mozilla/addons-frontend/issues/1416 is fixed.
+    const theme = {
```
Comment (kumar303) [inline tests/unit/core/reducers/test_addons.js]: this should extend from `fakeAddon`

File: tests/unit/core/reducers/test_addons.js (hunk 8 above)
Comment (tofumatt) [inline tests/unit/core/reducers/test_addons.js]: Yeah agreed actually, I was lazy, thanks for calling me out on it ^_^

**Comment by tofumatt** [comment]
Good ideas; added `...fakeAddon` to all the objects.
