### PR TITLE
fix: Use InstallButton all the time on AMO (fix #3557)

### LINKED ISSUE #3557: Change install switch to install button on AMO
According to our user research the install switch performs very poorly so we should disable it and use the fallback `InstallButton` everywhere on AMO for now. In the future we'll want to improve the button, but switching to it for MVP.

### PR DESCRIPTION
**Pull request by tofumatt**
Force the InstallButton to always be a button on AMO.

Note that the Disco Pane should still stay a switch because it's nice to have a toggle there and it's less an issue.

### After

screenshot 2017-10-18 21 35 53

### CODE REVIEW

File: tests/unit/core/components/TestInstallButton.js [hunk 1]
```diff
@@ -205,6 +205,38 @@ describe(__filename, () => {
     expect(button).toHaveProp('disabled', true);
   });
 
+  it('renders a switch button if useButton is false', () => {
+    const root = render({
+      addon: createInternalAddon({
```
Comment (willdurand) [inline tests/unit/core/components/TestInstallButton.js]: Why is this needed?

File: tests/unit/core/components/TestInstallButton.js [hunk 2]
```diff
@@ -205,6 +205,38 @@ describe(__filename, () => {
...
+        ...fakeAddon,
+        hasAddonManager: true,
+      }),
```
Comment (kumar303) [inline tests/unit/core/components/TestInstallButton.js]: I think you meant:

```js
const root = render({
  addon: createInternalAddon({
    ...fakeAddon,
  }),
  hasAddonManager: true,
});
```

And in the other test.

File: tests/unit/core/components/TestInstallButton.js (hunk 1 above)
Comment (tofumatt) [reply tests/unit/core/components/TestInstallButton.js]: Turns out: it's not! Copied from another test and assumed it was needed, but it wasn't.

File: tests/unit/core/components/TestInstallButton.js (hunk 2 above)
Comment (tofumatt) [reply tests/unit/core/components/TestInstallButton.js]: Yeah, bad assumptions in copypasta, fixing up now.

**Comment by muffinresearch** [comment]
Does dead code elimination mean we're not including the mozAddonManager install button code and CSS?

**Comment by tofumatt** [comment]
No, because it’s still used on Disco Pane and a fair bit of the code will be useful in the future. I think the safest/quickest route is just to supply the `useButton` prop for now.
