### PR TITLE
Fix shelf types (and rename types/functions for clarity)

### LINKED ISSUE #10496: Fix addon_type property for homepage shelves
Per QA feedback in #10357 and #10438, themes are not displaying correctly for homepage shelves.

The shelves are missing the`addonType` property.

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #10496

### CODE REVIEW

File: tests/unit/helpers.js [hunk 1]
```diff
@@ -224,12 +224,12 @@ export const fakeReview = Object.freeze({
...
 });
 
-export const fakeShelf = Object.freeze({
+export const fakeExternalShelf = Object.freeze({
   title: createLocalizedString('Top Rated Themes'),
   url:
     'https://addons-dev.allizom.org/api/v5/addons/search/?sort=rating&type=statictheme',
   endpoint: 'search-themes',
-  addonType: ADDON_TYPE_STATIC_THEME,
+  addon_ype: ADDON_TYPE_STATIC_THEME,
```
Comment (eviljeff) [inline tests/unit/helpers.js:232]: 😬

File: src/amo/reducers/home.js [hunk 2]
```diff
@@ -100,6 +100,9 @@ export type ExternalHeroCallToActionType = {|
   text: LocalizedString | null,
 |};
 
+// Type definitions are the same but we have an alias for better readability.
+export type ExternalFooterType = ExternalHeroCallToActionType;
```
Comment (eviljeff) [inline src/amo/reducers/home.js:104]: yeah... so why are we doing this?  We changed the API to use the CTA format so frontend wouldn't need to have two subtly different data structures for essentially the same thing and now we have the exact same data structure here but defined twice. Can't we just rename `ExternalHeroCallToActionType` and `createInternalHeroCallToAction ` to something more generic to still be DRY?

File: tests/unit/helpers.js (hunk 1 above)
Comment (eviljeff) [reply tests/unit/helpers.js:232]: Also, this is still passing? That's concerning.

Comment (willdurand) [reply tests/unit/helpers.js:232]: SERIOUSLY? 🤦

File: src/amo/reducers/home.js (hunk 2 above)
Comment (willdurand) [reply src/amo/reducers/home.js:104]: Would you have a name to suggest? I couldn't find one...

File: tests/unit/helpers.js (hunk 1 above)
Comment (willdurand) [reply tests/unit/helpers.js]: I think it's passing because we override `addon_type` every time we use this fake object.

File: src/amo/reducers/home.js (hunk 2 above)
Comment (eviljeff) [reply src/amo/reducers/home.js:104]: thinking, what it effectively is: `ExternalLinkWithTextType` and `CreateInternalLinkWithText`?  not great, I'll admit.

Comment (willdurand) [reply src/amo/reducers/home.js:104]: I take that.

**Review by eviljeff — APPROVED** [review]
