### PR TITLE
showing a warning for non public add-0n

### LINKED ISSUE #4244: Show a warning when viewing a non-public add-on
### Describe the problem and steps to reproduce it:

As an admin, log in to AMO and view the detail page for a disabled add-on

*or*

As a developer, upload an add-on, make it non-public, log in to AMO and view its detail page

### What happened?

You see a complete detail page as if nothing was different

### What did you expect to happen?

You should see a warning saying that the add-on is not public but you're seeing it anyway because you have elevated privileges.

### Anything else we should know?

This has created confusion a couple of times from admins or developers who are not expecting to see a public listing.

It should be pretty easy to fix:

```diff
diff --git a/src/amo/components/Addon/index.js b/src/amo/components/Addon/index.js
index a2d4eec21..52e2b4d4e 100644
--- a/src/amo/components/Addon/index.js
+++ b/src/amo/components/Addon/index.js
@@ -53,6 +53,7 @@ import Card from 'ui/components/Card';
 import Icon from 'ui/components/Icon';
 import LoadingText from 'ui/components/LoadingText';
 import ShowMoreCard from 'ui/components/ShowMoreCard';
+import Notice from 'ui/components/Notice';
 
 import './styles.scss';
 
@@ -537,6 +538,11 @@ export class AddonBase extends React.Component {
                 reason={compatibility.reason}
               />
             ) : null}
+            {addon && addon.status !== 'public' ? (
+              <Notice type="error">
+                {i18n.gettext('This is not a public listing. You are only seeing it because of elevated permissions.')}
+              </Notice>
+            ) : null}
             <header className="Addon-header">
               {this.headerImage({ compatible: isCompatible })}
 
```

### PR DESCRIPTION
**Pull request by championshuttler**
Fixes #4244

### CODE REVIEW

File: src/core/types/addons.js [hunk 1]
```diff
@@ -1,9 +1,11 @@
 /* @flow */
 import type { AddonTypeType } from 'core/constants';
 
+export const STATUS_PUBLIC: 'public' = 'public';
```
Comment (rebmullin) [inline src/core/types/addons.js]: I personally think the constant here should be moved to core/constants

Comment (willdurand) [reply src/core/types/addons.js]: I second @rebmullin's comment

Comment (willdurand) [reply src/core/types/addons.js]: @rebmullin is right, but I am not even sure we really need a constant outside the component.

Comment (championshuttler) [reply src/core/types/addons.js]: So do I need to move this to core/constants or can we use 'public' directly?

Comment (willdurand) [reply src/core/types/addons.js]: You can use a constant but only in the component file.

Comment (rebmullin) [reply src/core/types/addons.js]: also, I think this could just be `export const STATUS_PUBLIC = 'public';`

Comment (championshuttler) [reply src/core/types/addons.js]: mine dumbness++ :man_facepalming:

Comment (rebmullin) [reply src/core/types/addons.js]: hey @championshuttler, sorry for the confusion but I think what @willdurand suggests is better... to put this constant in the component file itself. If this ends up being a constant we need over and over we can move it back the core/constants file

**Comment by rebmullin** [comment]
hi @championshuttler, just making sure you saw the feedback on the questions above:

https://github.com/mozilla/addons-frontend/issues/4244#issuecomment-414024659

**Comment by championshuttler** [comment]
Hey @willdurand , can you please review it, I and @rebmullin tried another way also to write test case but it's not working.

We wrote test case firstly for verification of admin/developer and  `error` will appear to developer/admins only. 
```
  it('displays a notice on a disabled addon to [admin/developer]', () => {
    const { store } = dispatchSignInActions({
      userProps: {
        is_addon_developer: true,
        display_name: 'imadev',
        userId: 100,
        username: 'iamdev',
      },
    });

    const addon = createInternalAddon({
      ...fakeAddon,
      status: 'disabled',
    });

    const root = shallowRender({ addon, store });
    expect(root.find(Notice)).toHaveLength(1);
  });
  });
```

But this test case is working in both case like when we set true for `is_addon_developer` but its also passing when its `false` :astonished:

**Comment by championshuttler** [comment]
Added 10 px margin .
Before
https://camo.githubusercontent.com/e2ab12e980ba57ffbd9533b6ba3d228c342cbd1e/68747470733a2f2f6d6f6e6f736e61702e636f6d2f696d6167652f4955485071356f4e32314a5430696634324c4a7258724f303377787a34572e706e67
image

After: 
screenshot_2018-08-22 idkhtml add-ons for firefox 2

On Mobile 
Before 
movile

After 
screenshot_2018-08-22 idkhtml add-ons for firefox 1

File: src/ui/components/Notice/styles.scss [hunk 2]
```diff
@@ -11,6 +11,7 @@
   grid-gap: 4px;
   grid-template-columns: min-content auto;
   line-height: 1.1;
+  margin-bottom: 10px;
```
Comment (willdurand) [inline src/ui/components/Notice/styles.scss]: This will probably add a `margin` to all `Notice` components, which might not be a good idea.

File: tests/unit/amo/components/TestAddon.js [hunk 3]
```diff
@@ -1566,4 +1568,42 @@ describe(__filename, () => {
       expect(installButton).toHaveProp('uninstall', uninstall);
     });
   });
+
+  it('displays a notice to the admin/developer on a disabled addon', () => {
```
[the remark this answers is not in the document]
Comment (willdurand) [reply tests/unit/amo/components/TestAddon.js]: There should be one test case for an admin and one test case for the developer of the add-on.

`is_addon_developer` does not control anything because the API performs the permissions check. We should probably leave a comment mentioning that: "non-public add-ons require an account listed as a developer of the add-on or admin rights".

File: src/ui/components/Notice/styles.scss (hunk 2 above)
Comment (championshuttler) [reply src/ui/components/Notice/styles.scss]: Yes, you are correct, it will add margin to every Notice component.
 Should I define inline css for it?

**Comment by championshuttler** [comment]
Hi @willdurand i added test case for developer can you please review :see_no_evil:

File: src/ui/components/Notice/styles.scss (hunk 2 above)
Comment (championshuttler) [reply src/ui/components/Notice/styles.scss]: I think here https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/Addon/styles.scss#L67 ;)

Comment (willdurand) [reply src/ui/components/Notice/styles.scss]: Then, I'll add a class name to the `Notice` you've added and change the SCSS like this:

```scss
.AddonCompatibilityError,
.YourNewClassName {
  ...
}
```

Comment (championshuttler) [reply src/ui/components/Notice/styles.scss]: Got it :dancer:

Comment (championshuttler) [reply src/ui/components/Notice/styles.scss]: Fixed  :man_dancing: 

After changes
screenshot_2018-08-24 idkhtml add-ons for firefox 1
screenshot_2018-08-24 idkhtml add-ons for firefox

File: src/amo/components/Addon/index.js [hunk 4]
```diff
@@ -500,7 +500,7 @@ export class AddonBase extends React.Component {
               />
             ) : null}
             {addon && addon.status !== STATUS_PUBLIC ? (
-              <Notice type="error">
+              <Notice type="error" className="Non-public-addon-notice">
```
Comment (willdurand) [inline src/amo/components/Addon/index.js]: I think it should start with `Addon`, like `Addon-non-public-notice`.

Comment (championshuttler) [reply src/amo/components/Addon/index.js]: :man_facepalming: Done :)

**Comment by rebmullin** [comment]
hey @championshuttler, travis is reporting an error. I think if you rebase, it should get fixed..

File: tests/unit/amo/components/TestAddon.js [hunk 5]
```diff
@@ -1566,4 +1568,71 @@ describe(__filename, () => {
       expect(installButton).toHaveProp('uninstall', uninstall);
     });
   });
+  // non-public add-ons require an account listed as a developer of the add-on or admin rights
```
Comment (rebmullin) [inline tests/unit/amo/components/TestAddon.js]: hey @championshuttler, can you capitalize the first letter Non-public.. and end with a period?

Comment (championshuttler) [reply tests/unit/amo/components/TestAddon.js]: :+1:

File: tests/unit/amo/components/TestAddon.js [hunk 6]
```diff
@@ -1566,4 +1568,71 @@ describe(__filename, () => {
...
+    const addon = createInternalAddon({
+      ...fakeAddon,
+      status: 'disabled',
+    });
+
+    const root = shallowRender({
+      addon,
+      store: dispatchSignInActions({
+        userProps: {
+          permissions: [ALL_SUPER_POWERS],
```
Comment (rebmullin) [inline tests/unit/amo/components/TestAddon.js]: so @willdurand this is a sufficient test? if we do `permission: []` here, the test still passes (same with the below case - if we say `is_addon_developer: false` for the dev case). I understand the API will return a 403/404 if they are not authorized/logged in but I guess I am still a little confused myself on the usefulness of these tests shown in this way b/c if you change the details in the way I noted above it still passes. Maybe we should add more comment about this not even being reached (or the test case that checks this)? If that makes sense..

But if you're ok with this, then I'll defer to you : )

Comment (willdurand) [reply tests/unit/amo/components/TestAddon.js]: right, maybe a single test case would be enough.

Comment (championshuttler) [reply tests/unit/amo/components/TestAddon.js]: @willdurand thanks for the quick reply , should i delete the test case for developer?

Comment (willdurand) [reply tests/unit/amo/components/TestAddon.js]: yeah, I think @rebmullin is right. we should have test cases that fail if we change something, so I suppose we only need one test case that is the opposite of when api returns 403.

Comment (rebmullin) [reply tests/unit/amo/components/TestAddon.js]: @willdurand, so there is already this test case:

```javascript
it('renders NotFound page for forbidden add-on - 403 error', () => {
    const { store } = dispatchClientMetadata();

    const error = createApiError({
      response: { status: 403 },
      apiURL: 'https://some/api/endpoint',
      jsonResponse: { message: 'You do not have permission.' },
    });
    const errorHandler = new ErrorHandler({
      id: 'some-id',
      dispatch: store.dispatch,
    });
    errorHandler.handle(error);

    const root = renderComponent({ errorHandler, store });
    expect(root.find(NotFound)).toHaveLength(1);
  });
```

is this sufficient? I mean it shows that a 403 gives Notfound page..

and maybe we can just add the following to the above test:
`expect(root.find(Notice)).toHaveLength(0);` 

would that work?

(on top of merging the above dev and admin tests as you suggest above)

Comment (rebmullin) [reply tests/unit/amo/components/TestAddon.js]: still using the comment above the test case:
`// Non-public add-ons require an account listed as a developer of the add-on or admin rights.`

Comment (willdurand) [reply tests/unit/amo/components/TestAddon.js]: We keep the comment and we add a test case indicating that we display a notice message when an admin or the developer views the page.

**Comment by rebmullin** [comment]
looks 👍  to me. Thanks @championshuttler for tackling this one : )
