### PR TITLE
Change wording of Line badge tooltip

### LINKED ISSUE #10005: UX: Badge descriptions may give undesired impression
### Describe the problem and steps to reproduce it:

Look at the hover text for both a verified add-on and an official add-on.
Verified:
image

Official:

image

### What happened?

I interpreted the texts as follows:
- verified is very specific -- I know it is secure
- official is generic -- no mention of security
- For me "specific" trumps "generic", so I infer that there is no security statement about an "official" add-on

### What did you expect to happen?

I'd expect that anything we produce and ship under the Firefox brand has been appropriately checked for security and performance to at least the extent of a verified add-on.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Even after reading the [badge descriptions on SUMO](https://support.mozilla.org/en-US/kb/add-on-badges) (which I had to be told how to access -- it wasn't obvious to me), there was no material that led me to change my initial impression. Yes, _everything_ is reviewed for security per the sumo page, but:
- the "more specific" code review is again for verified extensions (details of payment and resource availability)
- the ordering of badges can be interpreted as going from a lower level of trust (recommended) to a higher level (verified), with official somewhere in between

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #10005

### CODE REVIEW

File: src/amo/components/PromotedBadge/index.js [hunk 1]
```diff
@@ -40,7 +40,7 @@ export const PromotedBadgeBase = ({
     case 'line':
       label = i18n.gettext('By Firefox');
       linkTitle = i18n.gettext(
-        'This is an official add-on built by the creators of Mozilla Firefox.',
+        'Official add-on built by Mozilla Firefox. Meets security and performance standards.',
```
Comment (eviljeff) [inline src/amo/components/PromotedBadge/index.js:43]: imo the phrasing is a little weird (e.g. "Meets security and performance standards." vs. "has been reviewed to meet our standards for security and performance") compared to the other two but 🤷 that's what's been decided.

**Review by eviljeff — APPROVED** [review]

File: src/amo/components/PromotedBadge/index.js (hunk 1 above)
Comment (bobsilverberg) [reply src/amo/components/PromotedBadge/index.js:43]: It is indeed what has been decided!
