### PR TITLE
Screenshot viewer on add-on detail

### LINKED ISSUE #936: Get add-on screenshots working
The add-on detail page was hooked up to API data in https://github.com/mozilla/addons-frontend/issues/883 but the screenshot widget is not working yet. It needs images and navigation, etc.

### PR DESCRIPTION
**Pull request by mstriemer**
Going to look through this diff one more time later tonight but wanted to get the PR up.

screenshots-portrait mov

screenshots-landscape mov

Fixes #936.

### CODE REVIEW

**Comment by kumar303** [comment]
This looks shiny!

**Comment by mstriemer** [comment]
@pwalm I have a version with the scroll indicator like in the mocks too but it unfortunately dropped the frame rate down to 10-20 fps on my OnePlus 3 so I'm thinking that might be a deal breaker on lower level hardware.

If you really want that to be a thing then let me know and I can look into optimising it but I'm not seeing what else I can do with it right now.

We'll need the dimensions of the images in the API response to make them format a little nicer. I have a start on a patch that I'll look at landing later but this is probably good enough for now.

File: src/amo/components/ScreenShots.js [hunk 1]
```diff
@@ -1,41 +1,59 @@
...
+  render() {
+    const { previews } = this.props;
+    const items = previews.map((preview) => ({
+      src: preview.image_url,
+      thumbnail_src: preview.thumbnail_url,
+      h: HEIGHT,
+      w: WIDTH,
+      title: preview.caption,
+    }));
+    const photoSwipeOptions = {
```
Comment (tofumatt) [inline src/amo/components/ScreenShots.js]: Setting this in the `render()` when it doesn't ever change based on props seems odd to me; I don't _really_ think the performance difference matters, but it just doesn't seem like it needs to be here.

If it could be moved out that'd be cool.

File: src/amo/components/ScreenShots.js [hunk 2]
```diff
@@ -1,41 +1,59 @@
...
+      closeEl: true,
+      captionEl: true,
+      fullscreenEl: false,
+      zoomEl: false,
+      shareEl: false,
+      counterEl: true,
+      arrowEl: true,
+      preloaderEl: true,
+    };
     return (
```
Comment (tofumatt) [inline src/amo/components/ScreenShots.js]: A newline here to separate out the return and the method setup would be nice.

File: src/amo/components/ScreenShots.js [hunk 3]
```diff
@@ -1,41 +1,59 @@
...
+          <PhotoSwipeGallery
+            className="ScreenShots-list" close={this.onClose} items={items}
+            options={photoSwipeOptions} thumbnailContent={this.thumbnailContent} />
+        </div>
       </div>
     );
   }
 }
-
-export default translate({ withRef: true })(ScreenShotsBase);
```
Comment (tofumatt) [inline src/amo/components/ScreenShots.js]: 🎉

File: tests/client/amo/components/TestScreenShots.js [hunk 4]
```diff
@@ -0,0 +1,72 @@
+import React from 'react';
+import { renderIntoDocument } from 'react-addons-test-utils';
+import { PhotoSwipeGallery } from 'react-photoswipe';
+
+import ScreenShots from 'amo/components/ScreenShots';
+import { shallowRender } from 'tests/client/helpers';
+
+describe('<ScreenShots />', () => {
+  const onePxImg = 'data:image/gif;base64,R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs=';
```
Comment (tofumatt) [inline tests/client/amo/components/TestScreenShots.js]: Bytes are cheap, we can call this `onePixelImage`

Comment (tofumatt) [inline tests/client/amo/components/TestScreenShots.js]: Unless you are just trying to get it under 80 chars... in which case I guess it's okay but I really dislike short variable names like this. 😃

Comment (tofumatt) [inline tests/client/amo/components/TestScreenShots.js]: Also this is only used in one test, it could go into there as it really only relates to it (for now, anyway).

**Comment by pwalm** [comment]
This looks SUPER good. Instead of a scrollbar, can we style the "1/5" to look nicer? I'll work on styling the description copy as well.
