### PR TITLE
I4917 screenshot size fix

### LINKED ISSUE #4197: Add-on screenshot images up-scaling degrades quality
I noticed that on AMO screens/images are up-scaled which causes them to lose clarity, especially for small images.

Example:
https://addons.mozilla.org/en-US/firefox/addon/foxytab/

Transferred from: https://github.com/mozilla/addons/issues/627

### PR DESCRIPTION
**Pull request by rebmullin**
fixes #4197 - 

instead of scaling up we are now we are using the actual image size. My understanding is that eventually we want to use srcset when the images are all set up (let me know if this assumption is not correct)

With the smaller image it looks a little odd so I have also centered the caption a bit more (it was left aligned in it's container which was centered). 

before:
Alt text

after:
Alt text

### CODE REVIEW

File: tests/unit/amo/components/TestScreenShots.js [hunk 1]
```diff
@@ -4,22 +4,27 @@ import { renderIntoDocument } from 'react-dom/test-utils';
...
 import ScreenShots, {
-  HEIGHT,
-  WIDTH,
   thumbnailContent,
 } from 'amo/components/ScreenShots';
 
+const HEIGHT = 400;
+const WIDTH = 200;
+
 describe('<ScreenShots />', () => {
```
Comment (willdurand) [inline tests/unit/amo/components/TestScreenShots.js]: Could you please update this description with `__filename`?

File: tests/unit/amo/components/TestScreenShots.js [hunk 2]
```diff
@@ -49,7 +54,7 @@ describe('<ScreenShots />', () => {
   });
 
   it('renders custom thumbnail', () => {
-    const item = { src: 'https://foo.com/img.png', title: 'test title' };
+    const item = { src: 'https://foo.com/img.png', title: 'test title', h: HEIGHT, w: WIDTH };
```
Comment (willdurand) [inline tests/unit/amo/components/TestScreenShots.js]: It would be better to pass different height/width here to make sure we use the values from `image_size`.

File: tests/unit/amo/components/TestScreenShots.js (hunk 1 above)
Comment (willdurand) [reply tests/unit/amo/components/TestScreenShots.js]: Also, I see that we are using `renderIntoDocument`. It could be nice to rewrite the test case with Enzyme.

File: src/amo/css/ScreenShots.scss [hunk 3]
```diff
@@ -7,8 +7,14 @@ $screenshot-height: 220px;
 $image-height: $screenshot-height - 20px;
 $screenshot-width: 320px;
 
-.ScreenShots .pswp-thumbnails {
-  line-height: 0;
+.ScreenShots {
+  .pswp-thumbnails {
+    line-height: 0;
```
Comment (willdurand) [inline src/amo/css/ScreenShots.scss]: Why is it needed?

File: src/amo/components/ScreenShots.js [hunk 4]
```diff
@@ -37,14 +35,14 @@ const formatPreviews = (previews) => (
...
-    w: WIDTH,
+    h: preview.image_size[1],
+    w: preview.image_size[0],
     title: preview.caption,
   }))
 );
 
 export const thumbnailContent = (item) => (
-  <img src={item.src} className="ScreenShots-image" height={HEIGHT} width={WIDTH} alt="" title={item.title} />
+  <img src={item.src} className="ScreenShots-image" height={item.h} width={item.w} alt="" title={item.title} />
```
Comment (willdurand) [inline src/amo/components/ScreenShots.js]: We could probably use `item.title` as `alt` content. It is not a super-best-practice, but it is better than having an empty `alt` I guess.

File: src/amo/css/ScreenShots.scss (hunk 3 above)
Comment (rebmullin) [reply src/amo/css/ScreenShots.scss]: do you mean the `line-height` style?  This was on the line above I just moved it so I could nest the caption style as well

Comment (willdurand) [reply src/amo/css/ScreenShots.scss]: heh. 🤕

File: tests/unit/amo/components/TestScreenShots.js (hunk 1 above)
Comment (rebmullin) [reply tests/unit/amo/components/TestScreenShots.js]: ahh..ok sure!

File: src/amo/components/ScreenShots.js (hunk 4 above)
Comment (willdurand) [reply src/amo/components/ScreenShots.js]: For accessibility, we should not have the same content for both `alt` and `title`.

`title` should be the title of the image (e.g. [The Treachery of Images](https://en.wikipedia.org/wiki/The_Treachery_of_Images)) and `alt` should be a description of what the image shows (e.g., `The picture shows a pipe. Below it, Magritte painted, "Ceci n'est pas une pipe.", French for "This is not a pipe."`).

File: src/amo/components/ScreenShots.js [hunk 5]
```diff
@@ -37,14 +35,14 @@ const formatPreviews = (previews) => (
...
-    w: WIDTH,
+    h: preview.image_size[1],
+    w: preview.image_size[0],
     title: preview.caption,
   }))
 );
 
 export const thumbnailContent = (item) => (
-  <img src={item.src} className="ScreenShots-image" height={HEIGHT} width={WIDTH} alt="" title={item.title} />
+  <img src={item.src} className="ScreenShots-image" height={item.h} width={item.w} alt={item.title} title={item.title} />
```
Comment (willdurand) [inline src/amo/components/ScreenShots.js]: I guess we could also write the props on different lines:

```
<img
  src={item.src}
  ...
/>
```

File: tests/unit/amo/components/TestScreenShots.js [hunk 6]
```diff
@@ -49,14 +53,14 @@ describe('<ScreenShots />', () => {
   });
 
   it('renders custom thumbnail', () => {
-    const item = { src: 'https://foo.com/img.png', title: 'test title' };
+    const item = { src: 'https://foo.com/img.png', title: 'test title', h: 123, w: 1234 };
```
Comment (willdurand) [inline tests/unit/amo/components/TestScreenShots.js]: You could introduce the variables `h` and `w`.

File: tests/unit/amo/components/TestScreenShots.js [hunk 7]
```diff
@@ -53,7 +53,10 @@ describe(__filename, () => {
   });
 
   it('renders custom thumbnail', () => {
-    const item = { src: 'https://foo.com/img.png', title: 'test title', h: 123, w: 1234 };
+    const h = 123;
+    const w = 1234;
```
Comment (willdurand) [inline tests/unit/amo/components/TestScreenShots.js]: you should reuse these variables in the `expect().toEqual()`.
