### PR TITLE
Right-click on the extension card area opens the extension page in a new tab

### LINKED ISSUE #8724: Using middle-click or CTRL+Right-click on the extension card area opens the extension page in a new tab
**Steps to reproduce:** 
1. Open addons.mozilla main page.
2. Scroll to the "Featured extensions" section (or any section that has addons cards). 
3. Hover over any extension's area (but not its title).
4. Try to open it in a new tab page using the middle click or CTRL+Click

**Actual results:**
Extension page opened in the same tab. 

**Expected results:**
Open the extension page in a new tab. 

(click where the cursor from the screenshot is located)
firefoxAddonClickCard

### PR DESCRIPTION
**Pull request by TheSTL**
Fixes #8724 

Changes inside:

1. Remove Link tag from the title.

2. Change extension-title className from `SearchResult-link` to `SearchResult-title`.

3. Replace className `SearchResult-wrapper` element `div` to `Link` tag.

4.Remove onClick Function on `li` element.

5.Update test cases.

### CODE REVIEW

File: src/amo/components/SearchResult/index.js [hunk 1]
```diff
@@ -132,7 +125,15 @@ export class SearchResultBase extends React.Component<InternalProps> {
     }
 
     return (
-      <div className="SearchResult-wrapper">
+      <Link
+        to={
+          addon
+            ? this.getAddonLink(addon, addonInstallSource)
+            : history.location.pathname
```
Comment (bobsilverberg) [inline src/amo/components/SearchResult/index.js]: I'm not sure this will give us what we want. It would redirect the user to the base page, but if there were any URL parameters they would be lost. I think what we want is a link that does nothing when clicked if there is no `addon`. Perhaps this could be achieved by using `href="#"` in the case where there is no `addon`?

Comment (bobsilverberg) [reply src/amo/components/SearchResult/index.js]: Also, as this is new logic, there should be a test added for the case where there is no `addon`, verifying that the `Link` is configured the way we expect it to be.

Comment (TheSTL) [reply src/amo/components/SearchResult/index.js]: Okay @bobsilverberg I will add new test case for this logic

File: src/amo/components/SearchResult/index.js [hunk 2]
```diff
@@ -132,7 +124,11 @@ export class SearchResultBase extends React.Component<InternalProps> {
     }
 
     return (
-      <div className="SearchResult-wrapper">
+      <Link
+        href={addon ? this.getAddonLink(addon, addonInstallSource) : '#'}
```
Comment (bobsilverberg) [inline src/amo/components/SearchResult/index.js]: I believe that we still want to use the `to` attribute when we have an `addon` as it doesn't force a page refresh, which is what using the `href` attribute will do. So I think the logic needs to be: If we have an `addon` use `to={this.getAddonLink(addon, addonInstallSource)}`, otherwise use `href="#"`.

Comment (TheSTL) [reply src/amo/components/SearchResult/index.js]: okay, understand

**Comment by bobsilverberg** [comment]
@TheSTL Is this ready for another review? If so, you can let me know either by pinging me in a comment, or by re-requesting a review in the "Reviewers" section to the right.

**Comment by TheSTL** [comment]
@bobsilverberg it's ready for another review.

File: tests/unit/amo/components/TestSearchResult.js [hunk 3]
```diff
@@ -64,35 +64,44 @@ describe(__filename, () => {
...
 
-  it('links the heading to the detail page', () => {
+  it('links the card to the detail page', () => {
     const slug = 'some-addon-slug';
     const addon = createInternalAddon({ ...fakeAddon, slug });
 
     const root = render({ addon });
 
-    expect(root.find('.SearchResult-link')).toHaveProp('to', getAddonURL(slug));
+    expect(root.find('.SearchResult-wrapper')).toHaveProp(
```
Comment (bobsilverberg) [inline tests/unit/amo/components/TestSearchResult.js]: This is good, but I think, because we have logic that creates either a `to` or an `href` attribute, we would also be checking that there is no `href` attribute in this test.

File: tests/unit/amo/components/TestSearchResult.js [hunk 4]
```diff
@@ -64,35 +64,44 @@ describe(__filename, () => {
...
+      'to',
+      getAddonURL(slug),
+    );
   });
 
-  it('stops propagation when clicking on the add-on name', () => {
+  it('links the card to do nothing when addon is null', () => {
+    const root = render({ addon: null });
+
+    expect(root.find('.SearchResult-wrapper')).toHaveProp('href', '#');
```
Comment (bobsilverberg) [inline tests/unit/amo/components/TestSearchResult.js]: This is good, but I think, because we have logic that creates either a `to` or an `href` attribute, we would also be checking that there is no `to` attribute in this test.

**Comment by TheSTL** [comment]
@bobsilverberg improved test cases. Please review :)

File: tests/unit/amo/components/TestSearchResult.js [hunk 5]
```diff
@@ -64,35 +64,50 @@ describe(__filename, () => {
...
     const addon = createInternalAddon({ ...fakeAddon, slug });
 
     const root = render({ addon });
 
-    expect(root.find('.SearchResult-link')).toHaveProp('to', getAddonURL(slug));
+    expect(root.find('.SearchResult-wrapper')).toHaveProp(
+      'to',
+      getAddonURL(slug),
+    );
+    expect(root.find('.SearchResult-wrapper')).not.toHaveProp('href', '#');
```
Comment (bobsilverberg) [inline tests/unit/amo/components/TestSearchResult.js]: This should just be `expect(root.find('.SearchResult-wrapper')).not.toHaveProp('href');`. I.e., we should check that it doesn't have an `href` prop at all, as opposed to checking that it doesn't have an `href` prop with a particular value.

File: tests/unit/amo/components/TestSearchResult.js [hunk 6]
```diff
@@ -64,35 +64,50 @@ describe(__filename, () => {
...
+  });
+
+  it('links the card to do nothing when addon is null', () => {
+    const slug = 'some-addon-slug';
+    const root = render({ addon: null });
+
+    expect(root.find('.SearchResult-wrapper')).toHaveProp('href', '#');
+    expect(root.find('.SearchResult-wrapper')).not.toHaveProp(
```
Comment (bobsilverberg) [inline tests/unit/amo/components/TestSearchResult.js]: This should just be `expect(root.find('.SearchResult-wrapper')).not.toHaveProp('to');`. I.e., we should check that it doesn't have an `to` prop at all, as opposed to checking that it doesn't have an `to` prop with a particular value.

**Comment by TheSTL** [comment]
Update the changes required. Please review again @bobsilverberg
