### PR TITLE
fix: Hide search sort in categories (fix #1626)

### LINKED ISSUE #1626: Sort appears in category pages but doesn't work
### Describe the problem and steps to reproduce it:
Visit http://localhost:3000/en-GB/firefox/extensions/feeds-news-blogging/ and activate the search sort.

### What happened?

Nothing.

### What did you expect to happen?

The sort should work... or it shouldn't appear (but the former is better).

### Anything else we should know?
The URLs are largely hooked up properly (though there is some erroneous data in there), but the params are likely just not passed through.

-----

sortmobile

### PR DESCRIPTION
**Pull request by tofumatt**
Removes the search sort from categories as it isn't needed there and was buggy.

-----

### Before
sortmobile

### After
screenshot 2017-02-15 18 19 29

### CODE REVIEW

File: src/amo/containers/CategoryPage.js [hunk 1]
```diff
@@ -9,6 +9,7 @@ import { apiAddonType } from 'core/utils';
 
 
 export function mapStateToProps(state, ownProps) {
+  const enableSearchSort = false;
```
Comment (kumar303) [inline src/amo/containers/CategoryPage.js]: I guess overloading `mapStateToProps` for more than just state is OK but it seems a little weird. I think you can use composition to accomplish this a little cleaner:
````js
function CategoryPageBase(props) {
  return <SearchPage enableSearchSort={false} hasSearchParams {...props} />;
}

export default compose(
  ...,
  connect(mapStateToProps),
)(CategoryPageBase);
````

Comment (tofumatt) [inline src/amo/containers/CategoryPage.js]: Oh that's nicer and I agree. I'll give it a go.

Comment (tofumatt) [inline src/amo/containers/CategoryPage.js]: I did that and adjusted the tests (which become ever-so-slightly more verbose) but I like the compositon over overloading `mapStateToProps`, thanks 👍
