### PR TITLE
Do not display footer link if not enough add-ons in LandingAddonsCard

### LINKED ISSUE #3745: "See more" link available for less than 4 add-ons in that section
Steps to reproduce:
1. Load an extension category i.e. : https://addons.allizom.org/en-US/android/extensions/feeds-news-blogging/
2. Observe "Featured" section

Expected results:
No "See more" link if less then 4 add-ons in this section.

Actual results:
"See more" link available even if there is only one add-on in that section.

Notes/Issues:
- reproducing on each category, for any section.
Verified on AMO-stage FF56(Win 7, Android 7.2.1).
Screenshot for this issue:

### PR DESCRIPTION
**Pull request by willdurand**
Fix #3745

---

This PR hides the "see more" (footer) link when there are less than 4 add-ons displayed in a landing card.

Before:

screen shot 2017-11-14 at 13 55 32

After:

screen shot 2017-11-14 at 13 55 11

### CODE REVIEW

**Comment by willdurand** [comment]
UI tests are failing for obscure reasons..

**Comment by willdurand** [comment]
Ok tests are back to green thanks to #3909, should be ready for a review.

File: tests/unit/amo/components/TestLandingPage.js [hunk 1]
```diff
@@ -214,7 +214,6 @@ describe(__filename, () => {
     });
 
     expect(root).toIncludeText('Featured extensions');
-    expect(root).toIncludeText('See more featured extensions');
```
Comment (kumar303) [inline tests/unit/amo/components/TestLandingPage.js]: ugh, this suite is not a good unit test of the component. One day we should rewrite the `renderAndMount()` parts.
