### PR TITLE
Reset page filter on change

### LINKED ISSUE #3579: Filtering by "Featured add-ons only" results in a 404 error for an inaccessible page number
Steps to reproduce:
1.Go to AMO homepage and perform a string search (i.e. 'block' - https://addons-dev.allizom.org/en-GB/firefox/search/?platform=windows&q=block)
2.Navigate to the next pages
3. Filter by "Featured add-ons only"

Expected result:
Featured add-ons are displayed, according to the selected filter

Actual result:
An 'invalid result' is displayed and the page is stuck in loading mode

Notes:
Reproduced on all AMO servers with FF56 (Win10 and Android 7.1.2)

image

### PR DESCRIPTION
**Pull request by willdurand**
Fix #3579

---

This PR resets the `page` search filter when one of these filters is updated.

### CODE REVIEW

File: src/amo/components/SearchFilters/index.js [hunk 1]
```diff
@@ -79,6 +84,11 @@ export class SearchFiltersBase extends React.Component {
       newFilters.featured = true;
     }
 
+    if (newFilters.page) {
+      // We reset the page as filters have changed.
+      newFilters.page = 1;
+    }
+
```
Comment (willdurand) [inline src/amo/components/SearchFilters/index.js]: At some point, this and the `router.push` could be a helper (or extracted into a new method). Worth doing there or?

Comment (kumar303) [reply src/amo/components/SearchFilters/index.js]: > At some point, this and the router.push could be a helper (or extracted into a new method). Worth doing there or?

Yeah, I'd say you can share it in component method:

```js
doSearch({ newFilters, filtersWereChanged = false }) {
  const { ... } = this.props;

  if (filtersWereChanged && newFilters.page) {
    // Since it's now a new search, reset the page.
    newFilters.page = 1;
  }

  router.push({
      pathname: `/${lang}/${clientApp}${pathname}`,
      query: convertFiltersToQueryParams(newFilters),
  });
}
```
