### PR TITLE
fix: Copy changes on Explore page

### LINKED ISSUE #1742: Copy changes on Explore page
- Change "What do you want Firefox to do?" to "You can change how Firefox works…"
- Change "How do you want Firefox to look?" to "…or what it looks like"

### PR DESCRIPTION
**Pull request by aayushsanghavi**
Fixes #1742

### CODE REVIEW

File: src/amo/containers/Home.js [hunk 1]
```diff
@@ -74,7 +74,7 @@ export class HomePageBase extends React.Component {
           {i18n.gettext('Browse all extensions')}
         </Link>
 
-        <h2 className="HomePage-subheading">{i18n.gettext('How do you want Firefox to look?')}</h2>
+        <h2 className="HomePage-subheading">{i18n.gettext('…or what it looks like')}</h2>
```
Comment (tofumatt) [inline src/amo/containers/Home.js]: I like that you used the real ellipsis (`…`) and not three dots in a row 👍 😄

**Comment by tofumatt** [comment]
Thanks :-)
