### PR TITLE
make sure collections get loaded when params change

### LINKED ISSUE #3482: Collections not updated on the client
### Describe the problem and steps to reproduce it:

1. Go to the "Block ads" collection from homepage
2. Return to the homepage
3. Navigate to the "Change your tabs" collection

### What happened?

You still get the old content, i.e. the data of the "Block ads" collection

### What did you expect to happen?

The new collection "Change your tabs" is loaded

### PR DESCRIPTION
**Pull request by willdurand**
Fix #3482

---

This PR makes sure collections get loaded correctly on the client.

## Gifs

Before:

After:

### CODE REVIEW

File: tests/unit/amo/components/TestCollection.js [hunk 1]
```diff
@@ -29,14 +29,18 @@ import {
 
 
 describe(__filename, () => {
+  // These values match the `createFakeCollectionDetail()` helper data.
+  const defaultUser = 'johndoe';
+  const defaultSlug = 'my-addons';
```
Comment (kumar303) [inline tests/unit/amo/components/TestCollection.js]: what about this?

```js
const defaultCollection = createFakeCollectionDetail();
const defaultUser = defaultCollection.author.username;
const defaultSlug = defaultCollection.slug;
```

File: src/amo/components/Collection/index.js [hunk 2]
```diff
@@ -79,6 +79,13 @@ export class CollectionBase extends React.Component {
       }
     }
 
+    if (collection && (
+      collection.slug !== params.slug ||
+      collection.authorUsername !== params.user
+    )) {
+      collectionChanged = true;
+    }
```
Comment (kumar303) [inline src/amo/components/Collection/index.js]: Ugh, the loading logic in this component is really complicated. It's my first time seeing it. I know it's necessary because of SSR though. Your new logic looks fine, I'm just complaining out loud :/

File: tests/unit/amo/components/TestCollection.js (hunk 1 above)
Comment (willdurand) [reply tests/unit/amo/components/TestCollection.js]: much better!
