### PR TITLE
Fix how we determine Quantum compatibility

### LINKED ISSUE #3868: Check that Mozilla signed extensions show up correctly
https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/ is a Mozilla signed extension. On the new site its showing up as "Not compatible with Firefox Quantum". On the old site it is showing up as a compatible.

Would consider this reasonably high priority (I just added that but feel free to disagree). Here's what mat said in IRC:

mat> the API says it is
mat> the frontend shouldn't use is_webextension or things like that, just rely on the compatibility info

### PR DESCRIPTION
**Pull request by willdurand**
Fix #3868

---

We use a forged User Agent string to be able to use the existing compatibility logic. It is not ideal but it is good-enough short-term. Th "not compatible with Firefox Quantum" badge should only be displayed if an add-on is not compatible with the desktop version of Quantum (`clientApp = firefox`).

## Screenshots

Before:

screen shot 2017-11-09 at 22 59 43

After:

screen shot 2017-11-09 at 23 00 32

**Important:** On Android, we do not show the badge on purpose because this extension is compatible with Quantum Desktop:

screen shot 2017-11-10 at 17 40 42

### CODE REVIEW

File: src/amo/components/AddonBadges/index.js [hunk 1]
```diff
@@ -30,24 +35,23 @@ export const AddonBadgesBase = (props: Props) => {
     }
   };
 
-  const isIncompatible = addon && addon.type === ADDON_TYPE_EXTENSION &&
-    !addon.isWebExtension;
+  const isIncompatible = isQuantumCompatible({ addon }) === false;
```
Comment (kumar303) [inline src/amo/components/AddonBadges/index.js]: I think it would be safer to do this as:

```js
const isIncompatible = addon.type === ADDON_TYPE_EXTENSION &&
  isQuantumCompatible({ addon }) === false;
```

It's hurting my brain a little bit but I'm worried because [the compatibility object patch](https://github.com/mozilla/addons-frontend/commit/3cecbed3269f715099a6c8c69430bd9da6d6b2da) has not landed in prod yet which means when we cherry pick it, this function may be getting compatibility objects that cannot be trusted.

File: src/core/utils/compatibility.js [hunk 2]
```diff
@@ -160,3 +162,17 @@ export function getClientCompatibility({
...
+export const isQuantumCompatible = ({ addon }) => {
+  // HACK: we use a hardcoded User Agent string corresponding to MacOS/Firefox
+  // 57.0 to determine whether the given `addon` is compatible with Quantum.
+  // The OS is not important as far as it is not `iOS`.
+  //
+  // See: https://github.com/mozilla/addons-frontend/issues/3868.
+  const userAgentInfo = UAParser(oneLine`Mozilla/5.0 (Macintosh; Intel Mac OS X
+    10.12; rv:57.0) Gecko/20100101 Firefox/57.0`);
+  // We set `clientApp` to `firefox` because we do not want to rely on it.
+  const clientApp = CLIENT_APP_FIREFOX;
```
Comment (kumar303) [inline src/core/utils/compatibility.js]: Actually, I think we do need to rely on `clientApp` because that's crucial to how the question "is this add-on compatible with 57" is answered. If an add-on is compatible with Firefox for Android 57 but is *not* compatible with Firefox for desktop 57 then we *do not* want to show the "incompatible with Quantum" banner.

File: tests/unit/core/utils/test_compatibility.js [hunk 3]
```diff
@@ -610,4 +614,36 @@ describe(__filename, () => {
...
     });
   });
+
+  describe('isQuantumCompatible', () => {
+    it('returns `true` when add-on is compatible', () => {
+      const addon = createInternalAddon(createFakeAddon({
+        name: 'Firefox Multi-Account Containers',
+        compatibility: {
+          [CLIENT_APP_FIREFOX]: {
+            max: '*',
```
Comment (kumar303) [inline tests/unit/core/utils/test_compatibility.js]: You should set this to `57.0` to make it realistic

File: tests/unit/amo/components/TestAddonBadges.js [hunk 4]
```diff
@@ -107,33 +118,34 @@ describe(__filename, () => {
...
-    }));
-    const root = shallowRender({ addon });
+      const root = shallowRender({ addon });
 
-    expect(root.find(Badge)).toHaveLength(0);
+      expect(root.find(Badge)).toHaveLength(0);
+    });
+
+    it('displays a badge when the addon is not compatible with Quantum', () => {
+      const addon = createInternalAddon(createFakeAddon());
```
Comment (kumar303) [inline tests/unit/amo/components/TestAddonBadges.js]: I don't think mocking out `isQuantumCompatible` is such a good idea for this case. Since we have no Flow coverage of the tests it's just too hard to keep the mock in sync with the real object. For starters, your tests do not make any assertions to guarantee that `isQuantumCompatible()` is called with the correct arguments. 

I think you should just set up the `addon` with realistic application data instead. This will naturally guarantee that `isQuantumCompatible()` gets called with the right arguments.

Comment (willdurand) [reply tests/unit/amo/components/TestAddonBadges.js]: That's what I did at the beginning but then I duplicated the same `addons` in the compatibility test file..

File: tests/unit/core/utils/test_compatibility.js (hunk 3 above)
Comment (willdurand) [reply tests/unit/core/utils/test_compatibility.js]: It is realistic since it is the prod data..

Comment (willdurand) [reply tests/unit/core/utils/test_compatibility.js]: See: https://addons.mozilla.org/api/v3/addons/addon/multi-account-containers/

File: src/amo/components/AddonBadges/index.js (hunk 1 above)
Comment (willdurand) [reply src/amo/components/AddonBadges/index.js]: but then we'll loose the possibility to test other add-on types?

Comment (willdurand) [reply src/amo/components/AddonBadges/index.js]: nevermind, let's play safe and do something better, later.

File: tests/unit/core/utils/test_compatibility.js (hunk 3 above)
Comment (willdurand) [reply tests/unit/core/utils/test_compatibility.js]: There is a new test with `57.0` as `max`.

Comment (kumar303) [reply tests/unit/core/utils/test_compatibility.js]: Oh, cool. I didn't notice that prod uses `*`. I was looking at dev.
