### PR TITLE
Fix the link to photos-music-videos from the Guides page

### LINKED ISSUE #8131: Redirect is missing for a link from Guides pages
Steps to reproduce:
1.Go to AMO Stage and open https://addons.allizom.org/en-US/firefox/guides/enhance-your-media-experience/
2. Go to "Bring media right into the browser" section and press the "photo, music & video extensions" link

Expected results:
The link should open https://addons.allizom.org/en-US/firefox/search/?category=photos-music-videos&sort=recommended%2Cusers&type=extension

Actual results:
"Oops! We can’t find that page" is returned

NOTES:
Probably a regression from https://github.com/mozilla/addons-frontend/issues/8094

Please see video for this bug : 
oopsguides

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #8131 

Note that I thought about using [`categoryResultsLinkTo`](https://github.com/mozilla/addons-frontend/blob/6dcf336e0834d98499a7ce837b37d4d3373211d7/src/amo/components/Categories/index.js#L59-L70) to build the link, but `exploreUrl` in the Guides page expects a string, which it uses in a couple of places, whereas `categoryResultsLinkTo` returns an object which we'd have to unpack and manipulate. Seeing as this page is always going to be manually edited whenever changes are required, and all the other values of `exploreUrl` are strings, I kept it simple and just included an explicit link.

### CODE REVIEW

File: src/amo/pages/Guides/index.js [hunk 1]
```diff
@@ -244,7 +244,8 @@ export const getSections = ({
           exploreMore: i18n.gettext(
             'Explore among thousands of %(linkStart)sphoto, music & video extensions%(linkEnd)s.',
           ),
-          exploreUrl: '/extensions/photos-music-videos/',
+          exploreUrl:
+            '/search/?category=photos-music-videos&sort=recommended%2Cusers&type=extension',
```
Comment (willdurand) [inline src/amo/pages/Guides/index.js]: Could you maybe use a helper function to build the query string? That would avoid to hardcode urlencoded values.

Comment (bobsilverberg) [reply src/amo/pages/Guides/index.js]: Well, if I'm going to do that, I might as well use [`categoryResultsLinkTo`](https://github.com/mozilla/addons-frontend/blob/6dcf336e0834d98499a7ce837b37d4d3373211d7/src/amo/components/Categories/index.js#L59-L70) as well, which is probably the "right" way to do this. I'll make that change.

Comment (bobsilverberg) [reply src/amo/pages/Guides/index.js]: Actually [`getCategoryResultsQuery`](https://github.com/mozilla/addons-frontend/blob/6dcf336e0834d98499a7ce837b37d4d3373211d7/src/core/utils/index.js#L380-L389) is more suitable, and addresses your issue. I've changed it to use that.
