### PR TITLE
I6900 guides pages with LoadingText

### LINKED ISSUE #6900: While guide addons are null use the LoadingText component
While we are fetching the addon we should show loading text instead of blank space

### LINKED ISSUE #7223: Log an error if a guides add-on doesn't load
### Describe the problem and steps to reproduce it:

* Configure a guides page with the incorrect add-on guid (see https://github.com/mozilla/addons-frontend/issues/7222)
* Load the guides page where the wrong add-on guid was configured

### What happened?

You see a blank space where the add-on was meant to be

### What did you expect to happen?

Showing a blank space is fine but we should log a descriptive message using `log.error()`. This will send a message to the console and also to Sentry, our error reporter.

### Anything else we should know?

I'm marking this as no QA because there's no way to simulate this scenario from the live site.

When implementing https://github.com/mozilla/addons-frontend/issues/6900 we need to also consider this case.

### PR DESCRIPTION
**Pull request by rebmullin**
fixes #6900 
fixes #7223

### CODE REVIEW

File: src/amo/pages/Guides/index.js [hunk 1]
```diff
@@ -263,7 +275,7 @@ export const getContent = (slug: string, i18n: I18nType): GuideType | null => {
           and security.`,
         ),
         icon: 'stop-hand',
-        sections: getSections({ slug, i18n }),
+        sections: _sections || getSections({ slug, i18n }),
```
Comment (rebmullin) [inline src/amo/pages/Guides/index.js]: note: I added this here because without this it was hard to test

File: tests/unit/amo/pages/TestGuides.js [hunk 2]
```diff
@@ -187,13 +183,14 @@ describe(__filename, () => {
...
+    it('passes a valid addon to GuidesAddonCard', () => {
       const { store } = _dispatchFirefoxClient();
+      const _log = getFakeLogger();
 
       const slug = 'stay-safe-online';
-      const guids = getSections({ slug, i18n: fakeI18n() }).map(
-        (section) => section.addonGuid,
-      );
+
+      // TODO: figure out why only this one guid is working in the test.
```
Comment (willdurand) [inline tests/unit/amo/pages/TestGuides.js]: What does that mean? No other GUID from the list of GUIDs for `stay-safe-online` work?

**Comment by rebmullin** [comment]
> A more in-depth review made me realize that we should always show the cards and use loading indicators when there is no data yet (cf. #6900).

can you clarify this? Are you saying we should always show the cards and inside have the indicator?

**Comment by willdurand** [comment]
> can you clarify this? Are you saying we should always show the cards and inside have the indicator?

Yep, exactly.

File: src/amo/components/GuidesAddonCard/index.js [hunk 3]
```diff
@@ -39,6 +40,13 @@ export class GuidesAddonCardBase extends React.Component<InternalProps> {
   render() {
     const { addon, i18n, staffPick } = this.props;
 
+    const fallback =
+      addon !== null ? (
+        <Card>
```
[the remark this answers is not in the document]
Comment (rebmullin) [reply src/amo/components/GuidesAddonCard/index.js]: yeh that's better. thanks for the suggestion

**Comment by rebmullin** [comment]
@willdurand, okay I made some updates per your last comment. 

note: on dev, there is 1 addon that is no longer showing up so you can see how a "bad" (guid) addon looks (the media experience tab, first addon). It does initially show the card and then nothing. It doesn't seem super smooth but I don't think there is anything we can do about that. 

please let me know what you think:)

File: src/amo/components/GuidesAddonCard/index.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (rebmullin) [reply src/amo/components/GuidesAddonCard/index.js]: I only am doing this with the title since that is really the only thing that we are getting from fetching the addon (except for the image which isn't text).

[the remark this answers is not in the document]
Comment (willdurand) [reply src/amo/components/GuidesAddonCard/index.js]: Great, I really like it!

**Comment by willdurand** [comment]
> @willdurand, okay I made some updates per your last comment.

As a user, that looks perfect to me!
 
> note: on dev, there is 1 addon that is no longer showing up so you can see how a "bad" (guid) addon looks (the media experience tab, first addon). It does initially show the card and then nothing. It doesn't seem super smooth but I don't think there is anything we can do about that.

Yep, that's fine. It is not that bad to be honest.

File: src/amo/components/GuidesAddonCard/styles.scss [hunk 4]
```diff
@@ -33,6 +33,25 @@
   }
 
   .GuidesAddonCard-content-header-title {
+    width: 100%;
+
+    @include respond-to(medium) {
+      display: flex;
+
+      &--loading {
```
Comment (willdurand) [inline src/amo/components/GuidesAddonCard/styles.scss]: Can you please use the full name and not `&`? It is more "grep-able".

File: src/amo/pages/Guides/index.js (hunk 1 above)
Comment (willdurand) [reply src/amo/pages/Guides/index.js]: Why not naming this prop `_sections` then?

File: src/amo/pages/Guides/index.js [hunk 5]
```diff
@@ -251,7 +254,16 @@ export const getSections = ({
...
+export const getContent = ({
+  slug,
+  i18n,
+  sections,
+}: {|
+  slug: string,
+  i18n: I18nType,
+  sections?: Array<SectionsType>,
+|} = {}): GuideType | null => {
+  const _sections = sections;
```
Comment (willdurand) [inline src/amo/pages/Guides/index.js]: This is a bit confusing because we don't do this usually (i.e. renaming a prop). Why do you need this? Can't you use `_sections` directly so that we know it is mainly used for testing purpose?

File: src/amo/pages/Guides/index.js [hunk 6]
```diff
@@ -331,15 +347,29 @@ export class GuidesBase extends React.Component<InternalProps> {
...
       });
 
-      const addon = addons[section.addonGuid] || null;
+      let addon;
+
+      if (hasAddonsLoaded) {
+        if (addons[section.addonGuid] === null) {
+          addon = null;
+          _log.error(
+            `There is an error with add-on guid: ${section.addonGuid}`,
```
Comment (willdurand) [inline src/amo/pages/Guides/index.js]: Maybe you can write `Could not load add-on with GUID: ${section.addonGuid}`? We know that it is an error thanks to the log level, so we could give a hint ("... load") in the content.

File: src/amo/pages/Guides/index.js [hunk 7]
```diff
@@ -364,7 +394,7 @@ export class GuidesBase extends React.Component<InternalProps> {
   render() {
     const { clientApp, i18n, match } = this.props;
     const { slug } = match.params;
-    const content = getContent(slug, i18n);
+    const content = getContent({ slug, i18n, sections: this.props.sections });
```
Comment (willdurand) [inline src/amo/pages/Guides/index.js]: Is that needed for testing purpose?

Also, you could extract `sections` two lines above (with the other props).

File: tests/unit/amo/components/TestGuidesAddonCard.js [hunk 8]
```diff
@@ -81,12 +79,16 @@ describe(__filename, () => {
     expect(root.find(InstallButtonWrapper)).toHaveLength(1);
   });
 
-  // TODO: This will be updated when we address the following issue:
-  // https://github.com/mozilla/addons-frontend/issues/6900.
-  it('returns null when there is no addon', () => {
-    const root = render({
-      addon: null,
-    });
+  it("renders a loading class when the addon hasn't been loaded", () => {
```
Comment (willdurand) [inline tests/unit/amo/components/TestGuidesAddonCard.js]: hasn't been loaded _yet_?

File: src/amo/pages/Guides/index.js (hunk 6 above)
Comment (rebmullin) [reply src/amo/pages/Guides/index.js]: I agree that message is better so I've updated this here (to "Could not load.."), but I am not sure what you think I should do regarding the hint:/ 
is this sufficient or are you suggesting I do something else too?

File: src/amo/pages/Guides/index.js (hunk 7 above)
Comment (rebmullin) [reply src/amo/pages/Guides/index.js]: > Is that needed for testing purpose?

yes


> Also, you could extract sections two lines above (with the other props).

sure

**Comment by rebmullin** [comment]
@willdurand, thanks for the feedback. I've made some changes. Can you please take another look?

File: src/amo/pages/Guides/index.js [hunk 9]
```diff
@@ -251,7 +254,15 @@ export const getSections = ({
...
 
-export const getContent = (slug: string, i18n: I18nType): GuideType | null => {
+export const getContent = ({
+  slug,
+  i18n,
+  sections,
+}: {|
+  slug: string,
+  i18n: I18nType,
+  sections?: Array<SectionsType>,
```
Comment (willdurand) [inline src/amo/pages/Guides/index.js]: Why not keeping `_sections` everywhere since it is mostly for testing purpose?

File: tests/unit/amo/pages/TestGuides.js [hunk 10]
```diff
@@ -210,14 +219,60 @@ describe(__filename, () => {
...
+        expect(root.find(GuidesAddonCard).at(index)).toHaveProp(
+          'addon',
+          createInternalAddon(addon),
+        );
+      });
+
+      sinon.assert.notCalled(_log.error);
+    });
+
+    it('passes addon value as null to GuidesAddonCard with a log message if the guid is not valid', () => {
```
Comment (willdurand) [inline tests/unit/amo/pages/TestGuides.js]: passes addon value as `null` to GuidesAddonCard and logs an error when the GUID is not valid

File: src/amo/components/GuidesAddonCard/index.js [hunk 11]
```diff
@@ -39,30 +40,44 @@ export class GuidesAddonCardBase extends React.Component<InternalProps> {
   render() {
     const { addon, i18n, staffPick } = this.props;
 
-    return addon ? (
+    return addon !== null ? (
       <Card>
         <AddonInstallError error={this.props.installError} />
         <div className="GuidesAddonCard">
-          <AddonCompatibilityError addon={addon} />
+          {addon && <AddonCompatibilityError addon={addon} />}
```
Comment (willdurand) [inline src/amo/components/GuidesAddonCard/index.js]: Maybe you could add an assertion for that too (in the newly added test case)

File: src/amo/pages/Guides/index.js (hunk 9 above)
Comment (rebmullin) [reply src/amo/pages/Guides/index.js]: well  `getGuidesSections`'s sections is not used for testing. are you suggesting i rename that too? or sections just within `getContent`?

File: src/amo/components/GuidesAddonCard/index.js (hunk 11 above)
Comment (rebmullin) [reply src/amo/components/GuidesAddonCard/index.js]: I have a test for AddonCompatabilityError already? Do you mean show that is has no length when there is no addon?

File: src/amo/pages/Guides/index.js (hunk 9 above)
Comment (willdurand) [reply src/amo/pages/Guides/index.js]: ah ok, sorry I got confused.

File: src/amo/components/GuidesAddonCard/index.js (hunk 11 above)
Comment (willdurand) [reply src/amo/components/GuidesAddonCard/index.js]: yep

Comment (rebmullin) [reply src/amo/components/GuidesAddonCard/index.js]: got it - thanks!
