### PR TITLE
I5682-static themes install/enable update

### LINKED ISSUE #5681: Update logic in disco pane so static themes are installed similiarly to lightweight themes
### Describe the problem and steps to reproduce it:

Right now, you can't see the theme when it's toggled on. It seems to install but be enabled

You should also be able to click the image to "toggle on"

### What did you expect to happen?

If should appear to work the same way lightweight themes

### Anything else we should know?
notes for dev: 
if you run `setCurrentStatus` on the change of status in `componentsWillReceiveProps`, you see the following with toggling on/off:

first toggle on: 
you see theme

first toggle off:
you see theme turn off and uninstalls

2nd toggle on:
it's seems to download/install but it gets disabled. You can click the switch here and enables  ** this is the issue - need to look into this more

2nd toggle off:
you see theme turns off and uninstalls

### PR DESCRIPTION
**Pull request by rebmullin**
fixes #5681

### CODE REVIEW

File: src/core/components/AMInstallButton/index.js [hunk 1]
```diff
@@ -119,14 +120,16 @@ export class AMInstallButtonBase extends React.Component<InternalProps> {
...
 
     event.preventDefault();
     event.stopPropagation();
 
     await install();
 
-    if (addon.type === ADDON_TYPE_STATIC_THEME) {
+    const isEnabled = await getCurrentStatus();
+
+    if (addon.type === ADDON_TYPE_STATIC_THEME && !isEnabled) {
```
Comment (willdurand) [inline src/core/components/AMInstallButton/index.js]: I think we should call `getCurrentStatus()` inside the `if`, because it is only needed for static themes.

File: src/core/installAddon.js [hunk 2]
```diff
@@ -333,6 +334,29 @@ export class WithInstallHelpers extends React.Component {
     }
   }
 
+  getCurrentStatus() {
```
Comment (willdurand) [inline src/core/installAddon.js]: I believe this method should be named `isAddonEnabled` because we only return the `isEnabled` value.

File: src/core/installAddon.js [hunk 3]
```diff
@@ -333,6 +334,29 @@ export class WithInstallHelpers extends React.Component {
...
+    const {
+      _addonManager,
+      addon: { guid },
+      hasAddonManager,
+    } = this.props;
+
+    if (!hasAddonManager) {
+      log.info('No addon manager, cannot set add-on status');
```
Comment (willdurand) [inline src/core/installAddon.js]: I am not sure we need this because other methods don't have it, since we'll use them only when we have mozAddonManager.

File: src/core/installAddon.js [hunk 4]
```diff
@@ -333,6 +334,29 @@ export class WithInstallHelpers extends React.Component {
...
+      return Promise.resolve();
+    }
+
+    log.info('Getting add-on status');
+    return _addonManager
+      .getAddon(guid)
+      .then((addon) => {
+        return addon.isEnabled;
```
Comment (willdurand) [inline src/core/installAddon.js]: I see that this code is the same as `setCurrentStatus`, which is called on every prop change.

I did not know we were using `getAddon` before so I wonder if this is needed. Maybe relying on `status` is enough.

File: src/core/components/AMInstallButton/index.js (hunk 1 above)
Comment (willdurand) [reply src/core/components/AMInstallButton/index.js]: Given that the status is likely up-to-date, can we maybe just do:

```
if (addon.type === ADDON_TYPE_STATIC_THEME && status !== ENABLED) {
  ...
}
```

File: src/core/installAddon.js (hunk 2 above)
Comment (rebmullin) [reply src/core/installAddon.js]: yep i was going to rename this : )

File: src/core/installAddon.js (hunk 4 above)
Comment (willdurand) [reply src/core/installAddon.js]: Ok, I missed the condition on the GUID. That makes sense performance-wise.

> I don't know that if we'll we see ENABLED right after install. I compared by testing install of a regular extension and its status right after install shows UNINSTALLED...which doesn't seem right to me..? So there may be a deeper issue here to fix.

oO, that does not sound right.

>  For now maybe I can check for the DISABLED state (in case it gets fixed and is working more like an extension and show UNINSTALLED). if that all makes sense : )

We can probably live with a new method in `installAddon`. I'd like to investigate more the potential bug above.

Comment (rebmullin) [reply src/core/installAddon.js]: More on this

> I don't know that if we'll we see ENABLED right after install. I compared by testing install of a regular extension and its status right after install shows UNINSTALLED...which doesn't seem right to me..? So there may be a deeper issue here to fix.

In the render, it does show a more accurate status. For a regular extension it says INSTALLED. If you refresh the page it shows ENABLED.

I think after the install, its just not updated at that point yet so it actually still shows the older status..

File: src/disco/components/Addon/index.js [hunk 5]
```diff
@@ -45,9 +45,9 @@ const CSS_TRANSITION_TIMEOUT = { enter: 700, exit: 300 };
 
 export const installStaticTheme = async (event, props) => {
   event.preventDefault();
-  const { status } = props;
+  const { hasAddonManager, status } = props;
 
-  if (status === UNINSTALLED) {
+  if (hasAddonManager && status === UNINSTALLED) {
```
Comment (willdurand) [inline src/disco/components/Addon/index.js]: ah yes, I think we should not have to call this method if we have no mozAddonManager, but it should not be done here IMO. Can we prevent the call where we bind the onClick event?

File: tests/unit/core/TestInstallAddon.js [hunk 6]
```diff
@@ -601,6 +601,30 @@ describe(__filename, () => {
...
+          ...fakeAddon,
+          _addonManager: fakeAddonManager,
+        });
+        const { root } = renderWithInstallHelpers({
+          ...addon,
+          addon: { guid },
+          _addonManager: fakeAddonManager,
+        });
+
+        guid = root.instance().props.guid;
```
Comment (rebmullin) [inline tests/unit/core/TestInstallAddon.js]: to me this seemed a little weird that I needed to do this but it doesn't work without this..?

File: src/disco/components/Addon/index.js [hunk 7]
```diff
@@ -242,6 +244,30 @@ export class AddonBase extends React.Component {
     }
   };
 
+  installStaticTheme = async (event) => {
```
Comment (rebmullin) [inline src/disco/components/Addon/index.js]: Originally I had this outside of the class so I could spy on it being called but I decided to move back inside the class b/c I couldn't seem to spy on the install and enable methods which I thought was more import to spy on (rather than the function itself). hopefully this is okay..

**Comment by rebmullin** [comment]
> I think after the install, its just not updated at that point yet so it actually still shows the older status..

@willdurand, given the above, I am going to keep this isAddonEnabled method. let me know if you see any issues w/ this now.

File: src/disco/components/Addon/index.js (hunk 5 above)
Comment (rebmullin) [reply src/disco/components/Addon/index.js]: i thought about doing that but then there will still be a link where we want to do event.preventDefault...

unless I make it not a link with this condition...is that better?

File: src/core/installAddon.js [hunk 8]
```diff
@@ -333,6 +334,23 @@ export class WithInstallHelpers extends React.Component {
...
+    } = this.props;
+
+    log.info('Getting add-on enabled status');
+    return _addonManager
+      .getAddon(guid)
+      .then((addon) => {
+        return addon.isEnabled;
+      })
+      .catch((error) => {
+        log.error(`Caught error from addonManager: ${error}`);
```
Comment (willdurand) [inline src/core/installAddon.js]: Should we return `false`?

Comment (willdurand) [reply src/core/installAddon.js]: Can we move to async/await syntax?

File: src/core/installAddon.js [hunk 9]
```diff
@@ -298,6 +298,7 @@ export class WithInstallHelpers extends React.Component {
     WrappedComponent: PropTypes.func.isRequired,
     _addonManager: PropTypes.object,
     _tracking: PropTypes.object,
+    addon: PropTypes.object,
```
Comment (willdurand) [inline src/core/installAddon.js]: We have the guid in the props already, no?

File: src/disco/components/Addon/index.js [hunk 10]
```diff
@@ -61,6 +62,7 @@ export class AddonBase extends React.Component {
     iconUrl: PropTypes.string,
     install: PropTypes.func.isRequired,
     installTheme: PropTypes.func.isRequired,
+    isAddonEnabled: PropTypes.bool,
```
Comment (willdurand) [inline src/disco/components/Addon/index.js]: that's a function, no? maybe the name of the function is not good enough as it implies a boolean.

File: src/disco/components/Addon/index.js [hunk 11]
```diff
@@ -242,6 +244,30 @@ export class AddonBase extends React.Component {
...
+    event.preventDefault();
+    const {
+      enable,
+      hasAddonManager,
+      isAddonEnabled,
+      install,
+      status,
+    } = this.props;
+
+    if (hasAddonManager && status === UNINSTALLED) {
```
Comment (willdurand) [inline src/disco/components/Addon/index.js]: do we really need to check the addonManager?

File: src/disco/components/Addon/index.js [hunk 12]
```diff
@@ -137,30 +139,30 @@ export class AddonBase extends React.Component {
 
       let imageUrl = getPreviewImage(addon);
 
-      if (!imageUrl && type === ADDON_TYPE_THEME) {
+      let headerLinkProps = {
+        className: 'theme-image',
+        href: '#',
```
Comment (willdurand) [inline src/disco/components/Addon/index.js]: we should probably link to the static theme, we have it no?

File: src/core/installAddon.js (hunk 8 above)
Comment (rebmullin) [reply src/core/installAddon.js]: > Can we move to async/await syntax?

that would be cool : ) i actually thought about that but was trying to keep consistent with other funcs..

File: src/disco/components/Addon/index.js (hunk 10 above)
Comment (rebmullin) [reply src/disco/components/Addon/index.js]: hmm..good point..

File: src/disco/components/Addon/index.js (hunk 12 above)
Comment (rebmullin) [reply src/disco/components/Addon/index.js]: the link here is supposed to install/enable (like lightweight theme currently does)

File: src/disco/components/Addon/index.js (hunk 11 above)
Comment (rebmullin) [reply src/disco/components/Addon/index.js]: i thought it would good to ck to be sure. We do pass this val into the button so thought there could be scenario would it's false for some reason here too, no?

File: src/core/installAddon.js (hunk 9 above)
Comment (rebmullin) [reply src/core/installAddon.js]: linting was complaining about this so I added this here

Comment (rebmullin) [reply src/core/installAddon.js]: actually after changing to async/await, it seems that we can remove..

File: src/disco/components/Addon/index.js (hunk 12 above)
Comment (willdurand) [reply src/disco/components/Addon/index.js]: even if we disable the mozAddonManager?

Comment (rebmullin) [reply src/disco/components/Addon/index.js]: well right now..the way it's set up it wouldn't do anything. I guess we could link the header in this case to the addon detail page

On a side but related note if mozAddonManager is false, then this value would be passed to the buttons and I don't see the buttons working here either in this case. Is this expected?

Comment (willdurand) [reply src/disco/components/Addon/index.js]: The install button works with or without the `mozAddonManager` by offering the link to the extension in a `href` prop.

File: src/core/installAddon.js [hunk 13]
```diff
@@ -333,6 +333,22 @@ export class WithInstallHelpers extends React.Component {
...
+      addon: { guid },
+    } = this.props;
+
+    log.info('Getting add-on enabled status');
+    try {
+      const addon = await _addonManager.getAddon(guid);
+      return addon.isEnabled;
+    } catch (error) {
+      log.error(`Caught error from addonManager: ${error}`);
+      return false;
```
Comment (willdurand) [inline src/core/installAddon.js]: Can we move the return statement outside the catch block? so that it shows that this function returns `false` by default.

File: src/disco/components/Addon/index.js (hunk 12 above)
Comment (willdurand) [reply src/disco/components/Addon/index.js]: I think what we could do is that if `hasAddonManager` is `false`, then we do not surround the `` with a link. No link, no action, for both lightweight and static themes.

That would also allow you to get rid of the test in `installStaticTheme()`.

File: tests/unit/core/components/TestAMInstallButton.js [hunk 14]
```diff
@@ -393,19 +393,48 @@ describe(__filename, () => {
...
+      getAddonEnabledStatus: sinon.stub().returns(false),
+    });
 
     const event = createFakeEvent();
 
     const installButton = root.find('.AMInstallButton-button');
     await installButton.simulate('click', event);
 
-    sinon.assert.calledOnce(install);
+    await sinon.assert.calledOnce(install);
```
Comment (willdurand) [inline tests/unit/core/components/TestAMInstallButton.js]: oh, we really have to `await` here?

File: tests/unit/core/TestInstallAddon.js (hunk 6 above)
Comment (willdurand) [reply tests/unit/core/TestInstallAddon.js]: That does not sound good 😛

File: src/amo/components/Addon/index.js [hunk 15]
```diff
@@ -69,6 +69,7 @@ export class AddonBase extends React.Component {
     enable: PropTypes.func.isRequired,
     errorHandler: PropTypes.object.isRequired,
     getClientCompatibility: PropTypes.func,
+    getAddonEnabledStatus: PropTypes.func.isRequired,
```
Comment (willdurand) [inline src/amo/components/Addon/index.js]: Thanks for renaming this function. I still don't like the name but I don't find a better name..

File: tests/unit/core/components/TestAMInstallButton.js (hunk 14 above)
Comment (rebmullin) [reply tests/unit/core/components/TestAMInstallButton.js]: yeh it wasn't hitting enable without this..should I be doing something else?

File: tests/unit/core/TestInstallAddon.js (hunk 6 above)
Comment (rebmullin) [reply tests/unit/core/TestInstallAddon.js]: lol..

actually I just noticed tho I think w/ the changes (I am not sure exactly what), its ok now without...?
I'll remove now...

File: src/amo/components/Addon/index.js (hunk 15 above)
Comment (rebmullin) [reply src/amo/components/Addon/index.js]: ok i'll keep for now. We can update if think of something better : )

File: tests/unit/disco/components/TestAddon.js [hunk 16]
```diff
@@ -443,42 +444,103 @@ describe(__filename, () => {
...
+    };
+
+    it('renders the correct image', () => {
+      const root = renderWithStaticTheme();
+      const image = root.find('.Addon-theme-header-image');
       expect(image).toHaveProp('src', fullImage);
       expect(image).toHaveProp('alt', `Preview of ${newAddonName}`);
     });
+
+    it("calls install and enable helper functions when clicking on the static theme's header image if hasAddonManager is true", async () => {
```
Comment (rebmullin) [inline tests/unit/disco/components/TestAddon.js]: I am wondering if it's better to group some of these tests here in a `hasAddonManager is false` (or true) describe?

File: src/amo/components/Addon/index.js (hunk 15 above)
Comment (willdurand) [reply src/amo/components/Addon/index.js]: Maybe `getEnabledState`? or we can revert back to `isAddonEnabled`...

File: src/core/components/AMInstallButton/index.js [hunk 17]
```diff
@@ -47,6 +47,7 @@ type Props = {|
   defaultInstallSource: string,
   disabled: boolean,
   enable: () => Promise<any>,
+  getAddonEnabledStatus: () => Promise<any>,
```
Comment (willdurand) [inline src/core/components/AMInstallButton/index.js]: I think we can use `Promise<boolean>`, no?

File: src/core/installAddon.js [hunk 18]
```diff
@@ -333,6 +333,23 @@ export class WithInstallHelpers extends React.Component {
     }
   }
 
+  async getAddonEnabledStatus() {
+    const {
+      _addonManager,
+      addon: { guid },
+    } = this.props;
+
+    log.info('Getting add-on enabled status');
```
Comment (willdurand) [inline src/core/installAddon.js]: Not sure we really need this `log.info`

File: src/disco/components/Addon/index.js [hunk 19]
```diff
@@ -242,6 +248,23 @@ export class AddonBase extends React.Component {
...
+    event.preventDefault();
+    const { enable, getAddonEnabledStatus, install, status } = this.props;
+
+    if (status === UNINSTALLED) {
+      await install();
+
+      // See: https://bugzilla.mozilla.org/show_bug.cgi?id=1477328
+      // on why we might explicitly be calling the enable function
+      // after install
+      const isEnabled = await getAddonEnabledStatus();
```
Comment (willdurand) [inline src/disco/components/Addon/index.js]: Maybe this could go outside the `status === UNINSTALLED` block

File: src/core/installAddon.js [hunk 20]
```diff
@@ -333,6 +333,23 @@ export class WithInstallHelpers extends React.Component {
...
+    try {
+      const addon = await _addonManager.getAddon(guid);
+      return addon.isEnabled;
+    } catch (error) {
+      log.error(`Caught error from addonManager: ${error}`);
```
Comment (willdurand) [inline src/core/installAddon.js]: I'd rather write:


```
log.error('could not determine whether the add-on was enabled', error);
```

File: src/disco/components/Addon/index.js [hunk 21]
```diff
@@ -242,6 +248,24 @@ export class AddonBase extends React.Component {
...
+
+    if (status === UNINSTALLED) {
+      await install();
+    }
+
+    const isEnabled = await getAddonEnabledStatus();
+
+    // See: https://bugzilla.mozilla.org/show_bug.cgi?id=1477328
+    // on why we might explicitly be calling the enable function
+    // after install
```
Comment (willdurand) [inline src/disco/components/Addon/index.js]: the `See: <link` is enough I think

File: tests/unit/core/components/TestAMInstallButton.js (hunk 14 above)
Comment (willdurand) [reply tests/unit/core/components/TestAMInstallButton.js]: I see. I think we could avoid the `await` here and above with `setImmediate()`.

Comment (willdurand) [reply tests/unit/core/components/TestAMInstallButton.js]: The problem I see here is that the test case above does not `await` the `install` and therefore no matter what happens the assertion `sinon.assert.notCalled(enable);` will always be correct. That means a bug will never be caught.

Comment (willdurand) [reply tests/unit/core/components/TestAMInstallButton.js]: @kumar303 would you have an idea to make it better?

File: tests/unit/core/components/TestAMInstallButton.js [hunk 22]
```diff
@@ -393,19 +393,48 @@ describe(__filename, () => {
...
     sinon.assert.calledOnce(enable);
     sinon.assert.calledOnce(event.preventDefault);
     sinon.assert.calledOnce(event.stopPropagation);
   });
 
+  it("does not call the `enable` after the `install `helper for a static theme if it's already enabled", async () => {
```
Comment (willdurand) [inline tests/unit/core/components/TestAMInstallButton.js]: enable helper?

File: tests/unit/core/test_installAddon.js [hunk 23]
```diff
@@ -601,6 +601,29 @@ describe(__filename, () => {
...
+        });
+        const { root } = renderWithInstallHelpers({
+          ...addon,
+          addon: { guid },
+          _addonManager: fakeAddonManager,
+        });
+
+        const { getAddonEnabledStatus } = root.instance().props;
+
+        return getAddonEnabledStatus().then((addonObject) => {
```
Comment (willdurand) [inline tests/unit/core/test_installAddon.js]: we can probably switch to async/await here too.

File: tests/unit/core/test_installAddon.js [hunk 24]
```diff
@@ -601,6 +601,29 @@ describe(__filename, () => {
         .returns(false);
     });
 
+    describe('getAddonEnabledStatus', () => {
+      it('calls addonManager.getAddon()', () => {
```
Comment (willdurand) [inline tests/unit/core/test_installAddon.js]: > returns true when the add-on is enabled

File: tests/unit/core/test_installAddon.js [hunk 25]
```diff
@@ -601,6 +601,29 @@ describe(__filename, () => {
...
+          _addonManager: fakeAddonManager,
+        });
+
+        const { getAddonEnabledStatus } = root.instance().props;
+
+        return getAddonEnabledStatus().then((addonObject) => {
+          sinon.assert.calledWith(fakeAddonManager.getAddon, addonObject.guid);
+        });
+      });
+    });
```
Comment (willdurand) [inline tests/unit/core/test_installAddon.js]: We need a test case for when there is an error (`it('returns false when there is an error'`)

File: tests/unit/disco/components/TestAddon.js [hunk 26]
```diff
@@ -443,42 +444,102 @@ describe(__filename, () => {
...
               image_url: fullImage,
             },
           ],
-          type: ADDON_TYPE_STATIC_THEME,
         },
+        status: UNINSTALLED,
+        install,
+        enable,
+        hasAddonManager: true,
+        getAddonEnabledStatus: sinon.stub().returns(false),
```
Comment (willdurand) [inline tests/unit/disco/components/TestAddon.js]: That should probably be `resolves` instead of `returns` because it is a promise

File: tests/unit/disco/components/TestAddon.js [hunk 27]
```diff
@@ -443,42 +444,102 @@ describe(__filename, () => {
...
+
+    it("does not call enable helper functions when clicking on the static theme's header image if addon is already enabled", async () => {
+      install = sinon.spy();
+      enable = sinon.spy();
+      const root = renderWithStaticTheme({
+        getAddonEnabledStatus: sinon.stub().returns(true),
+      });
+      const themeImage = root.find('.theme-image-link');
+      await themeImage.simulate('click', createFakeEvent());
+      await sinon.assert.called(install);
```
Comment (willdurand) [inline tests/unit/disco/components/TestAddon.js]: that's so weird... Maybe we should not use `simulate('click')` and call `await root.instance().installStaticTheme()` directly.. (cc @kumar303)

File: tests/unit/core/components/TestAMInstallButton.js (hunk 14 above)
Comment (kumar303) [inline tests/unit/core/components/TestAMInstallButton.js]: > @kumar303 would you have an idea to make it better?

This is the first time I've seen `sinon.assert.calledOnce()` used as a promise and I can't find any documentation on this behavior so I don't think we should rely on it. My guess is that it only works by chance in that it waits for one more tick on the event loop. Otherwise, what would cause the `calledOnce()` promise to resolve? It is not clear.

I would like to see these tests rewritten with proper async handling.

The problem is that the click handlers rely on promises. Here is a suggestion that doesn't fully cover hooking up the click handlers but I'd be fine with it since it's a simple change from what you have already and it's probably good enough.

```diff
diff --git a/tests/unit/core/components/TestAMInstallButton.js b/tests/unit/core/components/TestAMInstallButton.js
index 3d1b60693..b8bbf2233 100644
--- a/tests/unit/core/components/TestAMInstallButton.js
+++ b/tests/unit/core/components/TestAMInstallButton.js
@@ -403,9 +403,10 @@ describe(__filename, () => {
     const event = createFakeEvent();
 
     const installButton = root.find('.AMInstallButton-button');
-    await installButton.simulate('click', event);
+    const onClick = installButton.prop('onClick');
+    await onClick(event);
 
-    await sinon.assert.calledOnce(install);
+    sinon.assert.calledOnce(install);
     sinon.assert.calledOnce(enable);
     sinon.assert.calledOnce(event.preventDefault);
     sinon.assert.calledOnce(event.stopPropagation);
```

Comment (kumar303) [reply tests/unit/core/components/TestAMInstallButton.js]: > I see. I think we could avoid the `await` here and above with `setImmediate()`.

IMO `setImmediate()` is a hack and we shouldn't invest code in it.

File: tests/unit/disco/components/TestAddon.js (hunk 27 above)
Comment (rebmullin) [reply tests/unit/disco/components/TestAddon.js]: this works, thank you.... the way @kumar303 suggested below works here too. is one way better than the other?

**Comment by rebmullin** [comment]
> Are there any other TestAMInstallButton tests (not related to this patch) that need updating for the async behavior?

I'll take a look..

File: tests/unit/core/test_installAddon.js [hunk 28]
```diff
@@ -601,6 +601,48 @@ describe(__filename, () => {
...
+        });
+        const { root } = renderWithInstallHelpers({
+          ...addon,
+          addon: { guid },
+          _addonManager: fakeAddonManager,
+        });
+        const { isAddonEnabled } = root.instance().props;
+        const isEnabled = await isAddonEnabled();
+
+        expect(isEnabled).toEqual(true);
```
Comment (rebmullin) [inline tests/unit/core/test_installAddon.js]: is this acceptable/sufficient? or do i need to show it returning false and true individually?

**Comment by rebmullin** [comment]
Thanks @kumar303 @willdurand for the reviews. Please let me know how's it looking now?

File: tests/unit/disco/components/TestAddon.js (hunk 27 above)
Comment (willdurand) [reply tests/unit/disco/components/TestAddon.js]: it is fine to use Kumar's proposal (that is: getting the prop and invoking it)

File: src/disco/components/Addon/index.js [hunk 29]
```diff
@@ -242,6 +248,22 @@ export class AddonBase extends React.Component {
     }
   };
 
+  installStaticTheme = async (event) => {
+    event.preventDefault();
```
Comment (willdurand) [inline src/disco/components/Addon/index.js]: can you put this after the `const { ... } = this.props;`

File: tests/unit/core/components/TestAMInstallButton.js [hunk 30]
```diff
@@ -393,19 +393,52 @@ describe(__filename, () => {
     const enable = sinon.spy();
     const install = sinon.spy();
 
-    const root = render({ addon, enable, install });
+    const root = render({
```
Comment (willdurand) [inline tests/unit/core/components/TestAMInstallButton.js]: We should probably update the previous test case too (line 380 of that file)

File: tests/unit/core/components/TestAMInstallButton.js [hunk 31]
```diff
@@ -393,19 +393,52 @@ describe(__filename, () => {
...
+    const onClick = installButton.prop('onClick');
+    await onClick(event);
 
     sinon.assert.calledOnce(install);
     sinon.assert.calledOnce(enable);
     sinon.assert.calledOnce(event.preventDefault);
     sinon.assert.calledOnce(event.stopPropagation);
   });
 
+  it("does not call the `enable` helper after the `install `helper for a static theme if it's already enabled", async () => {
```
Comment (willdurand) [inline tests/unit/core/components/TestAMInstallButton.js]: s/`install `helper/`install` helper

File: tests/unit/core/test_installAddon.js (hunk 28 above)
Comment (willdurand) [reply tests/unit/core/test_installAddon.js]: that's fine.

File: tests/unit/core/test_installAddon.js [hunk 32]
```diff
@@ -601,6 +601,49 @@ describe(__filename, () => {
         .returns(false);
     });
 
+    describe('isAddonEnabled', () => {
+      it('returns add-on status', async () => {
+        const fakeAddonManager = getFakeAddonManagerWrapper();
+        let guid;
+        const addon = createInternalAddon({
+          ...fakeAddon,
+          _addonManager: fakeAddonManager,
```
Comment (willdurand) [inline tests/unit/core/test_installAddon.js]: Why would the add-on need a `_addonManager`? That does not look good to me.

File: tests/unit/core/test_installAddon.js [hunk 33]
```diff
@@ -601,6 +601,49 @@ describe(__filename, () => {
...
+        });
+        const { root } = renderWithInstallHelpers({
+          ...addon,
```
Comment (willdurand) [inline tests/unit/core/test_installAddon.js]: Can you remove this please? We should not do that anymore.

File: tests/unit/core/test_installAddon.js [hunk 34]
```diff
@@ -601,6 +601,49 @@ describe(__filename, () => {
         .returns(false);
     });
 
+    describe('isAddonEnabled', () => {
+      it('returns add-on status', async () => {
```
Comment (willdurand) [inline tests/unit/core/test_installAddon.js]: This test would be better as is:


```js
      it('returns true when the add-on is enabled', async () => {
        const fakeAddonManager = getFakeAddonManagerWrapper();
        const addon = createInternalAddon(fakeAddon);

        const { root } = renderWithInstallHelpers({
          addon,
          _addonManager: fakeAddonManager,
        });

        const { isAddonEnabled } = root.instance().props;
        const isEnabled = await isAddonEnabled();

        sinon.assert.calledWith(fakeAddonManager.getAddon, addon.guid);
        expect(isEnabled).toEqual(true);
      });
```

File: tests/unit/core/test_installAddon.js (hunk 32 above)
Comment (rebmullin) [reply tests/unit/core/test_installAddon.js]: I've left this in otherwise the assert doesn't work. You also have kept it below so I assume this is okay..?

File: tests/unit/core/components/TestAMInstallButton.js (hunk 30 above)
Comment (rebmullin) [reply tests/unit/core/components/TestAMInstallButton.js]: yep i missed that one, thanks!

File: tests/unit/core/test_installAddon.js (hunk 32 above)
Comment (willdurand) [reply tests/unit/core/test_installAddon.js]: the test case I provided above passes without that so I'd like to see it removed. It is not a good idea to add invalid props.

Comment (rebmullin) [reply tests/unit/core/test_installAddon.js]: hmm i see this:

```bash
● /Users/rmullin/Sites/www/addons-frontend/tests/unit/core/test_installAddon.js › withInstallHelpers › isAddonEnabled › returns true when the add-on is enabled

    AssertError: expected stub to be called with arguments 

      614 |         const isEnabled = await isAddonEnabled();
      615 | 
    > 616 |         sinon.assert.calledWith(fakeAddonManager.getAddon, addon.guid);
          |                      ^
      617 |         expect(isEnabled).toEqual(true);
      618 |       });
```

you don't see this?

File: tests/unit/disco/components/TestAddon.js (hunk 27 above)
Comment (rebmullin) [reply tests/unit/disco/components/TestAddon.js]: ok sure I'll update this.. thanks!

File: tests/unit/core/test_installAddon.js [hunk 35]
```diff
@@ -601,6 +601,42 @@ describe(__filename, () => {
...
+
+      it('returns false when there is an error', async () => {
+        const fakeAddonManager = getFakeAddonManagerWrapper({
+          // Resolve a null addon which will trigger an exception.
+          getAddon: Promise.resolve(null),
+        });
+
+        const { root } = renderWithInstallHelpers({
+          addon: createInternalAddon({
+            addon: null,
```
Comment (willdurand) [inline tests/unit/core/test_installAddon.js]: this does not work, it should be null directly and not createInternalAddon.

Comment (rebmullin) [reply tests/unit/core/test_installAddon.js]: I did initially try this but I see this without doing it this way:

```bash
 TypeError: Cannot read property 'guid' of null

      337 |     const {
      338 |       _addonManager,
    > 339 |       addon: { guid },
          |                ^
      340 |     } = this.props;
```

Comment (rebmullin) [reply tests/unit/core/test_installAddon.js]: should I be handling this another way in installAddon?

Comment (rebmullin) [reply tests/unit/core/test_installAddon.js]: I see...I'll update..thanks
