### PR TITLE
Fix collections URLs for guide pages

### LINKED ISSUE #7344: Server error message for mozilla collections opened from the guides pages
Possible regression from #6609 

STR:
1. Open AMO stage homepage
2. Go to a guideline page - i.e. https://addons.allizom.org/en-US/firefox/guides/stay-safe-online/
3. Click on Explore more [password managers] to open the mozilla password managers collection

Actual result:
A Server error page is opened

Expected result:
The collection details page is opened

Note:
- probably these collection pages are hardcoded, the same as in the case of #7297 ; you can see that `username` /mozilla/ is used in the URLs
- I've also noticed the following error in the console:
```
Caught application error: Invariant Violation: "Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. "
```
- reproduced on -dev and stage with FF64, Win10x64

### PR DESCRIPTION
**Pull request by willdurand**
Fixes #7344

---

This PR updates the mozilla collection URLs used in the guide pages to use `userId` instead of `username` values. I did not use a variable because URLs are hardcoded anyway.

### CODE REVIEW

File: src/amo/pages/Guides/index.js [hunk 1]
```diff
@@ -88,7 +88,7 @@ export const getSections = ({
           exploreMore: i18n.gettext(
             'Explore more %(linkStart)spassword manager%(linkEnd)s staff picks.',
           ),
-          exploreUrl: '/collections/mozilla/password-managers/',
+          exploreUrl: '/collections/4757633/password-managers/',
```
Comment (rebmullin) [inline src/amo/pages/Guides/index.js]: should this be hardcoded or is it better to use `config.get('mozillaUserId')`?

Comment (willdurand) [reply src/amo/pages/Guides/index.js]: The URLs are already hardcoded anyway, so I decided to write a simple patch.

Comment (rebmullin) [reply src/amo/pages/Guides/index.js]: good point

Comment (willdurand) [reply src/amo/pages/Guides/index.js]: Note: maybe we could to better in the future but we needed a simple patch to cherry-pick for this week's tag.
