### PR TITLE
Listen to onOperationCancelled to fix the install status

### LINKED ISSUE #562: Unable to reflect pending uninstall undo from about:addons#Extensions
STR:
- Install an add-on via the new disco pane
- Open about:addons#Extensions
- Click remove - see the state change to uninstalling (a restart UI should be shown here - that will be covered elsewhere)
- Click undo

What happens:
- Nothing

What should happen:
- We should get an event telling us the user has cancelled the pending uninstallation.

I've filed this platform bug to expose `onOperationCancelled` https://bugzilla.mozilla.org/show_bug.cgi?id=1279046

### LINKED ISSUE #6164: Listen to `onOperationCancelled`
### Describe the problem and steps to reproduce it:

1. Install an add-on from AMO
2. Go to about:addons
3. Remove this add-on
4. Undo the removed add-on in about:addons
5. Close about:addons

### What happened?

Closing about:addons when the add-on is restored does not send any event, causing AMO -dev to not know the status of the add-on. In other words, the install button on AMO is in a "pending" state.

### What did you expect to happen?

The install button on AMO should not have a "pending" state.

### Anything else we should know?

We should listen to `onOperationCancelled` to update the state of the add-on, which will fix the button status.

Related issues:

- https://github.com/mozilla/addons-frontend/issues/562
- https://github.com/mozilla/addons-frontend/issues/3562
- https://bugzilla.mozilla.org/show_bug.cgi?id=1477155

### LINKED ISSUE #6227: Without refreshing the page, the add-ons button state is "Add to Firefox" instead of "Remove"
Similar with https://github.com/mozilla/addons-frontend/issues/5929 

STR:
1. Install an extension from the add-ons detail page - using the new buttons AMInstallButton
2. Open the add-on manager in a new tab click "remove"
3. Go to the add-ons detail page and refresh it to see the "Add to Firefox" state 
4. Go back to add-on manager tab and click "Undo"
5. Observe the button's state on the detail page

Expected result:
"Remove" is displayed.

Actual result:
"Add to Firefox" is displayed.

Notes:
This issue is reproducible on AMO stage with FF64 (Win10)
Workaround: page must be refreshed again

only after refresh

### PR DESCRIPTION
**Pull request by willdurand**
Fix #6164
Fix #562
Fix #6227

~~⚠️ depends on #6237~~

---

The `onOperationCancelled` event is fired when a user clicks the "undo"
button in `about:addons` (after having removed an add-on from this
panel). This fixes a bug where the install button state was still
"pending" on the AMO side.

Update: this `onOperationCancelled` event seems to be only sent for extensions.

### CODE REVIEW

File: src/core/constants.js [hunk 1]
```diff
@@ -245,6 +245,7 @@ export const GLOBAL_EVENT_STATUS_MAP = {
   onUninstalled: UNINSTALLED,
   onEnabling: ENABLING,
   onDisabling: DISABLING,
+  onOperationCancelled: INSTALLED,
```
Comment (kumar303) [inline src/core/constants.js]: Should this always be mapped to install?

What about this:
- Go to `about:addons`
- Go to Extensions
- Click *Disable* for one of the extensions
- Click *Remove* on that same extension
- Click *undo*

After clicking undo, the extension goes back to disabled in `about:addons`. What happens to the install button for that case?

Comment (kumar303) [reply src/core/constants.js]: I either need https://github.com/mozilla/addons-frontend/issues/6143 or a new hard drive to test with `mozAddonManager` 🙁

Comment (willdurand) [reply src/core/constants.js]: mmh right, that will set the "installed" state to the AMO button whereas the `about:addons` shows "disabled".

I am not sure what to do though:

1. the initial issue is a super rare edge case
2. the code to hook into those listeners is not super extendable
3. your STR are a even more super rare edge case 😛 

We cannot easily set the previous state because, if we follow your STR, the previous state is "UNINSTALLING", not "DISABLED". We could filter the events to get "stable" events only and retain the last one, but this seems to introduce a lot of complexity.

Comment (willdurand) [reply src/core/constants.js]: > I either need #6143 or a new hard drive to test with `mozAddonManager` 🙁

no more excuse now 😸

Comment (willdurand) [reply src/core/constants.js]: so... I came up with a new patch here, which depends on https://github.com/mozilla/addons-frontend/pull/6237

**Comment by willdurand** [comment]
Rebased and ready for a new look!

File: src/core/addonManager.js [hunk 2]
```diff
@@ -164,18 +165,39 @@ export function addChangeListeners(
...
+          const status = getAddonStatus({ addon });
+
+          return callback({
+            guid,
+            status,
+            needsRestart,
+          });
+        })
+        .catch((error) => {
+          log.error(
```
Comment (kumar303) [inline src/core/addonManager.js]: This catch block is missing test coverage. I think it's important to cover this case because it won't get used a lot in real life. Yes, I know that statement sounds weird 😁

File: tests/unit/core/test_addonManager.js [hunk 3]
```diff
@@ -238,41 +256,79 @@ describe(__filename, () => {
...
+      const guid = 'foo@whatever';
+      const needsRestart = false;
+
+      await handleChangeEvent({
+        id: guid,
+        needsRestart,
+        type: ON_OPERATION_CANCELLED_EVENT,
+      });
+
+      sinon.assert.calledWith(fakeEventCallback, {
```
Comment (kumar303) [inline tests/unit/core/test_addonManager.js]: Are you making sure your tests fail at least once? If you don't do test first development then you need to comment out the code or something like that to check failures. 

This test never fails. I don't know if it's because of this patch or a previous one but there are some leaky stubs (this patch is just meant to illustrate the problem):

```diff
diff --git a/tests/unit/core/test_addonManager.js b/tests/unit/core/test_addonManager.js
index a0b16fc90..aabaf52cb 100644
--- a/tests/unit/core/test_addonManager.js
+++ b/tests/unit/core/test_addonManager.js
@@ -256,6 +256,11 @@ describe(__filename, () => {
       addEventListener: sinon.stub(),
     };
 
+    beforeEach(() => {
+      fakeEventCallback.resetHistory();
+      fakeMozAddonManager.addEventListener.resetHistory();
+    });
+
     describe('global events', () => {
       const handleChangeEvent = addonManager.addChangeListeners(
         fakeEventCallback,
```

Comment (willdurand) [reply tests/unit/core/test_addonManager.js]: Interesting. It actually fails if the event does not have the right `type`.

File: tests/unit/core/test_addonManager.js [hunk 4]
```diff
@@ -238,41 +256,116 @@ describe(__filename, () => {
       addEventListener: sinon.stub(),
     };
 
-    const handleChangeEvent = addonManager.addChangeListeners(
-      fakeEventCallback,
-      fakeMozAddonManager,
-    );
+    beforeEach(() => {
+      fakeEventCallback.resetHistory();
+      fakeMozAddonManager.addEventListener.resetHistory();
```
Comment (kumar303) [inline tests/unit/core/test_addonManager.js]: I took a closer look and you don't need to redefine `fakeMozAddonManager` here at all. You can just delete it. The current definition looks right:

https://github.com/mozilla/addons-frontend/blob/eb1134bf3a4f00e7f49be92aee7532aca8e41189/tests/unit/core/test_addonManager.js#L42-L46
