### PR TITLE
Do not display edit profile link if user is not loaded

### LINKED ISSUE #5036: Server error on user profile page when user does not exist
### Describe the problem and steps to reproduce it:

1. Make sure you are logged-in
2. Go to a user profile page with a username that does not exist

### What happened?

Server Error:

screen shot 2018-05-18 at 10 01 18

### What did you expect to happen?

No server error, but a 404.

### PR DESCRIPTION
**Pull request by willdurand**
Fix #5036

### CODE REVIEW

File: tests/unit/amo/components/TestUserProfile.js [hunk 1]
```diff
@@ -446,4 +446,20 @@ describe(__filename, () => {
...
+  it('does not render an edit link if user is not found', () => {
+    const username = 'current-logged-in-user';
+    const { store } = dispatchSignInActions({
+      userProps: {
+        username,
+        permissions: [USERS_EDIT],
+      },
+    });
+
+    // Navigate to another user profile page, not loaded.
```
Comment (rebmullin) [inline tests/unit/amo/components/TestUserProfile.js]: Maybe this comment could be worded a bit clearer

**Comment by rebmullin** [comment]
@willdurand  - great work! just a small note above... 

r+wc

File: tests/unit/amo/components/TestUserProfile.js (hunk 1 above)
Comment (willdurand) [reply tests/unit/amo/components/TestUserProfile.js]: yup, I will update it! thanks!
