### PR TITLE
Saga helpers for creating a collection

### LINKED ISSUE #4505: Saga helpers for creating a collection
We need saga helpers to facilitate creating a collection #4003 

For QA: please check for regressions in any of the existing collection pages and in particular with the "Edit a collection" feature.

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #4505

This adds code to reducers and sagas for creating a collection, as well as refactoring the code for updating a collection so that create/update can share some code.

It also removes `collectionUpdates` from state as it is never used.

### CODE REVIEW

File: src/amo/sagas/collections.js [hunk 1]
```diff
@@ -166,43 +169,56 @@ export function* addAddonToCollection({
   }
 }
 
-export function* updateCollection({
-  payload: {
-    errorHandlerId,
+export function* modifyCollection(
+  action: 'create' | 'update',
+  params: Object,
```
Comment (bobsilverberg) [inline src/amo/sagas/collections.js]: I know this should be something more specific than `Object`, but I couldn't figure out what to make it so that Flow was happy, so some advice would be welcome.

File: src/amo/sagas/collections.js [hunk 2]
```diff
@@ -213,25 +229,77 @@ export function* updateCollection({
       `/${lang}/${clientApp}/collections/${user}/${effectiveSlug}/`
     ));
 
+    const slugWasEdited = slug && slug !== collectionSlug;
```
Comment (bobsilverberg) [inline src/amo/sagas/collections.js]: I know we don't really need this line, but trying to inline it into the `if` statement below made the code a lot less understandable, so I kept this.

File: src/amo/sagas/collections.js [hunk 3]
```diff
@@ -213,25 +229,77 @@ export function* updateCollection({
...
+    errorHandlerId,
+    defaultLocale,
+    description,
+    formOverlayId,
+    name,
+    slug,
+    user,
+  },
+}: CreateCollectionAction,
+_modifyCollection: typeof modifyCollection = modifyCollection,
```
Comment (bobsilverberg) [inline src/amo/sagas/collections.js]: I designed `createCollection` and `updateCollection` to use dependency injection for `modifyCollection`, so we could test `modifyCollection` independently and just check that `createCollection` and `updateCollection` call it appropriately, but I couldn't figure out how to test `modifyCollection` independently using `sagaTester`.

File: tests/unit/amo/reducers/test_collections.js [hunk 4]
```diff
@@ -829,61 +828,6 @@ describe(__filename, () => {
     });
   });
 
-  describe('updateCollection', () => {
```
Comment (bobsilverberg) [inline tests/unit/amo/reducers/test_collections.js]: I removed this because there isn't anything left to test here, but I noticed that we don't have coverage for testing just action creators which don't result in any state changes. I suppose there's not much to test, other than that the return result is what we expect, so maybe this is fine. But it seemed weird to add code and not also add a test for it.

File: tests/unit/amo/sagas/test_collections.js [hunk 5]
```diff
@@ -487,4 +488,122 @@ describe(__filename, () => {
       ).not.toContain(closeFormOverlay(formOverlayId).type);
     });
   });
+
+  describe('createCollection', () => {
```
Comment (bobsilverberg) [inline tests/unit/amo/sagas/test_collections.js]: Please see my comments above about why this is still two big test cases for `create` and `update` rather than one for `modify`.

File: src/amo/sagas/collections.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (kumar303) [reply src/amo/sagas/collections.js]: If this gets too bonkers then you could just use one saga for both instead of defining separate create and update sagas. What I mean is instead of this:

```js
export default function* collectionsSaga() {
  yield takeLatest(CREATE_COLLECTION, createCollection);
  yield takeLatest(UPDATE_COLLECTION, updateCollection);
}
```

...just use the same handler for both actions:

```js
export default function* collectionsSaga() {
  yield takeLatest(
    [CREATE_COLLECTION, UPDATE_COLLECTION], 
    modifyCollection
  );
}
```
The `modifyCollection` handler could look at `action.type` to know if it got a create/update action.

I don't know if this would help with the testing problem or not, just something that came to mind.

**Comment by bobsilverberg** [comment]
Your idea of using `yield takeLatest([CREATE_COLLECTION, UPDATE_COLLECTION], modifyCollection)` along with a single method really cleaned things up. I think the test cases I wrote make sense - I believe they reduce duplication as much as makes sense and still give us full coverage.

File: tests/unit/amo/sagas/test_collections.js [hunk 6]
```diff
@@ -327,164 +328,248 @@ describe(__filename, () => {
...
-        description: { 'en-US': 'New collection description' },
-        formOverlayId: 'some-form-overlay',
-        name: { 'en-US': 'New collection name' },
-        slug: 'new-slug',
-        user: 543,
-      };
-      const state = sagaTester.getState();
+    describe('common logic', () => {
+      // The common logic can be tested either by dispatching updateCollection
+      // or createCollection, so we just use _updateCollection.
```
Comment (kumar303) [inline tests/unit/amo/sagas/test_collections.js]: I like this approach to the tests given the circumstances. The comment helps explain things too.

File: tests/unit/amo/sagas/test_collections.js [hunk 7]
```diff
@@ -327,164 +328,248 @@ describe(__filename, () => {
...
-      const expectedAction = finishFormOverlaySubmit(params.formOverlayId);
+      it('begins and finishes a form submit', async () => {
+        mockApi.expects('updateCollection').returns(Promise.resolve());
+        _updateCollection({ formOverlayId });
+
+        for (const expectedAction of [
+          beginFormOverlaySubmit(formOverlayId),
+          finishFormOverlaySubmit(formOverlayId),
+        ]) {
+          // eslint-disable-next-line no-await-in-loop
```
Comment (kumar303) [inline tests/unit/amo/sagas/test_collections.js]: We should delete this rule. We address the problem through code review. There are many legit uses of `await` within a for loop.

File: tests/unit/amo/sagas/test_collections.js [hunk 8]
```diff
@@ -327,164 +328,248 @@ describe(__filename, () => {
...
 
-      _updateCollection(params);
+        const action = await sagaTester.waitFor(expectedAction.type);
+        expect(action).toEqual(expectedAction);
+      });
 
-      const expectedAction = finishFormOverlaySubmit(params.formOverlayId);
+      it('begins and finishes a form submit', async () => {
+        mockApi.expects('updateCollection').returns(Promise.resolve());
+        _updateCollection({ formOverlayId });
```
Comment (kumar303) [inline tests/unit/amo/sagas/test_collections.js]: Hmm, yeah, I guess `formOverlayId` is used enough to warrant relying on the shared value. You might as well reap all the benefits and just leave it off everywhere:
```js
_updateCollection()
```

File: src/amo/sagas/collections.js [hunk 9]
```diff
@@ -166,43 +168,70 @@ export function* addAddonToCollection({
...
-      name,
-      slug,
-      user,
-    };
-    yield call(api.updateCollection, params);
 
-    const slugWasEdited = slug && slug !== collectionSlug;
-    const effectiveSlug = slug || collectionSlug;
+    if (creating) {
+      const apiParams = {
```
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/sagas/collections.js]: That's how I originally had it, but I couldn't seem to get Flow happy with that in place and the other type definitions I had. When I removed it Flow didn't complain, so I assumed that meant it wasn't necessary. I'll try adding it back in and see if I can work through the Flow errors. I may post them here for some help.

File: tests/unit/amo/sagas/test_collections.js (hunk 7 above)
Comment (bobsilverberg) [reply tests/unit/amo/sagas/test_collections.js]: I opened https://github.com/mozilla/eslint-config-amo/issues/53 as a follow-up for this.

File: src/amo/sagas/collections.js (hunk 9 above)
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/sagas/collections.js]: Ok, the problem was because in the type for the function parameters, I need to make `name`, `slug` and `collectionSlug` all optional, because some are optional for each of the two actions. That makes the types `CreateCollectionParams` and `UpdateCollectionParams` incompatible. I was able to solve this by adding some calls to `invariant` to ensure that they were not empty when they shouldn't be, and that makes Flow happy. I suppose there's nothing wrong with this, and is in fact appropriate, although I know the the only code we have that calls this also makes sure those properties are populated when needed, so the extra `invariant`s seem unnecessary. I suppose there's no guarantee that there won't be a future caller who doesn't ensure that, which is kind of the point of Flow in the first place.

So I guess this all makes sense and I'm happy with it, and I learned something too. 😄

**Comment by bobsilverberg** [comment]
Please ignore the eslint error for now. It will go away when I rebase this on top of https://github.com/mozilla/addons-frontend/commit/db95de86460733dc83da01ee327e68f8f5d39bbd, but I figured I'd wait for either another review request or an approval before doing that.

**Comment by kumar303** [comment]
I didn't get a review request for this but I saw it mentioned in https://github.com/mozilla/addons-frontend/pull/4564 -- I think it's ready? I'll take another look

File: src/amo/sagas/collections.js [hunk 10]
```diff
@@ -166,43 +171,71 @@ export function* addAddonToCollection({
...
+        description,
+        name,
+        slug,
+        user,
+      };
+      yield call(api.createCollection, apiParams);
+    } else {
+      invariant(collectionSlug,
+        'collectionSlug cannot be empty when updating');
+      const apiParams: UpdateCollectionParams = {
```
Comment (kumar303) [inline src/amo/sagas/collections.js]: Hmm. I see a lot of duplication between these two param objects. You can introduce a spread with a shared base object but Flow isn't able to compute all spread properties so it will complain about exact object types. There is a global `$Shape` utility we use to turn an exact type into an inexact type. It's not great because you lose the type safety around unexpected properties but being able to DRY up this code seems better.

Something like this should work as long you can get the disjoint unions to kick in:

```diff
diff --git a/src/amo/sagas/collections.js b/src/amo/sagas/collections.js
index 5cf55a0b6..f48a5a31f 100644
--- a/src/amo/sagas/collections.js
+++ b/src/amo/sagas/collections.js
@@ -202,29 +202,26 @@ export function* modifyCollection({
 
     const state = yield select(getState);
 
+    const baseApiParams = {
+      api: state.api,
+      defaultLocale,
+      description,
+      name,
+      slug,
+      user,
+    };
+
     if (creating) {
       invariant(name, 'name cannot be empty when creating');
       invariant(slug, 'slug cannot be empty when creating');
-      const apiParams: CreateCollectionParams = {
-        api: state.api,
-        defaultLocale,
-        description,
-        name,
-        slug,
-        user,
-      };
+      const apiParams: $Shape<CreateCollectionParams> = { ...baseApiParams };
       yield call(api.createCollection, apiParams);
     } else {
       invariant(collectionSlug,
         'collectionSlug cannot be empty when updating');
-      const apiParams: UpdateCollectionParams = {
-        api: state.api,
+      const apiParams: $Shape<UpdateCollectionParams> = {
+        ...baseApiParams,
         collectionSlug,
-        defaultLocale,
-        description,
-        name,
-        slug,
-        user,
       };
       yield call(api.updateCollection, apiParams);
     }
```

If this turns into a headache then it's no big deal. The most important part is gaining type safety for the API calls, which you already had.

**Comment by bobsilverberg** [comment]
Oh, my mistake. I thought I requested a review yesterday. :-P

File: tests/unit/amo/reducers/test_collections.js (hunk 4 above)
Comment (kumar303) [reply tests/unit/amo/reducers/test_collections.js]: > I removed this ... but I noticed that we don't have coverage for testing just action creators which don't result in any state changes.

We do. Any action creator that doesn't result in state changes exists solely to trigger a saga, which would be covered in [a test like this](https://github.com/mozilla/addons-frontend/blob/3d510e53b1011d83b3665a3de2aaecffaedc5da7/tests/unit/amo/sagas/test_collections.js#L332).

**Comment by bobsilverberg** [comment]
@tofumatt kumar gave me an r+wc at https://github.com/mozilla/addons-frontend/pull/4534#pullrequestreview-104353818, but that was awhile ago and I've made a few changes, so if you don't mind taking a look as well, before I merge it, I would appreciate it. Thanks!

**Comment by bobsilverberg** [comment]
Oops, I think I left some TODOs in there, although they should probably addressed by a follow-up, so it's probably okay.

File: src/amo/reducers/collections.js [hunk 11]
```diff
@@ -449,21 +451,78 @@ export const addAddonToCollection = ({
...
+  name,
+  slug,
+  user,
+}: CreateCollectionParams = {}): CreateCollectionAction => {
+  validateRequiredCollectionParams({
+    errorHandlerId,
+    user,
+  });
+
+  invariant(name, 'name is required when creating');
```
Comment (tofumatt) [inline src/amo/reducers/collections.js]: Nitpick: I'd add "a collection" to the end here for clarity.

File: src/amo/reducers/collections.js [hunk 12]
```diff
@@ -449,21 +451,78 @@ export const addAddonToCollection = ({
...
+
+export const createCollection = ({
+  errorHandlerId,
+  defaultLocale,
+  description,
+  name,
+  slug,
+  user,
+}: CreateCollectionParams = {}): CreateCollectionAction => {
+  validateRequiredCollectionParams({
```
Comment (tofumatt) [inline src/amo/reducers/collections.js]: This is actually more lines than just using the two invariant lines:

```js
invariant(errorHandlerId, 'errorHandlerId is required');
invariant(user, 'user is required');
```

I get it doesn't duplicate the messages but we already dupe them elsewhere and invariant should let us nix all the messages in production anyway. I'd rather us just use invariant directly.

File: tests/unit/amo/sagas/test_collections.js (hunk 6 above)
Comment (tofumatt) [reply tests/unit/amo/sagas/test_collections.js]: I know fast tests are good and we don't want to go overboard, but testing each action feels a bit safer for future refactors for me. I'm okay with this though, it's cool. 🤷‍♂️

File: tests/unit/amo/sagas/test_collections.js [hunk 13]
```diff
@@ -324,140 +325,220 @@ describe(__filename, () => {
...
+            name: params.name,
+            slug: params.slug,
+            user,
+          })
+          .once()
+          .returns(Promise.resolve());
+
+        _updateCollection(params);
+
+        // TODO: Instead of this we should probably update the collectionUpdates state,
```
Comment (tofumatt) [inline tests/unit/amo/sagas/test_collections.js]: Can we get an issue filed for this if it's still the case and a code quality thing we should fix in the future?

Comment (bobsilverberg) [reply tests/unit/amo/sagas/test_collections.js]: I added issue #4717 to track this, and added a link to that issue into the TODO comment.
