### PR TITLE
10351 add bug reporting information to about page

### LINKED ISSUE #10351: Add bug reporting information to /about page
Related to [#16884 on the addons-server repo](https://github.com/mozilla/addons-server/issues/16884). 

Let's add a few sentences about how to report bugs/issues on addons.mozilla.org/about. The following text should be added under the "Get Involved" section: 

_____

**Report an issue**
If you find a problem with the site, we'd love to fix it. Please file an [issue](https://github.com/mozilla/addons/issues/new) and include as much detail as possible.

To report a security vulnerability for an extension, even if it is not hosted on this site, please file an [issue](https://bugzilla.mozilla.org/enter_bug.cgi?product=addons.mozilla.org&component=Add-on%20Security&maketemplate=Add-on%20Security%20Bug&bit-23=1&rep_platform=All&op_sys=All) on Bugzilla or email amo-admins@mozilla.com. All security vulnerability reports are [confidential](https://www.mozilla.org/en-US/about/governance/policies/security-group/bugs/).

_____

This should be tagged as a good first issue. 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @bobsilverberg

### PR DESCRIPTION
**Pull request by pranav1601**
Fixes #10351

added bug reporting information to about page

after

before

### CODE REVIEW

File: src/amo/pages/StaticPages/About/index.js [hunk 1]
```diff
@@ -185,6 +185,49 @@ export class AboutBase extends React.Component<Props> {
               )}
             />
           </section>
+          <section>
```
Comment (bobsilverberg) [inline src/amo/pages/StaticPages/About/index.js:188]: The issue requested that an `id` attribute be added to this new section.

**Review by bobsilverberg — CHANGES_REQUESTED** [review]
This looks good, thanks @pranav1601. The changes to `.husky/pre-commit` should not be included in this patch. I'm not sure what caused those changes.

**Comment by pranav1601** [comment]
hey @bobsilverberg , 
I was getting an error when i was trying to commit saying .husky/pre-commit not found. I have fixed it now and I have committed it as well.
Thanks!

File: .husky/pre-commit [hunk 2]
```diff
@@ -1,4 +1,4 @@
 #!/bin/sh
 . "$(dirname "$0")/_/husky.sh"
 
-flow && lint-staged
+flow && lint-staged
```
Comment (bobsilverberg) [inline .husky/pre-commit:4]: It's still detecting a difference because this file is missing a new line at the end. This patch shouldn't contain any changes to `.husky/pre-commit`

**Review by bobsilverberg — CHANGES_REQUESTED** [review]
Thanks @pranav1601. The `.husky/pre-commit` still needs to be dealt with.

**Comment by pranav1601** [comment]
Hey @bobsilverberg ,
didnt see that new line! Corrected it now though. Please review it.
Thanks!

**Review by bobsilverberg — APPROVED** [review]
Looks good, nice work @pranav1601! Thanks for the patch.

**Comment by pranav1601** [comment]
Thanks @bobsilverberg !

**Comment by caitmuenster** [comment]
Yay, thank you so much, @pranav1601! 🎉Your contribution has been added to our [recognition wiki](https://wiki.mozilla.org/Add-ons/Contribute/Recognition). 

Hope to see you around the project in the future!
