### PR TITLE
Fix footer report-bug locale

### LINKED ISSUE #2032: "Report a bug" link is returning a 404 error page for some languages
Steps to reproduce:
1. Load AMO-stage homepage on device i.e. https://addons.allizom.org/en-US/android/
2. Change the language to `tr` aka Türkçe - https://addons-dev.allizom.org/tr/firefox/
3. Tap "Report a bug" link from footer

Expected results:
The page https://developer.mozilla.org/th/Add-ons/AMO/Policy/Contact is loaded.

Actual results:
A 404 page is loaded.

Notes/ Issues:
Other languages: nn-NO, hsb, 
Verified on FF52(Android 6.0.1, Win 7). Issue is reproducing on AMO-stage and -dev.
Video for this issue:

### PR DESCRIPTION
**Pull request by muffinresearch**
Fixes #2032

### CODE REVIEW

File: src/amo/components/Footer.js [hunk 1]
```diff
@@ -37,7 +37,7 @@ export class FooterBase extends React.Component {
             </a>
           </li>
           <li>
-            <a href={`https://developer.mozilla.org/${lang}/Add-ons/AMO/Policy/Contact`}
+            <a href={`https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Contact`}
```
Comment (tofumatt) [inline src/amo/components/Footer.js]: I think it would be better to omit the locale entirely; then MDN will at least try to redirect to the client's `Accept-Language` locale.

Comment (muffinresearch) [inline src/amo/components/Footer.js]: Ah ok, yeah good call

File: tests/client/amo/components/TestFooter.js [hunk 2]
```diff
@@ -36,7 +36,10 @@ describe('Footer', () => {
       'Legal notices');
     assert.equal(root.querySelector('.Footer-legal').href,
       'https://www.mozilla.org/en-GB/about/legal/');
+    // This link isn't localized because MDN will 404 on some
+    // locales and not others.
```
Comment (tofumatt) [inline tests/client/amo/components/TestFooter.js]: Worth including the link to the original issue in this code base too, if you want.
