### PR TITLE
Remove Guides pages

### LINKED ISSUE #9609: Remove the Guides page from AMO
We introduced "Guides" to AMO back in 2018, based on this mockup:

hero - article page

I believe we stopped using them back when we implemented the new Primary and Secondary Hero elements. Looking at the logic, these guides pages are never displayed on the desktop (`/firefox`) site, and on the mobile (`/android`) site all that is displayed is the header (see screenshot). Links to the actual guides pages are never displayed, so I don't think we need them anymore.

This has come up because some changes are required to the guides page to support the new promoted categories, and I'd rather not spend time updating pages that are not actually used by the site.

My suggestion is to delete all the code for the guides pages, and move the code for the header, which is still used on `/android` elsewhere (perhaps into the home page itself). 

@jvillalobos WDYT?

Screenshot showing header from `HomeHeroGuides` as appears on `/android`:

Screen Shot 2020-09-02 at 4 23 58 PM

For QA:

There should be no changes to the current site. Please just check the home page, both on Desktop and Android for regressions.

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #9609

### CODE REVIEW

File: src/amo/components/Routes/index.js [hunk 1]
```diff
@@ -77,8 +76,6 @@ const Routes = ({ _config = config }: Props = {}) => (
 
     <Route exact path="/:lang/:application/addon/:slug/" component={Addon} />
 
-    <Route exact path="/:lang/:application/guides/:slug/" component={Guides} />
```
Comment (eviljeff) [inline src/amo/components/Routes/index.js:80]: I'll leave the discussion to the issue but maybe we shouldn't just 404? 301 to the homepage  🤷

File: src/amo/pages/Home/index.js [hunk 2]
```diff
@@ -184,6 +183,23 @@ export class HomeBase extends React.Component {
...
+          {i18n.gettext('Extensions are like apps for your browser.')}
+        </h2>
+        <h3 className="Home-heroHeader-subtitle">
+          {i18n.gettext(
+            'They add features to Firefox to make browsing faster, smarter, or just plain fun.',
+          )}
+        </h3>
+      </div>
+    );
+  }
```
Comment (eviljeff) [inline src/amo/pages/Home/index.js:201]: Rather than hard-coding this, can't we use the secondary hero api response like we do on Desktop Firefox?

**Review by eviljeff — APPROVED** [review]

File: src/amo/pages/Home/index.js (hunk 2 above)
Comment (bobsilverberg) [reply src/amo/pages/Home/index.js:201]: > Rather than hard-coding this, can't we use the secondary hero api response like we do on Desktop Firefox?

This is a good idea which I hadn't thought of. Currently the wording is slightly different, which would cause some difficulty. On desktop the headline is "Extensions are like apps for Firefox.", while on android the headline is "Extensions are like apps for your browser."

@jvillalobos / @devaneymoz Is this distinction important, or perhaps just an artifact of these being developed at different times? Would we be okay with using the same text (one of the two above) for both `/firefox` and `/android`?

Comment (jvillalobos) [reply src/amo/pages/Home/index.js:201]: I think `Extensions are like apps for Firefox.` should work fine for both sites.

File: src/amo/components/Routes/index.js (hunk 1 above)
Comment (bobsilverberg) [reply src/amo/components/Routes/index.js:80]: We've decided to just 404 these.

**Comment by muffinresearch** [comment]
more-red-than-green-award
