### PR TITLE
fix: Check for DNT correctly

### LINKED ISSUE #2797: Add missing tests for DNT functionality in Tracking object
As a follow up to https://github.com/mozilla/addons-frontend/issues/2792 we need tests for the `Tracking` object to make sure it gets [disabled when DNT is enabled](https://github.com/mozilla/addons-frontend/commit/1312536f6e1b075c508bccb2de7f050876eba172#diff-d174de3c0985bc0d979157795f96ae2bR50).

For QA, here's how to check for regressions:
* Load AMO in a tab and in the Discovery Pane
* Make sure Google Analytics gets loaded when DNT (Do Not Track) is disabled
* Make sure Google Analytics does not get loaded when DNT is enabled

### LINKED ISSUE #2798: Google Analytics is disabled for everyone
### Describe the problem and steps to reproduce it:

Load the site after https://github.com/mozilla/addons-frontend/issues/2792

### What happened?

Google Analytics is never loaded

### What did you expect to happen?

We should load GA for anyone who doesn't have DNT enabled.

### Anything else we should know?

This logic is backwards: https://github.com/mozilla/addons-frontend/commit/1312536f6e1b075c508bccb2de7f050876eba172#diff-d174de3c0985bc0d979157795f96ae2bR134 It should be `!isDoNotTrackEnabled()` otherwise it will never be enabled for either case.

However, I recommend removing isDoNotTrackEnabled() from that line altogether since it's redundant (and makes the code more complicated). DNT is already checked in the constructor.

### PR DESCRIPTION
**Pull request by tofumatt**
Adds a test ensuring GA is disabled when DNT is true, as well.

Fixes #2798

### CODE REVIEW

File: src/core/tracking.js [hunk 1]
```diff
@@ -131,10 +136,7 @@ export function getAction(type) {
 }
 
 export default new Tracking({
-  trackingEnabled: (
-    convertBoolean(config.get('trackingEnabled')) &&
-    isDoNotTrackEnabled()
-  ),
+  trackingEnabled: convertBoolean(config.get('trackingEnabled')),
```
Comment (kumar303) [inline src/core/tracking.js]: I don't think this variable is useful. It's redundant and makes the code more complicated and harder to test (e.g. there is no test coverage of the config reading functionality at all). Let's *not* fix it in this patch though :) because it will require updating the tests. I'll file a lower priority follow-up.

File: tests/unit/core/test_tracking.js [hunk 2]
```diff
@@ -48,6 +48,18 @@ describe('Tracking', () => {
     ).toBe(true);
   });
 
+  it('should log OFF when not enabled due to Do Not Track', () => {
+    tracking = new Tracking({
+      _isDoNotTrackEnabled: () => true,
+      _log: {
+        info: sinon.stub(),
+      },
+      trackingEnabled: true,
```
Comment (kumar303) [inline tests/unit/core/test_tracking.js]: For example, it would be pretty hard to add coverage for the config logic here. Again, not important enough to block on.

File: tests/unit/core/test_tracking.js [hunk 3]
```diff
@@ -48,6 +48,18 @@ describe('Tracking', () => {
...
+      trackingId: 'whatever',
+    });
+    sinon.assert.calledWith(tracking._log.info, sinon.match(/OFF/));
```
Comment (kumar303) [inline tests/unit/core/test_tracking.js]: This doesn't actually test if GA is enabled or not but I don't want to block the patch. I'll file for a fixup.

**Comment by tofumatt** [comment]
Cool, thanks 👍
