### PR TITLE
Fix Primary Hero External prop to deal with l10n

### LINKED ISSUE #10016: Server errors on AMO homepage on stage
### Describe the problem and steps to reproduce it:
1. Create a new Firefox profile (just to make sure there is no caching involved)
2. Open addons.allizom.org

### What happened?
A Server Error page is displayed. Besides the 500 error for the homepage URL, I've also noticed the following error in the browser console: `Caught application error: TypeError: Parameter 'url' must be a string, not object`

### What did you expect to happen?
The homepage is loaded successfully

### Anything else we should know?
- if the issue does not reproduce by following the steps above (although I've been able to repeatedly reproduce it with this method) you can try reloading the homepage several times by clicking on the logo 
- initially, I thought this issue was connected to the server errors coming from the sponsored shelf API, but now with the shelf gone the issue persists 
- I only reproduced the error on stage and no other pages besides the homepage seem to be affected
- this issue is rather high priority because it causes many of our release tests to fail 

image_2021-01-20_123433

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #10016

### CODE REVIEW

**Comment by bobsilverberg** [comment]
@eviljeff @diox It's not a huge patch. If we want to consider cherry-picking it I don't think it will be risky. Neither do I think it's particularly important to land this week, though.

**Comment by willdurand** [comment]
> Neither do I think it's particularly important to land this week, though.

+1

File: src/amo/reducers/home.js [hunk 1]
```diff
@@ -220,6 +237,21 @@ const createInternalAddons = (
   return response.results.map((addon) => createInternalAddon(addon, lang));
 };
 
+export const createInternalPrimaryHeroShelfExternalAddon = (
+  external: PrimaryHeroShelfExternalAddonType,
```
Comment (eviljeff) [inline src/amo/reducers/home.js:241]: The naming confused me here at first v.s the `external` property inside the addon but I get that `Internal` and `External` are the terms used consistently with reducers in addons-frontend.  It's just unfortunate.

File: tests/unit/amo/components/TestHeroRecommendation.js [hunk 2]
```diff
@@ -153,34 +161,26 @@ describe(__filename, () => {
...
 
       const root = render({ _checkInternalURL, shelfData });
 
       const link = root.find('.HeroRecommendation-link');
       expect(link).toHaveProp('rel', 'noopener noreferrer');
       expect(link).toHaveProp('target', '_blank');
-      sinon.assert.calledWith(
-        _checkInternalURL,
-        sinon.match({ urlString: sinon.match(external.homepage) }),
-      );
```
Comment (eviljeff) [inline tests/unit/amo/components/TestHeroRecommendation.js:167]: mmm, we don't need this check any longer?

**Review by eviljeff — APPROVED** [review]

File: tests/unit/amo/components/TestHeroRecommendation.js (hunk 2 above)
Comment (bobsilverberg) [reply tests/unit/amo/components/TestHeroRecommendation.js:167]: We don't strictly need it, but I suppose it makes the test safer, in case for some reason the mock wasn't called and yet the link was assumed to be external, so I'll add it back in. Thanks!

File: src/amo/reducers/home.js (hunk 1 above)
Comment (bobsilverberg) [reply src/amo/reducers/home.js:241]: Yeah, when working on this I recognized that some of these names are quite a mouthful, but I think they accurately reflect what these things are.
