### PR TITLE
Fix TestAddon.js

### LINKED ISSUE #11677: Update /pages/TestAddon.js to work with future dependencies
Update /pages/TestAddon.js to work with future dependencies

### LINKED ISSUE #11678: Update /pages/TestAddonInfo.js to work with future dependencies
Update /pages/TestAddonInfo.js to work with future dependencies

### LINKED ISSUE #11680: Update /pages/TestBlock.js to work with future dependencies
Update /pages/TestBlock.js to work with future dependencies

### PR DESCRIPTION
**Pull request by bobsilverberg**
~~Depends on #11692~~
Fixes #11677 
Fixes #11678 
Fixes #11680

### CODE REVIEW

**Comment by diox** [comment]
Is this ready to be reviewed ? I need the change to `initialEntries`, but pulling that alone breaks other tests that you've fixed here.

**Comment by bobsilverberg** [comment]
> Is this ready to be reviewed ? I need the change to `initialEntries`, but pulling that alone breaks other tests that you've fixed here.

Yes it is, I was waiting for CI to pass and then I got distracted. Assigning you as a reviewer...

**Comment by bobsilverberg** [comment]
Oh, actually, I should merge the other one and rebase first. I'll do that right now...

**Comment by bobsilverberg** [comment]
> Oh, actually, I should merge the other one and rebase first. I'll do that right now...

@diox It's ready now.

File: tests/unit/amo/pages/TestAddonInfo.js [hunk 1]
```diff
@@ -344,10 +344,16 @@ describe(__filename, () => {
     const dispatch = jest.spyOn(store, 'dispatch');
     render();
 
-    expect(dispatch).toHaveBeenCalledWith(
+    // Expect only the LOCATION_CHANGE action which happens twice.
```
Comment (diox) [inline tests/unit/amo/pages/TestAddonInfo.js:347]: Here and in `TestBlock.js` and `TestHome.js` below, add a quick sentence explaining that's it because of `render()` as you did in `TestSearchTools.js` because that's not straightforward if you're not familiar with all this...

**Review by diox — APPROVED** [review]

File: tests/unit/amo/pages/TestAddonInfo.js (hunk 1 above)
Comment (bobsilverberg) [reply tests/unit/amo/pages/TestAddonInfo.js:347]: Done!
