### PR TITLE
Set viewContext as VIEW_CONTEXT_HOME when navigating to a DropdownLink when user is signed in

### LINKED ISSUE #10970: The “Extensions” and “Themes” menu buttons remain highlighted if the user navigates away from either of them to Profile or Collections pages
### Describe the problem and steps to reproduce it:
1. Log into AMO
2. Go to “Extensions” or “Themes” from the header menu. Alternatively click on an extension or a theme on the front page. Notice the header menu highlights the proper item in the header in all cases.
3. From Extensions or Themes, hover over the username in the top right corner of the page and navigate to any of the pages listed under “My Account” (Collections, Edit Profile, View Profile).

### What happened?
The “Extensions” or “Themes” buttons remain highlighted if the user  navigates away from either of them to Profile or Collections pages.

### What did you expect to happen?
None of the header menu items remain highlighted when accessing Collections or Profile pages since the context has changed

### Anything else we should know?
- the underline is removed if the Collections or Profile pages are refreshed
- the issue reproducers on all AMO servers, so it's not a new issue

### PR DESCRIPTION
**Pull request by kdbiddle**
Fixes #10970

When navigating from Extensions or Themes page, the viewContext was not being updated to VIEW_CONTEXT_HOME. This patch sets the viewContext as VIEW_CONTEXT_HOME when navigating to any of the Dropdown Links when user is signed in.

Before: Extensions link stays active when viewing collections.
image

After: Extensions link no longer active when viewing collections.
image

### CODE REVIEW

File: tests/unit/amo/pages/TestUserProfile.js [hunk 1]
```diff
@@ -776,7 +777,15 @@ describe(__filename, () => {
 
     renderUserProfile({ params, store });
 
-    sinon.assert.notCalled(dispatchSpy);
+    sinon.assert.neverCalledWith(
+      dispatchSpy,
+      setUserReviews({
```
Comment (bobsilverberg) [inline tests/unit/amo/pages/TestUserProfile.js:782]: I think you want to be asserting about `fetchUserReviews` here, not `setUserReviews`, as the test description states.

File: tests/unit/amo/pages/TestUserProfile.js [hunk 2]
```diff
@@ -858,7 +867,7 @@ describe(__filename, () => {
     const params = { userId: user.id };
     renderUserProfile({ params, store });
 
-    sinon.assert.notCalled(dispatchSpy);
+    sinon.assert.neverCalledWith(dispatchSpy, loadUserAccount({ user }));
```
Comment (bobsilverberg) [inline tests/unit/amo/pages/TestUserProfile.js:870]: The test description talks about it not fetching user reviews, which I don't think is the same thing as ` loadUserAccount`, so I think you need a different assertion here.

File: tests/unit/amo/pages/TestUserProfile.js [hunk 3]
```diff
@@ -1041,7 +1050,7 @@ describe(__filename, () => {
         url: `/${lang}/${clientApp}/user/${user.id}/`,
       }),
     );
-    sinon.assert.calledOnce(dispatchSpy);
+    sinon.assert.calledTwice(dispatchSpy);
```
Comment (bobsilverberg) [inline tests/unit/amo/pages/TestUserProfile.js:1053]: Please add a comment explaining why we expect this to be called twice.

File: tests/unit/amo/pages/TestUserProfile.js [hunk 4]
```diff
@@ -1067,7 +1076,7 @@ describe(__filename, () => {
         url: `/${lang}/${clientApp}/user/${anotherUserId}/`,
       }),
     );
-    sinon.assert.calledOnce(dispatchSpy);
+    sinon.assert.calledTwice(dispatchSpy);
```
Comment (bobsilverberg) [inline tests/unit/amo/pages/TestUserProfile.js:1079]: As above, please add a comment explaining why we expect this to be called twice.

File: tests/unit/amo/pages/TestUserProfile.js [hunk 5]
```diff
@@ -1095,4 +1104,11 @@ describe(__filename, () => {
       expect(extractId({ match })).toEqual(userId);
     });
   });
+
+  it(`dispatches setViewContext when component mounts`, () => {
```
Comment (bobsilverberg) [inline tests/unit/amo/pages/TestUserProfile.js:1108]: Please use single quotes and not backticks.

File: tests/unit/amo/pages/TestUserProfileEdit.js [hunk 6]
```diff
@@ -1696,4 +1705,11 @@ describe(__filename, () => {
 
     sinon.assert.notCalled(setStateSpy);
   });
+
+  it(`dispatches setViewContext when component mounts`, () => {
```
Comment (bobsilverberg) [inline tests/unit/amo/pages/TestUserProfileEdit.js:1709]: Please use single quotes and not backticks.

**Review by bobsilverberg — CHANGES_REQUESTED** [review]
Thank you for your contribution, @kdbiddle. You did a great job figuring out what the problem was and coming up with a solution. I have added quite a few comments, but overall you've done a very good job. Please re-request review from me after the comments have been addressed.

File: tests/unit/amo/pages/TestUserProfile.js [hunk 7]
```diff
@@ -666,7 +668,7 @@ describe(__filename, () => {
     expect(root.find('.UserProfile-admin-link')).toHaveLength(0);
   });
 
-  it('does not dispatch any action when there is an error', () => {
+  it('only dispatches setViewContext when there is an error', () => {
```
[the remark this answers is not in the document]
Comment (kdbiddle) [reply tests/unit/amo/pages/TestUserProfile.js:672]: This is a great point. I was a little confused about the spirit of the test case, but upon reading the `UserProfile.js` component, it looks like we want to ensure it doesn't fetch user data if there is an error. I think the best change is to ensure we aren't calling `dispatch` with any User action types.

File: tests/unit/amo/pages/TestCollectionList.js [hunk 8]
```diff
@@ -61,10 +65,13 @@ describe(__filename, () => {
   it('does not dispatch fetchUserCollections if there is no user', () => {
     const { store } = dispatchClientMetadata();
     const fakeDispatch = sinon.spy(store, 'dispatch');
+    const errorHandler = createStubErrorHandler();
 
-    renderComponent({ store });
+    renderComponent({ store, errorHandler });
```
Comment (bobsilverberg) [inline tests/unit/amo/pages/TestCollectionList.js:70]: There is no need to pass an `errorHandler` into `renderComponent` here, because it doesn't affect the outcome of the test and we never assert anything about it.

File: tests/unit/amo/pages/TestCollectionList.js [hunk 9]
```diff
@@ -61,10 +65,13 @@ describe(__filename, () => {
...
 
-    sinon.assert.notCalled(fakeDispatch);
+    sinon.assert.neverCalledWithMatch(fakeDispatch, {
+      type: FETCH_USER_COLLECTIONS,
```
Comment (bobsilverberg) [inline tests/unit/amo/pages/TestCollectionList.js:73]: Nice job!

File: tests/unit/amo/pages/TestCollectionList.js [hunk 10]
```diff
@@ -83,9 +90,15 @@ describe(__filename, () => {
 
     fakeDispatch.resetHistory();
 
-    renderComponent({ store });
+    renderComponent({ store, errorHandler });
 
-    sinon.assert.notCalled(fakeDispatch);
+    sinon.assert.neverCalledWith(
```
Comment (bobsilverberg) [inline tests/unit/amo/pages/TestCollectionList.js:95]: You could actually do the same thing here as you did above with `sinon.assert.neverCalledWithMatch(fakeDispatch, { type: FETCH_USER_COLLECTIONS })`, and then you don't need to pass `errorHandler` into the render method at all.

File: tests/unit/amo/pages/TestCollectionList.js [hunk 11]
```diff
@@ -101,10 +114,16 @@ describe(__filename, () => {
     );
 
     fakeDispatch.resetHistory();
+    const errorHandler = createStubErrorHandler();
+    renderComponent({ store, errorHandler });
 
-    renderComponent({ store });
-
-    sinon.assert.notCalled(fakeDispatch);
+    sinon.assert.neverCalledWith(
```
Comment (bobsilverberg) [inline tests/unit/amo/pages/TestCollectionList.js:120]: As above, because we only care that it's *not* called, you can use the simpler `neverCalledWithMatch`.

File: tests/unit/amo/pages/TestUserProfile.js [hunk 12]
```diff
@@ -773,10 +779,18 @@ describe(__filename, () => {
     _setUserReviews({ store, userId: user.id });
 
     const dispatchSpy = sinon.spy(store, 'dispatch');
+    const errorHandler = createStubErrorHandler();
 
-    renderUserProfile({ params, store });
+    renderUserProfile({ params, store, errorHandler });
 
-    sinon.assert.notCalled(dispatchSpy);
+    sinon.assert.neverCalledWith(
```
Comment (bobsilverberg) [inline tests/unit/amo/pages/TestUserProfile.js:786]: You could use `neverCalledWithMatch` here, and require less test setup.

File: tests/unit/amo/pages/TestUserProfileEdit.js [hunk 13]
```diff
@@ -197,36 +203,47 @@ describe(__filename, () => {
...
 
     // This happens when loading the user edit profile page of the current
     // logged-in user (e.g., page refresh).
     renderUserProfileEdit({ params: {}, store });
 
-    sinon.assert.notCalled(dispatchSpy);
+    sinon.assert.neverCalledWithMatch(dispatchSpy, {
+      type: FETCH_USER_ACCOUNT,
+    });
+    sinon.assert.neverCalledWith(dispatchSpy, loadUserNotificationsAction);
```
Comment (bobsilverberg) [inline tests/unit/amo/pages/TestUserProfileEdit.js:246]: I don't think we want to assert that user notifications were not loaded, I think we want to assert they were not fetched.

**Review by bobsilverberg — CHANGES_REQUESTED** [review]
This is looking much better, thank you for the updates @kdbiddle!. I have added a few more comments.

File: tests/unit/amo/pages/TestCollectionList.js (hunk 10 above)
Comment (kdbiddle) [reply tests/unit/amo/pages/TestCollectionList.js:95]: I like this, because it's more declarative. It seems that we should either memoize the action itself, rather than rebuild it OR simply assert the type, since we don't actually care about the other values of the payload.

**Comment by kdbiddle** [comment]
> I am not seeing the test results for this PR. @kdbiddle Do you have CI set up on your own fork? I think that prevents the test results from appearing here, and we really need to be able to see the test results on this page.

I don't, I assumed it would set it up since it was configured on the Mozilla repo. I wondered why it wasn't showing up; I'll look into configuring this.

File: src/amo/pages/CollectionList/index.js [hunk 14]
```diff
@@ -22,7 +22,8 @@ import type { AppState } from 'amo/store';
 import type { ErrorHandlerType } from 'amo/types/errorHandler';
 import type { I18nType } from 'amo/types/i18n';
 import type { DispatchFunc } from 'amo/types/redux';
-
```
[the remark this answers is not in the document]
Comment (kdbiddle) [reply src/amo/pages/CollectionList/index.js:25]: Oddly, eslint complains when I add it!

[the remark this answers is not in the document]
Comment (kdbiddle) [reply src/amo/pages/CollectionList/index.js:25]: Oddly, eslint complains when I add it back! 
```
24:1  error  There should be no empty line within import group  import/order
```

**Comment by kdbiddle** [comment]
@bobsilverberg I got the CI configured, and updated the PR for re-review!

**Comment by kdbiddle** [comment]
> > > I am not seeing the test results for this PR. @kdbiddle Do you have CI set up on your own fork? I think that prevents the test results from appearing here, and we really need to be able to see the test results on this page.
> > 
> > 
> > I don't, I assumed it would set it up since it was configured on the Mozilla repo. I wondered why it wasn't showing up; I'll look into configuring this.
> 
> Please don't! I asked because having it configured on your own fork can be a problem for us. I see the test results in the PR now, so I'm not sure what the problem was.

Oh no I just saw this! I already set it up, should I roll it back?

File: src/amo/pages/CollectionList/index.js (hunk 14 above)
[the remark this answers is not in the document]
Comment (bobsilverberg) [reply src/amo/pages/CollectionList/index.js:25]: Oh, I misread this. Could you please move these non-type imports above the `type` imports though?

File: tests/unit/amo/pages/TestCollectionList.js [hunk 15]
```diff
@@ -101,10 +109,12 @@ describe(__filename, () => {
     );
 
     fakeDispatch.resetHistory();
+    const errorHandler = createStubErrorHandler();
```
Comment (bobsilverberg) [inline tests/unit/amo/pages/TestCollectionList.js:112]: Now that you are using `neverCalledWithMatch`, you shouldn't need to create and pass in an `errorHandler`.

File: tests/unit/amo/pages/TestUserProfile.js [hunk 16]
```diff
@@ -781,10 +787,13 @@ describe(__filename, () => {
     _setUserReviews({ store, userId: user.id });
 
     const dispatchSpy = sinon.spy(store, 'dispatch');
+    const errorHandler = createStubErrorHandler();
```
Comment (bobsilverberg) [inline tests/unit/amo/pages/TestUserProfile.js:790]: As above, because you are using `neverCalledWithMatch`, you don't need to create and pass in an `errorHandler`.

**Review by bobsilverberg — CHANGES_REQUESTED** [review]
This is looking really good, nice work @kdbiddle! I just added a few minor comments.

**Review by bobsilverberg — APPROVED** [review]
Looks great, thanks for all of your hard work on this @kdbiddle!
