### PR TITLE
Fixes I4719 - disable submit if slug blank(edit collection)

### LINKED ISSUE #4719: Disable Save Collection button if the slug is blank
This is a replacement for issue #4650 and will be similar to the resolution in issue #4698. If the collection slug is blank, or a string which is only spaces, the "Save Collection" button should be disabled.

@tsl143 Are you interested in taking this one, as it's very similar to the work you did for #4698?

### PR DESCRIPTION
**Pull request by tsl143**
Fixes #4719 

Before: 
screen shot 2018-04-04 at 8 24 34 am

After: 
screen shot 2018-04-04 at 8 23 59 am

### CODE REVIEW

File: tests/unit/amo/components/TestCollectionManager.js [hunk 1]
```diff
@@ -268,6 +268,18 @@ describe(__filename, () => {
       .toHaveProp('disabled', true);
   });
 
+  it('disables submit button when the slug is blank', () => {
+    const root = render();
+
+    // Enter in a blank collection name.
+    typeInput({ root, name: 'slug', text: '' });
```
Comment (bobsilverberg) [inline tests/unit/amo/components/TestCollectionManager.js]: I'd like to see a test for a slug which isn't empty, but contains only spaces. We should add one for the name field too, if we don't have one already. I think it's fine to just add it to this case.

**Comment by tsl143** [comment]
Can we get this merged?

**Comment by bobsilverberg** [comment]
Yes!
