### PR TITLE
Always show `InstallWarning` when we could

### LINKED ISSUE #8642: Always show `InstallWarning` when we could
### Describe the problem and steps to reproduce it:

1. Make sure you are in the right cohort (`includeWarning`) so that you see the install warning banner when you browse an extension that is not recommended (and not installed)
2. Install the extension
3. Reload the page

### What happened?

The warning banner is not displayed (disappeared). 

### What did you expect to happen?

The warning banner is displayed because it could still be useful (and it is confusing).

We discussed this on Slack a while ago but AFAIK no one has filed an issue so here is one.

### PR DESCRIPTION
**Pull request by bobsilverberg**
Fixes #8642 

I'm unsure about one of the tests that I updated. I'll comment in the diff on that.

### CODE REVIEW

File: tests/unit/amo/components/TestInstallWarning.js [hunk 1]
```diff
@@ -98,29 +95,20 @@ describe(__filename, () => {
       expect(component.instance().couldShowWarning()).toEqual(true);
     });
 
-    it.each([UNINSTALLED, UNKNOWN])(
-      `returns true if mozAddonManager exists and the add-on has a status of %s`,
+    it.each(validInstallStates)(
```
Comment (bobsilverberg) [inline tests/unit/amo/components/TestInstallWarning.js]: We don't really need this test anymore, as any code that looks at install status has been removed. Therefore, there doesn't seem to be a reason for a test that makes sure that this returns `true` for a number of different statuses.

On the other hand, a code change was made that means that, whereas a number of statuses (including `INSTALLED`) in the past would have had this return `false`, it will now return `true` in those cases. So, do we need some sort of test that verifies this new behaviour?

Comment (bobsilverberg) [reply tests/unit/amo/components/TestInstallWarning.js]: Is the answer to this question to just add a comment above this test saying:

`// See https://github.com/mozilla/addons-frontend/issues/8642.`

(Which I just added)

Comment (willdurand) [reply tests/unit/amo/components/TestInstallWarning.js]: I would remove the test case because you would need a big change (aka something that will not pass a review) to make it fail.
